namespace OfficeIMO.Email.AddressBook;

internal static class OabPropertyTags {
    internal const ushort DisplayName = 0x3001;
    internal const ushort EmailAddress = 0x3003;
    internal const ushort Comment = 0x3004;
    internal const ushort ObjectType = 0x0FFE;
    internal const ushort SmtpAddress = 0x39FE;
    internal const ushort DisplayNamePrintable = 0x39FF;
    internal const ushort DisplayType = 0x3900;
    internal const ushort DisplayTypeEx = 0x3905;
    internal const ushort Account = 0x3A00;
    internal const ushort GivenName = 0x3A06;
    internal const ushort BusinessTelephone = 0x3A08;
    internal const ushort HomeTelephone = 0x3A09;
    internal const ushort Initials = 0x3A0A;
    internal const ushort Surname = 0x3A11;
    internal const ushort CompanyName = 0x3A16;
    internal const ushort Title = 0x3A17;
    internal const ushort Department = 0x3A18;
    internal const ushort OfficeLocation = 0x3A19;
    internal const ushort BusinessTelephone2 = 0x3A1B;
    internal const ushort MobileTelephone = 0x3A1C;
    internal const ushort PagerTelephone = 0x3A21;
    internal const ushort PrimaryFax = 0x3A23;
    internal const ushort Country = 0x3A26;
    internal const ushort Locality = 0x3A27;
    internal const ushort StateOrProvince = 0x3A28;
    internal const ushort StreetAddress = 0x3A29;
    internal const ushort PostalCode = 0x3A2A;
    internal const ushort AssistantTelephone = 0x3A2E;
    internal const ushort HomeTelephone2 = 0x3A2F;
    internal const ushort Assistant = 0x3A30;
    internal const ushort SendRichInfo = 0x3A40;
    internal const ushort ProxyAddresses = 0x800F;
    internal const ushort TargetAddress = 0x8011;
    internal const ushort Members = 0x8009;
    internal const ushort MemberOf = 0x8008;
    internal const ushort HierarchicalGroup = 0x8CDD;
    internal const ushort DistributionListMemberCount = 0x8CE2;
    internal const ushort DistributionListExternalMemberCount = 0x8CE3;
    internal const ushort TruncatedProperties = 0x6805;
    internal const ushort AddressBookName = 0x6800;
    internal const ushort AddressBookSequence = 0x6801;
    internal const ushort AddressBookContainerGuid = 0x6802;
    internal const ushort AddressBookDistinguishedName = 0x6804;
    internal const ushort HierarchicalRootDepartment = 0x8C98;
}
