trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    exclude:
      - docs
      - .github
      - .vs
      - Assets
      - README.md
      - CHANGELOG.MD

pr:
  autoCancel: true
  branches:
    include:
      - '*'
  paths:
    exclude:
      - docs
      - .github
      - .vs
      - Assets
      - README.md
      - CHANGELOG.MD

pool:
  vmImage: 'macos-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  DotNet8Version: '8.x'
  DotNet9Version: '9.x'
  MSBuildArgs: '"/p:Platform=$(BuildPlatform)" "/p:Configuration=$(BuildConfiguration)" "/BinaryLogger:$(Build.SourcesDirectory)\$(ArtifactsDirectoryName)\msbuild.binlog"'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install Nuget Tool Installer'

- task: UseDotNet@2
  displayName: 'Install .NET 8.0'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
    includePreviewVersions: true

- task: UseDotNet@2
  displayName: 'Install .NET 8.0'
  inputs:
    packageType: 'sdk'
    version: '9.0.x'
    includePreviewVersions: true

# Add a Command To List the Current .NET SDKs (Sanity Check)
- task: CmdLine@2
  displayName: 'List available .NET SDKs'
  inputs:
    script: 'dotnet --list-sdks'

- task: DotNetCoreCLI@2
  displayName: 'Install Nuget Packages'
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: CmdLine@2
  displayName: 'Install Global Tools...'
  inputs:
    targetType: 'inline'
    script: |
      dotnet tool install -g dotnet-reportgenerator-globaltool
  continueOnError: true

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests (.NET 8.0)'
  inputs:
    command: 'test'
    arguments: '--framework net8.0 /noautorsp'
    testRunTitle: 'macOS .NET 8.0'
    projects: |
      **/*.Tests.csproj
      !**/OfficeIMO.VerifyTests.csproj
  condition: succeededOrFailed()

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests (.NET 9.0)'
  inputs:
    command: 'test'
    arguments: '--framework net9.0 /noautorsp'
    testRunTitle: 'macOS .NET 9.0'
    projects: |
      **/*.Tests.csproj
      !**/OfficeIMO.VerifyTests.csproj
  condition: succeededOrFailed()