using OfficeIMO.Email;
using System.IO.Compression;
using System.Text;
using System.Text.Json;

namespace OfficeIMO.Workflows;

/// <summary>Bounds for portable email evidence and conversation reports.</summary>
public sealed class EmailEvidenceOptions {
    /// <summary>Reader policy for a single persisted message.</summary>
    public EmailReaderOptions ReaderOptions { get; set; } = new(maxInputBytes: 64L * 1024 * 1024);
    /// <summary>Whether the result contains a PDF generated by the first-party HTML renderer.</summary>
    public bool IncludePdf { get; set; } = true;
    /// <summary>Maximum source body characters accepted for semantic text projection.</summary>
    public int MaxBodySourceCharacters { get; set; } = 2 * 1024 * 1024;
    /// <summary>Maximum displayed body characters per message. Omission is reported in the manifest.</summary>
    public int MaxBodyTextCharacters { get; set; } = 100_000;
    /// <summary>Maximum messages exported from one conversation.</summary>
    public int MaxMessages { get; set; } = 100;
    /// <summary>Maximum items scanned when building the conversation graph.</summary>
    public int MaxItemsScanned { get; set; } = 10_000;
    /// <summary>Maximum characters in each HTML or Markdown report.</summary>
    public int MaxReportCharacters { get; set; } = 4 * 1024 * 1024;
    /// <summary>Maximum cumulative uncompressed output bytes, and maximum ZIP bytes.</summary>
    public long MaxOutputBytes { get; set; } = 64L * 1024 * 1024;
    /// <summary>Maximum rendered PDF pages.</summary>
    public int MaxPdfPages { get; set; } = 200;
    internal void Validate() {
        ArgumentNullException.ThrowIfNull(ReaderOptions);
        if (MaxBodySourceCharacters < 1 || MaxBodySourceCharacters > 16 * 1024 * 1024 ||
            MaxBodyTextCharacters < 1 || MaxBodyTextCharacters > 2 * 1024 * 1024 ||
            MaxMessages < 1 || MaxMessages > 1000 || MaxItemsScanned < 1 || MaxItemsScanned > 100_000 ||
            MaxReportCharacters < 1 || MaxReportCharacters > 16 * 1024 * 1024 ||
            MaxOutputBytes < 1 || MaxOutputBytes > 256L * 1024 * 1024 || MaxPdfPages < 1 || MaxPdfPages > 1000)
            throw new ArgumentOutOfRangeException(nameof(EmailEvidenceOptions), "Email evidence bounds are outside the supported range.");
    }
}

/// <summary>Portable report outputs. The ZIP contains reports and a manifest, without original message or attachment payloads.</summary>
public sealed class EmailEvidenceResult {
    private readonly byte[]? _pdf;
    private readonly byte[] _manifest;
    private readonly long _maximumBytes;
    internal EmailEvidenceResult(string html, string markdown, byte[]? pdf, EmailEvidenceManifest manifest, long maximumBytes) {
        Html = html; Markdown = markdown; _pdf = pdf; Manifest = manifest; _maximumBytes = maximumBytes;
        _manifest = JsonSerializer.SerializeToUtf8Bytes(manifest, new JsonSerializerOptions { WriteIndented = true });
        long bytes = Encoding.UTF8.GetByteCount(html) + (long)Encoding.UTF8.GetByteCount(markdown) + _manifest.LongLength + (pdf?.LongLength ?? 0);
        if (bytes > maximumBytes) throw new InvalidDataException("The email evidence output exceeds MaxOutputBytes.");
    }
    /// <summary>Self-contained, escaped HTML with semantic text bodies.</summary>
    public string Html { get; }
    /// <summary>Readable Markdown with literal body blocks.</summary>
    public string Markdown { get; }
    /// <summary>PDF bytes, or null when PDF generation was disabled. Returns a copy.</summary>
    public byte[]? PdfBytes => _pdf?.ToArray();
    /// <summary>Structured provenance, omissions, attachment indexes, thread evidence and diagnostics.</summary>
    public EmailEvidenceManifest Manifest { get; }
    /// <summary>Creates a bounded ZIP with fixed portable entry names and no filesystem side effects.</summary>
    public byte[] ToZipBytes(CancellationToken cancellationToken = default) {
        using var output = new MemoryStream();
        using (var archive = new ZipArchive(output, ZipArchiveMode.Create, leaveOpen: true)) {
            Write("report.html", Encoding.UTF8.GetBytes(Html));
            Write("report.md", Encoding.UTF8.GetBytes(Markdown));
            Write("manifest.json", _manifest);
            if (_pdf != null) Write("report.pdf", _pdf);
            void Write(string name, byte[] content) {
                cancellationToken.ThrowIfCancellationRequested();
                using var stream = archive.CreateEntry(name, CompressionLevel.Optimal).Open();
                for (int offset = 0; offset < content.Length; offset += 64 * 1024) {
                    cancellationToken.ThrowIfCancellationRequested();
                    stream.Write(content, offset, Math.Min(64 * 1024, content.Length - offset));
                }
            }
        }
        cancellationToken.ThrowIfCancellationRequested();
        if (output.Length > _maximumBytes) throw new InvalidDataException("The email evidence ZIP exceeds MaxOutputBytes.");
        return output.ToArray();
    }
}

/// <summary>Persisted evidence schema, version 1. Content is a projection, not cryptographic verification or anonymization.</summary>
public sealed record EmailEvidenceManifest(int SchemaVersion, string SourceFingerprint, string FingerprintKind,
    string Format, bool GraphComplete, IReadOnlyList<EmailEvidenceMessage> Messages,
    IReadOnlyList<EmailEvidenceThreadLink> ThreadLinks, IReadOnlyList<EmailEvidenceMissingParent> MissingParents,
    IReadOnlyList<EmailEvidenceDiagnostic> Diagnostics, int DiagnosticCount);
/// <summary>One projected message, with bounded display fields and explicit body omission.</summary>
public sealed record EmailEvidenceMessage(string Id, string? Subject, string? From, string? To, string? Cc,
    DateTimeOffset? Date, DateTimeOffset? ReceivedDate, string ProtectionKind, string IntegrityStatus,
    string BodySourceKind, bool BodyTextTruncated, IReadOnlyList<EmailEvidenceAttachment> Attachments);
/// <summary>Attachment metadata and resident payload hash. A null hash means the payload was not available without deferred I/O.</summary>
public sealed record EmailEvidenceAttachment(int Index, string? Name, string? ContentType, long Length, bool Inline, bool EmbeddedMessage, string? Sha256);
/// <summary>Existing graph edge, including authoritative versus heuristic evidence.</summary>
public sealed record EmailEvidenceThreadLink(string ParentId, string ChildId, string Kind, IReadOnlyList<string> Reasons, bool IsHeuristic);
/// <summary>A declared parent which the graph could not select uniquely.</summary>
public sealed record EmailEvidenceMissingParent(string ChildId, string ParentMessageId, string Reason);
/// <summary>Bounded diagnostic sample. DiagnosticCount preserves the total.</summary>
public sealed record EmailEvidenceDiagnostic(string Code, string Severity, string Message, string? Location);
