using DrawingCore = OfficeIMO.Drawing;
using PdfCore = OfficeIMO.Pdf;

namespace OfficeIMO.Html.Pdf;

/// <summary>
/// Controls direct HTML layout and PDF generation.
/// Layout, resource, page, and safety settings are inherited from <see cref="HtmlRenderOptions"/>.
/// </summary>
/// <example>
/// <code>
/// var options = new HtmlToPdfOptions {
///     PageSize = OfficePageSizes.A4,
///     Margins = HtmlRenderMargins.All(32),
///     DefaultFontFamily = "Arial"
/// };
/// byte[] pdf = HtmlConversionDocument.Parse(html).ToPdfBytes(options);
/// </code>
/// </example>
public sealed class HtmlToPdfOptions : HtmlRenderOptions {
    private int _maxOutlinedTextCharactersPerRun = 16_384;
    private int _maxOutlinedTextPathCommands = 1_000_000;
    private PdfCore.PdfResourcePolicy _resourcePolicy = PdfCore.PdfResourcePolicy.CreateDefault();
    private PdfCore.PdfOptions _documentOptions = new PdfCore.PdfOptions {
        CompressContentStreams = true
    }.EnableTaggedPdfCatalogMarkers();

    internal HtmlRenderResourceResolver? EmbeddedPackageResourceResolver { get; set; }
    internal HtmlUrlPolicy? EmbeddedPackageHostResourceUrlPolicy { get; set; }
    /// <summary>Creates direct paged HTML-to-PDF options using the standard defaults.</summary>
    public HtmlToPdfOptions() {
        Mode = HtmlRenderMode.Paged;
        UrlPolicy = HtmlUrlPolicy.CreateHyperlinkProfile();
    }

    /// <summary>
    /// Creates PDF-capable options from shared HTML rendering settings without changing their layout mode.
    /// PDF conversion enforces paged layout on its own conversion snapshot.
    /// </summary>
    /// <param name="renderOptions">Shared settings used by PNG, SVG, and PDF rendering.</param>
    /// <remarks>Generic rendering settings are intersected with the PDF hyperlink policy so caller restrictions are preserved. PDF-specific snapshots preserve their explicitly configured URL policy.</remarks>
    public HtmlToPdfOptions(HtmlRenderOptions renderOptions) : base(renderOptions) {
        if (renderOptions is HtmlToPdfOptions pdfOptions) {
            CopyPdfSettingsFrom(pdfOptions);
        } else {
            UrlPolicy = HtmlUrlPolicy.Intersect(UrlPolicy, HtmlUrlPolicy.CreateHyperlinkProfile());
        }
    }

    /// <summary>OfficeIMO-managed font fallback groups used by generated PDF text.</summary>
    public PdfCore.PdfTextFallbackFeatures TextFallbacks { get; set; } =
        PdfCore.PdfTextFallbackFeatures.Default |
        PdfCore.PdfTextFallbackFeatures.MultilingualFonts;

    /// <summary>Dependency-free shaping mode used by generated PDF text.</summary>
    public PdfCore.PdfTextShapingMode TextShapingMode { get; set; } = PdfCore.PdfTextShapingMode.LatinLigatures;

    /// <summary>Optional caller-supplied embedded font family used by generated PDF text.</summary>
    public PdfCore.PdfEmbeddedFontFamily? FontFamily { get; set; }

    /// <summary>
    /// Converts supported standard HTML inputs, text areas, and selects into interactive AcroForm fields.
    /// Disable this to retain the shared renderer's static control paint in the PDF.
    /// </summary>
    public bool InteractiveFormControls { get; set; } = true;

    /// <summary>
    /// Maximum UTF-16 characters expanded into vector font outlines for one rendered text run.
    /// Raise this only for trusted documents with unusually long unbroken text.
    /// </summary>
    public int MaxOutlinedTextCharactersPerRun {
        get => _maxOutlinedTextCharactersPerRun;
        set {
            if (value <= 0) throw new ArgumentOutOfRangeException(nameof(value));
            _maxOutlinedTextCharactersPerRun = value;
        }
    }

    /// <summary>
    /// Maximum path commands generated by text outlines across one PDF conversion.
    /// </summary>
    public int MaxOutlinedTextPathCommands {
        get => _maxOutlinedTextPathCommands;
        set {
            if (value <= 0) throw new ArgumentOutOfRangeException(nameof(value));
            _maxOutlinedTextPathCommands = value;
        }
    }

    /// <summary>
    /// PDF writer settings used for the generated document, including file version,
    /// forward-only serialization, tagging, compliance groundwork, and output intents.
    /// </summary>
    /// <remarks>
    /// Conversion snapshots this value. HTML-specific font and shaping properties are
    /// then applied as explicit adapter overrides.
    /// </remarks>
    public PdfCore.PdfOptions PdfOptions {
        get => _documentOptions;
        set => _documentOptions = value ?? throw new ArgumentNullException(nameof(value));
    }

    /// <summary>Optional host-provided shaping seam used with caller-supplied or resolved embedded fonts.</summary>
    public new DrawingCore.IOfficeTextShapingProvider? TextShapingProvider {
        get => base.TextShapingProvider;
        set => base.TextShapingProvider = value;
    }

    /// <summary>Host-resource policy. Defaults to balanced conversion: system fonts and bounded in-source resources are allowed, while local and remote reads are denied.</summary>
    public PdfCore.PdfResourcePolicy ResourcePolicy {
        get => _resourcePolicy;
        set => _resourcePolicy = value ?? throw new ArgumentNullException(nameof(value));
    }

    /// <summary>Creates an independent options snapshot for one PDF conversion.</summary>
    public HtmlToPdfOptions ClonePdf() {
        return new HtmlToPdfOptions(this);
    }

    /// <summary>Creates an independent options snapshot.</summary>
    public override HtmlRenderOptions Clone() => ClonePdf();

    /// <summary>Returns a snapshot of the active HTML resource policy.</summary>
    public HtmlPdfResourcePolicySummary GetResourcePolicySummary() => HtmlPdfResourcePolicySummary.From(this);

    private void CopyPdfSettingsFrom(HtmlToPdfOptions source) {
        TextFallbacks = source.TextFallbacks;
        TextShapingMode = source.TextShapingMode;
        FontFamily = source.FontFamily;
        InteractiveFormControls = source.InteractiveFormControls;
        MaxOutlinedTextCharactersPerRun = source.MaxOutlinedTextCharactersPerRun;
        MaxOutlinedTextPathCommands = source.MaxOutlinedTextPathCommands;
        PdfOptions = source.PdfOptions.Clone();
        TextShapingProvider = source.TextShapingProvider;
        ResourcePolicy = source.ResourcePolicy.Clone();
        EmbeddedPackageResourceResolver = source.EmbeddedPackageResourceResolver;
        EmbeddedPackageHostResourceUrlPolicy = source.EmbeddedPackageHostResourceUrlPolicy?.Clone();
    }
}
