namespace OfficeIMO.Pdf;

/// <summary>
/// Result returned by non-throwing in-memory PDF byte generation.
/// </summary>
public sealed class PdfBytesResult {
    private readonly byte[] _bytes;

    private PdfBytesResult(
        byte[] bytes,
        IReadOnlyList<string> diagnostics,
        Exception? exception,
        PdfPipelineReport? pipeline = null) {
        _bytes = (byte[])bytes.Clone();
        Diagnostics = diagnostics;
        Exception = exception;
        TextEncodingDiagnostics = PdfOutputDiagnostics.ExtractTextEncodingDiagnostics(exception);
        Report = new PdfConversionReport();
        Report.AddRange(PdfOutputDiagnostics.ToConversionWarnings(TextEncodingDiagnostics));
        Pipeline = pipeline ?? PdfPipelineReport.Empty();
    }

    /// <summary>True when byte generation completed.</summary>
    public bool Succeeded => Exception is null;

    /// <summary>Generated PDF bytes when the operation completed; otherwise an empty array.</summary>
    public byte[] Bytes => (byte[])_bytes.Clone();

    /// <summary>Number of generated bytes when the operation completed; otherwise 0.</summary>
    public long ByteCount => _bytes.LongLength;

    /// <summary>Human-readable diagnostics explaining why byte generation failed.</summary>
    public IReadOnlyList<string> Diagnostics { get; }

    /// <summary>Exception captured from the byte generation attempt, when available.</summary>
    public Exception? Exception { get; }

    /// <summary>Structured text encoding diagnostics captured from PDF generation failures.</summary>
    public IReadOnlyList<PdfTextEncodingDiagnostic> TextEncodingDiagnostics { get; }

    /// <summary>Structured PDF output warnings captured for this byte-generation attempt.</summary>
    public PdfConversionReport Report { get; }

    /// <summary>End-to-end create/open, mutation, and byte-generation evidence.</summary>
    public PdfPipelineReport Pipeline { get; }

    /// <summary>Structured PDF output warnings captured for this byte-generation attempt.</summary>
    public IReadOnlyList<PdfConversionWarning> Warnings => Report.Warnings;

    /// <summary>True when PDF output produced a warning.</summary>
    public bool HasWarnings => Report.HasWarnings;

    /// <summary>Returns generated PDF bytes or throws with diagnostics when generation failed.</summary>
    public byte[] RequireBytes() {
        if (Succeeded) {
            return Bytes;
        }

        string message = Diagnostics.Count == 0
            ? "PDF byte generation did not complete."
            : "PDF byte generation did not complete. " + string.Join(" ", Diagnostics);
        throw new InvalidOperationException(message, Exception);
    }

    /// <summary>Creates a successful byte generation result.</summary>
    public static PdfBytesResult FromSuccess(byte[] bytes) {
        Guard.NotNull(bytes, nameof(bytes));
        return new PdfBytesResult(bytes, Array.Empty<string>(), null);
    }

    /// <summary>Creates a failed byte generation result from an exception captured by a wrapper or adapter.</summary>
    public static PdfBytesResult FromFailure(Exception exception) {
        Guard.NotNull(exception, nameof(exception));
        IReadOnlyList<string> diagnostics = PdfOutputDiagnostics.BuildExceptionDiagnostics(exception);
        return new PdfBytesResult(Array.Empty<byte>(), diagnostics, exception);
    }

    internal static PdfBytesResult Success(byte[] bytes, PdfPipelineReport? pipeline = null) {
        Guard.NotNull(bytes, nameof(bytes));
        return new PdfBytesResult(bytes, Array.Empty<string>(), null, pipeline);
    }

    internal static PdfBytesResult Failed(Exception exception, PdfPipelineReport? pipeline = null) {
        Guard.NotNull(exception, nameof(exception));
        IReadOnlyList<string> diagnostics = PdfOutputDiagnostics.BuildExceptionDiagnostics(exception);
        return new PdfBytesResult(Array.Empty<byte>(), diagnostics, exception, pipeline);
    }
}
