using System;
using System.Globalization;
using OfficeIMO.Drawing;
using Xunit;

namespace OfficeIMO.Tests;

public sealed class DrawingWebpGroupTests {
    // Independently assembled VP8L streams alternate metadata groups 0/1 or
    // 0/5. Distance-one copies cross block and row boundaries. Native decoding
    // qualifies the expected runs, including pixels retained by those copies.
    [Theory]
    [InlineData(1, 65,
        "UklGRvIBAABXRUJQVlA4TOYBAAAvAAAQAIQpKEAB+l8AVVVAkgAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAC0oR/9bwCQJAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAABt6Ef/GwAkCQAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAEAb+tH/BgBJAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAANCGfvS/AUCSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAALShH/1vAJAkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAG3oR/8boAAAAAA=",
        "36:31,4:146,4:31,4:146,4:31,4:146,4:31,4:146,1:31")]
    [InlineData(9, 13,
        "UklGRvIBAABXRUJQVlA4TOUBAAAvCAADAIQpKEAB+l8AVQWSBAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAKAN/eh/A4AkAQAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAGhDP/rfACBJAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAANrQj/43AEgSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAgDb0o/8NAJIEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAoA396H8DgCQBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAaEM/+t8AgcABAAA=",
        "34:31,1:146,73:31,4:146,4:31,1:146")]
    [InlineData(17, 9,
        "UklGRrwAAABXRUJQVlA4TK8AAAAvEAACAIwJKEAB+l8AFUgSAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAgDb0o/8NAJIEAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAoA396H8DRNEEAAAAAA==",
        "42:31,42:54,43:31,8:54,1:31,8:54,8:31,1:54")]
    [InlineData(65, 17,
        "UklGRtIAAABXRUJQVlA4TMUAAAAvQAAEAJwJKEAB+l8AAUkCAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAA0IZ+9L8BQJIAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAtKEf/W+AQCAQCAQCgUAgEPgCgUAgEAgEAoFAIBAIBAIBAAA=",
        "34:31,35:54,35:31,35:54,35:31,35:54,35:31,35:54,35:31,35:54,35:31,35:54,84:31,35:54,35:31,35:54,35:31,35:54,35:31,1:54,34:31,35:54,35:31,35:54,35:31,35:54,35:31,35:54,35:31,35:54,35:31,6:54,1:31")]
    public void MetaGroupsPreservePixelsAcrossBlocksRowsAndCopyJumps(
        int width, int height, string fixture, string greenRuns) {
        byte[] encoded = Convert.FromBase64String(fixture);
        Assert.True(OfficeWebpCodec.TryDecode(encoded, out var decoded));
        Assert.NotNull(decoded);
        Assert.Equal(width, decoded!.Width);
        Assert.Equal(height, decoded.Height);

        var expected = new byte[width * height * 4];
        int position = 0;
        foreach (string run in greenRuns.Split(',')) {
            string[] parts = run.Split(':');
            int count = int.Parse(parts[0], CultureInfo.InvariantCulture);
            byte green = byte.Parse(parts[1], CultureInfo.InvariantCulture);
            for (int index = 0; index < count; index++) {
                expected[position++] = 13;
                expected[position++] = green;
                expected[position++] = 31;
                expected[position++] = 255;
            }
        }
        Assert.Equal(expected.Length, position);
        Assert.Equal(expected, decoded.GetPixels());
    }
}
