using System.Collections.ObjectModel;

namespace OfficeIMO.PowerPoint.LegacyPpt.Capabilities {
    /// <summary>
    /// Provides the versioned source of truth for binary PowerPoint import, authoring, round-trip, and conversion support.
    /// </summary>
    public static partial class LegacyPptCapabilityCatalog {
        private static readonly IReadOnlyList<LegacyPptCapability> CapabilityRows =
            new ReadOnlyCollection<LegacyPptCapability>(new[] {
                Native(LegacyPptFeature.FileLifecycle, "Lifecycle", "Load, save, save-copy, streams, bytes, and async flows."),
                Native(LegacyPptFeature.FileVariants, "Lifecycle", ".ppt, .pot, and .pps routing and extension semantics."),
                Native(LegacyPptFeature.SlideSize, "Structure", "Presentation page dimensions."),
                Native(LegacyPptFeature.Slides, "Structure", "Slide containers and editable slide content."),
                Native(LegacyPptFeature.SlideOrder, "Structure", "Display-order slide directory entries."),
                Native(LegacyPptFeature.SlideVisibility, "Structure", "Hidden-slide state."),
                Blocked(LegacyPptFeature.Sections, "Structure", "Modern presentation sections.",
                    "PowerPoint 97-2003 has no native section model."),
                new LegacyPptCapability(LegacyPptFeature.CustomShows, "Structure",
                    "Named custom slide shows.", LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native, LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native, LegacyPptCapabilityState.Native,
                    "NamedShows records decode to typed ordered slide-id sequences and project to native custom-show lists. Fresh PPT/POT/PPS writing and imported add/edit/remove preserve custom-show membership and identity incrementally. Custom-show actions, including show-and-return, project and round-trip natively."),
                new LegacyPptCapability(LegacyPptFeature.Masters, "Design",
                    "Main, title, notes, and handout masters.",
                    LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Blocked,
                    "Main and title master records, supported shapes, and title/body/other text styles through five levels are projected into native master/layout parts, including PPT9 automatic-numbering defaults. Fresh binary writing emits the referenced Open XML slide-master, notes-master, and handout-master topology; exact supported main-, notes-, and handout-master text, AutoShape, connector, group, and raster/metafile picture drawings; context-specific placeholder kinds; base and PPT9 title/body/other text-style atoms; referenced font-collection entries; and matching OfficeArt drawing-cluster counts. Imported supported main-master text-style edits append preservation-aware base and PPT9 records while retaining other text categories and unrelated programmable tags. Imported main-, title-, notes-, and handout-master position, size, and structurally plain text edits likewise append preservation-aware master persist objects. Binary title masters map to exact named layout parts and support preservation-aware shape, theme, color-scheme, background, and parent-master-shape visibility edits. Unsupported master objects, rich shape styling, interactions, transitions, timing, and unprojected later-version style fields are loss-blocked. Fresh authoring allocates slide-master, notes-master, slide, notes-page, and handout persist and drawing identifiers dynamically up to the binary format's persist-directory and OfficeArt limits. DocumentAtom notes and handout master references, schemes, shapes, placeholders, and connector rules project into native notesMaster and handoutMaster parts."),
                new LegacyPptCapability(LegacyPptFeature.Layouts, "Design",
                    "Slide layout and master inheritance.", LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native, LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Preserved, LegacyPptCapabilityState.Converted,
                    "All 14 SlideLayoutType values and their eight-slot placeholder signatures decode to typed metadata and distinct native Open XML layouts under the referenced master. Supported PPTX layouts write native binary hints for fresh and incrementally appended slides. Layout placeholder geometry, supported decorative shapes, backgrounds, and theme overrides are materialized into each owning binary slide when not overridden, preserving the visible layout despite the classic format having no independent PPTX-style layout persist object. Imported ordinary-layout type changes update each affected SlideAtom; newly added supported layout shapes and placeholders append native OfficeArt shape containers to every affected existing slide while retaining original shape records and drawing-cluster integrity. Imported layout background or theme edits likewise append one updated persist object per affected slide. Slide, title-layout, and notes-page master-shape visibility maps to schema-valid root attributes and native inheritance flags, including preservation-aware imported edits. Exact layouts projected from independent binary title-master persist objects support preservation-aware shape, theme, color-scheme, background, and visibility edits. Picture-bearing ordinary layouts without an owning slide, relationship-bearing layout additions, mutations or removals of pre-existing synthetic ordinary-layout shapes, and unsupported richer layout objects are explicitly loss-blocked."),
                new LegacyPptCapability(LegacyPptFeature.Themes, "Design",
                    "Theme colors, fonts, fills, lines, and effects.",
                    LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Native,
                    "PowerPoint 2007+ RoundTripTheme12Atom OPC packages and RoundTripColorMapping12Atom XML decode to a typed full-theme model and project to native theme or theme-override parts on main, title, notes, handout, slide, layout, and notes-page scopes. Fresh PPT/POT/PPS writing emits deterministic full DrawingML theme packages and color mappings, preserving all twelve colors, font schemes, fill/line/effect schemes, object defaults, and theme overrides; slide and notes-page color overrides also emit and select a synchronized classic eight-color fallback. Unmodified imported theme records are byte-preserved. Imported main-, title-, notes-, and handout-master theme edits plus edits to existing imported slide and notes-page theme overrides append preservation-aware persist objects while retaining unrelated source records and synchronizing changed classic fallback colors. Ordinary imported layout theme overrides materialize into every affected slide."),
                new LegacyPptCapability(LegacyPptFeature.ColorSchemes, "Design",
                    "Legacy master and slide color schemes.",
                    LegacyPptRepresentability.Approximation,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Converted,
                    "All eight classic scheme colors decode and map consistently between binary background/text/shadow/title/fill/accent slots and Open XML Light1/Dark1/Accent4/Dark2/Light2/Accent1/Accent2/Accent3. Fresh PPT/POT/PPS writing emits a distinct native classic scheme for every referenced master plus slide and notes-page color overrides, and no-op imported saves preserve original scheme records. The DrawingML round-trip theme extension preserves PPTX Accent5, Accent6, hyperlink, and followed-hyperlink colors exactly while retaining the classic eight-color fallback. Imported main-, title-, notes-, handout-master, and existing slide or notes-page theme color edits append synchronized native classic and DrawingML scheme records; ordinary layout color overrides materialize into affected slides."),
                new LegacyPptCapability(LegacyPptFeature.Placeholders, "Design",
                    "Placeholder identity, type, size, and inheritance.",
                    LegacyPptRepresentability.Native, LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native, LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Native,
                    "PlaceholderAtom position, all legacy kinds, full/half/quarter size, and vertical orientation project to native placeholder index/type/size/orientation on masters, generated layouts, and slides. Fresh main-, notes-, and handout-master drawings plus fresh or incrementally appended binary slides encode the corresponding context-specific placeholder kinds and fields. Supported identity, type, size, orientation, addition, and removal edits on imported slide and main-, title-, notes-, or handout-master placeholders append preservation-aware client-data and layout-signature updates; custom prompts and context-incompatible vertical kinds are loss-blocked. Object payloads are tracked by their separate capability rows."),
                new LegacyPptCapability(LegacyPptFeature.Backgrounds, "Design",
                    "Master and slide backgrounds.", LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Blocked,
                    "OfficeArt background shapes are distinguished from normal drawing content. Solid, no-fill, inherited, multi-stop linear/path gradient, texture, and picture backgrounds project to native Open XML fills on slides and all master types. Fresh PPT/POT/PPS writing emits explicit solid, no-fill, multi-stop linear, scaled, centered-path, and shape-path gradients plus stretched embedded raster or metafile picture backgrounds on slides, notes pages, main masters, notes masters, and handout masters. Picture backgrounds share the document BLIP catalog, deduplicate identical payloads, and materialize layout backgrounds onto each affected slide. The classic foreground/background opacity ramp preserves linearly interpolated gradient-stop opacity. Supported imported slide, notes-page, main-, title-, notes-, and handout-master background edits, including stretched picture additions, replacements, and removals, append preservation-aware records. Picture edits retain the original document and Pictures streams as exact prefixes, balance existing BLIP reference counts, and append deduplicated delayed BLIPs; ordinary PPTX-layout background edits materialize into every affected imported slide. Gradient focus, custom path rectangles, non-linear stop opacity, pattern fills, tiled or cropped pictures, picture effects, and exact texture semantics without a safe classic mapping are explicitly loss-blocked during conversion."),
                new LegacyPptCapability(LegacyPptFeature.PlainText, "Text",
                    "Unicode and byte text projected as editable plain text.", LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native, LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native, LegacyPptCapabilityState.Native,
                    "Unicode and byte text project editably, write natively for fresh PPT/POT/PPS files and appended slides, and support arbitrary-length preservation-aware edits. Text bodies with unprojected or malformed style structures are retained for unrelated edits and explicitly loss-blocked for text replacement."),
                new LegacyPptCapability(LegacyPptFeature.RichText, "Text",
                    "Character runs, fonts, sizes, colors, and emphasis.", LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native, LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Preserved, LegacyPptCapabilityState.Native,
                    "StyleTextPropAtom character runs and base TextMasterStyleAtom defaults project bold, italic, underline, point size, direct or mapped scheme color, baseline position, and document font-collection typefaces natively. TextSpecialInfoAtom runs project and write stable primary and alternate language LCIDs, no-proofing, spelling-error, and recheck state on text and paragraph-end markers. Fresh slide and master text plus appended slides write the same fields and add referenced document-font entries. Supported imported run formatting, language, proofing, and length edits append replacement style and special-info records while preserving unrelated records. Embedded font programs, later-version style extensions, smart tags, grammar-only flags, bidirectional analysis flags, transient LCIDs, mixed explicit no-language ranges, and legacy-only character effects remain preserve-only and are loss-blocked when an edit would replace them."),
                new LegacyPptCapability(LegacyPptFeature.ParagraphFormatting,
                    "Text", "Alignment, indentation, spacing, tabs, and margins.",
                    LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Native,
                    "StyleTextPropAtom runs, TextRulerAtom records, and five-level base master styles project alignment, margins, first-line indentation, default and explicit tabs, line and paragraph spacing, level, font alignment, RTL direction, East Asian breaking, Latin word wrapping, and hanging punctuation natively. Fresh slide and master text writes those fields, and supported imported shape, ruler, and master-style edits append preservation-aware records. Later-version fields without an exact mapping remain preserved for unrelated edits and are explicitly loss-blocked when changed."),
                new LegacyPptCapability(LegacyPptFeature.BulletsAndNumbering,
                    "Text", "Bullet glyphs, pictures, numbering, and levels.",
                    LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    "Base character bullets project and write native enabled/disabled state, glyph, resolved font and color, relative or point size, level, and ruler indentation. PPT9 StyleTextProp9Atom and TextMasterStyle9Atom extensions decode and author all 41 classic automatic-numbering schemes with exact start values. PPT9 picture-bullet collections and references import and author with exact image bytes. Fresh files and append-only imported shape or supported main-master edits support bullet or numbering add, change, and removal while preserving unrelated programmable-tag data."),
                new LegacyPptCapability(LegacyPptFeature.TextAutoFit, "Text",
                    "Text fitting, wrapping, and text-box inset behavior.",
                    LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Blocked,
                    "Classic OfficeArt text insets, square or no wrapping, vertical anchoring, horizontal/vertical/vertical-270 flow, explicit no-autofit, and resize-shape-to-fit-text project, author, and edit natively. DrawingML shrink-text normal autofit, including font-scale and line-space-reduction options, has no lossless classic binary PowerPoint mapping and is explicitly loss-blocked during PPTX conversion."),
                new LegacyPptCapability(LegacyPptFeature.Hyperlinks,
                    "Interaction", "Text and shape hyperlinks.",
                    LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Blocked,
                    "ExObjList, ExHyperlink, and PP9 ExHyperlink9 records decode to typed external and internal-slide targets plus screen tips. Shape and text click/hover interactions write to fresh PPT/POT/PPS files and support preservation-aware add/edit/remove, retargeting, slide reordering, and appended slides. Binary-only extension flags remain preserved when untouched. Target frames and richer Open XML hyperlink metadata without a classic representation are explicitly loss-blocked during conversion."),
                new LegacyPptCapability(LegacyPptFeature.Actions,
                    "Interaction", "Shape actions, slide jumps, and programs.",
                    LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Blocked,
                    "InteractiveInfoAtom click and mouse-over records decode to typed action metadata. Built-in slide-show jumps, macro names, program targets, named custom shows with show-and-return, animated-highlight state, stop-sound state, and referenced embedded sounds project and write natively, including preservation-aware add/edit/remove. Legacy OLE or media activation and visited-state behavior remain preserve-only; Open XML actions without an exact classic action are explicitly loss-blocked."),
                new LegacyPptCapability(LegacyPptFeature.AutoShapes, "Drawing",
                    "OfficeArt AutoShape geometry.",
                    LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Blocked,
                    "OfficeArt preset geometry with a DrawingML equivalent is projected as an editable native shape, including arrows, callouts, flowcharts, ribbons, stars, and action buttons. Fresh PPT/POT/PPS writing maps the canonical classic preset families back to native OfficeArt shape types. All eight signed adjustment slots are decoded without losing their shape-specific meaning; exact round-rectangle and donut adjustments project, author, and edit natively. Unmodified imported geometry is byte-preserved, and supported transform or style edits retain it. Other edited preset adjustments, custom geometry, text warps, and DrawingML-only presets are explicitly loss-blocked to prevent silent geometry changes."),
                new LegacyPptCapability(LegacyPptFeature.Connectors,
                    "Drawing", "Connector shapes and connection sites.",
                    LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Blocked,
                    "Straight, bent, and curved OfficeArt connectors are projected as native editable connection shapes. Fresh unattached connectors write native OfficeArt geometry, transforms, line styling, and arrowheads. Solver rules preserve imported start/end shape attachments and connection-site indexes, while supported top-level transform and style edits append preservation-aware records. Fresh or edited attachment rules are explicitly loss-blocked because emitting a different binary solver graph could silently change connectivity."),
                new LegacyPptCapability(LegacyPptFeature.Groups, "Drawing",
                    "Nested drawing groups and child coordinate systems.",
                    LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Native,
                    "Nested OfficeArt group hierarchies and child coordinate systems project as native editable Open XML groups. Fresh PPT/POT/PPS writing emits real nested group containers, group coordinate records, child anchors, and recursively cataloged pictures and interactions. Imported outer or child bounds, rotation, flips, visual style, supported geometry adjustments, and group-coordinate edits append preservation-aware records. Imported reparenting, child addition or removal, and explicit z-order changes remain loss-blocked."),
                new LegacyPptCapability(LegacyPptFeature.ShapeTransforms,
                    "Drawing", "Position, size, rotation, flip, and z-order.",
                    LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Native,
                    "Position, size, clockwise rotation, and horizontal or vertical mirroring are projected for mapped shapes, pictures, connectors, and nested groups. Fresh slide, master, and nested child shapes write native OfficeArt anchors, rotation, and flip flags. Imported slide, supported master, group, and child transform edits append incremental FSP, FOPT, anchor, child-anchor, and group-coordinate records while preserving unrelated rich properties. Reparenting and explicit z-order edits remain loss-blocked."),
                new LegacyPptCapability(LegacyPptFeature.ShapeStyles, "Drawing",
                    "Fill, outline, transparency, and shape properties.", LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Blocked,
                    "Shared OfficeArt FOPT decoding projects explicit solid RGB and scheme fills plus linear, scaled, centered-path, shape-path, and title gradients with resolved endpoint or multi-stop colors, opacity ramps, and page-oriented angles. Fill visibility, per-shape hidden state, line width, preset dashes, joins, caps, arrowheads, and offset-shadow style also project natively. Fresh shapes and supported imported slide, group-child, and master edits write solid RGB or no-fill state, per-shape hidden state, fill and line opacity, outline width, dash, join, cap, and arrowhead type and dimensions natively while retaining unrelated source properties. Gradient authoring or editing, focused or custom-path gradients, theme-referenced colors, patterns, image fills, group defaults, and richer DrawingML style references without an exact classic mapping are explicitly loss-blocked."),
                new LegacyPptCapability(LegacyPptFeature.ShapeEffects,
                    "Drawing", "Shadows and legacy OfficeArt effects.",
                    LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Blocked,
                    "Enabled offset shadows project as native DrawingML outer shadows with resolved color, opacity, signed direction, distance, and available softness. Fresh shapes and supported imported edits write or clear one RGB outer shadow with opacity, distance, direction, and softness while preserving unrelated OfficeArt properties. Double, rich, shape, drawing-plane, emboss/engrave, scaled or skewed, rotating, group-level, glow, reflection, soft-edge, and multiple DrawingML effects without a classic equivalent are explicitly loss-blocked."),
                new LegacyPptCapability(LegacyPptFeature.RasterPictures, "Images",
                    "PNG, JPEG, DIB, and TIFF BLIP records.", LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native, LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Preserved, LegacyPptCapabilityState.Native,
                    "Shared OfficeArt decoding resolves embedded and delayed picture stores, normalizes DIB data to BMP, and projects referenced slide, master, layout, and grouped pictures as editable Open XML image parts. Fresh PPT/POT/PPS writing embeds PNG, JPEG, BMP/DIB, and TIFF BLIPs, deduplicates identical payloads with accurate reference counts, and writes top-level or grouped picture frames natively on slides plus main, notes, and handout masters; referenced ordinary-layout pictures materialize into each affected slide, while unused picture-bearing layouts are loss-blocked. Fresh pictures and imported slide pictures write supported transform, frame style, crop, brightness, contrast, grayscale, classic bi-level, transparent-color, recolor, protection-lock, and simple shadow properties. Imported image replacement, linked images, unsupported effect sequences or vector formats, and picture additions to exact imported binary title masters remain loss-blocked."),
                new LegacyPptCapability(LegacyPptFeature.MetafilePictures,
                    "Images", "WMF and EMF BLIP records.",
                    LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Native,
                    "Shared OfficeArt decoding extracts compressed and uncompressed WMF/EMF payloads for editable image projection. Fresh PPT/POT/PPS writing emits standards-compliant zlib-compressed OfficeArt metafile BLIPs in the delayed Pictures stream, including source bounds and render dimensions parsed from EMF or placeable-WMF headers. Imported geometry edits and no-op saves preserve source content; imported image replacement and non-placeable WMF authoring remain loss-blocked."),
                new LegacyPptCapability(LegacyPptFeature.PictureCrop, "Images",
                    "Picture crop, transform, and recolor properties.",
                    LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native, LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Preserved, LegacyPptCapabilityState.Native,
                    "All four signed OfficeArt crop edges decode as 16.16 image fractions and project natively for slide, master, layout, and grouped pictures, including negative crop-out values. Fresh pictures and preservation-aware imported edits write the same crop properties. Brightness, contrast, grayscale, classic 50-percent bi-level, transparent-color, and whole-picture recolor state project as native DrawingML effects and write back through primary or tertiary OfficeArt properties. Arbitrary bi-level thresholds and other DrawingML effect sequences remain loss-blocked."),
                new LegacyPptCapability(LegacyPptFeature.Tables, "Content",
                    "Native OfficeArt tables and cell formatting.",
                    LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    "OfficeArt table groups project as editable DrawingML tables with semantic rows, columns, cell text, rich runs, hyperlinks, explicit RGB fills and borders, dimensions, and drawing order. Fresh PPT/POT/PPS writing and PPTX conversion emit native editable OfficeArt table groups rather than PNG fallbacks. Merged-cell writing and table-style features without an exact classic representation are explicitly loss-blocked; imported merged cells can still project when their native cell geometry exposes the complete grid."),
                new LegacyPptCapability(LegacyPptFeature.Charts, "Content",
                    "Legacy Microsoft Graph and embedded chart objects.",
                    LegacyPptRepresentability.Approximation,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Converted,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Converted,
                    "Supported editable DrawingML charts convert explicitly to deterministic static PNG picture frames through the shared OfficeIMO chart renderer. Default saving is blocked by PPT-WRITE-CHART-CONVERTED until PowerPointSaveOptions.LossPolicy is Allow; converted files preserve chart bounds and visible data but not chart editability or the embedded workbook. Existing legacy Microsoft Graph objects remain preserve-only through the embedded-OLE lane; editable Graph import and direct native Graph authoring are explicitly outside the conversion contract and structural edits are loss-blocked."),
                new LegacyPptCapability(LegacyPptFeature.SmartArt, "Content",
                    "SmartArt diagrams.", LegacyPptRepresentability.Approximation,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Converted,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Converted,
                    "Readable SmartArt node data maps to the shared semantic process, hierarchy, or cycle diagram contract and converts explicitly to a deterministic static PNG picture frame. Unknown SmartArt layout categories use the process approximation while retaining node order. Default saving is blocked by PPT-WRITE-SMARTART-CONVERTED until PowerPointSaveOptions.LossPolicy is Allow; the converted visual preserves bounds and node text but not SmartArt structure or editability. Legacy binary diagram records are preserve-only; editable legacy diagram projection and direct native diagram authoring are explicitly loss-blocked."),
                new LegacyPptCapability(LegacyPptFeature.SpeakerNotes, "Presentation",
                    "Editable speaker notes.", LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native, LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native, LegacyPptCapabilityState.Native,
                    "SlideAtom notes identifiers resolve through NotesPersistAtom entries to typed NotesContainer pages. Plain note text projects editably, fresh PPT/POT/PPS writing emits native notes directories and persist objects, and structurally plain imported note edits append preservation-aware records. Length-changing edits to styled note bodies remain loss-blocked."),
                new LegacyPptCapability(LegacyPptFeature.RichNotes,
                    "Presentation", "Notes-page drawings and formatting.",
                    LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Blocked,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Blocked,
                    "NotesAtom inheritance, schemes, backgrounds, placeholders, rich text, supported drawings, pictures, groups, and connector rules project into native notesSlide parts. Fresh binary notes-page theme overrides, classic color fallbacks, and supported backgrounds write natively; imported theme, classic-color, background, and structurally plain body-text edits compose into preservation-aware records. Speaker-note text has its own fully native capability lane. Fresh arbitrary notes-page drawings and broader notes drawing or rich-format edits are explicitly loss-blocked rather than silently omitted."),
                new LegacyPptCapability(LegacyPptFeature.HeadersAndFooters, "Presentation",
                    "Date, footer, header, and slide-number settings.",
                    LegacyPptRepresentability.Native, LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native, LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Native,
                    "Document slide defaults, notes/handout defaults, main-master and per-slide overrides decode with all six flags, date format ids, and fixed strings. Native Open XML master/layout settings project back to binary PPT/POT/PPS. Imported per-slide flag and text edits append preservation-aware records; edits to shared binary master/default scopes remain loss-blocked."),
                new LegacyPptCapability(LegacyPptFeature.Comments, "Review",
                    "Classic comment authors and comment records.",
                    LegacyPptRepresentability.Native, LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native, LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    "PowerPoint 2000-2003 PP10 comments decode with author, initials, text, index, UTC creation time, and master-unit position. Classic comments project editably, write natively to PPT/POT/PPS, and imported additions, edits, and removals append preservation-aware slide records without replacing unrelated PP10 tag data."),
                Blocked(LegacyPptFeature.ModernComments, "Review",
                    "Modern threaded comments, replies, status, and shape anchors.",
                    "PowerPoint 97-2003 has no native threaded-comment model; conversion is explicitly loss-blocked."),
                new LegacyPptCapability(LegacyPptFeature.Transitions, "Presentation",
                    "Slide transitions, speed, and advance settings.",
                    LegacyPptRepresentability.Native, LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native, LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Blocked,
                    "Every PowerPoint 97-2003 transition effect and valid direction projects to an exact editable PresentationML transition, including cut/fade-through-black variants, wheel spoke counts, and all directional effects. Fresh PPT/POT/PPS writing and preservation-aware imported edits encode the full classic effect table, all three legacy speeds, click advance, timed advance, and transition sound actions. Modern transitions without a binary equivalent are loss-blocked."),
                new LegacyPptCapability(LegacyPptFeature.TransitionAndActionSounds,
                    "Media", "Embedded WAV/AIFF sounds referenced by transitions and actions.",
                    LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Blocked,
                    "SoundCollection, Sound, sound-name, extension, identifier, built-in identifier, and data-blob records decode to one shared typed sound library. Transition and shape/text click or hover references project through deduplicated Open XML audio relationships. Fresh writing and incremental add/replace edits retain stable identifiers and exact audio bytes. PPTX sources using non-WAV/AIFF audio or built-in=true without an unambiguous imported numeric ID are explicitly loss-blocked."),
                new LegacyPptCapability(LegacyPptFeature.Animations,
                    "Presentation",
                    "Classic top-level shape and text entrance animations and their constrained PresentationML equivalents.",
                    LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Blocked,
                    "The complete 28-byte AnimationInfoAtom decodes to the typed binary model, including flags, sound reference, delay, order, slide count, build type, classic effect and direction, after-effect, text subdivision, OLE verb, raw dim color, and reserved trailing bytes. Supported top-level shape animations project to editable PresentationML timing, write natively to PPT/POT/PPS, and can be added, replaced, or removed through preservation-aware incremental records with shared embedded sounds. Recognizable PPTX entrance animEffect/bldP sequences—including PowerPoint's visibility-set scaffold—convert to the exact classic subset. With-previous concurrency, exit/emphasis effects, motion paths, arbitrary property/color/scale/rotation/set/command behavior, media timing, custom after-effect trees, and other modern timing semantics are explicitly loss-blocked; inline sound overrides and imported group-child animation edits remain preservation-guarded until their owning media and group paths are implemented."),
                new LegacyPptCapability(LegacyPptFeature.Media, "Media",
                    "Embedded WAV audio media.",
                    LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Native,
                    "ExWAVAudioEmbeddedContainer and ExMediaAtom records resolve document SoundCollection WAV payloads into editable PowerPointMedia audio shapes with exact bytes, duration, and geometry. Fresh PPT/POT/PPS authoring and PPTX conversion emit native media objects and deduplicate their sound data with transitions and actions. Imported position and size edits append preservation-aware records; payload replacement and loop, rewind, or narration edits remain loss-blocked."),
                Blocked(LegacyPptFeature.EmbeddedVideo, "Media",
                    "Embedded video media.",
                    "PowerPoint 97-2003 has path-based AVI and MCI movie objects but no native embedded-video payload representation; implicit extraction to an external path is deliberately loss-blocked."),
                new LegacyPptCapability(LegacyPptFeature.LinkedMedia,
                    "Media", "Linked and device-based audio or movies.",
                    LegacyPptRepresentability.Opaque,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Blocked,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Blocked,
                    "AVI, MCI movie, MIDI, linked WAV, and CD-audio containers decode to typed path, device-range, and playback metadata. Their source records and visible preview remain preservation-aware, while authoring and Open XML conversion are loss-blocked because external path, codec, and device semantics are not safely portable."),
                new LegacyPptCapability(LegacyPptFeature.EmbeddedOle,
                    "Embedded", "Embedded OLE compound objects.",
                    LegacyPptRepresentability.Opaque,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Native,
                    "ExOleEmbedContainer metadata, ExObjRefAtom shape references, and compressed or uncompressed ExOleObjStg records decode to an editable PowerPointOleObject with exact compound-storage bytes. Fresh PPT/POT/PPS writing emits native embedded-object metadata, storage, shape references, and embedded raster or metafile preview images through the shared BLIP catalog, including supported crop and picture effects. Imported geometry, ProgID, icon/content view, color-follow, and storage replacement use preservation-aware incremental records while untouched metadata, preview pictures, compound streams, and compressed source records remain exact. Malformed storage, unsupported related parts, linked previews, and non-representable preview metadata are loss-blocked rather than silently discarded."),
                new LegacyPptCapability(LegacyPptFeature.LinkedOle,
                    "Embedded", "Linked OLE objects and cached compound storages.",
                    LegacyPptRepresentability.Opaque,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Blocked,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Blocked,
                    "ExOleLinkContainer metadata, ExObjRefAtom shape references, automatic or manual update mode, optional icon metafile, and compressed or uncompressed ExOleObjStg cache records decode to a typed neutral model with exact compound-storage bytes. No-op saves and unrelated supported binary edits retain the source records and storage exactly. New linked-object authoring and projection to Open XML remain loss-blocked because the external moniker and cached native state cannot yet be mapped safely."),
                new LegacyPptCapability(LegacyPptFeature.ActiveX,
                    "Embedded", "ActiveX controls and associated storages.",
                    LegacyPptRepresentability.Opaque,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Blocked,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Blocked,
                    "ExControlContainer metadata, ExObjRefAtom shape references, optional icon metafile, and compressed or uncompressed ExControlStg records decode to a typed neutral model with exact Office Forms storage bytes. No-op saves and unrelated supported binary edits retain the source records and storage exactly. Control authoring, property editing, and Open XML projection remain loss-blocked until the binary control state can be mapped without changing behavior."),
                new LegacyPptCapability(LegacyPptFeature.VbaProjects,
                    "Embedded", "VBA project storage.",
                    LegacyPptRepresentability.Opaque,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Native,
                    "VBAInfoContainer references and compressed or uncompressed VbaProjectStg records decode to the normal Open XML VbaProjectPart. Fresh PPT/POT/PPS writing emits the native uncompressed structured-storage form. Unmodified imported projects retain their exact source record bytes; project replacement, addition, and removal use preservation-aware incremental persist records while retaining unrelated compound streams. Malformed projects and Open XML VBA projects with related signature or data parts remain loss-blocked."),
                new LegacyPptCapability(LegacyPptFeature.BuiltInProperties,
                    "Metadata", "Summary and document-summary properties.",
                    LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Native,
                    "SummaryInformation and DocumentSummaryInformation project title, subject, creator, keywords, description, category, revision, edit/print/create/modified times, application, presentation format, slide/note/hidden counts, manager, and company to the normal package and application-property surfaces. Fresh PPT/POT/PPS writing emits Unicode property sets. Supported imported edits replace only the owning compound stream; unrelated binary edits retain unknown properties byte-for-byte, while a metadata edit that would discard an unknown property id or type is loss-blocked."),
                new LegacyPptCapability(LegacyPptFeature.CustomProperties,
                    "Metadata", "Custom document properties.",
                    LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Preserved,
                    LegacyPptCapabilityState.Native,
                    "UserDefinedProperties dictionaries and text, Boolean, date/time, floating-point, signed/unsigned integer, and binary values project to the native Open XML custom-properties part and write to fresh PPT/POT/PPS files. Supported imported add/edit/remove operations rewrite only DocumentSummaryInformation; unrecognized property sections or variants remain byte-preserved for unrelated edits and loss-block metadata changes."),
                Blocked(LegacyPptFeature.CustomXml, "Metadata", "Open XML custom XML parts.",
                    "PowerPoint 97-2003 has no equivalent package-part representation."),
                new LegacyPptCapability(LegacyPptFeature.Encryption, "Security",
                    "Binary RC4 CryptoAPI password encryption.",
                    LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native,
                    "Password-protected PPT/POT/PPS files decode and encode through the normal detached encrypted-load/save APIs. The Current User token, canonical single UserEdit and PersistDirectory records, CryptSession10Container, per-persist-object keys, and field-scoped Pictures transforms follow the binary PowerPoint encryption contract. SHA-1 RC4 CryptoAPI keys from 40 through 128 bits are supported. EncryptedSummary document properties are restored on import and encrypted by default on save; callers can explicitly retain clear-text properties for compatibility. RC4 CryptoAPI is provided only for legacy interoperability and is not a modern security choice."),
                new LegacyPptCapability(LegacyPptFeature.DigitalSignatures, "Security",
                    "Legacy digital-signature streams and storages.", LegacyPptRepresentability.Opaque,
                    LegacyPptCapabilityState.Preserved, LegacyPptCapabilityState.Blocked,
                    LegacyPptCapabilityState.Preserved, LegacyPptCapabilityState.Blocked,
                    "The root _signatures stream and complete _xmlsignatures storage are detected and reported. Exact no-op saves preserve the signed package byte-for-byte. Edited binary saves block by default; callers can explicitly retain the invalidated carrier for preservation-aware edits or remove both carriers. Creating signatures and translating Open XML signatures into the binary formats are outside the writer contract."),
                new LegacyPptCapability(LegacyPptFeature.AccessibilityMetadata, "Accessibility",
                    "Alternative text and object names.", LegacyPptRepresentability.Native,
                    LegacyPptCapabilityState.Native, LegacyPptCapabilityState.Native,
                    LegacyPptCapabilityState.Native, LegacyPptCapabilityState.Native,
                    "OfficeArt object names and descriptions decode and project to native non-visual metadata for supported slide, master, layout, group, connector, picture, media, OLE, and converted static-visual shapes. Fresh PPT/POT/PPS writing and preservation-aware imported edits add, replace, or remove the native Unicode name and description properties while retaining unrelated OfficeArt properties. Modern accessibility titles and decorative state have no classic binary representation and are explicitly loss-blocked."),
                new LegacyPptCapability(LegacyPptFeature.UnknownRecordsAndStreams, "Preservation",
                    "Unknown live records and compound streams.", LegacyPptRepresentability.Opaque,
                    LegacyPptCapabilityState.Preserved, LegacyPptCapabilityState.Blocked,
                    LegacyPptCapabilityState.Preserved, LegacyPptCapabilityState.Blocked,
                    "No-op saves retain the exact package. Supported mapped slide, master, layout, text, drawing, interaction, notes, theme, property, OLE, VBA, and security-policy edits append a UserEdit or replace only the owning compound stream while preserving untouched records, storages, and streams. Any edit whose owning record family cannot be isolated safely is explicitly loss-blocked.")
            });

        private static readonly IReadOnlyDictionary<LegacyPptFeature, LegacyPptCapability> CapabilityByFeature =
            new ReadOnlyDictionary<LegacyPptFeature, LegacyPptCapability>(CapabilityRows.ToDictionary(row => row.Feature));

        /// <summary>Gets the contract schema version.</summary>
        public static int SchemaVersion => 1;

        /// <summary>Gets every capability row in stable feature order.</summary>
        public static IReadOnlyList<LegacyPptCapability> Capabilities => CapabilityRows;

        /// <summary>Gets whether any capability lane still contains planned parity work.</summary>
        public static bool HasRemainingParityWork => CapabilityRows.Any(row => row.HasRemainingParityWork);

        /// <summary>Gets all capability rows that still require implementation.</summary>
        public static IReadOnlyList<LegacyPptCapability> RemainingParityWork => CapabilityRows
            .Where(row => row.HasRemainingParityWork)
            .ToArray();

        /// <summary>Gets the contract row for a feature.</summary>
        public static LegacyPptCapability Get(LegacyPptFeature feature) {
            if (!CapabilityByFeature.TryGetValue(feature, out LegacyPptCapability? capability)) {
                throw new ArgumentOutOfRangeException(nameof(feature), feature, "The feature is not present in the capability contract.");
            }
            return capability;
        }

        private static LegacyPptCapability Native(LegacyPptFeature feature, string category, string description) =>
            new LegacyPptCapability(feature, category, description, LegacyPptRepresentability.Native,
                LegacyPptCapabilityState.Native, LegacyPptCapabilityState.Native,
                LegacyPptCapabilityState.Native, LegacyPptCapabilityState.Native, string.Empty);

        private static LegacyPptCapability Blocked(LegacyPptFeature feature, string category, string description,
            string note) =>
            new LegacyPptCapability(feature, category, description, LegacyPptRepresentability.NotRepresentable,
                LegacyPptCapabilityState.Blocked, LegacyPptCapabilityState.Blocked,
                LegacyPptCapabilityState.Blocked, LegacyPptCapabilityState.Blocked, note);
    }
}
