using System.Collections.Generic;
using System.Linq;

namespace OfficeIMO.Visio {
    /// <summary>
    /// Result returned by <see cref="VisioDesktopValidator"/>.
    /// </summary>
    public sealed class VisioDesktopValidationResult {
        internal VisioDesktopValidationResult(bool isAvailable, bool isValid, string? version, IEnumerable<string> issues) {
            IsAvailable = isAvailable;
            IsValid = isValid;
            Version = version;
            Issues = issues.ToList().AsReadOnly();
            OutputFiles = new List<string>().AsReadOnly();
        }

        internal VisioDesktopValidationResult(bool isAvailable, bool isValid, string? version, IEnumerable<string> issues, IEnumerable<string> outputFiles) {
            IsAvailable = isAvailable;
            IsValid = isValid;
            Version = version;
            Issues = issues.ToList().AsReadOnly();
            OutputFiles = outputFiles.ToList().AsReadOnly();
        }

        /// <summary>
        /// Gets whether Microsoft Visio desktop automation was available on this machine.
        /// </summary>
        public bool IsAvailable { get; }

        /// <summary>
        /// Gets whether Visio desktop opened the document successfully.
        /// </summary>
        public bool IsValid { get; }

        /// <summary>
        /// Gets the detected Visio version when available.
        /// </summary>
        public string? Version { get; }

        /// <summary>
        /// Gets validation issues or availability diagnostics.
        /// </summary>
        public IReadOnlyList<string> Issues { get; }

        /// <summary>
        /// Gets files generated by optional save-copy or export validation steps.
        /// </summary>
        public IReadOnlyList<string> OutputFiles { get; }
    }
}
