using PdfCore = OfficeIMO.Pdf;

namespace OfficeIMO.Rtf.Pdf;

/// <summary>
/// Provides extension methods for converting <see cref="RtfDocument"/> instances and RTF strings to PDF files.
/// </summary>
public static class RtfPdfConverterExtensions {
    /// <summary>Converts an RTF document to a first-party OfficeIMO PDF document model.</summary>
    public static PdfCore.PdfDocument ToPdfDocument(this RtfDocument document, RtfPdfSaveOptions? options = null) {
        if (document == null) {
            throw new ArgumentNullException(nameof(document));
        }

        return RtfPdfConverter.Convert(document, options);
    }

    /// <summary>Reads an RTF string and converts it to a first-party OfficeIMO PDF document model.</summary>
    public static PdfCore.PdfDocument ToPdfDocument(this string rtf, RtfReadOptions? readOptions = null, RtfPdfSaveOptions? options = null) {
        if (rtf == null) {
            throw new ArgumentNullException(nameof(rtf));
        }

        return RtfDocument.Read(rtf, readOptions).Document.ToPdfDocument(options);
    }

    /// <summary>Saves an RTF document as PDF at the specified path.</summary>
    public static void SaveAsPdf(this RtfDocument document, string path, RtfPdfSaveOptions? options = null) {
        if (document == null) {
            throw new ArgumentNullException(nameof(document));
        }

        document.ToPdfDocument(options).Save(path);
    }

    /// <summary>Saves an RTF string as PDF at the specified path.</summary>
    public static void SaveAsPdf(this string rtf, string path, RtfReadOptions? readOptions = null, RtfPdfSaveOptions? options = null) {
        if (rtf == null) {
            throw new ArgumentNullException(nameof(rtf));
        }

        rtf.ToPdfDocument(readOptions, options).Save(path);
    }

    /// <summary>Saves an RTF document as PDF to a writable stream.</summary>
    public static void SaveAsPdf(this RtfDocument document, Stream stream, RtfPdfSaveOptions? options = null) {
        if (document == null) {
            throw new ArgumentNullException(nameof(document));
        }

        if (stream == null) {
            throw new ArgumentNullException(nameof(stream));
        }

        document.ToPdfDocument(options).Save(stream);
        if (stream.CanSeek) {
            stream.Position = 0;
        }
    }

    /// <summary>Saves an RTF document as PDF and returns the generated bytes.</summary>
    public static byte[] SaveAsPdf(this RtfDocument document, RtfPdfSaveOptions? options = null) {
        if (document == null) {
            throw new ArgumentNullException(nameof(document));
        }

        return document.ToPdfDocument(options).ToBytes();
    }

    /// <summary>Saves an RTF string as PDF and returns the generated bytes.</summary>
    public static byte[] SaveAsPdf(this string rtf, RtfReadOptions? readOptions = null, RtfPdfSaveOptions? options = null) {
        if (rtf == null) {
            throw new ArgumentNullException(nameof(rtf));
        }

        return rtf.ToPdfDocument(readOptions, options).ToBytes();
    }

    /// <summary>Attempts to save an RTF document as PDF at the specified path and returns diagnostics instead of throwing.</summary>
    public static PdfCore.PdfSaveResult TrySaveAsPdf(this RtfDocument document, string path, RtfPdfSaveOptions? options = null) {
        try {
            if (document == null) {
                throw new ArgumentNullException(nameof(document));
            }

            return document.ToPdfDocument(options).TrySave(path);
        } catch (Exception ex) {
            return PdfCore.PdfSaveResult.FromFailure(path, ex);
        }
    }

    /// <summary>Attempts to save an RTF document as PDF to a stream and returns diagnostics instead of throwing.</summary>
    public static PdfCore.PdfSaveResult TrySaveAsPdf(this RtfDocument document, Stream stream, RtfPdfSaveOptions? options = null) {
        try {
            if (document == null) {
                throw new ArgumentNullException(nameof(document));
            }

            PdfCore.PdfSaveResult result = document.ToPdfDocument(options).TrySave(stream);
            if (result.Succeeded && stream != null && stream.CanSeek) {
                stream.Position = 0;
            }

            return result;
        } catch (Exception ex) {
            return PdfCore.PdfSaveResult.FromFailure(outputPath: null, ex);
        }
    }

    /// <summary>Saves an RTF document as PDF and returns the generated bytes asynchronously.</summary>
    public static async Task<byte[]> SaveAsPdfAsync(this RtfDocument document, RtfPdfSaveOptions? options = null, CancellationToken cancellationToken = default) {
        if (document == null) {
            throw new ArgumentNullException(nameof(document));
        }

        cancellationToken.ThrowIfCancellationRequested();
        using (MemoryStream stream = new MemoryStream()) {
            await document.ToPdfDocument(options).SaveAsync(stream, cancellationToken).ConfigureAwait(false);
            return stream.ToArray();
        }
    }

    /// <summary>Saves an RTF document as PDF at the specified path asynchronously.</summary>
    public static Task SaveAsPdfAsync(this RtfDocument document, string path, RtfPdfSaveOptions? options = null, CancellationToken cancellationToken = default) {
        if (document == null) {
            throw new ArgumentNullException(nameof(document));
        }

        return document.ToPdfDocument(options).SaveAsync(path, cancellationToken);
    }

    /// <summary>Saves an RTF document as PDF to a writable stream asynchronously.</summary>
    public static async Task SaveAsPdfAsync(this RtfDocument document, Stream stream, RtfPdfSaveOptions? options = null, CancellationToken cancellationToken = default) {
        if (document == null) {
            throw new ArgumentNullException(nameof(document));
        }

        if (stream == null) {
            throw new ArgumentNullException(nameof(stream));
        }

        await document.ToPdfDocument(options).SaveAsync(stream, cancellationToken).ConfigureAwait(false);
        if (stream.CanSeek) {
            stream.Position = 0;
        }
    }
}
