namespace OfficeIMO.Email;

internal static class EmailConversionAnalyzer {
    internal static EmailConversionReport Analyze(EmailDocument document, EmailFileFormat targetFormat,
        EmailWriterOptions options, bool preservesAppleMailMetadata = false) {
        if (document == null) throw new ArgumentNullException(nameof(document));
        if (options == null) throw new ArgumentNullException(nameof(options));

        var diagnostics = new List<EmailDiagnostic>();
        bool reusesSource = (options.UsePreservedRawSource || document.Protection.IsProtected) &&
            document.Format == targetFormat && document.RawSource != null &&
            document.RawSourceModelFingerprint != null &&
            EmailDocumentStateFingerprint.Matches(document, document.RawSourceModelFingerprint);
        // Exact artifact reuse serializes no projection, including any embedded models.
        if (!reusesSource) {
            EmailTransportIntegrity.Analyze(document, options, diagnostics, targetFormat == EmailFileFormat.Eml);
            AnalyzeDocumentTree(document, targetFormat, options, preservesAppleMailMetadata, diagnostics);
        }

        return new EmailConversionReport(document.Format, targetFormat, diagnostics.AsReadOnly());
    }

    private static void AnalyzeDocumentTree(EmailDocument root, EmailFileFormat targetFormat,
        EmailWriterOptions options, bool preservesAppleMailMetadata,
        IList<EmailDiagnostic> diagnostics) {
        var pending = new Stack<(EmailDocument Document, string Path, int Depth)>();
        var visited = new HashSet<EmailDocument>();
        pending.Push((root, string.Empty, 0));
        while (pending.Count > 0) {
            var item = pending.Pop();
            if (!visited.Add(item.Document)) continue;
            if (item.Depth > options.MaxNestedMessageDepth)
                throw new EmailLimitExceededException(nameof(options.MaxNestedMessageDepth), item.Depth, options.MaxNestedMessageDepth);
            // Embedded documents are regenerated by every artifact writer; their own raw source
            // is not a pass-through. Exact MIME part reuse is excluded below instead.
            if (item.Document.Protection.IsProtected) {
                Add(CreateLossDiagnostic(options.ConversionLossPolicy,
                    EmailArtifactDiagnosticCodes.ProtectedContentRewrite,
                    "The protected MIME or Outlook wrapper cannot be regenerated without invalidating its signature or encrypted payload. " +
                    "Write the unchanged artifact in its source format, or explicitly choose a non-blocking conversion loss policy.",
                    "protection"));
            }
            var semanticDiagnostics = new List<EmailDiagnostic>();
            if (targetFormat == EmailFileFormat.Eml) semanticDiagnostics.AddRange(AnalyzePortableContent(item.Document, options));
            else AddSemanticMutationDiagnostic(item.Document, options, semanticDiagnostics);
            foreach (EmailDiagnostic diagnostic in semanticDiagnostics) Add(diagnostic);
            if (targetFormat != EmailFileFormat.Eml && item.Document.MimeSemanticProjectionIsIncomplete) {
                Add(CreateLossDiagnostic(options.ConversionLossPolicy,
                    "EMAIL_STORE_SEMANTIC_PROJECTION_INCOMPLETE",
                    "The calendar or vCard contains semantics that cannot be projected completely into MSG/TNEF properties.",
                    "semantic-content"));
            }
            if ((targetFormat == EmailFileFormat.OutlookMsg || targetFormat == EmailFileFormat.OutlookTemplate) &&
                TnefWriter.HasUnmanagedRawAttributes(item.Document)) {
                Add(CreateLossDiagnostic(options.ConversionLossPolicy,
                    "EMAIL_TNEF_ATTRIBUTES_NOT_REPRESENTED_IN_MSG",
                    "Raw TNEF message or attachment attributes cannot be represented in an Outlook MSG artifact.",
                    "source-metadata/tnef"));
            }
            if (targetFormat == EmailFileFormat.Eml &&
                HasSourceSpecificMetadata(item.Document)) {
                Add(CreateLossDiagnostic(options.ConversionLossPolicy, "EMAIL_SOURCE_METADATA_NOT_REPRESENTED_IN_EML",
                    "The common message content is representable, but opaque MAPI, TNEF, compound-storage, conversation, reaction, or editor metadata has no portable EML equivalent.",
                    "source-metadata"));
            }
            // Only the outer RFC message has an EMLX envelope for its Apple metadata.
            foreach (EmailDiagnostic diagnostic in AnalyzeArchiveMetadata(item.Document,
                         preservesAppleMailMetadata && item.Depth == 0, options.ConversionLossPolicy)) Add(diagnostic);
            IList<EmailAttachment> attachments = targetFormat == EmailFileFormat.Eml ? item.Document.Attachments :
                OutlookTaskCommunicationAttachmentProjection.GetAttachmentsForPreflight(item.Document);
            for (int index = 0; index < attachments.Count; index++) {
                EmailAttachment attachment = attachments[index];
                if (targetFormat == EmailFileFormat.Eml && MimeWriter.CanPreservePartHeaders(attachment)) continue;
                if (attachment.EmbeddedDocument == null) continue;
                bool taskPayload = targetFormat != EmailFileFormat.Eml && index == 0 &&
                    item.Document.TaskCommunication?.Kind != OutlookTaskCommunicationKind.None &&
                    ReferenceEquals(attachment.EmbeddedDocument, item.Document.TaskCommunication?.EmbeddedTask);
                string path = taskPayload ? "task/embedded/" : "attachment/" + index.ToString(CultureInfo.InvariantCulture) + "/";
                pending.Push((attachment.EmbeddedDocument, item.Path + path, item.Depth + 1));
            }

            void Add(EmailDiagnostic diagnostic) {
                if (item.Path.Length == 0) { diagnostics.Add(diagnostic); return; }
                diagnostics.Add(new EmailDiagnostic(diagnostic.Code, diagnostic.Message, diagnostic.Severity,
                    item.Path + diagnostic.Location, diagnostic.Operation, diagnostic.ByteOffset,
                    diagnostic.LimitName, diagnostic.ActualValue, diagnostic.MaximumValue,
                    diagnostic.Disposition, diagnostic.DataLossRisk, diagnostic.SuggestedAction,
                    diagnostic.IsRetryable, diagnostic.LossKind));
            }
        }
    }

    internal static IReadOnlyList<EmailDiagnostic> AnalyzeArchiveMetadata(EmailDocument document, bool preservesAppleMailMetadata = false,
        EmailConversionLossPolicy lossPolicy = EmailConversionLossPolicy.Warn) {
        var diagnostics = new List<EmailDiagnostic>();
        if (document.Properties.TryGetValue("Olm:ProjectionIssues", out object? projection) && projection is string[] issues && issues.Length > 0) {
            diagnostics.Add(CreateLossDiagnostic(lossPolicy, "EMAIL_OLM_PROJECTION_INCOMPLETE",
                string.Join(" ", issues), "source-content/olm"));
        }
        if (!preservesAppleMailMetadata && document.Properties.Keys.Any(key =>
                key.Equals("Emlx:Metadata", StringComparison.OrdinalIgnoreCase) ||
                key.Equals("Emlx:RawMetadata", StringComparison.OrdinalIgnoreCase) ||
                key.StartsWith("Emlx:Metadata:", StringComparison.OrdinalIgnoreCase))) {
            diagnostics.Add(CreateLossDiagnostic(lossPolicy, "EMAIL_EMLX_METADATA_NOT_REPRESENTED",
                "The Apple Mail plist trailer, including mailbox flags and source-specific fields, has no representation in this message artifact.",
                "source-metadata/emlx"));
        }
        if (document.Properties.Keys.Any(key => key.StartsWith("Olm:", StringComparison.OrdinalIgnoreCase) &&
                !key.Equals("Olm:EntryPath", StringComparison.OrdinalIgnoreCase) &&
                !key.Equals("Olm:ElementName", StringComparison.OrdinalIgnoreCase))) {
            diagnostics.Add(CreateLossDiagnostic(lossPolicy, "EMAIL_OLM_METADATA_NOT_REPRESENTED",
                "Retained Outlook for Mac XML properties are available in the source projection but are omitted from this message artifact.",
                "source-metadata/olm"));
        }

        if (document.Properties.TryGetValue("Emlx:IsPartial", out object? partial) && partial is true) {
            diagnostics.Add(new EmailDiagnostic("EMAIL_EMLX_PARTIAL_CONTENT",
                "The source is a partial Apple Mail message. Supported local siblings are included when recovered; missing or remote content cannot be proven complete offline.",
                lossPolicy == EmailConversionLossPolicy.Block ? EmailDiagnosticSeverity.Error :
                    lossPolicy == EmailConversionLossPolicy.Warn ? EmailDiagnosticSeverity.Warning : EmailDiagnosticSeverity.Information,
                "source-content/emlx", "artifact-conversion", null, null, null, null,
                lossPolicy == EmailConversionLossPolicy.Block ? EmailDiagnosticDisposition.Stopped : EmailDiagnosticDisposition.Observed, EmailDataLossRisk.Possible,
                "Recover and verify the missing content before treating the output as a complete archive.", false, OfficeConversionLossKind.Omission));
        }
        return diagnostics;
    }

    internal static IReadOnlyList<EmailDiagnostic> AnalyzePortableContent(EmailDocument document, EmailWriterOptions options) {
        var diagnostics = new List<EmailDiagnostic>();
        if (document.OutlookItemKind == OutlookItemKind.Appointment) {
            if ((document.Appointment == null || !document.Appointment.Start.HasValue) &&
                !HasUnchangedMimeSemanticSource(document)) {
                diagnostics.Add(CreateLossDiagnostic(options.ConversionLossPolicy,
                    "EMAIL_ICALENDAR_START_REQUIRED",
                    "An appointment needs a start time before it can be represented as an iCalendar VEVENT.",
                    "appointment/start"));
            } else if (document.Appointment != null && IcsCalendarCodec.HasOpaqueAppointmentState(document.Appointment) &&
                !HasUnchangedMimeSemanticSource(document)) {
                diagnostics.Add(CreateLossDiagnostic(options.ConversionLossPolicy,
                    "EMAIL_ICALENDAR_OPAQUE_RECURRENCE",
                    "The appointment contains Outlook recurrence or time-zone blobs that cannot be translated safely to iCalendar without changing their meaning.",
                    "appointment/recurrence"));
            }
            if (document.Appointment != null && HasAddresslessAttendeeDisplayState(document) &&
                !HasUnchangedMimeSemanticSource(document)) {
                diagnostics.Add(CreateLossDiagnostic(options.ConversionLossPolicy,
                    "EMAIL_ICALENDAR_ATTENDEE_ADDRESS_REQUIRED",
                    "The appointment has attendee state without portable SMTP recipient addresses from which valid iCalendar ATTENDEE values can be created.",
                    "appointment/attendees"));
            }
            if (HasNonPortableCalendarOrganizer(document) &&
                !HasUnchangedMimeSemanticSource(document)) {
                diagnostics.Add(CreateLossDiagnostic(options.ConversionLossPolicy,
                    "EMAIL_ICALENDAR_ORGANIZER_ADDRESS_REQUIRED",
                    "The appointment organizer does not have a portable SMTP address from which a valid iCalendar ORGANIZER value can be created.",
                    "appointment/organizer"));
            }
            if (HasNonPortableMeetingLifecycle(document.MeetingCommunication) &&
                !HasUnchangedMimeSemanticSource(document)) {
                diagnostics.Add(CreateLossDiagnostic(options.ConversionLossPolicy,
                    "EMAIL_ICALENDAR_MEETING_LIFECYCLE_EXTENSION_LOSS",
                    "The meeting communication contains Outlook lifecycle or counter-proposal properties that the current iCalendar projection cannot represent completely.",
                    "appointment/meeting-communication"));
            }
        } else if (document.OutlookItemKind == OutlookItemKind.Task) {
            if (document.TaskCommunication != null &&
                document.TaskCommunication.Kind != OutlookTaskCommunicationKind.None &&
                !HasUnchangedMimeSemanticSource(document)) {
                diagnostics.Add(CreateLossDiagnostic(options.ConversionLossPolicy,
                    "EMAIL_ICALENDAR_TASK_COMMUNICATION_UNSUPPORTED",
                    "The current iCalendar projection does not represent an Outlook task request, acceptance, rejection, or update envelope with its embedded task.",
                    "task/communication"));
            }
            if (document.Task != null && IcsCalendarCodec.HasOpaqueTaskState(document.Task) &&
                !HasUnchangedMimeSemanticSource(document)) {
                diagnostics.Add(CreateLossDiagnostic(options.ConversionLossPolicy,
                    "EMAIL_ICALENDAR_OPAQUE_TASK_RECURRENCE",
                    "The task is recurring, but its recurrence rule is not available for a safe iCalendar VTODO representation.",
                    "task/recurrence"));
            }
            if (HasNonPortableCalendarRecipient(document) && !HasUnchangedMimeSemanticSource(document)) {
                diagnostics.Add(CreateLossDiagnostic(options.ConversionLossPolicy,
                    "EMAIL_ICALENDAR_ATTENDEE_ADDRESS_REQUIRED",
                    "The task has an assignee recipient without a portable SMTP address from which a valid iCalendar ATTENDEE value can be created.",
                    "task/attendees"));
            }
            if (HasNonPortableCalendarOrganizer(document, document.Task?.Owner) &&
                !HasUnchangedMimeSemanticSource(document)) {
                diagnostics.Add(CreateLossDiagnostic(options.ConversionLossPolicy,
                    "EMAIL_ICALENDAR_ORGANIZER_ADDRESS_REQUIRED",
                    "The task owner does not have a portable SMTP address from which a valid iCalendar ORGANIZER value can be created.",
                    "task/organizer"));
            }
        } else if (IsDistributionList(document)) {
            diagnostics.Add(CreateLossDiagnostic(options.ConversionLossPolicy,
                "EMAIL_VCARD_DISTRIBUTION_LIST_UNSUPPORTED",
                "An Outlook distribution list cannot be represented as an individual vCard without losing its membership.",
                "contact/distribution-list"));
        } else if (document.OutlookItemKind == OutlookItemKind.Contact &&
            (document.Contact == null || VCardCodec.HasOpaqueContactState(document.Contact))) {
            diagnostics.Add(CreateLossDiagnostic(options.ConversionLossPolicy,
                "EMAIL_VCARD_OPAQUE_CONTACT_IDENTITY",
                "The contact contains opaque Outlook entry identifiers that cannot be represented in vCard.",
                "contact/email-address"));
        } else if (document.OutlookItemKind == OutlookItemKind.Journal ||
            document.OutlookItemKind == OutlookItemKind.Note) {
            diagnostics.Add(CreateLossDiagnostic(options.ConversionLossPolicy,
                "EMAIL_OUTLOOK_ITEM_EML_REPRESENTATION_MISSING",
                string.Concat(document.OutlookItemKind.ToString(),
                    " does not yet have a standards-based EML representation."),
                "outlook-item"));
        }
        AddSemanticMutationDiagnostic(document, options, diagnostics);
        return diagnostics.AsReadOnly();
    }

    private static void AddSemanticMutationDiagnostic(EmailDocument document, EmailWriterOptions options, List<EmailDiagnostic> diagnostics) {
        if (document.MimeSemanticSourceModelFingerprint != null &&
            !EmailDocumentStateFingerprint.Matches(document, document.MimeSemanticSourceModelFingerprint)) {
            diagnostics.Add(CreateLossDiagnostic(options.ConversionLossPolicy,
                "EMAIL_MIME_SEMANTIC_CONTENT_CHANGED",
                "The message model changed after calendar or vCard content was projected. Regenerating that content can omit unmodeled source properties.",
                "semantic-content"));
        }

    }

    internal static bool CanPassThroughProtectedSource(EmailDocument document, EmailFileFormat targetFormat) {
        return document.Protection.IsProtected && document.Format == targetFormat && document.RawSource != null &&
            document.RawSourceModelFingerprint != null &&
            EmailDocumentStateFingerprint.Matches(document, document.RawSourceModelFingerprint);
    }

    internal static EmailDiagnostic CreateLossDiagnostic(EmailConversionLossPolicy policy, string code,
        string message, string? location = null) {
        EmailDiagnosticSeverity severity = policy == EmailConversionLossPolicy.Block
            ? EmailDiagnosticSeverity.Error
            : policy == EmailConversionLossPolicy.Warn
                ? EmailDiagnosticSeverity.Warning
                : EmailDiagnosticSeverity.Information;
        return new EmailDiagnostic(code, message, severity, location, "artifact-conversion", null,
            null, null, null,
            policy == EmailConversionLossPolicy.Block
                ? EmailDiagnosticDisposition.Stopped
                : EmailDiagnosticDisposition.Observed,
            EmailDataLossRisk.Confirmed,
            policy == EmailConversionLossPolicy.Block
                ? "Choose a target that preserves the source semantics or explicitly select Warn/Allow after reviewing the loss."
                : "Review the regenerated artifact and its diagnostics before transport or archival use.",
            isRetryable: false,
            lossKind: OfficeConversionLossKind.Omission);
    }

    private static bool HasSourceSpecificMetadata(EmailDocument document) {
        EmailMessageMetadata metadata = document.MessageMetadata;
        return document.MapiProperties.Count > 0 || document.TnefAttributes.Count > 0 ||
            document.Attachments.Any(attachment => attachment.MapiProperties.Count > 0 ||
                attachment.TnefAttributes.Count > 0 || attachment.StructuredStorageStreams.Count > 0) ||
            metadata.ConversationIndex != null || metadata.ConversationId != null || metadata.ReactionsSummary != null ||
            metadata.OwnerReactionHistory != null || metadata.IconIndex.HasValue || metadata.EditorFormat.HasValue;
    }

    private static bool IsDistributionList(EmailDocument document) =>
        document.OutlookItemKind == OutlookItemKind.DistributionList ||
        document.DistributionList != null ||
        string.Equals(document.MessageClass, "IPM.DistList", StringComparison.OrdinalIgnoreCase) ||
        document.MessageClass?.StartsWith("IPM.DistList.", StringComparison.OrdinalIgnoreCase) == true;

    internal static bool HasUnchangedMimeSemanticSource(EmailDocument document) =>
        document.Format == EmailFileFormat.Eml && document.MimeSemanticSourceModelFingerprint != null &&
        EmailDocumentStateFingerprint.Matches(document, document.MimeSemanticSourceModelFingerprint);

    private static bool HasNonPortableMeetingLifecycle(OutlookMeetingCommunication? communication) =>
        communication != null && (communication.RequestTypeValue.HasValue ||
            communication.OwnerCriticalChange.HasValue || communication.AttendeeCriticalChange.HasValue ||
            communication.IsSilent.HasValue || communication.IsCounterProposal == true ||
            communication.ProposedStart.HasValue || communication.ProposedEnd.HasValue ||
            communication.ProposedDurationMinutes.HasValue || communication.ReplyAt.HasValue ||
            communication.ReplyName != null);

    private static bool HasAddresslessAttendeeDisplayState(EmailDocument document) {
        OutlookAppointment appointment = document.Appointment!;
        if (HasNonPortableCalendarRecipient(document)) return true;

        EmailRecipient[] requiredRecipients = document.Recipients.Where(recipient =>
            recipient.Kind == EmailRecipientKind.To || recipient.Kind == EmailRecipientKind.Room ||
            recipient.Kind == EmailRecipientKind.Resource).ToArray();
        EmailRecipient[] optionalRecipients = document.Recipients.Where(recipient =>
            recipient.Kind == EmailRecipientKind.Cc).ToArray();
        bool hasRoleSpecificDisplays = !string.IsNullOrWhiteSpace(appointment.RequiredAttendees) ||
            !string.IsNullOrWhiteSpace(appointment.OptionalAttendees);
        if (hasRoleSpecificDisplays) {
            return HasUnmatchedAttendeeDisplay(appointment.RequiredAttendees, requiredRecipients) ||
                HasUnmatchedAttendeeDisplay(appointment.OptionalAttendees, optionalRecipients);
        }

        return HasUnmatchedAttendeeDisplay(appointment.AllAttendees,
            requiredRecipients.Concat(optionalRecipients).ToArray());
    }

    private static bool HasUnmatchedAttendeeDisplay(string? displayState,
        IReadOnlyList<EmailRecipient> recipients) {
        string[] displayValues = (displayState ?? string.Empty).Split(';')
            .Select(value => value.Trim()).Where(value => value.Length > 0).ToArray();
        if (displayValues.Length == 0) return false;
        if (displayValues.Length > recipients.Count) return true;

        var used = new bool[recipients.Count];
        foreach (string displayValue in displayValues) {
            int match = -1;
            for (int index = 0; index < recipients.Count; index++) {
                if (used[index] || !AttendeeDisplayMatches(displayValue, recipients[index].Address)) continue;
                match = index;
                break;
            }
            if (match < 0) return true;
            used[match] = true;
        }
        return false;
    }

    private static bool AttendeeDisplayMatches(string displayValue, EmailAddress address) {
        if (string.Equals(displayValue, address.DisplayName, StringComparison.OrdinalIgnoreCase) ||
            string.Equals(displayValue, address.Address, StringComparison.OrdinalIgnoreCase)) return true;
        return !string.IsNullOrWhiteSpace(address.Address) &&
            displayValue.EndsWith(string.Concat("<", address.Address, ">"), StringComparison.OrdinalIgnoreCase);
    }

    private static bool HasNonPortableCalendarRecipient(EmailDocument document) => document.Recipients.Any(recipient =>
        (recipient.Kind == EmailRecipientKind.To || recipient.Kind == EmailRecipientKind.Cc ||
         recipient.Kind == EmailRecipientKind.Room || recipient.Kind == EmailRecipientKind.Resource) &&
        !IcsCalendarCodec.HasPortableMailtoAddress(recipient.Address));

    private static bool HasNonPortableCalendarOrganizer(EmailDocument document, string? taskOwner = null) {
        EmailAddress? from = document.From;
        string? fromAddress = from?.Address;
        if (string.IsNullOrWhiteSpace(fromAddress) ||
            document.OutlookItemKind == OutlookItemKind.Task &&
            !string.Equals(fromAddress, taskOwner, StringComparison.OrdinalIgnoreCase)) return false;
        return !IcsCalendarCodec.HasPortableMailtoAddress(from);
    }
}
