namespace OfficeIMO.Rtf;

/// <summary>
/// Dynamic text generated by an RTF reader or renderer, such as page number or current date.
/// </summary>
public sealed class RtfGeneratedText : IRtfInline {
    /// <summary>Creates a generated text marker.</summary>
    public RtfGeneratedText(RtfGeneratedTextKind kind, string? fallbackText = null) {
        Kind = kind;
        FallbackText = fallbackText;
    }

    /// <summary>Kind of generated text represented by this marker.</summary>
    public RtfGeneratedTextKind Kind { get; set; }

    /// <summary>Optional text used by semantic conversions that cannot evaluate the generated value.</summary>
    public string? FallbackText { get; set; }

    /// <summary>Optional note attached to this generated marker, such as an automatic footnote reference.</summary>
    public RtfNote? Note { get; set; }

    /// <summary>Returns the optional fallback text, or an empty string when the value must be generated by a renderer.</summary>
    public string ToPlainText() {
        return FallbackText ?? string.Empty;
    }
}
