using System.Threading;
using System.Threading.Tasks;

namespace OfficeIMO.Word.Pdf {

    /// <summary>
    /// Provides extension methods for converting <see cref="WordDocument"/> instances to PDF files.
    /// </summary>
    public static partial class WordPdfConverterExtensions {
        /// <summary>
        /// Saves the specified <see cref="WordDocument"/> as a PDF at the given <paramref name="path"/>.
        /// </summary>
        /// <param name="document">The document to convert.</param>
        /// <param name="path">The output PDF file path.</param>
        /// <param name="options">Optional PDF configuration.</param>
        public static void SaveAsPdf(this WordDocument document, string path, PdfSaveOptions? options = null) {
            if (document == null) {
                throw new ArgumentNullException(nameof(document));
            }

            if (path == null) {
                throw new ArgumentNullException(nameof(path));
            }

            if (string.IsNullOrWhiteSpace(path)) {
                throw new ArgumentException("Path cannot be empty or whitespace.", nameof(path));
            }

            string fullPath = ValidateOutputPath(path, nameof(path));
            string? directory = Path.GetDirectoryName(fullPath);
            if (!string.IsNullOrEmpty(directory)) {
                Directory.CreateDirectory(directory);
            }

            CreateOfficeIMOPdfDocument(document, options).Save(fullPath);
        }

        /// <summary>
        /// Saves the specified <see cref="WordDocument"/> as a PDF to the provided <paramref name="stream"/>.
        /// </summary>
        /// <param name="document">The document to convert.</param>
        /// <param name="stream">The output stream to receive the PDF data.</param>
        /// <param name="options">Optional PDF configuration.</param>
        public static void SaveAsPdf(this WordDocument document, Stream stream, PdfSaveOptions? options = null) {
            if (document == null) {
                throw new ArgumentNullException(nameof(document));
            }

            if (stream == null) {
                throw new ArgumentNullException(nameof(stream));
            }

            if (!stream.CanWrite) {
                throw new ArgumentException("Stream must be writable.", nameof(stream));
            }

            CreateOfficeIMOPdfDocument(document, options).Save(stream);
            if (stream.CanSeek) {
                stream.Position = 0;
            }
        }

        /// <summary>
        /// Saves the specified <see cref="WordDocument"/> as a PDF and returns the generated bytes.
        /// </summary>
        /// <param name="document">The document to convert.</param>
        /// <param name="options">Optional PDF configuration.</param>
        /// <returns>The generated PDF as a byte array.</returns>
        public static byte[] SaveAsPdf(this WordDocument document, PdfSaveOptions? options = null) {
            if (document == null) {
                throw new ArgumentNullException(nameof(document));
            }

            return CreateOfficeIMOPdfDocument(document, options).ToBytes();
        }

        /// <summary>
        /// Saves the specified <see cref="WordDocument"/> as a PDF and returns the generated bytes asynchronously.
        /// </summary>
        /// <param name="document">The document to convert.</param>
        /// <param name="options">Optional PDF configuration.</param>
        /// <param name="cancellationToken">A token to observe while waiting for the task to complete.</param>
        /// <returns>The generated PDF as a byte array.</returns>
        public static async Task<byte[]> SaveAsPdfAsync(this WordDocument document, PdfSaveOptions? options = null, CancellationToken cancellationToken = default) {
            if (document == null) {
                throw new ArgumentNullException(nameof(document));
            }

            cancellationToken.ThrowIfCancellationRequested();
            using (MemoryStream stream = new MemoryStream()) {
                await CreateOfficeIMOPdfDocument(document, options).SaveAsync(stream, cancellationToken).ConfigureAwait(false);
                return stream.ToArray();
            }
        }

        /// <summary>
        /// Saves the specified <see cref="WordDocument"/> as a PDF at the given <paramref name="path"/> asynchronously.
        /// </summary>
        /// <param name="document">The document to convert.</param>
        /// <param name="path">The output PDF file path.</param>
        /// <param name="options">Optional PDF configuration.</param>
        /// <param name="cancellationToken">A token to observe while waiting for the task to complete.</param>
        /// <returns>A task representing the asynchronous operation.</returns>
        public static async Task SaveAsPdfAsync(this WordDocument document, string path, PdfSaveOptions? options = null, CancellationToken cancellationToken = default) {
            if (document == null) {
                throw new ArgumentNullException(nameof(document));
            }

            if (path == null) {
                throw new ArgumentNullException(nameof(path));
            }

            if (string.IsNullOrWhiteSpace(path)) {
                throw new ArgumentException("Path cannot be empty or whitespace.", nameof(path));
            }

            string fullPath = ValidateOutputPath(path, nameof(path));
            string? directory = Path.GetDirectoryName(fullPath);
            cancellationToken.ThrowIfCancellationRequested();
            if (!string.IsNullOrEmpty(directory)) {
                Directory.CreateDirectory(directory);
            }

            await CreateOfficeIMOPdfDocument(document, options).SaveAsync(fullPath, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Saves the specified <see cref="WordDocument"/> as a PDF to the provided <paramref name="stream"/> asynchronously.
        /// </summary>
        /// <param name="document">The document to convert.</param>
        /// <param name="stream">The output stream to receive the PDF data.</param>
        /// <param name="options">Optional PDF configuration.</param>
        /// <param name="cancellationToken">A token to observe while waiting for the task to complete.</param>
        /// <returns>A task representing the asynchronous operation.</returns>
        public static async Task SaveAsPdfAsync(this WordDocument document, Stream stream, PdfSaveOptions? options = null, CancellationToken cancellationToken = default) {
            if (document == null) {
                throw new ArgumentNullException(nameof(document));
            }

            if (stream == null) {
                throw new ArgumentNullException(nameof(stream));
            }

            cancellationToken.ThrowIfCancellationRequested();

            if (!stream.CanWrite) {
                throw new ArgumentException("Stream must be writable.", nameof(stream));
            }

            await CreateOfficeIMOPdfDocument(document, options).SaveAsync(stream, cancellationToken).ConfigureAwait(false);
            if (stream.CanSeek) {
                stream.Position = 0;
            }
        }

        private static string ValidateOutputPath(string path, string paramName) {
            string fullPath;
            try {
                fullPath = Path.GetFullPath(path);
            } catch (Exception ex) {
                throw new ArgumentException("Path is invalid.", paramName, ex);
            }

            if (Directory.Exists(fullPath) && (File.GetAttributes(fullPath) & FileAttributes.Directory) == FileAttributes.Directory) {
                throw new ArgumentException("Path refers to a directory; a file path is required.", paramName);
            }

            string fileName = Path.GetFileName(fullPath);
            if (string.IsNullOrEmpty(fileName)) {
                throw new ArgumentException("Path must include a file name.", paramName);
            }

            if (fileName.IndexOfAny(Path.GetInvalidFileNameChars()) >= 0) {
                throw new ArgumentException("Path contains invalid file name characters.", paramName);
            }

            return fullPath;
        }
    }
}
