using System.Collections.ObjectModel;

namespace OfficeIMO.Html;

/// <summary>
/// Catalog of stable OfficeIMO HTML diagnostics and support remediation text.
/// </summary>
public static class HtmlDiagnosticCatalog {
    private static readonly IReadOnlyDictionary<string, HtmlDiagnosticDefinition> Definitions = new ReadOnlyDictionary<string, HtmlDiagnosticDefinition>(new Dictionary<string, HtmlDiagnosticDefinition>(StringComparer.OrdinalIgnoreCase) {
        [HtmlConversionDiagnosticCodes.SemanticContentMissing] = ConversionDefinition(HtmlConversionDiagnosticCodes.SemanticContentMissing, "SemanticImport", HtmlDiagnosticSeverity.Error, "The expected format-specific semantic HTML envelope was not present.", "Use generic import mode for ordinary HTML or export with the matching OfficeIMO semantic profile."),
        [HtmlConversionDiagnosticCodes.SemanticBlockMissing] = ConversionDefinition(HtmlConversionDiagnosticCodes.SemanticBlockMissing, "SemanticImport", HtmlDiagnosticSeverity.Warning, "An expected semantic content block was not present.", "Regenerate the semantic HTML from the source adapter or supply the missing block."),
        [HtmlConversionDiagnosticCodes.SemanticValueInvalid] = ConversionDefinition(HtmlConversionDiagnosticCodes.SemanticValueInvalid, "SemanticImport", HtmlDiagnosticSeverity.Warning, "A semantic value could not be parsed safely.", "Use finite, target-valid values in OfficeIMO semantic metadata."),
        [HtmlConversionDiagnosticCodes.ResourceDecodeFailed] = ConversionDefinition(HtmlConversionDiagnosticCodes.ResourceDecodeFailed, "ResourcePolicy", HtmlDiagnosticSeverity.Warning, "An embedded resource could not be decoded.", "Provide a valid, bounded data URI or use an approved resource resolver."),
        [HtmlConversionDiagnosticCodes.ResourceTypeUnsupported] = ConversionDefinition(HtmlConversionDiagnosticCodes.ResourceTypeUnsupported, "ResourcePolicy", HtmlDiagnosticSeverity.Warning, "A resource media type is unsupported by the target adapter.", "Convert the resource to a media type supported by the target adapter."),
        [HtmlConversionDiagnosticCodes.ContentApproximated] = ConversionDefinition(HtmlConversionDiagnosticCodes.ContentApproximated, "ConversionFidelity", HtmlDiagnosticSeverity.Warning, "Content was represented using a documented approximation.", "Use semantic HTML emitted by the matching adapter when exact round-trip fidelity is required."),
        [HtmlConversionDiagnosticCodes.ContentOmitted] = ConversionDefinition(HtmlConversionDiagnosticCodes.ContentOmitted, "ConversionFidelity", HtmlDiagnosticSeverity.Warning, "Content could not be represented by the target and was omitted.", "Simplify the source construct or choose a target that supports it."),
        [HtmlConversionDiagnosticCodes.ArtifactCreationFailed] = ConversionDefinition(HtmlConversionDiagnosticCodes.ArtifactCreationFailed, "Conversion", HtmlDiagnosticSeverity.Error, "The target artifact could not be constructed.", "Inspect the diagnostic detail and validate the source and target-specific constraints."),
        [HtmlConversionDiagnosticCodes.TargetLimitExceeded] = ConversionDefinition(HtmlConversionDiagnosticCodes.TargetLimitExceeded, "Safety", HtmlDiagnosticSeverity.Error, "Input exceeded a target-native or shared import limit.", "Reduce or split the document, or raise the explicit limit only for trusted input."),
        [HtmlConversionDiagnosticCodes.TableSpanInvalid] = ConversionDefinition(HtmlConversionDiagnosticCodes.TableSpanInvalid, "TableFidelity", HtmlDiagnosticSeverity.Warning, "An invalid or overlapping HTML table span was normalized.", "Use positive, non-overlapping rowspan and colspan values."),
        [HtmlConversionDiagnosticCodes.HtmlDepthLimitExceeded] = ConversionDefinition(HtmlConversionDiagnosticCodes.HtmlDepthLimitExceeded, "Safety", HtmlDiagnosticSeverity.Error, "HTML nesting exceeded the shared pre-analysis depth budget.", "Reduce nesting or raise MaxHtmlDepth only for trusted input."),
        [HtmlConversionDiagnosticCodes.CssSizeLimitExceeded] = ConversionDefinition(HtmlConversionDiagnosticCodes.CssSizeLimitExceeded, "Safety", HtmlDiagnosticSeverity.Error, "One embedded stylesheet exceeded the shared byte budget.", "Reduce the stylesheet or raise MaxCssBytes only for trusted input."),
        [HtmlConversionDiagnosticCodes.CssTotalSizeLimitExceeded] = ConversionDefinition(HtmlConversionDiagnosticCodes.CssTotalSizeLimitExceeded, "Safety", HtmlDiagnosticSeverity.Error, "Embedded stylesheets exceeded the operation-wide byte budget.", "Reduce embedded CSS or raise MaxTotalCssBytes only for trusted input."),
        [HtmlConversionDiagnosticCodes.CssRuleLimitExceeded] = ConversionDefinition(HtmlConversionDiagnosticCodes.CssRuleLimitExceeded, "Safety", HtmlDiagnosticSeverity.Error, "Active CSS rules exceeded the shared complexity budget.", "Reduce CSS rule volume or raise MaxCssRules only for trusted input."),
        [HtmlConversionDiagnosticCodes.CssDeclarationLimitExceeded] = ConversionDefinition(HtmlConversionDiagnosticCodes.CssDeclarationLimitExceeded, "Safety", HtmlDiagnosticSeverity.Error, "CSS declarations exceeded the shared complexity budget.", "Reduce CSS declaration volume or raise MaxCssDeclarations only for trusted input."),
        [HtmlConversionDiagnosticCodes.CssNestingDepthLimitExceeded] = ConversionDefinition(HtmlConversionDiagnosticCodes.CssNestingDepthLimitExceeded, "Safety", HtmlDiagnosticSeverity.Error, "Nested CSS rule blocks exceeded the shared depth budget.", "Flatten nested media, supports, or rule blocks, or raise MaxCssNestingDepth only for trusted input."),
        [HtmlConversionDiagnosticCodes.CssSelectorEvaluationLimitExceeded] = ConversionDefinition(HtmlConversionDiagnosticCodes.CssSelectorEvaluationLimitExceeded, "Safety", HtmlDiagnosticSeverity.Error, "Selector matching exceeded the shared evaluation budget.", "Simplify selectors or raise MaxSelectorEvaluations only for trusted input."),
        [HtmlConversionDiagnosticCodes.SemanticMetadataLimitExceeded] = ConversionDefinition(HtmlConversionDiagnosticCodes.SemanticMetadataLimitExceeded, "Safety", HtmlDiagnosticSeverity.Error, "A semantic metadata field exceeded its shared limit.", "Reduce oversized metadata or raise the explicit metadata limit only for trusted input."),
        [HtmlConversionDiagnosticCodes.SemanticSchemaUnsupported] = ConversionDefinition(HtmlConversionDiagnosticCodes.SemanticSchemaUnsupported, "SemanticImport", HtmlDiagnosticSeverity.Error, "The semantic source or schema version is unsupported.", "Use a matching OfficeIMO adapter and supported semantic schema version."),
        [HtmlConversionDiagnosticCodes.SemanticSchemaLegacy] = ConversionDefinition(HtmlConversionDiagnosticCodes.SemanticSchemaLegacy, "SemanticImport", HtmlDiagnosticSeverity.Info, "A legacy semantic envelope without a schema version was accepted.", "Re-export the content to add the current semantic schema version."),
        [HtmlConversionDiagnosticCodes.SemanticRestorationTrustRequired] = ConversionDefinition(HtmlConversionDiagnosticCodes.SemanticRestorationTrustRequired, "SemanticImport", HtmlDiagnosticSeverity.Warning, "The envelope requested target-specific restoration but the caller marked the HTML as untrusted.", "Parse the document with a trusted profile only after authenticating its source, or use public-safe semantic restoration."),
        [HtmlConversionDiagnosticCodes.MediaFilterFailed] = ConversionDefinition(HtmlConversionDiagnosticCodes.MediaFilterFailed, "CssFidelity", HtmlDiagnosticSeverity.Warning, "An active stylesheet could not be filtered safely for the selected media.", "Correct invalid CSS or simplify nested media rules."),
        [HtmlConversionDiagnosticCodes.ExcelPivotReviewApproximated] = ConversionDefinition(HtmlConversionDiagnosticCodes.ExcelPivotReviewApproximated, "ConversionFidelity", HtmlDiagnosticSeverity.Warning, "An Excel pivot table was projected as static review metadata.", "Use the workbook when refresh, drill, caches, slicers, or timelines are required."),
        [HtmlConversionDiagnosticCodes.PowerPointMasterReviewApproximated] = ConversionDefinition(HtmlConversionDiagnosticCodes.PowerPointMasterReviewApproximated, "ConversionFidelity", HtmlDiagnosticSeverity.Warning, "PowerPoint master and layout inheritance was projected as static review metadata.", "Use the presentation when editable master inheritance or theme behavior is required."),
        [HtmlConversionDiagnosticCodes.PowerPointMasterReviewOmitted] = ConversionDefinition(HtmlConversionDiagnosticCodes.PowerPointMasterReviewOmitted, "ConversionFidelity", HtmlDiagnosticSeverity.Warning, "A PowerPoint master inventory could not be read safely and was omitted.", "Validate or repair the presentation package before exporting its master inventory."),
        [HtmlConversionDiagnosticCodes.PowerPointSmartArtReviewApproximated] = ConversionDefinition(HtmlConversionDiagnosticCodes.PowerPointSmartArtReviewApproximated, "ConversionFidelity", HtmlDiagnosticSeverity.Warning, "PowerPoint SmartArt was projected through a static semantic drawing or text fallback.", "Use the presentation when editable diagram layout and SmartArt authoring behavior are required."),
        [HtmlConversionDiagnosticCodes.PowerPointMediaReviewApproximated] = ConversionDefinition(HtmlConversionDiagnosticCodes.PowerPointMediaReviewApproximated, "ConversionFidelity", HtmlDiagnosticSeverity.Warning, "PowerPoint media was projected as an inert poster frame and playback inventory.", "Use the presentation or an application-managed media player when playback is required."),
        [HtmlConversionDiagnosticCodes.PowerPointEffectReviewApproximated] = ConversionDefinition(HtmlConversionDiagnosticCodes.PowerPointEffectReviewApproximated, "ConversionFidelity", HtmlDiagnosticSeverity.Warning, "PowerPoint picture effects were preserved as inert review metadata.", "Use the presentation when editable effects or native PowerPoint rendering are required."),
        [HtmlEditableLayoutDiagnosticCodes.RegionProjected] = ConversionDefinition(HtmlEditableLayoutDiagnosticCodes.RegionProjected, "EditableLayout", HtmlDiagnosticSeverity.Info, "A bounded single-surface HTML layout region was exposed for native editable projection.", "Inspect the destination result contract for its native geometry and effect mapping."),
        [HtmlEditableLayoutDiagnosticCodes.RegionFragmented] = ConversionDefinition(HtmlEditableLayoutDiagnosticCodes.RegionFragmented, "EditableLayout", HtmlDiagnosticSeverity.Warning, "A repeated or fragmented layout region remained in semantic flow because one native geometry would be ambiguous.", "Split the source into bounded single-surface regions or retain semantic flow."),
        [HtmlEditableLayoutDiagnosticCodes.BackgroundLayersFlattened] = ConversionDefinition(HtmlEditableLayoutDiagnosticCodes.BackgroundLayersFlattened, "EditableLayout", HtmlDiagnosticSeverity.Warning, "The destination retained supported native paint but flattened or omitted additional CSS background layers.", "Use supported bounded image layers or a visual-first target when every browser paint layer is required."),
        [HtmlEditableLayoutDiagnosticCodes.EffectUnsupported] = ConversionDefinition(HtmlEditableLayoutDiagnosticCodes.EffectUnsupported, "EditableLayout", HtmlDiagnosticSeverity.Warning, "The destination retained editable content and geometry without one or more unsupported CSS effects.", "Use the destination's documented native picture and shadow subset or a visual-first target."),
        [HtmlEditableLayoutDiagnosticCodes.PlacementSimplified] = ConversionDefinition(HtmlEditableLayoutDiagnosticCodes.PlacementSimplified, "EditableLayout", HtmlDiagnosticSeverity.Warning, "The destination moved an editable region to preserve existing native content or avoid an invalid overlapping anchor.", "Use non-overlapping bounded regions or a visual-first target when exact browser overlap is required."),
        [HtmlEditableLayoutDiagnosticCodes.RegionImageOmitted] = ConversionDefinition(HtmlEditableLayoutDiagnosticCodes.RegionImageOmitted, "EditableLayout", HtmlDiagnosticSeverity.Warning, "A picture inside an editable layout region could not be represented by the destination under the active resource policy or format limits.", "Use a supported bounded image type, allow the resource explicitly, or inspect the destination-specific limit detail."),
        [HtmlRenderDiagnosticCodes.BackgroundImageLayerLimit] = RenderDefinition(HtmlRenderDiagnosticCodes.BackgroundImageLayerLimit, "ResourceLimit", HtmlDiagnosticSeverity.Warning, "CSS background-image layers beyond the configured per-element limit were omitted.", "Increase MaxBackgroundImageLayers only for trusted documents or reduce the number of declared background layers."),
        [HtmlRenderDiagnosticCodes.BackgroundImageRepeatUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.BackgroundImageRepeatUnsupported, "PaintFidelity", HtmlDiagnosticSeverity.Warning, "A CSS background-repeat value used a single-image fallback.", "Use repeat, no-repeat, space, round, repeat-x, repeat-y, or a supported two-axis combination."),
        [HtmlRenderDiagnosticCodes.BackgroundImageValueUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.BackgroundImageValueUnsupported, "PaintFidelity", HtmlDiagnosticSeverity.Warning, "A CSS background image value used a deterministic supported fallback or was omitted.", "Use URL backgrounds, opaque linear gradients, or opaque radial circles and ellipses with keyword, length, or percentage geometry and percentage or implicit color stops until additional image functions are enabled."),
        [HtmlRenderDiagnosticCodes.ColorValueUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.ColorValueUnsupported, "PaintFidelity", HtmlDiagnosticSeverity.Warning, "A CSS foreground or background color value used its inherited or transparent fallback.", "Use a color form listed in the static color contract, or configure the authored value before rendering."),
        [HtmlRenderDiagnosticCodes.BackgroundImageTileLimitExceeded] = RenderDefinition(HtmlRenderDiagnosticCodes.BackgroundImageTileLimitExceeded, "ResourceLimit", HtmlDiagnosticSeverity.Error, "Repeated CSS background images exceeded the configured operation-wide tile limit.", "Increase MaxBackgroundImageTiles only for trusted documents or use a larger background tile."),
        [HtmlRenderDiagnosticCodes.GradientStopLimitExceeded] = RenderDefinition(HtmlRenderDiagnosticCodes.GradientStopLimitExceeded, "ResourceLimit", HtmlDiagnosticSeverity.Error, "CSS gradients exceeded the configured color-stop limit.", "Increase MaxGradientStops only for trusted documents or reduce the number of gradient color stops."),
        ["HtmlCommentSkipped"] = new HtmlDiagnosticDefinition(
            "HtmlCommentSkipped",
            "ContentSimplification",
            HtmlDiagnosticSeverity.Info,
            "An HTML comment was omitted from generated document content.",
            "Enable HTML comment import when comments are part of the expected document contract, or keep comments as source-only metadata."),
        ["ImageResourceRejectedByPolicy"] = new HtmlDiagnosticDefinition(
            "ImageResourceRejectedByPolicy",
            "ResourcePolicy",
            HtmlDiagnosticSeverity.Warning,
            "An image candidate was rejected before loading because its URI is not allowed by policy.",
            "Allow the URI scheme or host for trusted inputs, embed the image as data URI, or provide a local resource resolver."),
        ["StylesheetResourceRejectedByPolicy"] = new HtmlDiagnosticDefinition(
            "StylesheetResourceRejectedByPolicy",
            "ResourcePolicy",
            HtmlDiagnosticSeverity.Warning,
            "A stylesheet was rejected before loading because its URI is not allowed by policy.",
            "Use caller-provided stylesheet contents for untrusted HTML, or allow the stylesheet scheme and host for trusted documents."),
        ["HyperlinkRejectedByPolicy"] = new HtmlDiagnosticDefinition(
            "HyperlinkRejectedByPolicy",
            "ResourcePolicy",
            HtmlDiagnosticSeverity.Warning,
            "A hyperlink target was rejected because its URI is not allowed by policy.",
            "Use http, https, mailto, or a caller-approved scheme instead of script or local file targets."),
        [HtmlRenderDiagnosticCodes.HyperlinkTargetUnavailable] = new HtmlDiagnosticDefinition(
            HtmlRenderDiagnosticCodes.HyperlinkTargetUnavailable,
            "Hyperlink",
            HtmlDiagnosticSeverity.Warning,
            "A document-internal hyperlink referenced a fragment target that does not exist.",
            "Add an element with the referenced id, update the fragment, or remove the broken link."),
        ["ScriptResourceRejectedByPolicy"] = new HtmlDiagnosticDefinition(
            "ScriptResourceRejectedByPolicy",
            "ResourcePolicy",
            HtmlDiagnosticSeverity.Warning,
            "A script dependency was rejected before loading because its URI is not allowed by policy.",
            "Use caller-provided script handling for trusted automation scenarios, or remove script dependencies from document-oriented HTML inputs."),
        ["MediaResourceRejectedByPolicy"] = new HtmlDiagnosticDefinition(
            "MediaResourceRejectedByPolicy",
            "ResourcePolicy",
            HtmlDiagnosticSeverity.Warning,
            "A media dependency was rejected before loading because its URI is not allowed by policy.",
            "Allow trusted media hosts explicitly, package approved media with the input, or provide a local resource resolver."),
        ["FontResourceRejectedByPolicy"] = new HtmlDiagnosticDefinition(
            "FontResourceRejectedByPolicy",
            "ResourcePolicy",
            HtmlDiagnosticSeverity.Warning,
            "A font dependency was rejected before loading because its URI is not allowed by policy.",
            "Use packaged fonts from trusted locations or allow approved font hosts in the URL policy."),
        ["UnsupportedCssDeclaration"] = new HtmlDiagnosticDefinition(
            "UnsupportedCssDeclaration",
            "CssFidelity",
            HtmlDiagnosticSeverity.Warning,
            "A CSS declaration could not be mapped to the target document model.",
            "Prefer document-friendly CSS or route visual-first workloads through the high-fidelity print profile."),
        ["HtmlResourceRejectedByPolicy"] = new HtmlDiagnosticDefinition(
            "HtmlResourceRejectedByPolicy",
            "ResourcePolicy",
            HtmlDiagnosticSeverity.Warning,
            "A resource dependency was rejected before loading because its URI is not allowed by policy.",
            "Adjust the URL policy only for trusted sources, or package the dependency with the HTML input."),
        [HtmlRenderDiagnosticCodes.DepthLimitExceeded] = RenderDefinition(HtmlRenderDiagnosticCodes.DepthLimitExceeded, "Safety", HtmlDiagnosticSeverity.Error, "HTML layout exceeded the configured nesting-depth limit.", "Reduce nesting or raise the explicit layout-depth limit for trusted input."),
        [HtmlRenderDiagnosticCodes.LayoutOperationLimitExceeded] = RenderDefinition(HtmlRenderDiagnosticCodes.LayoutOperationLimitExceeded, "Safety", HtmlDiagnosticSeverity.Error, "HTML layout exceeded the configured operation budget.", "Simplify the layout or raise MaxLayoutOperations only for trusted input."),
        [HtmlRenderDiagnosticCodes.RunningStringLimitExceeded] = RenderDefinition(HtmlRenderDiagnosticCodes.RunningStringLimitExceeded, "Safety", HtmlDiagnosticSeverity.Warning, "A paged running-string value exceeded its configured character budget and was omitted.", "Reduce string-set content or raise MaxRunningStringCharacters only for trusted input."),
        [HtmlRenderDiagnosticCodes.InputCharacterLimitExceeded] = RenderDefinition(HtmlRenderDiagnosticCodes.InputCharacterLimitExceeded, "Safety", HtmlDiagnosticSeverity.Error, "HTML source text exceeded the configured character budget before parsing.", "Reduce or split the document, move large payloads behind a bounded resolver, or raise MaxInputCharacters only for trusted input."),
        [HtmlRenderDiagnosticCodes.NodeLimitExceeded] = RenderDefinition(HtmlRenderDiagnosticCodes.NodeLimitExceeded, "Safety", HtmlDiagnosticSeverity.Error, "The parsed HTML document exceeded the configured DOM node budget before styling or layout.", "Reduce repeated markup or raise MaxHtmlNodes only for trusted input."),
        [HtmlRenderDiagnosticCodes.EmptyTable] = RenderDefinition(HtmlRenderDiagnosticCodes.EmptyTable, "LayoutFidelity", HtmlDiagnosticSeverity.Info, "A table contained no renderable rows or cells.", "Add table rows and cells or remove the empty table."),
        [HtmlRenderDiagnosticCodes.TableLimitExceeded] = RenderDefinition(HtmlRenderDiagnosticCodes.TableLimitExceeded, "Safety", HtmlDiagnosticSeverity.Error, "A table exceeded the configured row or column limit.", "Reduce table dimensions or raise MaxTableRows or MaxTableColumns only for trusted input."),
        [HtmlRenderDiagnosticCodes.CollapsedTableBorderLimitExceeded] = RenderDefinition(HtmlRenderDiagnosticCodes.CollapsedTableBorderLimitExceeded, "Safety", HtmlDiagnosticSeverity.Error, "Collapsed table-border resolution exceeded the configured segment budget.", "Reduce table border complexity or raise MaxCollapsedTableBorderSegments only for trusted input."),
        [HtmlRenderDiagnosticCodes.ExternalImagePending] = RenderDefinition(HtmlRenderDiagnosticCodes.ExternalImagePending, "ResourcePolicy", HtmlDiagnosticSeverity.Warning, "An external image requires asynchronous resource resolution.", "Use RenderAsync with an application-supplied resource resolver or embed the image as a data URI."),
        [HtmlRenderDiagnosticCodes.ExternalStylesheetPending] = RenderDefinition(HtmlRenderDiagnosticCodes.ExternalStylesheetPending, "ResourcePolicy", HtmlDiagnosticSeverity.Warning, "An external stylesheet requires asynchronous resource resolution.", "Use RenderAsync with an application-supplied resource resolver or place trusted CSS in a style element."),
        [HtmlRenderDiagnosticCodes.FontDataUriInvalid] = RenderDefinition(HtmlRenderDiagnosticCodes.FontDataUriInvalid, "Typography", HtmlDiagnosticSeverity.Warning, "A font data URI could not be decoded.", "Provide a valid percent-encoded or base64 font data URI."),
        [HtmlRenderDiagnosticCodes.FontFaceInvalid] = RenderDefinition(HtmlRenderDiagnosticCodes.FontFaceInvalid, "Typography", HtmlDiagnosticSeverity.Warning, "An @font-face rule has no usable family descriptor.", "Provide a font-family descriptor and at least one usable src entry."),
        [HtmlRenderDiagnosticCodes.FontFaceUnavailable] = RenderDefinition(HtmlRenderDiagnosticCodes.FontFaceUnavailable, "Typography", HtmlDiagnosticSeverity.Warning, "No source from an @font-face rule was available.", "Use an allowed data URI or resolve the external font through RenderAsync."),
        [HtmlRenderDiagnosticCodes.FontFormatUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.FontFormatUnsupported, "Typography", HtmlDiagnosticSeverity.Warning, "The font source does not contain a supported first-party outline program and no configured font-program provider accepted it.", "Use a valid TrueType, WOFF 1, CFF/CFF2, or variable OpenType face. Single-face WOFF 2 decoding requires .NET 8 or newer; extract collection faces before registration."),
        [HtmlRenderDiagnosticCodes.FontVariantApproximated] = RenderDefinition(HtmlRenderDiagnosticCodes.FontVariantApproximated, "Typography", HtmlDiagnosticSeverity.Warning, "A CSS font variant used a documented managed-rendering approximation.", "Use the browser-backed renderer for native CSS small caps, or accept uppercase glyphs in managed PDF and image output."),
        [HtmlRenderDiagnosticCodes.ComplexTextShapingUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.ComplexTextShapingUnsupported, "Typography", HtmlDiagnosticSeverity.Warning, "A complex-script run required provider-owned shaping, but no configured provider accepted it.", "Configure a shaping provider that supports the required script, bidirectional layout, and OpenType substitutions or positioning."),
        [HtmlRenderDiagnosticCodes.InlinePaintEffectUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.InlinePaintEffectUnsupported, "Compatibility", HtmlDiagnosticSeverity.Warning, "Legacy diagnostic retained for source compatibility; inline paint effects are rendered by the shared effect model.", "Inspect current transform, opacity, or clip-path diagnostics for an actionable fallback."),
        [HtmlRenderDiagnosticCodes.FlexLayoutPending] = RenderDefinition(HtmlRenderDiagnosticCodes.FlexLayoutPending, "LayoutFidelity", HtmlDiagnosticSeverity.Warning, "A flex formatting case currently falls back to normal flow.", "Use row or column flex directions with static or relatively positioned items; absolute, fixed, sticky, and nested generated flex formatting contexts remain pending."),
        [HtmlRenderDiagnosticCodes.FlexValueUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.FlexValueUnsupported, "LayoutFidelity", HtmlDiagnosticSeverity.Warning, "A flex property value used a deterministic fallback.", "Use supported length or percentage bases, flex-start/start, flex-end/end, center, stretch, space-between, space-around, or space-evenly."),
        [HtmlRenderDiagnosticCodes.FloatValueUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.FloatValueUnsupported, "LayoutFidelity", HtmlDiagnosticSeverity.Warning, "A float or clear property value used a deterministic fallback.", "Use none, left, right, inline-start, or inline-end for float; use those values or both for clear."),
        [HtmlRenderDiagnosticCodes.MultiColumnLimitExceeded] = RenderDefinition(HtmlRenderDiagnosticCodes.MultiColumnLimitExceeded, "Safety", HtmlDiagnosticSeverity.Error, "Multi-column generation exceeded the configured column limit.", "Reduce column-count, increase column-width or available height, or raise MaxColumnCount only for trusted documents."),
        [HtmlRenderDiagnosticCodes.MultiColumnValueUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.MultiColumnValueUnsupported, "LayoutFidelity", HtmlDiagnosticSeverity.Warning, "A multi-column property value used a deterministic fallback.", "Use supported positive count/width values, balance or auto fill, none or all span, and solid, dashed, dotted, or double rules."),
        [HtmlRenderDiagnosticCodes.ForcedFragment] = RenderDefinition(HtmlRenderDiagnosticCodes.ForcedFragment, "PagedMedia", HtmlDiagnosticSeverity.Warning, "Content had no safe break opportunity within one page.", "Add break opportunities or reduce the size of the unbreakable content."),
        [HtmlRenderDiagnosticCodes.GeneratedContentUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.GeneratedContentUnsupported, "LayoutFidelity", HtmlDiagnosticSeverity.Warning, "A CSS generated-content expression was omitted.", "Use quoted text, attr(), counter(), or counters() with decimal, alphabetic, or Roman counter styles until additional generated-content forms are enabled."),
        [HtmlRenderDiagnosticCodes.GeneratedCounterUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.GeneratedCounterUnsupported, "LayoutFidelity", HtmlDiagnosticSeverity.Warning, "A CSS counter declaration was ignored.", "Use counter-reset, counter-set, and counter-increment with counter names and optional integer values; reversed counters remain unsupported."),
        [HtmlRenderDiagnosticCodes.CounterRepresentationLimitExceeded] = RenderDefinition(HtmlRenderDiagnosticCodes.CounterRepresentationLimitExceeded, "Safety", HtmlDiagnosticSeverity.Warning, "A generated CSS counter representation exceeded its bounded output budget and used a decimal fallback.", "Use a bounded ordinal, a compact counter system, or raise the authored counter range only when its representation remains small."),
        [HtmlRenderDiagnosticCodes.GridLayoutPending] = RenderDefinition(HtmlRenderDiagnosticCodes.GridLayoutPending, "LayoutFidelity", HtmlDiagnosticSeverity.Warning, "A grid formatting case currently falls back to normal flow.", "Use block or inline grid with static or relatively positioned items; absolute/fixed/sticky items and nested generated grid formatting contexts remain pending."),
        [HtmlRenderDiagnosticCodes.GridTrackLimitExceeded] = RenderDefinition(HtmlRenderDiagnosticCodes.GridTrackLimitExceeded, "Safety", HtmlDiagnosticSeverity.Error, "Grid track expansion exceeded the configured limit.", "Reduce explicit, implicit, or repeat()-generated tracks, or raise MaxGridTracks for trusted input."),
        [HtmlRenderDiagnosticCodes.GridValueUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.GridValueUnsupported, "LayoutFidelity", HtmlDiagnosticSeverity.Warning, "A grid property value used a deterministic fallback.", "Use fixed, percentage, auto, fr, repeat(), or minmax() tracks with numeric lines and span values for the active grid contract."),
        [HtmlRenderDiagnosticCodes.OverflowScrollSnapshot] = RenderDefinition(HtmlRenderDiagnosticCodes.OverflowScrollSnapshot, "LayoutFidelity", HtmlDiagnosticSeverity.Info, "A scrollable overflow box was captured at its initial static scroll position.", "Use visible overflow when all content must remain visible, or hidden/clip when a static clipped export is intended."),
        [HtmlRenderDiagnosticCodes.OverflowClipMarginValueUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.OverflowClipMarginValueUnsupported, "LayoutFidelity", HtmlDiagnosticSeverity.Warning, "An overflow-clip-margin value used its initial fallback.", "Use an optional content-box, padding-box, or border-box keyword and one non-negative absolute length."),
        [HtmlRenderDiagnosticCodes.OverflowValueUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.OverflowValueUnsupported, "LayoutFidelity", HtmlDiagnosticSeverity.Warning, "An overflow property value used the visible fallback.", "Use visible, hidden, clip, auto, or scroll for overflow, overflow-x, and overflow-y."),
        [HtmlRenderDiagnosticCodes.TransformValueUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.TransformValueUnsupported, "PaintFidelity", HtmlDiagnosticSeverity.Warning, "A CSS transform or transform-origin value used the identity fallback.", "Use supported 2D matrix, translate, scale, rotate, or skew functions and a two-dimensional transform origin."),
        [HtmlRenderDiagnosticCodes.ClipPathValueUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.ClipPathValueUnsupported, "PaintFidelity", HtmlDiagnosticSeverity.Warning, "A CSS clip-path value used no clipping because its geometry could not be represented.", "Use inset(), circle(), ellipse(), or polygon() with bounded length and percentage geometry and an optional margin-box, border-box, padding-box, or content-box reference."),
        [HtmlRenderDiagnosticCodes.PdfSemanticTagUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.PdfSemanticTagUnsupported, "SemanticFidelity", HtmlDiagnosticSeverity.Warning, "A PDF semantic tag override was invalid and automatic HTML semantics were used.", "Use auto, artifact, none, or a supported PDF structure role such as Sect, Div, P, H1-H6, L, LI, Table, TR, TH, TD, or Caption."),
        [HtmlRenderDiagnosticCodes.BookmarkValueUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.BookmarkValueUnsupported, "NavigationFidelity", HtmlDiagnosticSeverity.Warning, "A CSS bookmark value was invalid and automatic heading navigation was used.", "Use bookmark-level:none or an integer from 1 through 64, bookmark-label:content(text) or a quoted string, and bookmark-state:open or closed."),
        [HtmlRenderDiagnosticCodes.FormFieldTransformStaticFallback] = RenderDefinition(HtmlRenderDiagnosticCodes.FormFieldTransformStaticFallback, "Interactivity", HtmlDiagnosticSeverity.Warning, "A form control inside a transformed, translucent, or clipped paint group used faithful static rendering instead of an interactive PDF widget.", "Remove the ancestor transform, opacity, or clip-path when PDF form interactivity is required, or keep the effect when visual fidelity is more important."),
        [HtmlRenderDiagnosticCodes.FormFieldZeroMaximumLengthStaticFallback] = RenderDefinition(HtmlRenderDiagnosticCodes.FormFieldZeroMaximumLengthStaticFallback, "Interactivity", HtmlDiagnosticSeverity.Warning, "A text control with maxlength=0 used faithful static rendering instead of an unrestricted interactive PDF widget.", "Use a positive maxlength when an interactive PDF field is required, or keep maxlength=0 when the zero-length HTML contract matters."),
        [HtmlRenderDiagnosticCodes.FormFieldInitialValueExceedsMaximumLengthStaticFallback] = RenderDefinition(HtmlRenderDiagnosticCodes.FormFieldInitialValueExceedsMaximumLengthStaticFallback, "Interactivity", HtmlDiagnosticSeverity.Warning, "A text control whose initial value exceeds maxlength used faithful static rendering instead of an inconsistent interactive PDF widget.", "Keep the authored value within maxlength when an interactive PDF field is required, or use static rendering to preserve the complete initial value."),
        [HtmlRenderDiagnosticCodes.FileMultipleSelectionStaticFallback] = RenderDefinition(HtmlRenderDiagnosticCodes.FileMultipleSelectionStaticFallback, "Interactivity", HtmlDiagnosticSeverity.Warning, "A multiple-file input used faithful static rendering instead of a scalar PDF file-select widget.", "Remove multiple when one interactive PDF file selection is sufficient, or keep multiple when preserving the HTML selection contract is more important."),
        [HtmlRenderDiagnosticCodes.FormFieldBlankNameStaticFallback] = RenderDefinition(HtmlRenderDiagnosticCodes.FormFieldBlankNameStaticFallback, "Interactivity", HtmlDiagnosticSeverity.Warning, "A form control with a whitespace-only name used faithful static rendering instead of an invalid PDF field name.", "Use a name containing at least one non-whitespace character when an interactive PDF field is required."),
        [HtmlRenderDiagnosticCodes.FormFieldBlankButtonValueStaticFallback] = RenderDefinition(HtmlRenderDiagnosticCodes.FormFieldBlankButtonValueStaticFallback, "Interactivity", HtmlDiagnosticSeverity.Warning, "A checkbox or radio control with an empty or whitespace-only submitted value used faithful static rendering instead of an invalid PDF button export value.", "Use a nonblank value when an interactive PDF button is required, or omit value to use the HTML default on value."),
        [HtmlRenderDiagnosticCodes.RadioDuplicateValueStaticFallback] = RenderDefinition(HtmlRenderDiagnosticCodes.RadioDuplicateValueStaticFallback, "Interactivity", HtmlDiagnosticSeverity.Warning, "A radio group with duplicate submitted values used faithful static rendering instead of synthetic PDF option values.", "Give each radio option a distinct value when an interactive PDF field is required, or keep duplicate HTML values when visual fidelity is more important."),
        [HtmlRenderDiagnosticCodes.ChoiceDuplicateSelectedValueStaticFallback] = RenderDefinition(HtmlRenderDiagnosticCodes.ChoiceDuplicateSelectedValueStaticFallback, "Interactivity", HtmlDiagnosticSeverity.Warning, "A multi-select with duplicate selected submitted values used faithful static rendering instead of an ambiguous PDF choice selection.", "Give selected options distinct values when an interactive PDF field is required, or keep duplicate HTML values when preserving the visible selection is more important."),
        [HtmlRenderDiagnosticCodes.RadioMixedDisabledStateStaticFallback] = RenderDefinition(HtmlRenderDiagnosticCodes.RadioMixedDisabledStateStaticFallback, "Interactivity", HtmlDiagnosticSeverity.Warning, "A radio group mixing enabled and disabled options used faithful static rendering instead of an interactive PDF group that changes disabled semantics.", "Use a consistently enabled or disabled radio group when an interactive PDF field is required, or keep mixed state when visual fidelity is more important."),
        [HtmlRenderDiagnosticCodes.ChoiceDisabledOptionStaticFallback] = RenderDefinition(HtmlRenderDiagnosticCodes.ChoiceDisabledOptionStaticFallback, "Interactivity", HtmlDiagnosticSeverity.Warning, "A select containing disabled options used faithful static rendering instead of an interactive PDF choice field that would make every option selectable.", "Remove disabled options when an interactive PDF choice field is required, or keep them when preserving HTML choice restrictions is more important."),
        [HtmlRenderDiagnosticCodes.FormFieldRepeatedNameStaticFallback] = RenderDefinition(HtmlRenderDiagnosticCodes.FormFieldRepeatedNameStaticFallback, "Interactivity", HtmlDiagnosticSeverity.Warning, "HTML controls repeated across pages or sharing one submitted name used faithful static rendering instead of unsafe duplicate PDF field identities.", "Keep controls out of repeated page content and use unique names when interactive PDF fields are required."),
        [HtmlRenderDiagnosticCodes.ChoiceBlankLabelStaticFallback] = RenderDefinition(HtmlRenderDiagnosticCodes.ChoiceBlankLabelStaticFallback, "Interactivity", HtmlDiagnosticSeverity.Warning, "A select containing a blank option label used faithful static rendering instead of an interactive PDF choice field that would invent visible text.", "Use non-empty option labels when an interactive PDF choice field is required, or keep the blank label when preserving the authored choice UI is more important."),
        [HtmlRenderDiagnosticCodes.ChoiceEmptyOptionsStaticFallback] = RenderDefinition(HtmlRenderDiagnosticCodes.ChoiceEmptyOptionsStaticFallback, "Interactivity", HtmlDiagnosticSeverity.Warning, "An empty select used faithful static rendering instead of constructing an invalid PDF choice field without options.", "Add at least one option when an interactive PDF choice field is required, or keep the select empty when preserving the authored UI is more important."),
        [HtmlRenderDiagnosticCodes.FormFieldNonUniformRadiusStaticFallback] = RenderDefinition(HtmlRenderDiagnosticCodes.FormFieldNonUniformRadiusStaticFallback, "Interactivity", HtmlDiagnosticSeverity.Warning, "A form control with non-uniform or elliptical corner radii used faithful static rendering instead of a PDF widget with different corner geometry.", "Use one uniform circular radius when an interactive PDF field is required, or keep the authored radii when visual fidelity is more important."),
        [HtmlRenderDiagnosticCodes.FormFieldColorTransparencyStaticFallback] = RenderDefinition(HtmlRenderDiagnosticCodes.FormFieldColorTransparencyStaticFallback, "Interactivity", HtmlDiagnosticSeverity.Warning, "A form control with translucent background, border, text, or mark paint used faithful static rendering instead of an opaque PDF widget appearance.", "Use opaque control colors when an interactive PDF field is required, or keep the authored alpha when visual fidelity is more important."),
        [HtmlRenderDiagnosticCodes.FormFieldBackgroundImageStaticFallback] = RenderDefinition(HtmlRenderDiagnosticCodes.FormFieldBackgroundImageStaticFallback, "Interactivity", HtmlDiagnosticSeverity.Warning, "A form control with background-image layers used faithful static rendering instead of a PDF widget that drops the authored paint.", "Remove background-image layers when an interactive PDF field is required, or keep them when visual fidelity is more important."),
        [HtmlRenderDiagnosticCodes.FormFieldBorderStyleStaticFallback] = RenderDefinition(HtmlRenderDiagnosticCodes.FormFieldBorderStyleStaticFallback, "Interactivity", HtmlDiagnosticSeverity.Warning, "A form control with a border style unavailable to PDF widgets used faithful static rendering instead of changing its appearance.", "Use a solid or dashed border when an interactive PDF field is required, or keep dotted, double, or mixed borders when visual fidelity is more important."),
        [HtmlRenderDiagnosticCodes.FormFieldTypographyStaticFallback] = RenderDefinition(HtmlRenderDiagnosticCodes.FormFieldTypographyStaticFallback, "Interactivity", HtmlDiagnosticSeverity.Warning, "A text or choice control used faithful static rendering because the generated PDF widget cannot preserve its authored font family or style.", "Use regular Arial, Helvetica, or generic sans-serif typography when an interactive PDF field is required, or keep the authored typography when visual fidelity is more important."),
        [HtmlRenderDiagnosticCodes.FormFieldNoWrapStaticFallback] = RenderDefinition(HtmlRenderDiagnosticCodes.FormFieldNoWrapStaticFallback, "Interactivity", HtmlDiagnosticSeverity.Warning, "A textarea with wrap=off used faithful static rendering because generated PDF multiline widgets cannot preserve no-wrap appearance semantics.", "Remove wrap=off when an interactive PDF textarea is required, or keep it for faithful static rendering."),
        [HtmlRenderDiagnosticCodes.OpacityValueUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.OpacityValueUnsupported, "PaintFidelity", HtmlDiagnosticSeverity.Warning, "A CSS opacity value used the opaque fallback.", "Use a finite number or percentage; values outside the visible range are clamped."),
        [HtmlRenderDiagnosticCodes.ReplacedElementValueUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.ReplacedElementValueUnsupported, "LayoutFidelity", HtmlDiagnosticSeverity.Warning, "A replaced-element sizing or object-placement value used a deterministic fallback.", "Use a positive aspect ratio, fill, contain, cover, none, or scale-down object fitting, and a supported keyword, length, or percentage object position."),
        [HtmlRenderDiagnosticCodes.BorderRadiusValueUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.BorderRadiusValueUnsupported, "PaintFidelity", HtmlDiagnosticSeverity.Warning, "A CSS border radius used square-corner fallback.", "Use one to four non-negative length or percentage radii, an optional slash-separated vertical axis, or valid one- or two-axis corner longhands."),
        [HtmlRenderDiagnosticCodes.BoxShadowLayerLimit] = RenderDefinition(HtmlRenderDiagnosticCodes.BoxShadowLayerLimit, "ResourceLimit", HtmlDiagnosticSeverity.Warning, "CSS box-shadow layers beyond the configured per-element limit were omitted.", "Increase MaxBoxShadowLayers only for trusted documents or reduce the number of declared shadows."),
        [HtmlRenderDiagnosticCodes.BoxShadowValueUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.BoxShadowValueUnsupported, "PaintFidelity", HtmlDiagnosticSeverity.Warning, "A CSS box shadow was omitted.", "Use comma-separated inset or outer shadows with two offsets, an optional non-negative blur radius, an optional signed spread radius, and a supported color."),
        [HtmlRenderDiagnosticCodes.TextShadowLayerLimit] = RenderDefinition(HtmlRenderDiagnosticCodes.TextShadowLayerLimit, "ResourceLimit", HtmlDiagnosticSeverity.Warning, "CSS text-shadow layers beyond the configured per-element limit were omitted.", "Increase MaxTextShadowLayers only for trusted documents or reduce the number of declared shadows."),
        [HtmlRenderDiagnosticCodes.TextShadowValueUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.TextShadowValueUnsupported, "PaintFidelity", HtmlDiagnosticSeverity.Warning, "A CSS text shadow was omitted.", "Use comma-separated shadows with two offsets, an optional non-negative blur radius, and a supported color."),
        [HtmlRenderDiagnosticCodes.BorderPaintValueUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.BorderPaintValueUnsupported, "PaintFidelity", HtmlDiagnosticSeverity.Warning, "A CSS border paint declaration used no-border fallback.", "Use one to four non-negative widths, supported colors, and solid, dashed, dotted, double, none, or hidden side styles."),
        [HtmlRenderDiagnosticCodes.OutlinePaintValueUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.OutlinePaintValueUnsupported, "PaintFidelity", HtmlDiagnosticSeverity.Warning, "A CSS outline paint declaration was omitted.", "Use one non-negative width, supported color, signed offset, and solid, dashed, dotted, double, none, or hidden style."),
        [HtmlRenderDiagnosticCodes.PositionInsetUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.PositionInsetUnsupported, "LayoutFidelity", HtmlDiagnosticSeverity.Warning, "A positioned inset could not be resolved and used its documented fallback.", "Use a supported CSS length or percentage with a definite containing-block dimension."),
        [HtmlRenderDiagnosticCodes.PositioningModeUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.PositioningModeUnsupported, "LayoutFidelity", HtmlDiagnosticSeverity.Warning, "A CSS positioning mode currently falls back to normal flow.", "Use static, relative, absolute, fixed, or sticky positioning without unsupported containing-block features."),
        [HtmlRenderDiagnosticCodes.PositionStaticAnchorFallback] = RenderDefinition(HtmlRenderDiagnosticCodes.PositionStaticAnchorFallback, "LayoutFidelity", HtmlDiagnosticSeverity.Warning, "An automatic positioned inset could not use the element's hypothetical normal-flow anchor.", "Use an explicit inset or place the positioned element in a supported block, flex, or grid static-position context."),
        [HtmlRenderDiagnosticCodes.PositionStickyStatic] = RenderDefinition(HtmlRenderDiagnosticCodes.PositionStickyStatic, "LayoutFidelity", HtmlDiagnosticSeverity.Info, "A sticky-positioned element was captured at its stable static document position.", "Use fixed positioning for repeated page overlays; sticky scroll-state changes are not meaningful in a static document snapshot."),
        [HtmlRenderDiagnosticCodes.PositionZIndexPending] = RenderDefinition(HtmlRenderDiagnosticCodes.PositionZIndexPending, "CssSyntax", HtmlDiagnosticSeverity.Warning, "A z-index declaration could not be parsed as an integer or auto and therefore used auto stacking.", "Use auto or an integer z-index value."),
        [HtmlRenderDiagnosticCodes.PageMarginContentUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.PageMarginContentUnsupported, "PagedMedia", HtmlDiagnosticSeverity.Warning, "A page-margin generated-content expression could not be represented.", "Use quoted text, counter(page), counter(pages), string(), or a standalone element() reference with a supported page selection keyword."),
        [HtmlRenderDiagnosticCodes.PageMarginPositionUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.PageMarginPositionUnsupported, "PagedMedia", HtmlDiagnosticSeverity.Warning, "A page-margin position is not recognized by the direct renderer.", "Use one of the standard CSS top, bottom, left, right, or corner page-margin box names."),
        [HtmlRenderDiagnosticCodes.PagePseudoGeometryPending] = RenderDefinition(HtmlRenderDiagnosticCodes.PagePseudoGeometryPending, "PagedMedia", HtmlDiagnosticSeverity.Warning, "A fragment crossing into a page with different geometry could not be reconstructed from logical source progress.", "Avoid changing page geometry across this complex continuation, or split the content at an explicit page boundary."),
        [HtmlRenderDiagnosticCodes.PageSelectorPending] = RenderDefinition(HtmlRenderDiagnosticCodes.PageSelectorPending, "PagedMedia", HtmlDiagnosticSeverity.Warning, "A complex page selector could not be applied per page.", "Use a generic, named, :first, :left, or :right @page selector, optionally combining one name with one supported pseudo-page."),
        [HtmlRenderDiagnosticCodes.PageSizeUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.PageSizeUnsupported, "PagedMedia", HtmlDiagnosticSeverity.Warning, "An @page size declaration could not be mapped.", "Use a supported named size or two absolute physical lengths."),
        [HtmlRenderDiagnosticCodes.PageBleedUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.PageBleedUnsupported, "PrintProduction", HtmlDiagnosticSeverity.Warning, "An @page bleed declaration could not be mapped.", "Use auto or one non-negative absolute CSS length."),
        [HtmlRenderDiagnosticCodes.PageMarksUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.PageMarksUnsupported, "PrintProduction", HtmlDiagnosticSeverity.Warning, "An @page marks declaration could not be mapped.", "Use none, crop, cross, or crop cross."),
        [HtmlRenderDiagnosticCodes.MathMlContentUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.MathMlContentUnsupported, "LayoutFidelity", HtmlDiagnosticSeverity.Warning, "MathML content could not be represented by the bounded shared mathematical expression model.", "Use supported Presentation MathML rows, tokens, fractions, roots, scripts, limits, fences, matrices, enclosures, and annotations."),
        [HtmlRenderDiagnosticCodes.SvgContentUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.SvgContentUnsupported, "ImageFidelity", HtmlDiagnosticSeverity.Warning, "SVG content could not be represented completely by the bounded shared vector scene.", "Use supported primitives or paths, bounded local shape/group references, local linear/radial paint servers, user-space masks, static drop-shadow/blur/offset filters, bounded inline foreign-object XHTML, standard blend modes, positioned tspan text, and affine transforms; dynamic filter graphs and external references require a caller-managed fallback."),
        [HtmlRenderDiagnosticCodes.SvgRasterFallback] = RenderDefinition(HtmlRenderDiagnosticCodes.SvgRasterFallback, "ImageFidelity", HtmlDiagnosticSeverity.Info, "A caller-supplied image codec rasterized SVG features outside the bounded shared vector scene.", "Keep the codec configured when visual fidelity matters more than searchable vector content, or simplify the SVG to the supported vector subset."),
        [HtmlRenderDiagnosticCodes.ResourceByteLimitExceeded] = RenderDefinition(HtmlRenderDiagnosticCodes.ResourceByteLimitExceeded, "ResourcePolicy", HtmlDiagnosticSeverity.Warning, "A resource exceeded the configured per-resource byte limit.", "Reduce the resource or raise the explicit limit for trusted input."),
        [HtmlRenderDiagnosticCodes.ResourceCountLimitExceeded] = RenderDefinition(HtmlRenderDiagnosticCodes.ResourceCountLimitExceeded, "ResourcePolicy", HtmlDiagnosticSeverity.Error, "Resolved resources exceeded the configured count limit.", "Reduce the resource graph or raise the explicit count limit for trusted input."),
        [HtmlRenderDiagnosticCodes.ResourceRequestLimitExceeded] = RenderDefinition(HtmlRenderDiagnosticCodes.ResourceRequestLimitExceeded, "ResourcePolicy", HtmlDiagnosticSeverity.Error, "Resource resolver invocations exceeded the configured request limit.", "Reduce broken or unavailable references, or raise the explicit request limit for trusted input."),
        [HtmlRenderDiagnosticCodes.ResourceContentTypeRejected] = RenderDefinition(HtmlRenderDiagnosticCodes.ResourceContentTypeRejected, "ResourcePolicy", HtmlDiagnosticSeverity.Warning, "A resolver returned an incompatible media type.", "Return bytes whose declared media type matches the requested image or stylesheet kind."),
        [HtmlRenderDiagnosticCodes.ResourceLoadFailed] = RenderDefinition(HtmlRenderDiagnosticCodes.ResourceLoadFailed, "ResourcePolicy", HtmlDiagnosticSeverity.Warning, "The configured resource resolver failed.", "Inspect the resolver boundary and return null for intentionally unavailable resources."),
        [HtmlRenderDiagnosticCodes.ResourceTimeout] = RenderDefinition(HtmlRenderDiagnosticCodes.ResourceTimeout, "ResourcePolicy", HtmlDiagnosticSeverity.Warning, "Resource resolution exceeded its timeout.", "Reduce resolver latency or raise the bounded timeout for trusted workloads."),
        [HtmlRenderDiagnosticCodes.ResourceUnavailable] = RenderDefinition(HtmlRenderDiagnosticCodes.ResourceUnavailable, "ResourcePolicy", HtmlDiagnosticSeverity.Warning, "The configured resolver returned no resource.", "Provide the resource or accept the diagnosed placeholder."),
        [HtmlRenderDiagnosticCodes.ResourceUriInvalid] = RenderDefinition(HtmlRenderDiagnosticCodes.ResourceUriInvalid, "ResourcePolicy", HtmlDiagnosticSeverity.Warning, "A resource URI could not be represented as an absolute URI.", "Provide a valid base URI and resource reference."),
        [HtmlRenderDiagnosticCodes.StylesheetEncodingUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.StylesheetEncodingUnsupported, "CssFidelity", HtmlDiagnosticSeverity.Warning, "A resolved stylesheet could not be decoded as supported CSS text.", "Return UTF-8 CSS or UTF-16 CSS with a byte-order mark."),
        [HtmlRenderDiagnosticCodes.StylesheetImportCycle] = RenderDefinition(HtmlRenderDiagnosticCodes.StylesheetImportCycle, "CssFidelity", HtmlDiagnosticSeverity.Warning, "A recursive stylesheet import cycle was suppressed.", "Remove the cyclic @import relationship."),
        [HtmlRenderDiagnosticCodes.StylesheetImportDepthExceeded] = RenderDefinition(HtmlRenderDiagnosticCodes.StylesheetImportDepthExceeded, "ResourcePolicy", HtmlDiagnosticSeverity.Error, "Stylesheet imports exceeded the configured recursion depth.", "Flatten the import graph or raise the explicit depth limit for trusted input."),
        [HtmlRenderDiagnosticCodes.StylesheetUrlResourcesPending] = RenderDefinition(HtmlRenderDiagnosticCodes.StylesheetUrlResourcesPending, "Compatibility", HtmlDiagnosticSeverity.Warning, "Legacy diagnostic retained for source compatibility; external stylesheet URL images, fonts, and imports are resolved by the bounded resource graph.", "Inspect current resource-policy, load, decoding, or format diagnostics for the actionable failure."),
        [HtmlRenderDiagnosticCodes.TableFooterRepeatSuppressed] = RenderDefinition(HtmlRenderDiagnosticCodes.TableFooterRepeatSuppressed, "PagedMedia", HtmlDiagnosticSeverity.Warning, "A repeated table footer left no safe body-row break on an empty page.", "Reduce the footer or row height, increase the page content area, or allow the body row to move without a repeated footer."),
        [HtmlRenderDiagnosticCodes.TableHeaderRepeatSuppressed] = RenderDefinition(HtmlRenderDiagnosticCodes.TableHeaderRepeatSuppressed, "PagedMedia", HtmlDiagnosticSeverity.Warning, "A repeated table header left no safe body-row break on an empty page.", "Reduce the header or row height, increase the page content area, or allow the body row to move without a repeated header."),
        [HtmlRenderDiagnosticCodes.TableValueUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.TableValueUnsupported, "LayoutFidelity", HtmlDiagnosticSeverity.Warning, "A table formatting property used its documented fallback.", "Use top or bottom for caption-side, auto or fixed for table-layout, separate or collapse for border-collapse, and one or two non-negative absolute lengths for border-spacing."),
        [HtmlRenderDiagnosticCodes.TotalResourceByteLimitExceeded] = RenderDefinition(HtmlRenderDiagnosticCodes.TotalResourceByteLimitExceeded, "ResourcePolicy", HtmlDiagnosticSeverity.Error, "Resolved resources exceeded the total byte budget.", "Reduce resource volume or raise the explicit total limit for trusted input."),
        [HtmlRenderDiagnosticCodes.VisualFragmentUnsupported] = RenderDefinition(HtmlRenderDiagnosticCodes.VisualFragmentUnsupported, "PagedMedia", HtmlDiagnosticSeverity.Warning, "A visual could not cross a forced page boundary safely.", "Resize the visual or add a safe break before it.")
    });

    private static readonly IReadOnlyList<HtmlDiagnosticDefinition> OrderedDefinitions = Definitions.Values
        .OrderBy(definition => definition.Category, StringComparer.Ordinal)
        .ThenBy(definition => definition.Code, StringComparer.Ordinal)
        .ToList()
        .AsReadOnly();

    /// <summary>All stable diagnostic definitions in deterministic category/code order.</summary>
    public static IReadOnlyList<HtmlDiagnosticDefinition> Ordered => OrderedDefinitions;

    /// <summary>
    /// Gets all known diagnostic definitions.
    /// </summary>
    public static IReadOnlyDictionary<string, HtmlDiagnosticDefinition> All => Definitions;

    /// <summary>
    /// Looks up support metadata for a diagnostic code.
    /// </summary>
    public static bool TryGet(string code, out HtmlDiagnosticDefinition definition) {
        if (string.IsNullOrWhiteSpace(code)) {
            definition = null!;
            return false;
        }

        HtmlDiagnosticDefinition? found;
        if (Definitions.TryGetValue(code.Trim(), out found)) {
            definition = found;
            return true;
        }

        definition = null!;
        return false;
    }

    /// <summary>
    /// Gets support metadata for a diagnostic code, or a generic definition when the code is unknown.
    /// </summary>
    public static HtmlDiagnosticDefinition GetOrCreateGeneric(string code) {
        if (TryGet(code, out HtmlDiagnosticDefinition definition)) {
            return definition;
        }

        return new HtmlDiagnosticDefinition(
            string.IsNullOrWhiteSpace(code) ? "HtmlDiagnostic" : code.Trim(),
            "General",
            HtmlDiagnosticSeverity.Warning,
            "The HTML workflow emitted a diagnostic that is not yet cataloged.",
            "Use the diagnostic source and detail fields to decide whether input, policy, or converter support should be adjusted.");
    }

    private static HtmlDiagnosticDefinition RenderDefinition(string code, string category, HtmlDiagnosticSeverity severity, string message, string remediation) =>
        new HtmlDiagnosticDefinition(code, category, severity, message, remediation);

    private static HtmlDiagnosticDefinition ConversionDefinition(string code, string category, HtmlDiagnosticSeverity severity, string message, string remediation) =>
        RenderDefinition(code, category, severity, message, remediation);
}
