using OfficeIMO.Excel.GoogleSheets;
using OfficeIMO.PowerPoint.GoogleSlides;
using OfficeIMO.Word.GoogleDocs;

namespace OfficeIMO.Examples.Google {
    internal static class GoogleWorkspaceSupportMatrixWriter {
        public static string ToMarkdown() {
            var markdown = new StringBuilder();
            markdown.AppendLine("---");
            markdown.AppendLine("title: Google Workspace support matrix");
            markdown.AppendLine("description: Code-generated Docs, Sheets, and Slides translation support levels.");
            markdown.AppendLine("order: 80");
            markdown.AppendLine("---");
            markdown.AppendLine();
            markdown.AppendLine("# Google Workspace support matrix");
            markdown.AppendLine();
            markdown.AppendLine("> Generated by `dotnet run --project OfficeIMO.Examples -f net10.0 -- --google-support-matrix Website/content/docs/google-workspace/support/index.md`. Edit the three `*FeatureSupportCatalog` classes, then regenerate this file.");
            markdown.AppendLine();
            Append(markdown, "Google Docs", GoogleDocsFeatureSupportCatalog.Features.Select(row => new Row(row.Feature, row.Export.ToString(), row.Import.ToString(), row.Notes)));
            Append(markdown, "Google Sheets", GoogleSheetsFeatureSupportCatalog.Features.Select(row => new Row(row.Feature, row.Export.ToString(), row.Import.ToString(), row.Notes)));
            Append(markdown, "Google Slides", GoogleSlidesFeatureSupportCatalog.Features.Select(row => new Row(row.Feature, row.Export.ToString(), row.Import.ToString(), row.Notes)));
            markdown.AppendLine("## How to read the matrix");
            markdown.AppendLine();
            markdown.AppendLine("`Native` means OfficeIMO maps the documented editable API model. `Partial` means a defined subset is native and the notes name the boundary. `Flattened` or `Rasterized` is an executed fallback, not a promise of editability. `DriveFallback` means import through Google Office-format conversion. `Unsupported` is reported before mutation according to the selected fidelity policy.");
            return markdown.ToString();
        }

        public static void WriteTo(string path) {
            if (string.IsNullOrWhiteSpace(path)) throw new ArgumentException("An output path is required.", nameof(path));
            string fullPath = Path.GetFullPath(path);
            Directory.CreateDirectory(Path.GetDirectoryName(fullPath)!);
            File.WriteAllText(fullPath, ToMarkdown(), new UTF8Encoding(false));
        }

        private static void Append(StringBuilder markdown, string title, IEnumerable<Row> rows) {
            markdown.AppendLine("## " + title);
            markdown.AppendLine();
            markdown.AppendLine("| Capability | Export | Import | Current boundary |");
            markdown.AppendLine("|---|---|---|---|");
            foreach (Row row in rows) markdown.AppendLine($"| {Escape(row.Feature)} | {row.Export} | {row.Import} | {Escape(row.Notes)} |");
            markdown.AppendLine();
        }

        private static string Escape(string value) => (value ?? string.Empty).Replace("|", "\\|").Replace("\r", " ").Replace("\n", " ");
        private sealed class Row {
            internal Row(string feature, string export, string import, string notes) { Feature = feature; Export = export; Import = import; Notes = notes; }
            internal string Feature { get; }
            internal string Export { get; }
            internal string Import { get; }
            internal string Notes { get; }
        }
    }
}
