#!/usr/bin/env python3
"""Opt-in partition oracle: hash-pinned AOM tables and isolated entropy APIs.

Python stdlib and a C11 compiler are required. Use --work-dir for task-owned
scratch; normal builds never invoke this script. Inspect generated bytes before
using --output to replace the checked-in partition-reference.json.
"""
import argparse
import base64
import json
import pathlib
import re
import shutil
import subprocess
import sys
import urllib.request
sys.dont_write_bytecode = True
from GenerateEntropyFixtures import sha256, write_json


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--work-dir", required=True, type=pathlib.Path)
    parser.add_argument("--output", type=pathlib.Path)
    parser.add_argument("--cc", default="clang")
    args = parser.parse_args()
    here = pathlib.Path(__file__).resolve().parent
    work = args.work_dir.resolve()
    subprocess.run([sys.executable, str(here / "GenerateEntropyFixtures.py"), "--work-dir", str(work), "--cc", args.cc], check=True)
    manifest = json.loads((here / "partition-oracle.json").read_text(encoding="utf-8"))
    source = work / "entropymode.c"
    if source.is_file():
        data = source.read_bytes()
    else:
        with urllib.request.urlopen(manifest["sourceUrl"], timeout=60) as response:
            data = base64.b64decode(response.read(), validate=True)
    if sha256(data) != manifest["sourceSha256"]:
        raise ValueError("AOM partition table source hash mismatch")
    if not source.is_file():
        source.write_bytes(data)
    source_text = data.decode("utf-8")
    match = re.search(r"static const aom_cdf_prob default_partition_cdf.*?=\s*(\{.*?\n\});", source_text, re.S)
    if not match or len(re.findall(r"AOM_CDF(?:4|8|10)\(", match[1])) != 20:
        raise ValueError("Unexpected AOM default partition table shape")
    header = work / "partition-defaults.h"
    notice = source_text[:source_text.index("*/") + 2]
    header.write_text(notice + "\n/* Extracted pinned reference data; see entropymode.c and native-aom notices. */\n"
                      "static const aom_cdf_prob default_partition_cdf[20][11] = " + match[1] + ";\n", encoding="utf-8")
    compiler = shutil.which(args.cc)
    if not compiler:
        raise FileNotFoundError(args.cc)
    harness = here / "GeneratePartitionFixtures.c"
    native = work / "native-aom"
    executable = work / "generate-partitions"
    command = [compiler, "-std=c11", "-Wall", "-Wextra", "-Werror", "-O2", "-I", str(native), "-I", str(work), str(harness)]
    command += [str(native / "aom_dsp" / name) for name in ("entenc.c", "entdec.c", "entcode.c")]
    subprocess.run(command + ["-o", str(executable)], check=True)
    raw = work / "native-partitions.json"
    subprocess.run([str(executable), str(raw)], check=True)
    vectors = json.loads(raw.read_text(encoding="utf-8"))
    repo = here.parents[2]
    entropy_manifest = json.loads((here / manifest["entropySourceManifest"]).read_text(encoding="utf-8"))
    prefixes = []
    for fixture in entropy_manifest["framePrefixes"]:
        geometry = manifest["prefixGeometry"][fixture["name"]]
        result = work / (fixture["name"] + "-partitions.json")
        subprocess.run([str(executable), str(repo / fixture["path"]), str(fixture["offset"]), str(fixture["length"]),
                        str(geometry["miRows"]), str(geometry["miCols"]), str(geometry["superblockPixels"]), str(result)], check=True)
        prefix = {key: fixture[key] for key in ("name", "alpha", "offset", "length")}
        prefix.update(geometry)
        prefix["partitions"] = json.loads(result.read_text(encoding="utf-8"))
        prefixes.append(prefix)
    vectors["framePrefixes"] = prefixes
    output = args.output.resolve() if args.output else work / "partition-reference.json"
    write_json(output, vectors)
    receipt = {"tag": manifest["tag"], "sourceSha256": manifest["sourceSha256"],
               "harnessSha256": sha256(harness.read_bytes()), "generatorSha256": sha256(pathlib.Path(__file__).read_bytes()),
               "entropyReceiptSha256": sha256((work / "oracle-receipt.json").read_bytes()),
               "fixtureSha256": sha256(output.read_bytes()), "nativeSelfCheck": vectors["nativeSelfCheck"], "cases": len(vectors["cases"]),
               "framePrefixes": len(prefixes)}
    write_json(work / "partition-oracle-receipt.json", receipt)
    print("Generated " + str(output) + " (SHA256 " + receipt["fixtureSha256"] + ")")


if __name__ == "__main__":
    main()
