using System.Text;
using System.Text.Json;
using OfficeIMO;
using OfficeIMO.Access;

if (args.Length == 2 && args[0] == "--bootstrap") {
    OfficeIMO.Access.Verification.NativeBootstrapProbe.Generate(args[1]);
    Console.WriteLine("Generated a fixed native catalog/table probe without seed files. Run the independent DAO qualification route.");
    return;
}
if (args.Length == 2 && args[0] == "--catalog") {
    string directory = Path.GetFullPath(args[1]);
    Directory.CreateDirectory(directory);
    var catalog = new { schemaVersion = 1, operations = AccessCapabilities.Operations.Select(x => new { operation = x.Operation, supported = x.IsSupported, boundary = x.Boundary }) };
    File.WriteAllText(Path.Combine(directory, "operations.json"), JsonSerializer.Serialize(catalog, new JsonSerializerOptions { WriteIndented = true }) + "\n", new UTF8Encoding(false));
    var markdown = new StringBuilder("<!-- Generated by OfficeIMO.Access.Verification --catalog. Edit AccessCapabilities.cs. -->\n# Access operation capabilities\n\nDetection and in-memory modeling are separate from native decoding and writing.\n\n| Operation | Supported | Qualified boundary |\n| --- | --- | --- |\n");
    foreach (var operation in AccessCapabilities.Operations) markdown.AppendLine($"| `{operation.Operation}` | {(operation.IsSupported ? "Yes" : "No")} | {operation.Boundary} |");
    File.WriteAllText(Path.Combine(directory, "CAPABILITIES.md"), markdown.ToString(), new UTF8Encoding(false));
    return;
}
if (args.Length != 1) throw new ArgumentException("Supply the independent corpus directory, or --catalog <output-directory>.");
string corpus = Path.GetFullPath(args[0]);

using AccessDocument database = AccessDocument.Create(new AccessCreateOptions { Format = AccessFileFormat.Accdb });
AccessTable contacts = database.Tables.Add("Contacts");
contacts.Columns.Add("Id", AccessDataType.AutoNumber);
contacts.Columns.Add("Name", AccessDataType.ShortText, maxLength: 120);
contacts.Indexes.AddPrimaryKey("PK_Contacts", "Id");
using (AccessUpdateScope edit = database.BeginUpdate()) {
    contacts.AppendRow(new AccessRowValues { ["Name"] = "Ada" });
    edit.Commit();
}
using (AccessDataReader reader = contacts.OpenDataReader()) {
    if (!reader.Read() || reader.GetString(1) != "Ada" || reader.IsSpecified(0)) throw new InvalidDataException("Model row contract failed.");
}
// Exercise the actual provider-neutral DbDataReader consumer boundary.
using (var table = new System.Data.DataTable()) {
    using AccessDataReader reader = contacts.OpenDataReader();
    table.Load(reader);
    if (table.Rows.Count != 1 || (string)table.Rows[0]["Name"] != "Ada") throw new InvalidDataException("DataTable.Load reader interoperability failed.");
}
database.Queries.Add("Names", "SELECT Name FROM Contacts;");
Console.WriteLine(database.Queries["Names"].Sql);
AccessOperationReport assessment = database.AssessSave("contacts.accdb");
assessment.RequireCurrent(database);
ExpectUnsupported(() => assessment.RequireNoLoss());
ExpectUnsupported(() => database.Save("contacts.accdb"));
ExpectUnsupported(() => database.AssessSave("contacts.mdb", new AccessSaveOptions { LossPolicy = OfficeConversionLossPolicy.Block }).RequireNoLoss());

foreach (string file in new[] { "jet4.mdb", "ace12.accdb" }) {
    using AccessDocument source = await AccessDocument.LoadAsync(Path.Combine(corpus, file), new AccessLoadOptions { AccessMode = DocumentAccessMode.ReadOnly });
    source.ValidateSourceIdentity();
    if (source.CatalogStatus != AccessCatalogStatus.NotDecoded || source.VbaProject.CatalogStatus != AccessCatalogStatus.NotDecoded) throw new InvalidDataException("Native inventory support was overstated.");
    Console.WriteLine($"{file}: {source.Profile}; {source.Inspection!.PageCount} pages; {source.Inspection.Sha256}; native catalog/VBA not decoded");
    foreach (AccessQueryDefinition query in source.Queries) Console.WriteLine(query.Sql);
    foreach (AccessApplicationObject form in source.Forms) Console.WriteLine(form.Name);
    foreach (AccessApplicationObject report in source.Reports) Console.WriteLine(report.Name);
    foreach (string module in source.VbaProject.ModuleNames) Console.WriteLine(module);
    ExpectUnsupported(() => { using var rows = source.Tables["Contacts"].OpenDataReader(); });
}
Console.WriteLine("External consumer: model, reader, edit scope, inert inspection and unsupported output contracts passed.");
static void ExpectUnsupported(Action action) {
    try { action(); throw new InvalidOperationException("An unqualified operation unexpectedly succeeded."); }
    catch (NotSupportedException) { }
}
