using OfficeIMO;
using OfficeIMO.Access;
using System.Data;
using System.Text;
using System.Text.Json;

if (args.Length == 3 && args[0] == "--edit-vba-hosts") {
    OfficeIMO.Access.Verification.VbaHostEditingProbe.Generate(args[1], args[2]);
    Console.WriteLine("Public native code-behind/event edits and unrelated stream preservation verified. Native Access qualification is separate.");
    return;
}

if (args.Length == 3 && (args[0] == "--edit-vba" || args[0] == "--recreate-vba")) {
    OfficeIMO.Access.Verification.VbaEditingProbe.Generate(args[1], args[2], args[0] == "--recreate-vba");
    Console.WriteLine("Public native VBA edits and unchanged unrelated streams verified. Native Access/VBE qualification is separate.");
    return;
}

if (args.Length == 2 && args[0] == "--create") {
    OfficeIMO.Access.Verification.CreationProbe.Generate(args[1]);
    Console.WriteLine("Public model creation and native decode passed. Run independent creation qualification."); return;
}

if (args.Length == 3 && args[0] == "--preserve") {
    OfficeIMO.Access.Verification.PreservationProbe.Generate(args[1], args[2]);
    Console.WriteLine("Whole-file and application-stream preservation verified. Run Test-NativePreservation.ps1 for independent Access reopening.");
    return;
}

if (args.Length == 2 && args[0] == "--verify-edits") {
    OfficeIMO.Access.Verification.CreationProbe.VerifyAccessEdits(args[1]);
    Console.WriteLine("Access-resaved changes, deletion, append, relationships and original values decoded successfully.");
    return;
}
if (args.Length == 2 && args[0] == "--catalog") {
    string directory = Path.GetFullPath(args[1]);
    Directory.CreateDirectory(directory);
    var catalog = new { schemaVersion = 1, operations = AccessCapabilities.Operations.Select(x => new { operation = x.Operation, supported = x.IsSupported, boundary = x.Boundary }) };
    File.WriteAllText(Path.Combine(directory, "operations.json"), JsonSerializer.Serialize(catalog, new JsonSerializerOptions { WriteIndented = true }) + "\n", new UTF8Encoding(false));
    StringBuilder markdown = new StringBuilder("<!-- Generated by OfficeIMO.Access.Verification --catalog. Edit AccessCapabilities.cs. -->\n# Access operation capabilities\n\nNative read, in-memory modeling and persistence have separate qualification boundaries.\n\n| Operation | Supported | Qualified boundary |\n| --- | --- | --- |\n");
    foreach (AccessOperationCapability operation in AccessCapabilities.Operations) markdown.AppendLine($"| `{operation.Operation}` | {(operation.IsSupported ? "Yes" : "No")} | {operation.Boundary} |");
    File.WriteAllText(Path.Combine(directory, "CAPABILITIES.md"), markdown.ToString(), new UTF8Encoding(false));
    return;
}
if (args.Length != 1) throw new ArgumentException("Supply the independent corpus directory, or --catalog <output-directory>.");
string corpus = Path.GetFullPath(args[0]);

using AccessDocument database = AccessDocument.Create(new AccessCreateOptions { Format = AccessFileFormat.Accdb });
AccessTable contacts = database.Tables.Add("Contacts");
contacts.Columns.Add("Id", AccessDataType.AutoNumber);
contacts.Columns.Add("Name", AccessDataType.ShortText, maxLength: 120);
contacts.Indexes.AddPrimaryKey("PK_Contacts", "Id");
using (AccessUpdateScope edit = database.BeginUpdate()) {
    contacts.AppendRow(new AccessRowValues { ["Name"] = "Ada" });
    edit.Commit();
}
using (AccessDataReader reader = contacts.OpenDataReader()) {
    Require(reader.Read() && reader.GetString(1) == "Ada" && !reader.IsSpecified(0), "Model row contract");
}
database.Queries.Add("Names", "SELECT Name FROM Contacts;");
AccessOperationReport assessment = database.AssessSave("contacts.accdb");
assessment.RequireCurrent(database);
ExpectUnsupported(() => assessment.RequireNoLoss());
ExpectUnsupported(() => database.Save("contacts.accdb"));
ExpectUnsupported(() => database.AssessSave("contacts.mdb", new AccessSaveOptions { LossPolicy = OfficeConversionLossPolicy.Block }).RequireNoLoss());

foreach (string file in new[] { "jet4.mdb", "ace12.accdb" }) {
    using AccessDocument source = await AccessDocument.LoadAsync(Path.Combine(corpus, file), new AccessLoadOptions { AccessMode = DocumentAccessMode.ReadOnly });
    source.ValidateSourceIdentity();
    Require(source.CatalogStatus == AccessCatalogStatus.Decoded && source.Forms.CatalogStatus == AccessCatalogStatus.Decoded && source.VbaProject.CatalogStatus == AccessCatalogStatus.Decoded, "Separate native inventories");
    Require(source.Tables["Contacts"].Indexes["PK_Contacts"].IsPrimaryKey && source.Relationships.Count == 1, "Native schema");
    using DataTable table = new DataTable(); using AccessDataReader reader = source.Tables["Contacts"].OpenDataReader();
    table.Load(reader);
    Require(table.Rows.Count == 2 && (string)table.Rows[0]["DisplayName"] == "Ada" && (decimal)table.Rows[0]["Amount"] == 12.3456m, "DataTable native interoperability");
    Require(source.Queries["ContactsByGroup"].HasSql && source.Queries["ContactsByGroup"].Parameters.Count == 1, "Inert native query");
    using AccessDocument headerOnly = AccessDocument.Load(Path.Combine(corpus, file), new AccessLoadOptions { DecodeCatalog = false });
    Require(headerOnly.CatalogStatus == AccessCatalogStatus.NotDecoded, "Header-only inventory");
    ExpectUnsupported(() => { _ = headerOnly.Tables["Contacts"]; });
    Console.WriteLine($"{file}: {source.Profile}; {source.Tables.Count} user tables; native catalog and typed rows passed");
}
using (AccessDocument source = AccessDocument.Load(Path.Combine(corpus, "Readers/values-ace.accdb"), new AccessLoadOptions { TableNames = new[] { "Scalars", "Structured" } })) {
    using AccessDataReader rows = source.Tables["Scalars"].OpenDataReader(); Require(rows.Read(), "First native row");
    Require(rows.GetDecimal(rows.GetOrdinal("Precise")) == 1234567890123456789.123456789m, "Decimal precision");
    using Stream binary = rows.GetStream(rows.GetOrdinal("Payload"));
    byte[] buffer = new byte[1024]; int length = 0, count;
    while ((count = await binary.ReadAsync(buffer, 0, buffer.Length)) != 0) {
        for (int i = 0; i < count; i++) Require(buffer[i] == (byte)((length + i) * 17 % 251), "Incremental native binary bytes");
        length += count;
    }
    Require(length == 20000, "Native binary length");
    using AccessDataReader complexRows = source.Tables["Structured"].OpenDataReader(); Require(complexRows.Read(), "Structured row");
    AccessComplexValue tags = (AccessComplexValue)complexRows["Tags"];
    Require(tags.EnumerateValues().Cast<string>().SequenceEqual(new[] { "Alpha", "Ł🙂" }), "Multivalued structure");
    AccessComplexValue files = (AccessComplexValue)complexRows["Files"];
    AccessAttachment attachment = files.EnumerateAttachments().Single();
    Require(attachment.FileName == "synthetic.bin" && attachment.GetBytes().SequenceEqual(Enumerable.Range(0, 256).Select(x => (byte)x)), "Independent attachment bytes");
}
foreach (string? file in new[] { "access2000.mdb", "access2002-2003.mdb" }) {
    using AccessDocument source = AccessDocument.Load(Path.Combine(corpus, "Generations", file));
    Require(source.Tables["Legacy"].Columns["Link"].IsHyperlink && source.Queries["LegacyRawUnion"].Sql.Contains("UNION ALL"), "Jet 4 generation metadata");
    Require(!source.Queries["LegacyGrouped"].HasSql && source.Queries["LegacyGrouped"].NativeRecords.Count > 0, "Unsupported query remains exact and explicit");
    ExpectUnsupported(() => source.Tables["LocalLink"].OpenDataReader());
    Require(!source.Tables["CredentialLink"].LinkedTable!.Connection!.Contains("Fixture123"), "Credential redaction");
}
using (AccessDocument source = AccessDocument.Load(Path.Combine(corpus, "Generations/fractional-values.accdb"))) {
    using AccessDataReader rows = source.Tables["Extended"].OpenDataReader(); Require(rows.Read(), "Modern profile row");
    Require(rows.GetDateTime(rows.GetOrdinal("Occurred")) == new DateTime(2, 1, 2, 3, 4, 5).AddTicks(1234567), "Seven-digit extended precision");
    Require(rows.GetInt64(rows.GetOrdinal("Large")) == long.MaxValue, "Large Number precision");
    Require(source.AssessSave("target.mdb").Diagnostics.Any(x => x.Code == "access.conversion.loss.extended-date"), "Generation conversion assessment");
}
Console.WriteLine("Public consumer passed: model, native schema/rows, selective reads, lazy binary, complex values, generation metadata and unsupported query authoring/conversion.");
static void Require(bool condition, string contract) { if (!condition) throw new InvalidDataException(contract + " failed."); }
static void ExpectUnsupported(Action action) {
    try { action(); throw new InvalidOperationException("An unqualified operation unexpectedly succeeded."); }
    catch (NotSupportedException) { }
}
