namespace OfficeIMO.Invoicing.Pdf;

public sealed partial class InvoicePdfLanguagePack {
    private static readonly IReadOnlyDictionary<InvoicePdfText, string> DutchLabels = Translate(EnglishLabels,
        (InvoicePdfText.Invoice, "Factuur"), (InvoicePdfText.CreditNote, "Creditnota"),
        (InvoicePdfText.Seller, "Verkoper"), (InvoicePdfText.Buyer, "Koper"), (InvoicePdfText.Item, "Artikel"),
        (InvoicePdfText.Quantity, "Hoeveelheid"), (InvoicePdfText.NetPrice, "Nettoprijs"), (InvoicePdfText.Vat, "Btw"),
        (InvoicePdfText.NetAmount, "Nettobedrag"), (InvoicePdfText.VatCategory, "Btw-categorie"),
        (InvoicePdfText.TaxableAmount, "Belastbaar bedrag"), (InvoicePdfText.VatAmount, "Btw-bedrag"),
        (InvoicePdfText.Exemption, "Vrijstelling"), (InvoicePdfText.Issued, "Uitgegeven"), (InvoicePdfText.Due, "Vervaldatum"),
        (InvoicePdfText.BuyerReference, "Kopersreferentie"), (InvoicePdfText.Currency, "Valuta"),
        (InvoicePdfText.DocumentAdjustments, "Documentcorrecties"), (InvoicePdfText.Charge, "Toeslag"),
        (InvoicePdfText.Allowance, "Korting"), (InvoicePdfText.LineNetTotal, "Totaal nettoregels"),
        (InvoicePdfText.Allowances, "Kortingen"), (InvoicePdfText.Charges, "Toeslagen"),
        (InvoicePdfText.TotalExcludingVat, "Totaal excl. btw"), (InvoicePdfText.VatTotal, "Btw totaal"),
        (InvoicePdfText.TotalIncludingVat, "Totaal incl. btw"), (InvoicePdfText.Prepaid, "Vooruitbetaald"),
        (InvoicePdfText.Rounding, "Afronding"), (InvoicePdfText.AmountDue, "Te betalen"),
        (InvoicePdfText.From, "Vanaf"), (InvoicePdfText.Until, "Tot"), (InvoicePdfText.To, "tot"),
        (InvoicePdfText.Identifier, "Identificatie"), (InvoicePdfText.LegalRegistration, "Wettelijke registratie"),
        (InvoicePdfText.ElectronicAddress, "Elektronisch adres"), (InvoicePdfText.OrderLine, "Bestelregel"),
        (InvoicePdfText.AccountingReference, "Boekhoudreferentie"), (InvoicePdfText.ObjectIdentifier, "Object"),
        (InvoicePdfText.StandardItem, "Standaardartikel"), (InvoicePdfText.SellerItem, "Artikel verkoper"),
        (InvoicePdfText.BuyerItem, "Artikel koper"), (InvoicePdfText.Origin, "Oorsprong"),
        (InvoicePdfText.Classification, "Classificatie"), (InvoicePdfText.Version, "versie"),
        (InvoicePdfText.Period, "Periode"), (InvoicePdfText.GrossPrice, "Brutoprijs"),
        (InvoicePdfText.PriceDiscount, "Prijskorting"), (InvoicePdfText.ReasonCode, "Redencode"),
        (InvoicePdfText.Base, "Basis"), (InvoicePdfText.Percentage, "Percentage"),
        (InvoicePdfText.PurchaseOrder, "Inkooporder"), (InvoicePdfText.SalesOrder, "Verkooporder"),
        (InvoicePdfText.Contract, "Contract"), (InvoicePdfText.Project, "Project"),
        (InvoicePdfText.DespatchAdvice, "Verzendadvies"), (InvoicePdfText.ReceivingAdvice, "Ontvangstadvies"),
        (InvoicePdfText.Tender, "Aanbesteding"), (InvoicePdfText.InvoicedObject, "Gefactureerd object"),
        (InvoicePdfText.BusinessProcess, "Bedrijfsproces"), (InvoicePdfText.DocumentType, "Documenttype"),
        (InvoicePdfText.TaxPoint, "Btw-datum"), (InvoicePdfText.PrecedingInvoice, "Vorige factuur"),
        (InvoicePdfText.VatAccountingCurrency, "Btw in boekhoudvaluta"), (InvoicePdfText.References, "Referenties"),
        (InvoicePdfText.Delivery, "Levering"), (InvoicePdfText.Location, "Locatie"), (InvoicePdfText.Payee, "Begunstigde"),
        (InvoicePdfText.TaxRepresentative, "Fiscaal vertegenwoordiger"), (InvoicePdfText.Payment, "Betaling"),
        (InvoicePdfText.PaymentMeans, "Betaalmiddel"), (InvoicePdfText.Reference, "Referentie"),
        (InvoicePdfText.Account, "Rekening"), (InvoicePdfText.Mandate, "Mandaat"),
        (InvoicePdfText.Creditor, "Schuldeiser"), (InvoicePdfText.DebitedAccount, "Gedebiteerde rekening"),
        (InvoicePdfText.Card, "Kaart"), (InvoicePdfText.Ending, "Eindigend op"), (InvoicePdfText.Notes, "Notities"),
        (InvoicePdfText.SupportingDocuments, "Ondersteunende documenten"),
        (InvoicePdfText.PaymentReference, "Betalingsreferentie"), (InvoicePdfText.Approvals, "Goedkeuringen"));

    private static readonly IReadOnlyDictionary<InvoicePdfText, string> PortugueseLabels = Translate(EnglishLabels,
        (InvoicePdfText.Invoice, "Fatura"), (InvoicePdfText.CreditNote, "Nota de crédito"),
        (InvoicePdfText.Seller, "Vendedor"), (InvoicePdfText.Buyer, "Comprador"), (InvoicePdfText.Item, "Item"),
        (InvoicePdfText.Quantity, "Quantidade"), (InvoicePdfText.NetPrice, "Preço líquido"), (InvoicePdfText.Vat, "IVA"),
        (InvoicePdfText.NetAmount, "Montante líquido"), (InvoicePdfText.VatCategory, "Categoria de IVA"),
        (InvoicePdfText.TaxableAmount, "Montante tributável"), (InvoicePdfText.VatAmount, "Montante de IVA"),
        (InvoicePdfText.Exemption, "Isenção"), (InvoicePdfText.Issued, "Emitida"), (InvoicePdfText.Due, "Vencimento"),
        (InvoicePdfText.BuyerReference, "Referência do comprador"), (InvoicePdfText.Currency, "Moeda"),
        (InvoicePdfText.DocumentAdjustments, "Ajustes do documento"), (InvoicePdfText.Charge, "Encargo"),
        (InvoicePdfText.Allowance, "Desconto"), (InvoicePdfText.LineNetTotal, "Total líquido das linhas"),
        (InvoicePdfText.Allowances, "Descontos"), (InvoicePdfText.Charges, "Encargos"),
        (InvoicePdfText.TotalExcludingVat, "Total sem IVA"), (InvoicePdfText.VatTotal, "IVA total"),
        (InvoicePdfText.TotalIncludingVat, "Total com IVA"), (InvoicePdfText.Prepaid, "Pré-pago"),
        (InvoicePdfText.Rounding, "Arredondamento"), (InvoicePdfText.AmountDue, "Montante a pagar"),
        (InvoicePdfText.From, "De"), (InvoicePdfText.Until, "Até"), (InvoicePdfText.To, "até"),
        (InvoicePdfText.Identifier, "Identificador"), (InvoicePdfText.LegalRegistration, "Registo legal"),
        (InvoicePdfText.ElectronicAddress, "Endereço eletrónico"), (InvoicePdfText.OrderLine, "Linha da encomenda"),
        (InvoicePdfText.AccountingReference, "Referência contabilística"), (InvoicePdfText.ObjectIdentifier, "Objeto"),
        (InvoicePdfText.StandardItem, "Item padrão"), (InvoicePdfText.SellerItem, "Item do vendedor"),
        (InvoicePdfText.BuyerItem, "Item do comprador"), (InvoicePdfText.Origin, "Origem"),
        (InvoicePdfText.Classification, "Classificação"), (InvoicePdfText.Version, "versão"),
        (InvoicePdfText.Period, "Período"), (InvoicePdfText.GrossPrice, "Preço bruto"),
        (InvoicePdfText.PriceDiscount, "Desconto de preço"), (InvoicePdfText.ReasonCode, "Código do motivo"),
        (InvoicePdfText.Base, "Base"), (InvoicePdfText.Percentage, "Percentagem"),
        (InvoicePdfText.PurchaseOrder, "Ordem de compra"), (InvoicePdfText.SalesOrder, "Ordem de venda"),
        (InvoicePdfText.Contract, "Contrato"), (InvoicePdfText.Project, "Projeto"),
        (InvoicePdfText.DespatchAdvice, "Aviso de expedição"), (InvoicePdfText.ReceivingAdvice, "Aviso de receção"),
        (InvoicePdfText.Tender, "Concurso"), (InvoicePdfText.InvoicedObject, "Objeto faturado"),
        (InvoicePdfText.BusinessProcess, "Processo de negócio"), (InvoicePdfText.DocumentType, "Tipo de documento"),
        (InvoicePdfText.TaxPoint, "Data de exigibilidade do IVA"), (InvoicePdfText.PrecedingInvoice, "Fatura anterior"),
        (InvoicePdfText.VatAccountingCurrency, "IVA em moeda contabilística"), (InvoicePdfText.References, "Referências"),
        (InvoicePdfText.Delivery, "Entrega"), (InvoicePdfText.Location, "Localização"), (InvoicePdfText.Payee, "Beneficiário"),
        (InvoicePdfText.TaxRepresentative, "Representante fiscal"), (InvoicePdfText.Payment, "Pagamento"),
        (InvoicePdfText.PaymentMeans, "Meio de pagamento"), (InvoicePdfText.Reference, "Referência"),
        (InvoicePdfText.Account, "Conta"), (InvoicePdfText.Mandate, "Mandato"),
        (InvoicePdfText.Creditor, "Credor"), (InvoicePdfText.DebitedAccount, "Conta debitada"),
        (InvoicePdfText.Card, "Cartão"), (InvoicePdfText.Ending, "Terminação"), (InvoicePdfText.Notes, "Notas"),
        (InvoicePdfText.SupportingDocuments, "Documentos de suporte"),
        (InvoicePdfText.PaymentReference, "Referência de pagamento"), (InvoicePdfText.Approvals, "Aprovações"));
}
