using System.Collections.ObjectModel;

namespace OfficeIMO.Invoicing.Pdf;

public sealed partial class InvoicePdfLanguagePack {
    private static ReadOnlyDictionary<InvoicePdfText, string> Labels(params (InvoicePdfText Key, string Value)[] entries) =>
        new ReadOnlyDictionary<InvoicePdfText, string>(entries.ToDictionary(entry => entry.Key, entry => entry.Value));

    private static readonly ReadOnlyDictionary<InvoicePdfText, string> EnglishLabels = Labels(
        (InvoicePdfText.Invoice, "Invoice"), (InvoicePdfText.CreditNote, "Credit note"),
        (InvoicePdfText.Seller, "Seller"), (InvoicePdfText.Buyer, "Buyer"), (InvoicePdfText.Item, "Item"),
        (InvoicePdfText.Quantity, "Quantity"), (InvoicePdfText.NetPrice, "Net price"), (InvoicePdfText.Vat, "VAT"),
        (InvoicePdfText.NetAmount, "Net amount"), (InvoicePdfText.VatCategory, "VAT category"),
        (InvoicePdfText.TaxableAmount, "Taxable amount"), (InvoicePdfText.VatAmount, "VAT amount"),
        (InvoicePdfText.Exemption, "Exemption"), (InvoicePdfText.Issued, "Issued"), (InvoicePdfText.Due, "Due"),
        (InvoicePdfText.BuyerReference, "Buyer reference"), (InvoicePdfText.Currency, "Currency"),
        (InvoicePdfText.DocumentAdjustments, "Document adjustments"), (InvoicePdfText.Charge, "Charge"),
        (InvoicePdfText.Allowance, "Allowance"), (InvoicePdfText.LineNetTotal, "Line net total"),
        (InvoicePdfText.Allowances, "Allowances"), (InvoicePdfText.Charges, "Charges"),
        (InvoicePdfText.TotalExcludingVat, "Total excluding VAT"), (InvoicePdfText.VatTotal, "VAT total"),
        (InvoicePdfText.TotalIncludingVat, "Total including VAT"), (InvoicePdfText.Prepaid, "Prepaid"),
        (InvoicePdfText.Rounding, "Rounding"), (InvoicePdfText.AmountDue, "Amount due"),
        (InvoicePdfText.From, "From"), (InvoicePdfText.Until, "Until"), (InvoicePdfText.To, "to"),
        (InvoicePdfText.Identifier, "Identifier"), (InvoicePdfText.LegalRegistration, "Legal registration"),
        (InvoicePdfText.ElectronicAddress, "Electronic address"), (InvoicePdfText.OrderLine, "Order line"),
        (InvoicePdfText.AccountingReference, "Accounting reference"), (InvoicePdfText.ObjectIdentifier, "Object"),
        (InvoicePdfText.StandardItem, "Standard item"), (InvoicePdfText.SellerItem, "Seller item"),
        (InvoicePdfText.BuyerItem, "Buyer item"), (InvoicePdfText.Origin, "Origin"),
        (InvoicePdfText.Classification, "Classification"), (InvoicePdfText.Version, "version"),
        (InvoicePdfText.Period, "Period"), (InvoicePdfText.GrossPrice, "Gross price"),
        (InvoicePdfText.PriceDiscount, "Price discount"), (InvoicePdfText.ReasonCode, "Reason code"),
        (InvoicePdfText.Base, "Base"), (InvoicePdfText.Percentage, "Percentage"),
        (InvoicePdfText.PurchaseOrder, "Purchase order"), (InvoicePdfText.SalesOrder, "Sales order"),
        (InvoicePdfText.Contract, "Contract"), (InvoicePdfText.Project, "Project"),
        (InvoicePdfText.DespatchAdvice, "Despatch advice"), (InvoicePdfText.ReceivingAdvice, "Receiving advice"),
        (InvoicePdfText.Tender, "Tender"), (InvoicePdfText.InvoicedObject, "Invoiced object"),
        (InvoicePdfText.BusinessProcess, "Business process"), (InvoicePdfText.DocumentType, "Document type"),
        (InvoicePdfText.TaxPoint, "Tax point"), (InvoicePdfText.PrecedingInvoice, "Preceding invoice"),
        (InvoicePdfText.VatAccountingCurrency, "VAT in accounting currency"), (InvoicePdfText.References, "References"),
        (InvoicePdfText.Delivery, "Delivery"), (InvoicePdfText.Location, "Location"), (InvoicePdfText.Payee, "Payee"),
        (InvoicePdfText.TaxRepresentative, "Tax representative"), (InvoicePdfText.Payment, "Payment"),
        (InvoicePdfText.PaymentMeans, "Payment means"), (InvoicePdfText.Reference, "Reference"),
        (InvoicePdfText.Account, "Account"), (InvoicePdfText.Mandate, "Mandate"),
        (InvoicePdfText.Creditor, "Creditor"), (InvoicePdfText.DebitedAccount, "Debited account"),
        (InvoicePdfText.Card, "Card"), (InvoicePdfText.Ending, "Ending"), (InvoicePdfText.Notes, "Notes"),
        (InvoicePdfText.SupportingDocuments, "Supporting documents"));

    private static readonly ReadOnlyDictionary<InvoicePdfText, string> GermanLabels = Translate(EnglishLabels,
        (InvoicePdfText.Invoice, "Rechnung"), (InvoicePdfText.CreditNote, "Gutschrift"),
        (InvoicePdfText.Seller, "Verkäufer"), (InvoicePdfText.Buyer, "Käufer"), (InvoicePdfText.Item, "Position"),
        (InvoicePdfText.Quantity, "Menge"), (InvoicePdfText.NetPrice, "Nettopreis"), (InvoicePdfText.Vat, "MwSt."),
        (InvoicePdfText.NetAmount, "Nettobetrag"), (InvoicePdfText.VatCategory, "MwSt.-Kategorie"),
        (InvoicePdfText.TaxableAmount, "Steuerpflichtiger Betrag"), (InvoicePdfText.VatAmount, "MwSt.-Betrag"),
        (InvoicePdfText.Exemption, "Befreiung"), (InvoicePdfText.Issued, "Ausgestellt"), (InvoicePdfText.Due, "Fällig"),
        (InvoicePdfText.BuyerReference, "Käuferreferenz"), (InvoicePdfText.Currency, "Währung"),
        (InvoicePdfText.DocumentAdjustments, "Belegzu- und -abschläge"), (InvoicePdfText.Charge, "Zuschlag"),
        (InvoicePdfText.Allowance, "Abschlag"), (InvoicePdfText.LineNetTotal, "Summe Positionen netto"),
        (InvoicePdfText.Allowances, "Abschläge"), (InvoicePdfText.Charges, "Zuschläge"),
        (InvoicePdfText.TotalExcludingVat, "Gesamt ohne MwSt."), (InvoicePdfText.VatTotal, "MwSt. gesamt"),
        (InvoicePdfText.TotalIncludingVat, "Gesamt inkl. MwSt."), (InvoicePdfText.Prepaid, "Vorausbezahlt"),
        (InvoicePdfText.Rounding, "Rundung"), (InvoicePdfText.AmountDue, "Fälliger Betrag"),
        (InvoicePdfText.From, "Von"), (InvoicePdfText.Until, "Bis"), (InvoicePdfText.To, "bis"),
        (InvoicePdfText.Identifier, "Kennung"), (InvoicePdfText.LegalRegistration, "Handelsregister"),
        (InvoicePdfText.ElectronicAddress, "Elektronische Adresse"), (InvoicePdfText.OrderLine, "Bestellposition"),
        (InvoicePdfText.AccountingReference, "Buchungsreferenz"), (InvoicePdfText.ObjectIdentifier, "Objekt"),
        (InvoicePdfText.StandardItem, "Standardartikel"), (InvoicePdfText.SellerItem, "Artikel des Verkäufers"),
        (InvoicePdfText.BuyerItem, "Artikel des Käufers"), (InvoicePdfText.Origin, "Ursprung"),
        (InvoicePdfText.Classification, "Klassifizierung"), (InvoicePdfText.Version, "Version"),
        (InvoicePdfText.Period, "Zeitraum"), (InvoicePdfText.GrossPrice, "Bruttopreis"),
        (InvoicePdfText.PriceDiscount, "Preisnachlass"), (InvoicePdfText.ReasonCode, "Grundcode"),
        (InvoicePdfText.Base, "Basis"), (InvoicePdfText.Percentage, "Prozentsatz"),
        (InvoicePdfText.PurchaseOrder, "Bestellung"), (InvoicePdfText.SalesOrder, "Verkaufsauftrag"),
        (InvoicePdfText.Contract, "Vertrag"), (InvoicePdfText.Project, "Projekt"),
        (InvoicePdfText.DespatchAdvice, "Versandanzeige"), (InvoicePdfText.ReceivingAdvice, "Empfangsbestätigung"),
        (InvoicePdfText.Tender, "Ausschreibung"), (InvoicePdfText.InvoicedObject, "Abgerechnetes Objekt"),
        (InvoicePdfText.BusinessProcess, "Geschäftsprozess"), (InvoicePdfText.DocumentType, "Belegart"),
        (InvoicePdfText.TaxPoint, "Steuerzeitpunkt"), (InvoicePdfText.PrecedingInvoice, "Vorherige Rechnung"),
        (InvoicePdfText.VatAccountingCurrency, "MwSt. in Buchungswährung"), (InvoicePdfText.References, "Referenzen"),
        (InvoicePdfText.Delivery, "Lieferung"), (InvoicePdfText.Location, "Ort"), (InvoicePdfText.Payee, "Zahlungsempfänger"),
        (InvoicePdfText.TaxRepresentative, "Steuervertreter"), (InvoicePdfText.Payment, "Zahlung"),
        (InvoicePdfText.PaymentMeans, "Zahlungsmittel"), (InvoicePdfText.Reference, "Referenz"),
        (InvoicePdfText.Account, "Konto"), (InvoicePdfText.Mandate, "Mandat"),
        (InvoicePdfText.Creditor, "Gläubiger"), (InvoicePdfText.DebitedAccount, "Belastetes Konto"),
        (InvoicePdfText.Card, "Karte"), (InvoicePdfText.Ending, "Endziffern"), (InvoicePdfText.Notes, "Hinweise"),
        (InvoicePdfText.SupportingDocuments, "Belege"));

    private static readonly ReadOnlyDictionary<InvoicePdfText, string> PolishLabels = Translate(EnglishLabels,
        (InvoicePdfText.Invoice, "Faktura"), (InvoicePdfText.CreditNote, "Faktura korygująca"),
        (InvoicePdfText.Seller, "Sprzedawca"), (InvoicePdfText.Buyer, "Nabywca"), (InvoicePdfText.Item, "Pozycja"),
        (InvoicePdfText.Quantity, "Ilość"), (InvoicePdfText.NetPrice, "Cena netto"), (InvoicePdfText.Vat, "VAT"),
        (InvoicePdfText.NetAmount, "Wartość netto"), (InvoicePdfText.VatCategory, "Kategoria VAT"),
        (InvoicePdfText.TaxableAmount, "Podstawa opodatkowania"), (InvoicePdfText.VatAmount, "Kwota VAT"),
        (InvoicePdfText.Exemption, "Zwolnienie"), (InvoicePdfText.Issued, "Data wystawienia"), (InvoicePdfText.Due, "Termin płatności"),
        (InvoicePdfText.BuyerReference, "Referencja nabywcy"), (InvoicePdfText.Currency, "Waluta"),
        (InvoicePdfText.DocumentAdjustments, "Korekty dokumentu"), (InvoicePdfText.Charge, "Dopłata"),
        (InvoicePdfText.Allowance, "Rabat"), (InvoicePdfText.LineNetTotal, "Suma pozycji netto"),
        (InvoicePdfText.Allowances, "Rabaty"), (InvoicePdfText.Charges, "Dopłaty"),
        (InvoicePdfText.TotalExcludingVat, "Razem bez VAT"), (InvoicePdfText.VatTotal, "VAT razem"),
        (InvoicePdfText.TotalIncludingVat, "Razem z VAT"), (InvoicePdfText.Prepaid, "Zapłacono"),
        (InvoicePdfText.Rounding, "Zaokrąglenie"), (InvoicePdfText.AmountDue, "Do zapłaty"),
        (InvoicePdfText.From, "Od"), (InvoicePdfText.Until, "Do"), (InvoicePdfText.To, "do"),
        (InvoicePdfText.Identifier, "Identyfikator"), (InvoicePdfText.LegalRegistration, "Rejestracja prawna"),
        (InvoicePdfText.ElectronicAddress, "Adres elektroniczny"), (InvoicePdfText.OrderLine, "Pozycja zamówienia"),
        (InvoicePdfText.AccountingReference, "Referencja księgowa"), (InvoicePdfText.ObjectIdentifier, "Obiekt"),
        (InvoicePdfText.StandardItem, "Identyfikator standardowy"), (InvoicePdfText.SellerItem, "Pozycja sprzedawcy"),
        (InvoicePdfText.BuyerItem, "Pozycja nabywcy"), (InvoicePdfText.Origin, "Kraj pochodzenia"),
        (InvoicePdfText.Classification, "Klasyfikacja"), (InvoicePdfText.Version, "wersja"),
        (InvoicePdfText.Period, "Okres"), (InvoicePdfText.GrossPrice, "Cena brutto"),
        (InvoicePdfText.PriceDiscount, "Rabat cenowy"), (InvoicePdfText.ReasonCode, "Kod przyczyny"),
        (InvoicePdfText.Base, "Podstawa"), (InvoicePdfText.Percentage, "Procent"),
        (InvoicePdfText.PurchaseOrder, "Zamówienie zakupu"), (InvoicePdfText.SalesOrder, "Zamówienie sprzedaży"),
        (InvoicePdfText.Contract, "Umowa"), (InvoicePdfText.Project, "Projekt"),
        (InvoicePdfText.DespatchAdvice, "Awizo wysyłki"), (InvoicePdfText.ReceivingAdvice, "Potwierdzenie odbioru"),
        (InvoicePdfText.Tender, "Przetarg"), (InvoicePdfText.InvoicedObject, "Przedmiot faktury"),
        (InvoicePdfText.BusinessProcess, "Proces biznesowy"), (InvoicePdfText.DocumentType, "Typ dokumentu"),
        (InvoicePdfText.TaxPoint, "Data podatkowa"), (InvoicePdfText.PrecedingInvoice, "Faktura poprzedzająca"),
        (InvoicePdfText.VatAccountingCurrency, "VAT w walucie księgowej"), (InvoicePdfText.References, "Referencje"),
        (InvoicePdfText.Delivery, "Dostawa"), (InvoicePdfText.Location, "Lokalizacja"), (InvoicePdfText.Payee, "Odbiorca płatności"),
        (InvoicePdfText.TaxRepresentative, "Przedstawiciel podatkowy"), (InvoicePdfText.Payment, "Płatność"),
        (InvoicePdfText.PaymentMeans, "Sposób płatności"), (InvoicePdfText.Reference, "Referencja"),
        (InvoicePdfText.Account, "Rachunek"), (InvoicePdfText.Mandate, "Mandat"),
        (InvoicePdfText.Creditor, "Wierzyciel"), (InvoicePdfText.DebitedAccount, "Obciążany rachunek"),
        (InvoicePdfText.Card, "Karta"), (InvoicePdfText.Ending, "Końcówka"), (InvoicePdfText.Notes, "Uwagi"),
        (InvoicePdfText.SupportingDocuments, "Dokumenty dodatkowe"));

    private static readonly ReadOnlyDictionary<InvoicePdfText, string> FrenchLabels = Translate(EnglishLabels,
        (InvoicePdfText.Invoice, "Facture"), (InvoicePdfText.CreditNote, "Avoir"),
        (InvoicePdfText.Seller, "Vendeur"), (InvoicePdfText.Buyer, "Acheteur"), (InvoicePdfText.Item, "Article"),
        (InvoicePdfText.Quantity, "Quantité"), (InvoicePdfText.NetPrice, "Prix net"), (InvoicePdfText.Vat, "TVA"),
        (InvoicePdfText.NetAmount, "Montant net"), (InvoicePdfText.VatCategory, "Catégorie de TVA"),
        (InvoicePdfText.TaxableAmount, "Base imposable"), (InvoicePdfText.VatAmount, "Montant de TVA"),
        (InvoicePdfText.Exemption, "Exonération"), (InvoicePdfText.Issued, "Émise le"), (InvoicePdfText.Due, "Échéance"),
        (InvoicePdfText.BuyerReference, "Référence acheteur"), (InvoicePdfText.Currency, "Devise"),
        (InvoicePdfText.DocumentAdjustments, "Ajustements du document"), (InvoicePdfText.Charge, "Frais"),
        (InvoicePdfText.Allowance, "Remise"), (InvoicePdfText.LineNetTotal, "Total net des lignes"),
        (InvoicePdfText.Allowances, "Remises"), (InvoicePdfText.Charges, "Frais"),
        (InvoicePdfText.TotalExcludingVat, "Total hors TVA"), (InvoicePdfText.VatTotal, "Total TVA"),
        (InvoicePdfText.TotalIncludingVat, "Total TVA comprise"), (InvoicePdfText.Prepaid, "Déjà payé"),
        (InvoicePdfText.Rounding, "Arrondi"), (InvoicePdfText.AmountDue, "Montant dû"),
        (InvoicePdfText.From, "Du"), (InvoicePdfText.Until, "Au"), (InvoicePdfText.To, "au"),
        (InvoicePdfText.Identifier, "Identifiant"), (InvoicePdfText.LegalRegistration, "Immatriculation"),
        (InvoicePdfText.ElectronicAddress, "Adresse électronique"), (InvoicePdfText.OrderLine, "Ligne de commande"),
        (InvoicePdfText.AccountingReference, "Référence comptable"), (InvoicePdfText.ObjectIdentifier, "Objet"),
        (InvoicePdfText.StandardItem, "Article standard"), (InvoicePdfText.SellerItem, "Article vendeur"),
        (InvoicePdfText.BuyerItem, "Article acheteur"), (InvoicePdfText.Origin, "Origine"),
        (InvoicePdfText.Classification, "Classification"), (InvoicePdfText.Version, "version"),
        (InvoicePdfText.Period, "Période"), (InvoicePdfText.GrossPrice, "Prix brut"),
        (InvoicePdfText.PriceDiscount, "Remise sur prix"), (InvoicePdfText.ReasonCode, "Code motif"),
        (InvoicePdfText.Base, "Base"), (InvoicePdfText.Percentage, "Pourcentage"),
        (InvoicePdfText.PurchaseOrder, "Bon de commande"), (InvoicePdfText.SalesOrder, "Commande client"),
        (InvoicePdfText.Contract, "Contrat"), (InvoicePdfText.Project, "Projet"),
        (InvoicePdfText.DespatchAdvice, "Avis d'expédition"), (InvoicePdfText.ReceivingAdvice, "Avis de réception"),
        (InvoicePdfText.Tender, "Appel d'offres"), (InvoicePdfText.InvoicedObject, "Objet facturé"),
        (InvoicePdfText.BusinessProcess, "Processus métier"), (InvoicePdfText.DocumentType, "Type de document"),
        (InvoicePdfText.TaxPoint, "Date d'exigibilité"), (InvoicePdfText.PrecedingInvoice, "Facture précédente"),
        (InvoicePdfText.VatAccountingCurrency, "TVA en devise comptable"), (InvoicePdfText.References, "Références"),
        (InvoicePdfText.Delivery, "Livraison"), (InvoicePdfText.Location, "Lieu"), (InvoicePdfText.Payee, "Bénéficiaire"),
        (InvoicePdfText.TaxRepresentative, "Représentant fiscal"), (InvoicePdfText.Payment, "Paiement"),
        (InvoicePdfText.PaymentMeans, "Moyen de paiement"), (InvoicePdfText.Reference, "Référence"),
        (InvoicePdfText.Account, "Compte"), (InvoicePdfText.Mandate, "Mandat"),
        (InvoicePdfText.Creditor, "Créancier"), (InvoicePdfText.DebitedAccount, "Compte débité"),
        (InvoicePdfText.Card, "Carte"), (InvoicePdfText.Ending, "Finissant par"), (InvoicePdfText.Notes, "Notes"),
        (InvoicePdfText.SupportingDocuments, "Pièces justificatives"));

    private static ReadOnlyDictionary<InvoicePdfText, string> Translate(
        IReadOnlyDictionary<InvoicePdfText, string> fallback,
        params (InvoicePdfText Key, string Value)[] entries) {
        var result = fallback.ToDictionary(entry => entry.Key, entry => entry.Value);
        foreach ((InvoicePdfText key, string value) in entries) result[key] = value;
        return new ReadOnlyDictionary<InvoicePdfText, string>(result);
    }
}
