namespace OfficeIMO.Invoicing.Pdf;

public sealed partial class InvoicePdfLanguagePack {
    private static readonly IReadOnlyDictionary<InvoicePdfText, string> CzechLabels = Translate(EnglishLabels,
        (InvoicePdfText.Invoice, "Faktura"), (InvoicePdfText.CreditNote, "Dobropis"),
        (InvoicePdfText.Seller, "Prodávající"), (InvoicePdfText.Buyer, "Kupující"), (InvoicePdfText.Item, "Položka"),
        (InvoicePdfText.Quantity, "Množství"), (InvoicePdfText.NetPrice, "Čistá cena"), (InvoicePdfText.Vat, "DPH"),
        (InvoicePdfText.NetAmount, "Čistá částka"), (InvoicePdfText.VatCategory, "Kategorie DPH"),
        (InvoicePdfText.TaxableAmount, "Základ daně"), (InvoicePdfText.VatAmount, "Částka DPH"),
        (InvoicePdfText.Exemption, "Osvobození"), (InvoicePdfText.Issued, "Vystaveno"), (InvoicePdfText.Due, "Splatnost"),
        (InvoicePdfText.BuyerReference, "Reference kupujícího"), (InvoicePdfText.Currency, "Měna"),
        (InvoicePdfText.DocumentAdjustments, "Úpravy dokladu"), (InvoicePdfText.Charge, "Příplatek"),
        (InvoicePdfText.Allowance, "Sleva"), (InvoicePdfText.LineNetTotal, "Čistý součet položek"),
        (InvoicePdfText.Allowances, "Slevy"), (InvoicePdfText.Charges, "Příplatky"),
        (InvoicePdfText.TotalExcludingVat, "Celkem bez DPH"), (InvoicePdfText.VatTotal, "DPH celkem"),
        (InvoicePdfText.TotalIncludingVat, "Celkem včetně DPH"), (InvoicePdfText.Prepaid, "Předplaceno"),
        (InvoicePdfText.Rounding, "Zaokrouhlení"), (InvoicePdfText.AmountDue, "Částka k úhradě"),
        (InvoicePdfText.From, "Od"), (InvoicePdfText.Until, "Do"), (InvoicePdfText.To, "do"),
        (InvoicePdfText.Identifier, "Identifikátor"), (InvoicePdfText.LegalRegistration, "Právní registrace"),
        (InvoicePdfText.ElectronicAddress, "Elektronická adresa"), (InvoicePdfText.OrderLine, "Řádek objednávky"),
        (InvoicePdfText.AccountingReference, "Účetní reference"), (InvoicePdfText.ObjectIdentifier, "Objekt"),
        (InvoicePdfText.StandardItem, "Standardní položka"), (InvoicePdfText.SellerItem, "Položka prodávajícího"),
        (InvoicePdfText.BuyerItem, "Položka kupujícího"), (InvoicePdfText.Origin, "Původ"),
        (InvoicePdfText.Classification, "Klasifikace"), (InvoicePdfText.Version, "verze"),
        (InvoicePdfText.Period, "Období"), (InvoicePdfText.GrossPrice, "Hrubá cena"),
        (InvoicePdfText.PriceDiscount, "Sleva z ceny"), (InvoicePdfText.ReasonCode, "Kód důvodu"),
        (InvoicePdfText.Base, "Základ"), (InvoicePdfText.Percentage, "Procento"),
        (InvoicePdfText.PurchaseOrder, "Nákupní objednávka"), (InvoicePdfText.SalesOrder, "Prodejní objednávka"),
        (InvoicePdfText.Contract, "Smlouva"), (InvoicePdfText.Project, "Projekt"),
        (InvoicePdfText.DespatchAdvice, "Avízo o odeslání"), (InvoicePdfText.ReceivingAdvice, "Avízo o přijetí"),
        (InvoicePdfText.Tender, "Výběrové řízení"), (InvoicePdfText.InvoicedObject, "Fakturovaný objekt"),
        (InvoicePdfText.BusinessProcess, "Obchodní proces"), (InvoicePdfText.DocumentType, "Typ dokladu"),
        (InvoicePdfText.TaxPoint, "Datum zdanitelného plnění"), (InvoicePdfText.PrecedingInvoice, "Předchozí faktura"),
        (InvoicePdfText.VatAccountingCurrency, "DPH v účetní měně"), (InvoicePdfText.References, "Reference"),
        (InvoicePdfText.Delivery, "Dodání"), (InvoicePdfText.Location, "Místo"), (InvoicePdfText.Payee, "Příjemce platby"),
        (InvoicePdfText.TaxRepresentative, "Daňový zástupce"), (InvoicePdfText.Payment, "Platba"),
        (InvoicePdfText.PaymentMeans, "Platební prostředek"), (InvoicePdfText.Reference, "Reference"),
        (InvoicePdfText.Account, "Účet"), (InvoicePdfText.Mandate, "Mandát"),
        (InvoicePdfText.Creditor, "Věřitel"), (InvoicePdfText.DebitedAccount, "Zatížený účet"),
        (InvoicePdfText.Card, "Karta"), (InvoicePdfText.Ending, "Koncovka"), (InvoicePdfText.Notes, "Poznámky"),
        (InvoicePdfText.SupportingDocuments, "Podpůrné dokumenty"),
        (InvoicePdfText.PaymentReference, "Platební reference"), (InvoicePdfText.Approvals, "Schválení"));

    private static readonly IReadOnlyDictionary<InvoicePdfText, string> SlovakLabels = Translate(EnglishLabels,
        (InvoicePdfText.Invoice, "Faktúra"), (InvoicePdfText.CreditNote, "Dobropis"),
        (InvoicePdfText.Seller, "Predávajúci"), (InvoicePdfText.Buyer, "Kupujúci"), (InvoicePdfText.Item, "Položka"),
        (InvoicePdfText.Quantity, "Množstvo"), (InvoicePdfText.NetPrice, "Čistá cena"), (InvoicePdfText.Vat, "DPH"),
        (InvoicePdfText.NetAmount, "Čistá suma"), (InvoicePdfText.VatCategory, "Kategória DPH"),
        (InvoicePdfText.TaxableAmount, "Základ dane"), (InvoicePdfText.VatAmount, "Suma DPH"),
        (InvoicePdfText.Exemption, "Oslobodenie"), (InvoicePdfText.Issued, "Vystavené"), (InvoicePdfText.Due, "Splatnosť"),
        (InvoicePdfText.BuyerReference, "Referencia kupujúceho"), (InvoicePdfText.Currency, "Mena"),
        (InvoicePdfText.DocumentAdjustments, "Úpravy dokladu"), (InvoicePdfText.Charge, "Príplatok"),
        (InvoicePdfText.Allowance, "Zľava"), (InvoicePdfText.LineNetTotal, "Čistý súčet položiek"),
        (InvoicePdfText.Allowances, "Zľavy"), (InvoicePdfText.Charges, "Príplatky"),
        (InvoicePdfText.TotalExcludingVat, "Celkom bez DPH"), (InvoicePdfText.VatTotal, "DPH celkom"),
        (InvoicePdfText.TotalIncludingVat, "Celkom s DPH"), (InvoicePdfText.Prepaid, "Predplatené"),
        (InvoicePdfText.Rounding, "Zaokrúhlenie"), (InvoicePdfText.AmountDue, "Suma na úhradu"),
        (InvoicePdfText.From, "Od"), (InvoicePdfText.Until, "Do"), (InvoicePdfText.To, "do"),
        (InvoicePdfText.Identifier, "Identifikátor"), (InvoicePdfText.LegalRegistration, "Právna registrácia"),
        (InvoicePdfText.ElectronicAddress, "Elektronická adresa"), (InvoicePdfText.OrderLine, "Riadok objednávky"),
        (InvoicePdfText.AccountingReference, "Účtovná referencia"), (InvoicePdfText.ObjectIdentifier, "Objekt"),
        (InvoicePdfText.StandardItem, "Štandardná položka"), (InvoicePdfText.SellerItem, "Položka predávajúceho"),
        (InvoicePdfText.BuyerItem, "Položka kupujúceho"), (InvoicePdfText.Origin, "Pôvod"),
        (InvoicePdfText.Classification, "Klasifikácia"), (InvoicePdfText.Version, "verzia"),
        (InvoicePdfText.Period, "Obdobie"), (InvoicePdfText.GrossPrice, "Hrubá cena"),
        (InvoicePdfText.PriceDiscount, "Zľava z ceny"), (InvoicePdfText.ReasonCode, "Kód dôvodu"),
        (InvoicePdfText.Base, "Základ"), (InvoicePdfText.Percentage, "Percento"),
        (InvoicePdfText.PurchaseOrder, "Nákupná objednávka"), (InvoicePdfText.SalesOrder, "Predajná objednávka"),
        (InvoicePdfText.Contract, "Zmluva"), (InvoicePdfText.Project, "Projekt"),
        (InvoicePdfText.DespatchAdvice, "Oznámenie o odoslaní"), (InvoicePdfText.ReceivingAdvice, "Oznámenie o prijatí"),
        (InvoicePdfText.Tender, "Verejná súťaž"), (InvoicePdfText.InvoicedObject, "Fakturovaný objekt"),
        (InvoicePdfText.BusinessProcess, "Obchodný proces"), (InvoicePdfText.DocumentType, "Typ dokladu"),
        (InvoicePdfText.TaxPoint, "Dátum daňovej povinnosti"), (InvoicePdfText.PrecedingInvoice, "Predchádzajúca faktúra"),
        (InvoicePdfText.VatAccountingCurrency, "DPH v účtovnej mene"), (InvoicePdfText.References, "Referencie"),
        (InvoicePdfText.Delivery, "Dodanie"), (InvoicePdfText.Location, "Miesto"), (InvoicePdfText.Payee, "Príjemca platby"),
        (InvoicePdfText.TaxRepresentative, "Daňový zástupca"), (InvoicePdfText.Payment, "Platba"),
        (InvoicePdfText.PaymentMeans, "Platobný prostriedok"), (InvoicePdfText.Reference, "Referencia"),
        (InvoicePdfText.Account, "Účet"), (InvoicePdfText.Mandate, "Mandát"),
        (InvoicePdfText.Creditor, "Veriteľ"), (InvoicePdfText.DebitedAccount, "Zaťažený účet"),
        (InvoicePdfText.Card, "Karta"), (InvoicePdfText.Ending, "Koncovka"), (InvoicePdfText.Notes, "Poznámky"),
        (InvoicePdfText.SupportingDocuments, "Podporné dokumenty"),
        (InvoicePdfText.PaymentReference, "Referencia platby"), (InvoicePdfText.Approvals, "Schválenia"));
}
