namespace OfficeIMO.Invoicing.Pdf;

public sealed partial class InvoicePdfLanguagePack {
    private static readonly IReadOnlyDictionary<InvoicePdfText, string> SpanishLabels = Translate(EnglishLabels,
        (InvoicePdfText.Invoice, "Factura"), (InvoicePdfText.CreditNote, "Nota de crédito"),
        (InvoicePdfText.Seller, "Vendedor"), (InvoicePdfText.Buyer, "Comprador"), (InvoicePdfText.Item, "Artículo"),
        (InvoicePdfText.Quantity, "Cantidad"), (InvoicePdfText.NetPrice, "Precio neto"), (InvoicePdfText.Vat, "IVA"),
        (InvoicePdfText.NetAmount, "Importe neto"), (InvoicePdfText.VatCategory, "Categoría de IVA"),
        (InvoicePdfText.TaxableAmount, "Base imponible"), (InvoicePdfText.VatAmount, "Importe de IVA"),
        (InvoicePdfText.Exemption, "Exención"), (InvoicePdfText.Issued, "Emitida"), (InvoicePdfText.Due, "Vencimiento"),
        (InvoicePdfText.BuyerReference, "Referencia del comprador"), (InvoicePdfText.Currency, "Moneda"),
        (InvoicePdfText.DocumentAdjustments, "Ajustes del documento"), (InvoicePdfText.Charge, "Cargo"),
        (InvoicePdfText.Allowance, "Descuento"), (InvoicePdfText.LineNetTotal, "Total neto de líneas"),
        (InvoicePdfText.Allowances, "Descuentos"), (InvoicePdfText.Charges, "Cargos"),
        (InvoicePdfText.TotalExcludingVat, "Total sin IVA"), (InvoicePdfText.VatTotal, "IVA total"),
        (InvoicePdfText.TotalIncludingVat, "Total con IVA"), (InvoicePdfText.Prepaid, "Anticipo"),
        (InvoicePdfText.Rounding, "Redondeo"), (InvoicePdfText.AmountDue, "Importe pendiente"),
        (InvoicePdfText.From, "Desde"), (InvoicePdfText.Until, "Hasta"), (InvoicePdfText.To, "a"),
        (InvoicePdfText.Identifier, "Identificador"), (InvoicePdfText.LegalRegistration, "Registro legal"),
        (InvoicePdfText.ElectronicAddress, "Dirección electrónica"), (InvoicePdfText.OrderLine, "Línea de pedido"),
        (InvoicePdfText.AccountingReference, "Referencia contable"), (InvoicePdfText.ObjectIdentifier, "Objeto"),
        (InvoicePdfText.StandardItem, "Artículo estándar"), (InvoicePdfText.SellerItem, "Artículo del vendedor"),
        (InvoicePdfText.BuyerItem, "Artículo del comprador"), (InvoicePdfText.Origin, "Origen"),
        (InvoicePdfText.Classification, "Clasificación"), (InvoicePdfText.Version, "versión"),
        (InvoicePdfText.Period, "Período"), (InvoicePdfText.GrossPrice, "Precio bruto"),
        (InvoicePdfText.PriceDiscount, "Descuento de precio"), (InvoicePdfText.ReasonCode, "Código de motivo"),
        (InvoicePdfText.Base, "Base"), (InvoicePdfText.Percentage, "Porcentaje"),
        (InvoicePdfText.PurchaseOrder, "Pedido de compra"), (InvoicePdfText.SalesOrder, "Pedido de venta"),
        (InvoicePdfText.Contract, "Contrato"), (InvoicePdfText.Project, "Proyecto"),
        (InvoicePdfText.DespatchAdvice, "Aviso de expedición"), (InvoicePdfText.ReceivingAdvice, "Aviso de recepción"),
        (InvoicePdfText.Tender, "Licitación"), (InvoicePdfText.InvoicedObject, "Objeto facturado"),
        (InvoicePdfText.BusinessProcess, "Proceso de negocio"), (InvoicePdfText.DocumentType, "Tipo de documento"),
        (InvoicePdfText.TaxPoint, "Fecha de devengo"), (InvoicePdfText.PrecedingInvoice, "Factura anterior"),
        (InvoicePdfText.VatAccountingCurrency, "IVA en moneda contable"), (InvoicePdfText.References, "Referencias"),
        (InvoicePdfText.Delivery, "Entrega"), (InvoicePdfText.Location, "Ubicación"), (InvoicePdfText.Payee, "Beneficiario"),
        (InvoicePdfText.TaxRepresentative, "Representante fiscal"), (InvoicePdfText.Payment, "Pago"),
        (InvoicePdfText.PaymentMeans, "Medio de pago"), (InvoicePdfText.Reference, "Referencia"),
        (InvoicePdfText.Account, "Cuenta"), (InvoicePdfText.Mandate, "Mandato"),
        (InvoicePdfText.Creditor, "Acreedor"), (InvoicePdfText.DebitedAccount, "Cuenta debitada"),
        (InvoicePdfText.Card, "Tarjeta"), (InvoicePdfText.Ending, "Terminación"), (InvoicePdfText.Notes, "Notas"),
        (InvoicePdfText.SupportingDocuments, "Documentos justificativos"),
        (InvoicePdfText.PaymentReference, "Referencia de pago"), (InvoicePdfText.Approvals, "Aprobaciones"));

    private static readonly IReadOnlyDictionary<InvoicePdfText, string> ItalianLabels = Translate(EnglishLabels,
        (InvoicePdfText.Invoice, "Fattura"), (InvoicePdfText.CreditNote, "Nota di credito"),
        (InvoicePdfText.Seller, "Venditore"), (InvoicePdfText.Buyer, "Acquirente"), (InvoicePdfText.Item, "Voce"),
        (InvoicePdfText.Quantity, "Quantità"), (InvoicePdfText.NetPrice, "Prezzo netto"), (InvoicePdfText.Vat, "IVA"),
        (InvoicePdfText.NetAmount, "Importo netto"), (InvoicePdfText.VatCategory, "Categoria IVA"),
        (InvoicePdfText.TaxableAmount, "Imponibile"), (InvoicePdfText.VatAmount, "Importo IVA"),
        (InvoicePdfText.Exemption, "Esenzione"), (InvoicePdfText.Issued, "Emessa"), (InvoicePdfText.Due, "Scadenza"),
        (InvoicePdfText.BuyerReference, "Riferimento acquirente"), (InvoicePdfText.Currency, "Valuta"),
        (InvoicePdfText.DocumentAdjustments, "Rettifiche documento"), (InvoicePdfText.Charge, "Addebito"),
        (InvoicePdfText.Allowance, "Sconto"), (InvoicePdfText.LineNetTotal, "Totale netto righe"),
        (InvoicePdfText.Allowances, "Sconti"), (InvoicePdfText.Charges, "Addebiti"),
        (InvoicePdfText.TotalExcludingVat, "Totale IVA esclusa"), (InvoicePdfText.VatTotal, "IVA totale"),
        (InvoicePdfText.TotalIncludingVat, "Totale IVA inclusa"), (InvoicePdfText.Prepaid, "Pagato in anticipo"),
        (InvoicePdfText.Rounding, "Arrotondamento"), (InvoicePdfText.AmountDue, "Importo dovuto"),
        (InvoicePdfText.From, "Da"), (InvoicePdfText.Until, "Fino a"), (InvoicePdfText.To, "a"),
        (InvoicePdfText.Identifier, "Identificativo"), (InvoicePdfText.LegalRegistration, "Registrazione legale"),
        (InvoicePdfText.ElectronicAddress, "Indirizzo elettronico"), (InvoicePdfText.OrderLine, "Riga ordine"),
        (InvoicePdfText.AccountingReference, "Riferimento contabile"), (InvoicePdfText.ObjectIdentifier, "Oggetto"),
        (InvoicePdfText.StandardItem, "Articolo standard"), (InvoicePdfText.SellerItem, "Articolo venditore"),
        (InvoicePdfText.BuyerItem, "Articolo acquirente"), (InvoicePdfText.Origin, "Origine"),
        (InvoicePdfText.Classification, "Classificazione"), (InvoicePdfText.Version, "versione"),
        (InvoicePdfText.Period, "Periodo"), (InvoicePdfText.GrossPrice, "Prezzo lordo"),
        (InvoicePdfText.PriceDiscount, "Sconto sul prezzo"), (InvoicePdfText.ReasonCode, "Codice motivo"),
        (InvoicePdfText.Base, "Base"), (InvoicePdfText.Percentage, "Percentuale"),
        (InvoicePdfText.PurchaseOrder, "Ordine di acquisto"), (InvoicePdfText.SalesOrder, "Ordine di vendita"),
        (InvoicePdfText.Contract, "Contratto"), (InvoicePdfText.Project, "Progetto"),
        (InvoicePdfText.DespatchAdvice, "Avviso di spedizione"), (InvoicePdfText.ReceivingAdvice, "Avviso di ricevimento"),
        (InvoicePdfText.Tender, "Gara"), (InvoicePdfText.InvoicedObject, "Oggetto fatturato"),
        (InvoicePdfText.BusinessProcess, "Processo aziendale"), (InvoicePdfText.DocumentType, "Tipo documento"),
        (InvoicePdfText.TaxPoint, "Data esigibilità IVA"), (InvoicePdfText.PrecedingInvoice, "Fattura precedente"),
        (InvoicePdfText.VatAccountingCurrency, "IVA in valuta contabile"), (InvoicePdfText.References, "Riferimenti"),
        (InvoicePdfText.Delivery, "Consegna"), (InvoicePdfText.Location, "Luogo"), (InvoicePdfText.Payee, "Beneficiario"),
        (InvoicePdfText.TaxRepresentative, "Rappresentante fiscale"), (InvoicePdfText.Payment, "Pagamento"),
        (InvoicePdfText.PaymentMeans, "Mezzo di pagamento"), (InvoicePdfText.Reference, "Riferimento"),
        (InvoicePdfText.Account, "Conto"), (InvoicePdfText.Mandate, "Mandato"),
        (InvoicePdfText.Creditor, "Creditore"), (InvoicePdfText.DebitedAccount, "Conto addebitato"),
        (InvoicePdfText.Card, "Carta"), (InvoicePdfText.Ending, "Finale"), (InvoicePdfText.Notes, "Note"),
        (InvoicePdfText.SupportingDocuments, "Documenti di supporto"),
        (InvoicePdfText.PaymentReference, "Riferimento pagamento"), (InvoicePdfText.Approvals, "Approvazioni"));
}
