// <auto-generated/>
// Generated by Build/Generate-WordOpenXmlValueTypes.ps1. Do not edit by hand.
using System.Globalization;

namespace OfficeIMO.Word;

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Bibliography.DataSourceValues.</summary>
public enum WordBibliographySourceType {
    /// <summary>Represents the Open XML value <c>ArticleInAPeriodical</c>.</summary>
    ArticleInAPeriodical,
    /// <summary>Represents the Open XML value <c>Book</c>.</summary>
    Book,
    /// <summary>Represents the Open XML value <c>BookSection</c>.</summary>
    BookSection,
    /// <summary>Represents the Open XML value <c>JournalArticle</c>.</summary>
    JournalArticle,
    /// <summary>Represents the Open XML value <c>ConferenceProceedings</c>.</summary>
    ConferenceProceedings,
    /// <summary>Represents the Open XML value <c>Report</c>.</summary>
    Report,
    /// <summary>Represents the Open XML value <c>SoundRecording</c>.</summary>
    SoundRecording,
    /// <summary>Represents the Open XML value <c>Performance</c>.</summary>
    Performance,
    /// <summary>Represents the Open XML value <c>Art</c>.</summary>
    Art,
    /// <summary>Represents the Open XML value <c>DocumentFromInternetSite</c>.</summary>
    DocumentFromInternetSite,
    /// <summary>Represents the Open XML value <c>InternetSite</c>.</summary>
    InternetSite,
    /// <summary>Represents the Open XML value <c>Film</c>.</summary>
    Film,
    /// <summary>Represents the Open XML value <c>Interview</c>.</summary>
    Interview,
    /// <summary>Represents the Open XML value <c>Patent</c>.</summary>
    Patent,
    /// <summary>Represents the Open XML value <c>ElectronicSource</c>.</summary>
    ElectronicSource,
    /// <summary>Represents the Open XML value <c>Case</c>.</summary>
    Case,
    /// <summary>Represents the Open XML value <c>Misc</c>.</summary>
    Miscellaneous,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.BlackWhiteModeValues.</summary>
public enum WordImageBlackWhiteMode {
    /// <summary>Represents the Open XML value <c>clr</c>.</summary>
    Color,
    /// <summary>Represents the Open XML value <c>auto</c>.</summary>
    Auto,
    /// <summary>Represents the Open XML value <c>gray</c>.</summary>
    Gray,
    /// <summary>Represents the Open XML value <c>ltGray</c>.</summary>
    LightGray,
    /// <summary>Represents the Open XML value <c>invGray</c>.</summary>
    InvGray,
    /// <summary>Represents the Open XML value <c>grayWhite</c>.</summary>
    GrayWhite,
    /// <summary>Represents the Open XML value <c>blackGray</c>.</summary>
    BlackGray,
    /// <summary>Represents the Open XML value <c>blackWhite</c>.</summary>
    BlackWhite,
    /// <summary>Represents the Open XML value <c>black</c>.</summary>
    Black,
    /// <summary>Represents the Open XML value <c>white</c>.</summary>
    White,
    /// <summary>Represents the Open XML value <c>hidden</c>.</summary>
    Hidden,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.BlipCompressionValues.</summary>
public enum WordImageCompressionQuality {
    /// <summary>Represents the Open XML value <c>email</c>.</summary>
    Email,
    /// <summary>Represents the Open XML value <c>screen</c>.</summary>
    Screen,
    /// <summary>Represents the Open XML value <c>print</c>.</summary>
    Print,
    /// <summary>Represents the Open XML value <c>hqprint</c>.</summary>
    HighQualityPrint,
    /// <summary>Represents the Open XML value <c>none</c>.</summary>
    None,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.Charts.BarDirectionValues.</summary>
public enum WordChartBarDirection {
    /// <summary>Represents the Open XML value <c>bar</c>.</summary>
    Bar,
    /// <summary>Represents the Open XML value <c>col</c>.</summary>
    Column,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.Charts.BarGroupingValues.</summary>
public enum WordChartBarGrouping {
    /// <summary>Represents the Open XML value <c>percentStacked</c>.</summary>
    PercentStacked,
    /// <summary>Represents the Open XML value <c>clustered</c>.</summary>
    Clustered,
    /// <summary>Represents the Open XML value <c>standard</c>.</summary>
    Standard,
    /// <summary>Represents the Open XML value <c>stacked</c>.</summary>
    Stacked,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Office2010.Word.Drawing.SizeRelativeHorizontallyValues.</summary>
public enum WordTextBoxHorizontalSizeReference {
    /// <summary>Represents the Open XML value <c>margin</c>.</summary>
    Margin,
    /// <summary>Represents the Open XML value <c>page</c>.</summary>
    Page,
    /// <summary>Represents the Open XML value <c>leftMargin</c>.</summary>
    LeftMargin,
    /// <summary>Represents the Open XML value <c>rightMargin</c>.</summary>
    RightMargin,
    /// <summary>Represents the Open XML value <c>insideMargin</c>.</summary>
    InsideMargin,
    /// <summary>Represents the Open XML value <c>outsideMargin</c>.</summary>
    OutsideMargin,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Wordprocessing.BorderValues.</summary>
public enum WordBorderStyle {
    /// <summary>Represents the Open XML value <c>nil</c>.</summary>
    Nil,
    /// <summary>Represents the Open XML value <c>none</c>.</summary>
    None,
    /// <summary>Represents the Open XML value <c>single</c>.</summary>
    Single,
    /// <summary>Represents the Open XML value <c>thick</c>.</summary>
    Thick,
    /// <summary>Represents the Open XML value <c>double</c>.</summary>
    Double,
    /// <summary>Represents the Open XML value <c>dotted</c>.</summary>
    Dotted,
    /// <summary>Represents the Open XML value <c>dashed</c>.</summary>
    Dashed,
    /// <summary>Represents the Open XML value <c>dotDash</c>.</summary>
    DotDash,
    /// <summary>Represents the Open XML value <c>dotDotDash</c>.</summary>
    DotDotDash,
    /// <summary>Represents the Open XML value <c>triple</c>.</summary>
    Triple,
    /// <summary>Represents the Open XML value <c>thinThickSmallGap</c>.</summary>
    ThinThickSmallGap,
    /// <summary>Represents the Open XML value <c>thickThinSmallGap</c>.</summary>
    ThickThinSmallGap,
    /// <summary>Represents the Open XML value <c>thinThickThinSmallGap</c>.</summary>
    ThinThickThinSmallGap,
    /// <summary>Represents the Open XML value <c>thinThickMediumGap</c>.</summary>
    ThinThickMediumGap,
    /// <summary>Represents the Open XML value <c>thickThinMediumGap</c>.</summary>
    ThickThinMediumGap,
    /// <summary>Represents the Open XML value <c>thinThickThinMediumGap</c>.</summary>
    ThinThickThinMediumGap,
    /// <summary>Represents the Open XML value <c>thinThickLargeGap</c>.</summary>
    ThinThickLargeGap,
    /// <summary>Represents the Open XML value <c>thickThinLargeGap</c>.</summary>
    ThickThinLargeGap,
    /// <summary>Represents the Open XML value <c>thinThickThinLargeGap</c>.</summary>
    ThinThickThinLargeGap,
    /// <summary>Represents the Open XML value <c>wave</c>.</summary>
    Wave,
    /// <summary>Represents the Open XML value <c>doubleWave</c>.</summary>
    DoubleWave,
    /// <summary>Represents the Open XML value <c>dashSmallGap</c>.</summary>
    DashSmallGap,
    /// <summary>Represents the Open XML value <c>dashDotStroked</c>.</summary>
    DashDotStroked,
    /// <summary>Represents the Open XML value <c>threeDEmboss</c>.</summary>
    ThreeDEmboss,
    /// <summary>Represents the Open XML value <c>threeDEngrave</c>.</summary>
    ThreeDEngrave,
    /// <summary>Represents the Open XML value <c>outset</c>.</summary>
    Outset,
    /// <summary>Represents the Open XML value <c>inset</c>.</summary>
    Inset,
    /// <summary>Represents the Open XML value <c>apples</c>.</summary>
    Apples,
    /// <summary>Represents the Open XML value <c>archedScallops</c>.</summary>
    ArchedScallops,
    /// <summary>Represents the Open XML value <c>babyPacifier</c>.</summary>
    BabyPacifier,
    /// <summary>Represents the Open XML value <c>babyRattle</c>.</summary>
    BabyRattle,
    /// <summary>Represents the Open XML value <c>balloons3Colors</c>.</summary>
    Balloons3Colors,
    /// <summary>Represents the Open XML value <c>balloonsHotAir</c>.</summary>
    BalloonsHotAir,
    /// <summary>Represents the Open XML value <c>basicBlackDashes</c>.</summary>
    BasicBlackDashes,
    /// <summary>Represents the Open XML value <c>basicBlackDots</c>.</summary>
    BasicBlackDots,
    /// <summary>Represents the Open XML value <c>basicBlackSquares</c>.</summary>
    BasicBlackSquares,
    /// <summary>Represents the Open XML value <c>basicThinLines</c>.</summary>
    BasicThinLines,
    /// <summary>Represents the Open XML value <c>basicWhiteDashes</c>.</summary>
    BasicWhiteDashes,
    /// <summary>Represents the Open XML value <c>basicWhiteDots</c>.</summary>
    BasicWhiteDots,
    /// <summary>Represents the Open XML value <c>basicWhiteSquares</c>.</summary>
    BasicWhiteSquares,
    /// <summary>Represents the Open XML value <c>basicWideInline</c>.</summary>
    BasicWideInline,
    /// <summary>Represents the Open XML value <c>basicWideMidline</c>.</summary>
    BasicWideMidline,
    /// <summary>Represents the Open XML value <c>basicWideOutline</c>.</summary>
    BasicWideOutline,
    /// <summary>Represents the Open XML value <c>bats</c>.</summary>
    Bats,
    /// <summary>Represents the Open XML value <c>birds</c>.</summary>
    Birds,
    /// <summary>Represents the Open XML value <c>birdsFlight</c>.</summary>
    BirdsFlight,
    /// <summary>Represents the Open XML value <c>cabins</c>.</summary>
    Cabins,
    /// <summary>Represents the Open XML value <c>cakeSlice</c>.</summary>
    CakeSlice,
    /// <summary>Represents the Open XML value <c>candyCorn</c>.</summary>
    CandyCorn,
    /// <summary>Represents the Open XML value <c>celticKnotwork</c>.</summary>
    CelticKnotwork,
    /// <summary>Represents the Open XML value <c>certificateBanner</c>.</summary>
    CertificateBanner,
    /// <summary>Represents the Open XML value <c>chainLink</c>.</summary>
    ChainLink,
    /// <summary>Represents the Open XML value <c>champagneBottle</c>.</summary>
    ChampagneBottle,
    /// <summary>Represents the Open XML value <c>checkedBarBlack</c>.</summary>
    CheckedBarBlack,
    /// <summary>Represents the Open XML value <c>checkedBarColor</c>.</summary>
    CheckedBarColor,
    /// <summary>Represents the Open XML value <c>checkered</c>.</summary>
    Checkered,
    /// <summary>Represents the Open XML value <c>christmasTree</c>.</summary>
    ChristmasTree,
    /// <summary>Represents the Open XML value <c>circlesLines</c>.</summary>
    CirclesLines,
    /// <summary>Represents the Open XML value <c>circlesRectangles</c>.</summary>
    CirclesRectangles,
    /// <summary>Represents the Open XML value <c>classicalWave</c>.</summary>
    ClassicalWave,
    /// <summary>Represents the Open XML value <c>clocks</c>.</summary>
    Clocks,
    /// <summary>Represents the Open XML value <c>compass</c>.</summary>
    Compass,
    /// <summary>Represents the Open XML value <c>confetti</c>.</summary>
    Confetti,
    /// <summary>Represents the Open XML value <c>confettiGrays</c>.</summary>
    ConfettiGrays,
    /// <summary>Represents the Open XML value <c>confettiOutline</c>.</summary>
    ConfettiOutline,
    /// <summary>Represents the Open XML value <c>confettiStreamers</c>.</summary>
    ConfettiStreamers,
    /// <summary>Represents the Open XML value <c>confettiWhite</c>.</summary>
    ConfettiWhite,
    /// <summary>Represents the Open XML value <c>cornerTriangles</c>.</summary>
    CornerTriangles,
    /// <summary>Represents the Open XML value <c>couponCutoutDashes</c>.</summary>
    CouponCutoutDashes,
    /// <summary>Represents the Open XML value <c>couponCutoutDots</c>.</summary>
    CouponCutoutDots,
    /// <summary>Represents the Open XML value <c>crazyMaze</c>.</summary>
    CrazyMaze,
    /// <summary>Represents the Open XML value <c>creaturesButterfly</c>.</summary>
    CreaturesButterfly,
    /// <summary>Represents the Open XML value <c>creaturesFish</c>.</summary>
    CreaturesFish,
    /// <summary>Represents the Open XML value <c>creaturesInsects</c>.</summary>
    CreaturesInsects,
    /// <summary>Represents the Open XML value <c>creaturesLadyBug</c>.</summary>
    CreaturesLadyBug,
    /// <summary>Represents the Open XML value <c>crossStitch</c>.</summary>
    CrossStitch,
    /// <summary>Represents the Open XML value <c>cup</c>.</summary>
    Cup,
    /// <summary>Represents the Open XML value <c>decoArch</c>.</summary>
    DecoArch,
    /// <summary>Represents the Open XML value <c>decoArchColor</c>.</summary>
    DecoArchColor,
    /// <summary>Represents the Open XML value <c>decoBlocks</c>.</summary>
    DecoBlocks,
    /// <summary>Represents the Open XML value <c>diamondsGray</c>.</summary>
    DiamondsGray,
    /// <summary>Represents the Open XML value <c>doubleD</c>.</summary>
    DoubleD,
    /// <summary>Represents the Open XML value <c>doubleDiamonds</c>.</summary>
    DoubleDiamonds,
    /// <summary>Represents the Open XML value <c>earth1</c>.</summary>
    Earth1,
    /// <summary>Represents the Open XML value <c>earth2</c>.</summary>
    Earth2,
    /// <summary>Represents the Open XML value <c>eclipsingSquares1</c>.</summary>
    EclipsingSquares1,
    /// <summary>Represents the Open XML value <c>eclipsingSquares2</c>.</summary>
    EclipsingSquares2,
    /// <summary>Represents the Open XML value <c>eggsBlack</c>.</summary>
    EggsBlack,
    /// <summary>Represents the Open XML value <c>fans</c>.</summary>
    Fans,
    /// <summary>Represents the Open XML value <c>film</c>.</summary>
    Film,
    /// <summary>Represents the Open XML value <c>firecrackers</c>.</summary>
    Firecrackers,
    /// <summary>Represents the Open XML value <c>flowersBlockPrint</c>.</summary>
    FlowersBlockPrint,
    /// <summary>Represents the Open XML value <c>flowersDaisies</c>.</summary>
    FlowersDaisies,
    /// <summary>Represents the Open XML value <c>flowersModern1</c>.</summary>
    FlowersModern1,
    /// <summary>Represents the Open XML value <c>flowersModern2</c>.</summary>
    FlowersModern2,
    /// <summary>Represents the Open XML value <c>flowersPansy</c>.</summary>
    FlowersPansy,
    /// <summary>Represents the Open XML value <c>flowersRedRose</c>.</summary>
    FlowersRedRose,
    /// <summary>Represents the Open XML value <c>flowersRoses</c>.</summary>
    FlowersRoses,
    /// <summary>Represents the Open XML value <c>flowersTeacup</c>.</summary>
    FlowersTeacup,
    /// <summary>Represents the Open XML value <c>flowersTiny</c>.</summary>
    FlowersTiny,
    /// <summary>Represents the Open XML value <c>gems</c>.</summary>
    Gems,
    /// <summary>Represents the Open XML value <c>gingerbreadMan</c>.</summary>
    GingerbreadMan,
    /// <summary>Represents the Open XML value <c>gradient</c>.</summary>
    Gradient,
    /// <summary>Represents the Open XML value <c>handmade1</c>.</summary>
    Handmade1,
    /// <summary>Represents the Open XML value <c>handmade2</c>.</summary>
    Handmade2,
    /// <summary>Represents the Open XML value <c>heartBalloon</c>.</summary>
    HeartBalloon,
    /// <summary>Represents the Open XML value <c>heartGray</c>.</summary>
    HeartGray,
    /// <summary>Represents the Open XML value <c>hearts</c>.</summary>
    Hearts,
    /// <summary>Represents the Open XML value <c>heebieJeebies</c>.</summary>
    HeebieJeebies,
    /// <summary>Represents the Open XML value <c>holly</c>.</summary>
    Holly,
    /// <summary>Represents the Open XML value <c>houseFunky</c>.</summary>
    HouseFunky,
    /// <summary>Represents the Open XML value <c>hypnotic</c>.</summary>
    Hypnotic,
    /// <summary>Represents the Open XML value <c>iceCreamCones</c>.</summary>
    IceCreamCones,
    /// <summary>Represents the Open XML value <c>lightBulb</c>.</summary>
    LightBulb,
    /// <summary>Represents the Open XML value <c>lightning1</c>.</summary>
    Lightning1,
    /// <summary>Represents the Open XML value <c>lightning2</c>.</summary>
    Lightning2,
    /// <summary>Represents the Open XML value <c>mapPins</c>.</summary>
    MapPins,
    /// <summary>Represents the Open XML value <c>mapleLeaf</c>.</summary>
    MapleLeaf,
    /// <summary>Represents the Open XML value <c>mapleMuffins</c>.</summary>
    MapleMuffins,
    /// <summary>Represents the Open XML value <c>marquee</c>.</summary>
    Marquee,
    /// <summary>Represents the Open XML value <c>marqueeToothed</c>.</summary>
    MarqueeToothed,
    /// <summary>Represents the Open XML value <c>moons</c>.</summary>
    Moons,
    /// <summary>Represents the Open XML value <c>mosaic</c>.</summary>
    Mosaic,
    /// <summary>Represents the Open XML value <c>musicNotes</c>.</summary>
    MusicNotes,
    /// <summary>Represents the Open XML value <c>northwest</c>.</summary>
    Northwest,
    /// <summary>Represents the Open XML value <c>ovals</c>.</summary>
    Ovals,
    /// <summary>Represents the Open XML value <c>packages</c>.</summary>
    Packages,
    /// <summary>Represents the Open XML value <c>palmsBlack</c>.</summary>
    PalmsBlack,
    /// <summary>Represents the Open XML value <c>palmsColor</c>.</summary>
    PalmsColor,
    /// <summary>Represents the Open XML value <c>paperClips</c>.</summary>
    PaperClips,
    /// <summary>Represents the Open XML value <c>papyrus</c>.</summary>
    Papyrus,
    /// <summary>Represents the Open XML value <c>partyFavor</c>.</summary>
    PartyFavor,
    /// <summary>Represents the Open XML value <c>partyGlass</c>.</summary>
    PartyGlass,
    /// <summary>Represents the Open XML value <c>pencils</c>.</summary>
    Pencils,
    /// <summary>Represents the Open XML value <c>people</c>.</summary>
    People,
    /// <summary>Represents the Open XML value <c>peopleWaving</c>.</summary>
    PeopleWaving,
    /// <summary>Represents the Open XML value <c>peopleHats</c>.</summary>
    PeopleHats,
    /// <summary>Represents the Open XML value <c>poinsettias</c>.</summary>
    Poinsettias,
    /// <summary>Represents the Open XML value <c>postageStamp</c>.</summary>
    PostageStamp,
    /// <summary>Represents the Open XML value <c>pumpkin1</c>.</summary>
    Pumpkin1,
    /// <summary>Represents the Open XML value <c>pushPinNote2</c>.</summary>
    PushPinNote2,
    /// <summary>Represents the Open XML value <c>pushPinNote1</c>.</summary>
    PushPinNote1,
    /// <summary>Represents the Open XML value <c>pyramids</c>.</summary>
    Pyramids,
    /// <summary>Represents the Open XML value <c>pyramidsAbove</c>.</summary>
    PyramidsAbove,
    /// <summary>Represents the Open XML value <c>quadrants</c>.</summary>
    Quadrants,
    /// <summary>Represents the Open XML value <c>rings</c>.</summary>
    Rings,
    /// <summary>Represents the Open XML value <c>safari</c>.</summary>
    Safari,
    /// <summary>Represents the Open XML value <c>sawtooth</c>.</summary>
    Sawtooth,
    /// <summary>Represents the Open XML value <c>sawtoothGray</c>.</summary>
    SawtoothGray,
    /// <summary>Represents the Open XML value <c>scaredCat</c>.</summary>
    ScaredCat,
    /// <summary>Represents the Open XML value <c>seattle</c>.</summary>
    Seattle,
    /// <summary>Represents the Open XML value <c>shadowedSquares</c>.</summary>
    ShadowedSquares,
    /// <summary>Represents the Open XML value <c>sharksTeeth</c>.</summary>
    SharksTeeth,
    /// <summary>Represents the Open XML value <c>shorebirdTracks</c>.</summary>
    ShorebirdTracks,
    /// <summary>Represents the Open XML value <c>skyrocket</c>.</summary>
    Skyrocket,
    /// <summary>Represents the Open XML value <c>snowflakeFancy</c>.</summary>
    SnowflakeFancy,
    /// <summary>Represents the Open XML value <c>snowflakes</c>.</summary>
    Snowflakes,
    /// <summary>Represents the Open XML value <c>sombrero</c>.</summary>
    Sombrero,
    /// <summary>Represents the Open XML value <c>southwest</c>.</summary>
    Southwest,
    /// <summary>Represents the Open XML value <c>stars</c>.</summary>
    Stars,
    /// <summary>Represents the Open XML value <c>starsTop</c>.</summary>
    StarsTop,
    /// <summary>Represents the Open XML value <c>stars3d</c>.</summary>
    Stars3d,
    /// <summary>Represents the Open XML value <c>starsBlack</c>.</summary>
    StarsBlack,
    /// <summary>Represents the Open XML value <c>starsShadowed</c>.</summary>
    StarsShadowed,
    /// <summary>Represents the Open XML value <c>sun</c>.</summary>
    Sun,
    /// <summary>Represents the Open XML value <c>swirligig</c>.</summary>
    Swirligig,
    /// <summary>Represents the Open XML value <c>tornPaper</c>.</summary>
    TornPaper,
    /// <summary>Represents the Open XML value <c>tornPaperBlack</c>.</summary>
    TornPaperBlack,
    /// <summary>Represents the Open XML value <c>trees</c>.</summary>
    Trees,
    /// <summary>Represents the Open XML value <c>triangleParty</c>.</summary>
    TriangleParty,
    /// <summary>Represents the Open XML value <c>triangles</c>.</summary>
    Triangles,
    /// <summary>Represents the Open XML value <c>tribal1</c>.</summary>
    Tribal1,
    /// <summary>Represents the Open XML value <c>tribal2</c>.</summary>
    Tribal2,
    /// <summary>Represents the Open XML value <c>tribal3</c>.</summary>
    Tribal3,
    /// <summary>Represents the Open XML value <c>tribal4</c>.</summary>
    Tribal4,
    /// <summary>Represents the Open XML value <c>tribal5</c>.</summary>
    Tribal5,
    /// <summary>Represents the Open XML value <c>tribal6</c>.</summary>
    Tribal6,
    /// <summary>Represents the Open XML value <c>triangle1</c>.</summary>
    Triangle1,
    /// <summary>Represents the Open XML value <c>triangle2</c>.</summary>
    Triangle2,
    /// <summary>Represents the Open XML value <c>triangleCircle1</c>.</summary>
    TriangleCircle1,
    /// <summary>Represents the Open XML value <c>triangleCircle2</c>.</summary>
    TriangleCircle2,
    /// <summary>Represents the Open XML value <c>shapes1</c>.</summary>
    Shapes1,
    /// <summary>Represents the Open XML value <c>shapes2</c>.</summary>
    Shapes2,
    /// <summary>Represents the Open XML value <c>twistedLines1</c>.</summary>
    TwistedLines1,
    /// <summary>Represents the Open XML value <c>twistedLines2</c>.</summary>
    TwistedLines2,
    /// <summary>Represents the Open XML value <c>vine</c>.</summary>
    Vine,
    /// <summary>Represents the Open XML value <c>waveline</c>.</summary>
    Waveline,
    /// <summary>Represents the Open XML value <c>weavingAngles</c>.</summary>
    WeavingAngles,
    /// <summary>Represents the Open XML value <c>weavingBraid</c>.</summary>
    WeavingBraid,
    /// <summary>Represents the Open XML value <c>weavingRibbon</c>.</summary>
    WeavingRibbon,
    /// <summary>Represents the Open XML value <c>weavingStrips</c>.</summary>
    WeavingStrips,
    /// <summary>Represents the Open XML value <c>whiteFlowers</c>.</summary>
    WhiteFlowers,
    /// <summary>Represents the Open XML value <c>woodwork</c>.</summary>
    Woodwork,
    /// <summary>Represents the Open XML value <c>xIllusions</c>.</summary>
    XIllusions,
    /// <summary>Represents the Open XML value <c>zanyTriangles</c>.</summary>
    ZanyTriangles,
    /// <summary>Represents the Open XML value <c>zigZag</c>.</summary>
    ZigZag,
    /// <summary>Represents the Open XML value <c>zigZagStitch</c>.</summary>
    ZigZagStitch,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Wordprocessing.CharacterSpacingValues.</summary>
public enum WordCharacterSpacing {
    /// <summary>Represents the Open XML value <c>doNotCompress</c>.</summary>
    DoNotCompress,
    /// <summary>Represents the Open XML value <c>compressPunctuation</c>.</summary>
    CompressPunctuation,
    /// <summary>Represents the Open XML value <c>compressPunctuationAndJapaneseKana</c>.</summary>
    CompressPunctuationAndJapaneseKana,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Wordprocessing.EndnotePositionValues.</summary>
public enum WordEndnotePosition {
    /// <summary>Represents the Open XML value <c>sectEnd</c>.</summary>
    SectionEnd,
    /// <summary>Represents the Open XML value <c>docEnd</c>.</summary>
    DocumentEnd,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Wordprocessing.FootnotePositionValues.</summary>
public enum WordFootnotePosition {
    /// <summary>Represents the Open XML value <c>pageBottom</c>.</summary>
    PageBottom,
    /// <summary>Represents the Open XML value <c>beneathText</c>.</summary>
    BeneathText,
    /// <summary>Represents the Open XML value <c>sectEnd</c>.</summary>
    SectionEnd,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Wordprocessing.HighlightColorValues.</summary>
public enum WordHighlightColor {
    /// <summary>Represents the Open XML value <c>black</c>.</summary>
    Black,
    /// <summary>Represents the Open XML value <c>blue</c>.</summary>
    Blue,
    /// <summary>Represents the Open XML value <c>cyan</c>.</summary>
    Cyan,
    /// <summary>Represents the Open XML value <c>green</c>.</summary>
    Green,
    /// <summary>Represents the Open XML value <c>magenta</c>.</summary>
    Magenta,
    /// <summary>Represents the Open XML value <c>red</c>.</summary>
    Red,
    /// <summary>Represents the Open XML value <c>yellow</c>.</summary>
    Yellow,
    /// <summary>Represents the Open XML value <c>white</c>.</summary>
    White,
    /// <summary>Represents the Open XML value <c>darkBlue</c>.</summary>
    DarkBlue,
    /// <summary>Represents the Open XML value <c>darkCyan</c>.</summary>
    DarkCyan,
    /// <summary>Represents the Open XML value <c>darkGreen</c>.</summary>
    DarkGreen,
    /// <summary>Represents the Open XML value <c>darkMagenta</c>.</summary>
    DarkMagenta,
    /// <summary>Represents the Open XML value <c>darkRed</c>.</summary>
    DarkRed,
    /// <summary>Represents the Open XML value <c>darkYellow</c>.</summary>
    DarkYellow,
    /// <summary>Represents the Open XML value <c>darkGray</c>.</summary>
    DarkGray,
    /// <summary>Represents the Open XML value <c>lightGray</c>.</summary>
    LightGray,
    /// <summary>Represents the Open XML value <c>none</c>.</summary>
    None,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Wordprocessing.HorizontalAlignmentValues.</summary>
public enum WordTableHorizontalAlignment {
    /// <summary>Represents the Open XML value <c>left</c>.</summary>
    Left,
    /// <summary>Represents the Open XML value <c>center</c>.</summary>
    Center,
    /// <summary>Represents the Open XML value <c>right</c>.</summary>
    Right,
    /// <summary>Represents the Open XML value <c>inside</c>.</summary>
    Inside,
    /// <summary>Represents the Open XML value <c>outside</c>.</summary>
    Outside,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Wordprocessing.HorizontalAnchorValues.</summary>
public enum WordTableHorizontalAnchor {
    /// <summary>Represents the Open XML value <c>text</c>.</summary>
    Text,
    /// <summary>Represents the Open XML value <c>margin</c>.</summary>
    Margin,
    /// <summary>Represents the Open XML value <c>page</c>.</summary>
    Page,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Wordprocessing.LevelJustificationValues.</summary>
public enum WordListLevelAlignment {
    /// <summary>Represents the Open XML value <c>left</c>.</summary>
    Left,
    /// <summary>Represents the Open XML value <c>center</c>.</summary>
    Center,
    /// <summary>Represents the Open XML value <c>right</c>.</summary>
    Right,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Wordprocessing.LevelSuffixValues.</summary>
public enum WordListLevelSuffix {
    /// <summary>Represents the Open XML value <c>tab</c>.</summary>
    Tab,
    /// <summary>Represents the Open XML value <c>space</c>.</summary>
    Space,
    /// <summary>Represents the Open XML value <c>nothing</c>.</summary>
    Nothing,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Wordprocessing.LineSpacingRuleValues.</summary>
public enum WordLineSpacingRule {
    /// <summary>Represents the Open XML value <c>auto</c>.</summary>
    Auto,
    /// <summary>Represents the Open XML value <c>exact</c>.</summary>
    Exact,
    /// <summary>Represents the Open XML value <c>atLeast</c>.</summary>
    AtLeast,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Wordprocessing.MergedCellValues.</summary>
public enum WordCellMerge {
    /// <summary>Represents the Open XML value <c>continue</c>.</summary>
    Continue,
    /// <summary>Represents the Open XML value <c>restart</c>.</summary>
    Restart,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Wordprocessing.NumberFormatValues.</summary>
public enum WordNumberFormat {
    /// <summary>Represents the Open XML value <c>decimal</c>.</summary>
    Decimal,
    /// <summary>Represents the Open XML value <c>upperRoman</c>.</summary>
    UpperRoman,
    /// <summary>Represents the Open XML value <c>lowerRoman</c>.</summary>
    LowerRoman,
    /// <summary>Represents the Open XML value <c>upperLetter</c>.</summary>
    UpperLetter,
    /// <summary>Represents the Open XML value <c>lowerLetter</c>.</summary>
    LowerLetter,
    /// <summary>Represents the Open XML value <c>ordinal</c>.</summary>
    Ordinal,
    /// <summary>Represents the Open XML value <c>cardinalText</c>.</summary>
    CardinalText,
    /// <summary>Represents the Open XML value <c>ordinalText</c>.</summary>
    OrdinalText,
    /// <summary>Represents the Open XML value <c>hex</c>.</summary>
    Hex,
    /// <summary>Represents the Open XML value <c>chicago</c>.</summary>
    Chicago,
    /// <summary>Represents the Open XML value <c>ideographDigital</c>.</summary>
    IdeographDigital,
    /// <summary>Represents the Open XML value <c>japaneseCounting</c>.</summary>
    JapaneseCounting,
    /// <summary>Represents the Open XML value <c>aiueo</c>.</summary>
    Aiueo,
    /// <summary>Represents the Open XML value <c>iroha</c>.</summary>
    Iroha,
    /// <summary>Represents the Open XML value <c>decimalFullWidth</c>.</summary>
    DecimalFullWidth,
    /// <summary>Represents the Open XML value <c>decimalHalfWidth</c>.</summary>
    DecimalHalfWidth,
    /// <summary>Represents the Open XML value <c>japaneseLegal</c>.</summary>
    JapaneseLegal,
    /// <summary>Represents the Open XML value <c>japaneseDigitalTenThousand</c>.</summary>
    JapaneseDigitalTenThousand,
    /// <summary>Represents the Open XML value <c>decimalEnclosedCircle</c>.</summary>
    DecimalEnclosedCircle,
    /// <summary>Represents the Open XML value <c>decimalFullWidth2</c>.</summary>
    DecimalFullWidth2,
    /// <summary>Represents the Open XML value <c>aiueoFullWidth</c>.</summary>
    AiueoFullWidth,
    /// <summary>Represents the Open XML value <c>irohaFullWidth</c>.</summary>
    IrohaFullWidth,
    /// <summary>Represents the Open XML value <c>decimalZero</c>.</summary>
    DecimalZero,
    /// <summary>Represents the Open XML value <c>bullet</c>.</summary>
    Bullet,
    /// <summary>Represents the Open XML value <c>ganada</c>.</summary>
    Ganada,
    /// <summary>Represents the Open XML value <c>chosung</c>.</summary>
    Chosung,
    /// <summary>Represents the Open XML value <c>decimalEnclosedFullstop</c>.</summary>
    DecimalEnclosedFullstop,
    /// <summary>Represents the Open XML value <c>decimalEnclosedParen</c>.</summary>
    DecimalEnclosedParen,
    /// <summary>Represents the Open XML value <c>decimalEnclosedCircleChinese</c>.</summary>
    DecimalEnclosedCircleChinese,
    /// <summary>Represents the Open XML value <c>ideographEnclosedCircle</c>.</summary>
    IdeographEnclosedCircle,
    /// <summary>Represents the Open XML value <c>ideographTraditional</c>.</summary>
    IdeographTraditional,
    /// <summary>Represents the Open XML value <c>ideographZodiac</c>.</summary>
    IdeographZodiac,
    /// <summary>Represents the Open XML value <c>ideographZodiacTraditional</c>.</summary>
    IdeographZodiacTraditional,
    /// <summary>Represents the Open XML value <c>taiwaneseCounting</c>.</summary>
    TaiwaneseCounting,
    /// <summary>Represents the Open XML value <c>ideographLegalTraditional</c>.</summary>
    IdeographLegalTraditional,
    /// <summary>Represents the Open XML value <c>taiwaneseCountingThousand</c>.</summary>
    TaiwaneseCountingThousand,
    /// <summary>Represents the Open XML value <c>taiwaneseDigital</c>.</summary>
    TaiwaneseDigital,
    /// <summary>Represents the Open XML value <c>chineseCounting</c>.</summary>
    ChineseCounting,
    /// <summary>Represents the Open XML value <c>chineseLegalSimplified</c>.</summary>
    ChineseLegalSimplified,
    /// <summary>Represents the Open XML value <c>chineseCountingThousand</c>.</summary>
    ChineseCountingThousand,
    /// <summary>Represents the Open XML value <c>koreanDigital</c>.</summary>
    KoreanDigital,
    /// <summary>Represents the Open XML value <c>koreanCounting</c>.</summary>
    KoreanCounting,
    /// <summary>Represents the Open XML value <c>koreanLegal</c>.</summary>
    KoreanLegal,
    /// <summary>Represents the Open XML value <c>koreanDigital2</c>.</summary>
    KoreanDigital2,
    /// <summary>Represents the Open XML value <c>vietnameseCounting</c>.</summary>
    VietnameseCounting,
    /// <summary>Represents the Open XML value <c>russianLower</c>.</summary>
    RussianLower,
    /// <summary>Represents the Open XML value <c>russianUpper</c>.</summary>
    RussianUpper,
    /// <summary>Represents the Open XML value <c>none</c>.</summary>
    None,
    /// <summary>Represents the Open XML value <c>numberInDash</c>.</summary>
    NumberInDash,
    /// <summary>Represents the Open XML value <c>hebrew1</c>.</summary>
    Hebrew1,
    /// <summary>Represents the Open XML value <c>hebrew2</c>.</summary>
    Hebrew2,
    /// <summary>Represents the Open XML value <c>arabicAlpha</c>.</summary>
    ArabicAlpha,
    /// <summary>Represents the Open XML value <c>arabicAbjad</c>.</summary>
    ArabicAbjad,
    /// <summary>Represents the Open XML value <c>hindiVowels</c>.</summary>
    HindiVowels,
    /// <summary>Represents the Open XML value <c>hindiConsonants</c>.</summary>
    HindiConsonants,
    /// <summary>Represents the Open XML value <c>hindiNumbers</c>.</summary>
    HindiNumbers,
    /// <summary>Represents the Open XML value <c>hindiCounting</c>.</summary>
    HindiCounting,
    /// <summary>Represents the Open XML value <c>thaiLetters</c>.</summary>
    ThaiLetters,
    /// <summary>Represents the Open XML value <c>thaiNumbers</c>.</summary>
    ThaiNumbers,
    /// <summary>Represents the Open XML value <c>thaiCounting</c>.</summary>
    ThaiCounting,
    /// <summary>Represents the Open XML value <c>bahtText</c>.</summary>
    BahtText,
    /// <summary>Represents the Open XML value <c>dollarText</c>.</summary>
    DollarText,
    /// <summary>Represents the Open XML value <c>custom</c>.</summary>
    Custom,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Wordprocessing.PresetZoomValues.</summary>
public enum WordZoomPreset {
    /// <summary>Represents the Open XML value <c>none</c>.</summary>
    None,
    /// <summary>Represents the Open XML value <c>fullPage</c>.</summary>
    FullPage,
    /// <summary>Represents the Open XML value <c>bestFit</c>.</summary>
    BestFit,
    /// <summary>Represents the Open XML value <c>textFit</c>.</summary>
    TextFit,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Wordprocessing.RestartNumberValues.</summary>
public enum WordNoteNumberRestart {
    /// <summary>Represents the Open XML value <c>continuous</c>.</summary>
    Continuous,
    /// <summary>Represents the Open XML value <c>eachSect</c>.</summary>
    EachSection,
    /// <summary>Represents the Open XML value <c>eachPage</c>.</summary>
    EachPage,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Wordprocessing.ShadingPatternValues.</summary>
public enum WordShadingPattern {
    /// <summary>Represents the Open XML value <c>nil</c>.</summary>
    Nil,
    /// <summary>Represents the Open XML value <c>clear</c>.</summary>
    Clear,
    /// <summary>Represents the Open XML value <c>solid</c>.</summary>
    Solid,
    /// <summary>Represents the Open XML value <c>horzStripe</c>.</summary>
    HorizontalStripe,
    /// <summary>Represents the Open XML value <c>vertStripe</c>.</summary>
    VerticalStripe,
    /// <summary>Represents the Open XML value <c>reverseDiagStripe</c>.</summary>
    ReverseDiagonalStripe,
    /// <summary>Represents the Open XML value <c>diagStripe</c>.</summary>
    DiagonalStripe,
    /// <summary>Represents the Open XML value <c>horzCross</c>.</summary>
    HorizontalCross,
    /// <summary>Represents the Open XML value <c>diagCross</c>.</summary>
    DiagonalCross,
    /// <summary>Represents the Open XML value <c>thinHorzStripe</c>.</summary>
    ThinHorizontalStripe,
    /// <summary>Represents the Open XML value <c>thinVertStripe</c>.</summary>
    ThinVerticalStripe,
    /// <summary>Represents the Open XML value <c>thinReverseDiagStripe</c>.</summary>
    ThinReverseDiagonalStripe,
    /// <summary>Represents the Open XML value <c>thinDiagStripe</c>.</summary>
    ThinDiagonalStripe,
    /// <summary>Represents the Open XML value <c>thinHorzCross</c>.</summary>
    ThinHorizontalCross,
    /// <summary>Represents the Open XML value <c>thinDiagCross</c>.</summary>
    ThinDiagonalCross,
    /// <summary>Represents the Open XML value <c>pct5</c>.</summary>
    Percent5,
    /// <summary>Represents the Open XML value <c>pct10</c>.</summary>
    Percent10,
    /// <summary>Represents the Open XML value <c>pct12</c>.</summary>
    Percent12,
    /// <summary>Represents the Open XML value <c>pct15</c>.</summary>
    Percent15,
    /// <summary>Represents the Open XML value <c>pct20</c>.</summary>
    Percent20,
    /// <summary>Represents the Open XML value <c>pct25</c>.</summary>
    Percent25,
    /// <summary>Represents the Open XML value <c>pct30</c>.</summary>
    Percent30,
    /// <summary>Represents the Open XML value <c>pct35</c>.</summary>
    Percent35,
    /// <summary>Represents the Open XML value <c>pct37</c>.</summary>
    Percent37,
    /// <summary>Represents the Open XML value <c>pct40</c>.</summary>
    Percent40,
    /// <summary>Represents the Open XML value <c>pct45</c>.</summary>
    Percent45,
    /// <summary>Represents the Open XML value <c>pct50</c>.</summary>
    Percent50,
    /// <summary>Represents the Open XML value <c>pct55</c>.</summary>
    Percent55,
    /// <summary>Represents the Open XML value <c>pct60</c>.</summary>
    Percent60,
    /// <summary>Represents the Open XML value <c>pct62</c>.</summary>
    Percent62,
    /// <summary>Represents the Open XML value <c>pct65</c>.</summary>
    Percent65,
    /// <summary>Represents the Open XML value <c>pct70</c>.</summary>
    Percent70,
    /// <summary>Represents the Open XML value <c>pct75</c>.</summary>
    Percent75,
    /// <summary>Represents the Open XML value <c>pct80</c>.</summary>
    Percent80,
    /// <summary>Represents the Open XML value <c>pct85</c>.</summary>
    Percent85,
    /// <summary>Represents the Open XML value <c>pct87</c>.</summary>
    Percent87,
    /// <summary>Represents the Open XML value <c>pct90</c>.</summary>
    Percent90,
    /// <summary>Represents the Open XML value <c>pct95</c>.</summary>
    Percent95,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Wordprocessing.TabStopLeaderCharValues.</summary>
public enum WordTabLeader {
    /// <summary>Represents the Open XML value <c>none</c>.</summary>
    None,
    /// <summary>Represents the Open XML value <c>dot</c>.</summary>
    Dot,
    /// <summary>Represents the Open XML value <c>hyphen</c>.</summary>
    Hyphen,
    /// <summary>Represents the Open XML value <c>underscore</c>.</summary>
    Underscore,
    /// <summary>Represents the Open XML value <c>heavy</c>.</summary>
    Heavy,
    /// <summary>Represents the Open XML value <c>middleDot</c>.</summary>
    MiddleDot,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Wordprocessing.TabStopValues.</summary>
public enum WordTabAlignment {
    /// <summary>Represents the Open XML value <c>clear</c>.</summary>
    Clear,
    /// <summary>Represents the Open XML value <c>left</c>.</summary>
    Left,
    /// <summary>Represents the Open XML value <c>start</c>.</summary>
    Start,
    /// <summary>Represents the Open XML value <c>center</c>.</summary>
    Center,
    /// <summary>Represents the Open XML value <c>right</c>.</summary>
    Right,
    /// <summary>Represents the Open XML value <c>end</c>.</summary>
    End,
    /// <summary>Represents the Open XML value <c>decimal</c>.</summary>
    Decimal,
    /// <summary>Represents the Open XML value <c>bar</c>.</summary>
    Bar,
    /// <summary>Represents the Open XML value <c>num</c>.</summary>
    Number,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Wordprocessing.TableOverlapValues.</summary>
public enum WordTableOverlap {
    /// <summary>Represents the Open XML value <c>never</c>.</summary>
    Never,
    /// <summary>Represents the Open XML value <c>overlap</c>.</summary>
    Overlap,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Wordprocessing.TableRowAlignmentValues.</summary>
public enum WordTableAlignment {
    /// <summary>Represents the Open XML value <c>left</c>.</summary>
    Left,
    /// <summary>Represents the Open XML value <c>center</c>.</summary>
    Center,
    /// <summary>Represents the Open XML value <c>right</c>.</summary>
    Right,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Wordprocessing.TableWidthUnitValues.</summary>
public enum WordTableWidthUnit {
    /// <summary>Represents the Open XML value <c>nil</c>.</summary>
    Nil,
    /// <summary>Represents the Open XML value <c>pct</c>.</summary>
    Pct,
    /// <summary>Represents the Open XML value <c>dxa</c>.</summary>
    Dxa,
    /// <summary>Represents the Open XML value <c>auto</c>.</summary>
    Auto,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Wordprocessing.ThemeColorValues.</summary>
public enum WordThemeColor {
    /// <summary>Represents the Open XML value <c>dark1</c>.</summary>
    Dark1,
    /// <summary>Represents the Open XML value <c>light1</c>.</summary>
    Light1,
    /// <summary>Represents the Open XML value <c>dark2</c>.</summary>
    Dark2,
    /// <summary>Represents the Open XML value <c>light2</c>.</summary>
    Light2,
    /// <summary>Represents the Open XML value <c>accent1</c>.</summary>
    Accent1,
    /// <summary>Represents the Open XML value <c>accent2</c>.</summary>
    Accent2,
    /// <summary>Represents the Open XML value <c>accent3</c>.</summary>
    Accent3,
    /// <summary>Represents the Open XML value <c>accent4</c>.</summary>
    Accent4,
    /// <summary>Represents the Open XML value <c>accent5</c>.</summary>
    Accent5,
    /// <summary>Represents the Open XML value <c>accent6</c>.</summary>
    Accent6,
    /// <summary>Represents the Open XML value <c>hyperlink</c>.</summary>
    Hyperlink,
    /// <summary>Represents the Open XML value <c>followedHyperlink</c>.</summary>
    FollowedHyperlink,
    /// <summary>Represents the Open XML value <c>none</c>.</summary>
    None,
    /// <summary>Represents the Open XML value <c>background1</c>.</summary>
    Background1,
    /// <summary>Represents the Open XML value <c>text1</c>.</summary>
    Text1,
    /// <summary>Represents the Open XML value <c>background2</c>.</summary>
    Background2,
    /// <summary>Represents the Open XML value <c>text2</c>.</summary>
    Text2,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Wordprocessing.VerticalAlignmentValues.</summary>
public enum WordTableVerticalPositionAlignment {
    /// <summary>Represents the Open XML value <c>inline</c>.</summary>
    Inline,
    /// <summary>Represents the Open XML value <c>top</c>.</summary>
    Top,
    /// <summary>Represents the Open XML value <c>center</c>.</summary>
    Center,
    /// <summary>Represents the Open XML value <c>bottom</c>.</summary>
    Bottom,
    /// <summary>Represents the Open XML value <c>inside</c>.</summary>
    Inside,
    /// <summary>Represents the Open XML value <c>outside</c>.</summary>
    Outside,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Wordprocessing.VerticalAnchorValues.</summary>
public enum WordTableVerticalAnchor {
    /// <summary>Represents the Open XML value <c>text</c>.</summary>
    Text,
    /// <summary>Represents the Open XML value <c>margin</c>.</summary>
    Margin,
    /// <summary>Represents the Open XML value <c>page</c>.</summary>
    Page,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Wordprocessing.VerticalPositionValues.</summary>
public enum WordVerticalTextPosition {
    /// <summary>Represents the Open XML value <c>baseline</c>.</summary>
    Baseline,
    /// <summary>Represents the Open XML value <c>superscript</c>.</summary>
    Superscript,
    /// <summary>Represents the Open XML value <c>subscript</c>.</summary>
    Subscript,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Wordprocessing.VerticalTextAlignmentValues.</summary>
public enum WordVerticalCharacterAlignment {
    /// <summary>Represents the Open XML value <c>top</c>.</summary>
    Top,
    /// <summary>Represents the Open XML value <c>center</c>.</summary>
    Center,
    /// <summary>Represents the Open XML value <c>baseline</c>.</summary>
    Baseline,
    /// <summary>Represents the Open XML value <c>bottom</c>.</summary>
    Bottom,
    /// <summary>Represents the Open XML value <c>auto</c>.</summary>
    Auto,
}

internal static class WordOpenXmlValueTypeExtensions {
    private static readonly string[] WordBibliographySourceTypeTokens = {
        "ArticleInAPeriodical",
        "Book",
        "BookSection",
        "JournalArticle",
        "ConferenceProceedings",
        "Report",
        "SoundRecording",
        "Performance",
        "Art",
        "DocumentFromInternetSite",
        "InternetSite",
        "Film",
        "Interview",
        "Patent",
        "ElectronicSource",
        "Case",
        "Misc",
    };

    internal static DocumentFormat.OpenXml.Bibliography.DataSourceValues ToOpenXml(this WordBibliographySourceType value) =>
        new(GetToken(value, WordBibliographySourceTypeTokens));

    internal static DocumentFormat.OpenXml.Bibliography.DataSourceValues? ToOpenXml(this WordBibliographySourceType? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordBibliographySourceType ToOfficeEnum(this DocumentFormat.OpenXml.Bibliography.DataSourceValues value) =>
        (WordBibliographySourceType)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordBibliographySourceTypeTokens, nameof(WordBibliographySourceType));

    internal static WordBibliographySourceType? ToOfficeEnum(this DocumentFormat.OpenXml.Bibliography.DataSourceValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordImageBlackWhiteModeTokens = {
        "clr",
        "auto",
        "gray",
        "ltGray",
        "invGray",
        "grayWhite",
        "blackGray",
        "blackWhite",
        "black",
        "white",
        "hidden",
    };

    internal static DocumentFormat.OpenXml.Drawing.BlackWhiteModeValues ToOpenXml(this WordImageBlackWhiteMode value) =>
        new(GetToken(value, WordImageBlackWhiteModeTokens));

    internal static DocumentFormat.OpenXml.Drawing.BlackWhiteModeValues? ToOpenXml(this WordImageBlackWhiteMode? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordImageBlackWhiteMode ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.BlackWhiteModeValues value) =>
        (WordImageBlackWhiteMode)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordImageBlackWhiteModeTokens, nameof(WordImageBlackWhiteMode));

    internal static WordImageBlackWhiteMode? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.BlackWhiteModeValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordImageCompressionQualityTokens = {
        "email",
        "screen",
        "print",
        "hqprint",
        "none",
    };

    internal static DocumentFormat.OpenXml.Drawing.BlipCompressionValues ToOpenXml(this WordImageCompressionQuality value) =>
        new(GetToken(value, WordImageCompressionQualityTokens));

    internal static DocumentFormat.OpenXml.Drawing.BlipCompressionValues? ToOpenXml(this WordImageCompressionQuality? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordImageCompressionQuality ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.BlipCompressionValues value) =>
        (WordImageCompressionQuality)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordImageCompressionQualityTokens, nameof(WordImageCompressionQuality));

    internal static WordImageCompressionQuality? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.BlipCompressionValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordChartBarDirectionTokens = {
        "bar",
        "col",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.BarDirectionValues ToOpenXml(this WordChartBarDirection value) =>
        new(GetToken(value, WordChartBarDirectionTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.BarDirectionValues? ToOpenXml(this WordChartBarDirection? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordChartBarDirection ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.BarDirectionValues value) =>
        (WordChartBarDirection)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordChartBarDirectionTokens, nameof(WordChartBarDirection));

    internal static WordChartBarDirection? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.BarDirectionValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordChartBarGroupingTokens = {
        "percentStacked",
        "clustered",
        "standard",
        "stacked",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.BarGroupingValues ToOpenXml(this WordChartBarGrouping value) =>
        new(GetToken(value, WordChartBarGroupingTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.BarGroupingValues? ToOpenXml(this WordChartBarGrouping? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordChartBarGrouping ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.BarGroupingValues value) =>
        (WordChartBarGrouping)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordChartBarGroupingTokens, nameof(WordChartBarGrouping));

    internal static WordChartBarGrouping? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.BarGroupingValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordTextBoxHorizontalSizeReferenceTokens = {
        "margin",
        "page",
        "leftMargin",
        "rightMargin",
        "insideMargin",
        "outsideMargin",
    };

    internal static DocumentFormat.OpenXml.Office2010.Word.Drawing.SizeRelativeHorizontallyValues ToOpenXml(this WordTextBoxHorizontalSizeReference value) =>
        new(GetToken(value, WordTextBoxHorizontalSizeReferenceTokens));

    internal static DocumentFormat.OpenXml.Office2010.Word.Drawing.SizeRelativeHorizontallyValues? ToOpenXml(this WordTextBoxHorizontalSizeReference? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordTextBoxHorizontalSizeReference ToOfficeEnum(this DocumentFormat.OpenXml.Office2010.Word.Drawing.SizeRelativeHorizontallyValues value) =>
        (WordTextBoxHorizontalSizeReference)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordTextBoxHorizontalSizeReferenceTokens, nameof(WordTextBoxHorizontalSizeReference));

    internal static WordTextBoxHorizontalSizeReference? ToOfficeEnum(this DocumentFormat.OpenXml.Office2010.Word.Drawing.SizeRelativeHorizontallyValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordBorderStyleTokens = {
        "nil",
        "none",
        "single",
        "thick",
        "double",
        "dotted",
        "dashed",
        "dotDash",
        "dotDotDash",
        "triple",
        "thinThickSmallGap",
        "thickThinSmallGap",
        "thinThickThinSmallGap",
        "thinThickMediumGap",
        "thickThinMediumGap",
        "thinThickThinMediumGap",
        "thinThickLargeGap",
        "thickThinLargeGap",
        "thinThickThinLargeGap",
        "wave",
        "doubleWave",
        "dashSmallGap",
        "dashDotStroked",
        "threeDEmboss",
        "threeDEngrave",
        "outset",
        "inset",
        "apples",
        "archedScallops",
        "babyPacifier",
        "babyRattle",
        "balloons3Colors",
        "balloonsHotAir",
        "basicBlackDashes",
        "basicBlackDots",
        "basicBlackSquares",
        "basicThinLines",
        "basicWhiteDashes",
        "basicWhiteDots",
        "basicWhiteSquares",
        "basicWideInline",
        "basicWideMidline",
        "basicWideOutline",
        "bats",
        "birds",
        "birdsFlight",
        "cabins",
        "cakeSlice",
        "candyCorn",
        "celticKnotwork",
        "certificateBanner",
        "chainLink",
        "champagneBottle",
        "checkedBarBlack",
        "checkedBarColor",
        "checkered",
        "christmasTree",
        "circlesLines",
        "circlesRectangles",
        "classicalWave",
        "clocks",
        "compass",
        "confetti",
        "confettiGrays",
        "confettiOutline",
        "confettiStreamers",
        "confettiWhite",
        "cornerTriangles",
        "couponCutoutDashes",
        "couponCutoutDots",
        "crazyMaze",
        "creaturesButterfly",
        "creaturesFish",
        "creaturesInsects",
        "creaturesLadyBug",
        "crossStitch",
        "cup",
        "decoArch",
        "decoArchColor",
        "decoBlocks",
        "diamondsGray",
        "doubleD",
        "doubleDiamonds",
        "earth1",
        "earth2",
        "eclipsingSquares1",
        "eclipsingSquares2",
        "eggsBlack",
        "fans",
        "film",
        "firecrackers",
        "flowersBlockPrint",
        "flowersDaisies",
        "flowersModern1",
        "flowersModern2",
        "flowersPansy",
        "flowersRedRose",
        "flowersRoses",
        "flowersTeacup",
        "flowersTiny",
        "gems",
        "gingerbreadMan",
        "gradient",
        "handmade1",
        "handmade2",
        "heartBalloon",
        "heartGray",
        "hearts",
        "heebieJeebies",
        "holly",
        "houseFunky",
        "hypnotic",
        "iceCreamCones",
        "lightBulb",
        "lightning1",
        "lightning2",
        "mapPins",
        "mapleLeaf",
        "mapleMuffins",
        "marquee",
        "marqueeToothed",
        "moons",
        "mosaic",
        "musicNotes",
        "northwest",
        "ovals",
        "packages",
        "palmsBlack",
        "palmsColor",
        "paperClips",
        "papyrus",
        "partyFavor",
        "partyGlass",
        "pencils",
        "people",
        "peopleWaving",
        "peopleHats",
        "poinsettias",
        "postageStamp",
        "pumpkin1",
        "pushPinNote2",
        "pushPinNote1",
        "pyramids",
        "pyramidsAbove",
        "quadrants",
        "rings",
        "safari",
        "sawtooth",
        "sawtoothGray",
        "scaredCat",
        "seattle",
        "shadowedSquares",
        "sharksTeeth",
        "shorebirdTracks",
        "skyrocket",
        "snowflakeFancy",
        "snowflakes",
        "sombrero",
        "southwest",
        "stars",
        "starsTop",
        "stars3d",
        "starsBlack",
        "starsShadowed",
        "sun",
        "swirligig",
        "tornPaper",
        "tornPaperBlack",
        "trees",
        "triangleParty",
        "triangles",
        "tribal1",
        "tribal2",
        "tribal3",
        "tribal4",
        "tribal5",
        "tribal6",
        "triangle1",
        "triangle2",
        "triangleCircle1",
        "triangleCircle2",
        "shapes1",
        "shapes2",
        "twistedLines1",
        "twistedLines2",
        "vine",
        "waveline",
        "weavingAngles",
        "weavingBraid",
        "weavingRibbon",
        "weavingStrips",
        "whiteFlowers",
        "woodwork",
        "xIllusions",
        "zanyTriangles",
        "zigZag",
        "zigZagStitch",
    };

    internal static DocumentFormat.OpenXml.Wordprocessing.BorderValues ToOpenXml(this WordBorderStyle value) =>
        new(GetToken(value, WordBorderStyleTokens));

    internal static DocumentFormat.OpenXml.Wordprocessing.BorderValues? ToOpenXml(this WordBorderStyle? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordBorderStyle ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.BorderValues value) =>
        (WordBorderStyle)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordBorderStyleTokens, nameof(WordBorderStyle));

    internal static WordBorderStyle? ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.BorderValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordCharacterSpacingTokens = {
        "doNotCompress",
        "compressPunctuation",
        "compressPunctuationAndJapaneseKana",
    };

    internal static DocumentFormat.OpenXml.Wordprocessing.CharacterSpacingValues ToOpenXml(this WordCharacterSpacing value) =>
        new(GetToken(value, WordCharacterSpacingTokens));

    internal static DocumentFormat.OpenXml.Wordprocessing.CharacterSpacingValues? ToOpenXml(this WordCharacterSpacing? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordCharacterSpacing ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.CharacterSpacingValues value) =>
        (WordCharacterSpacing)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordCharacterSpacingTokens, nameof(WordCharacterSpacing));

    internal static WordCharacterSpacing? ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.CharacterSpacingValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordEndnotePositionTokens = {
        "sectEnd",
        "docEnd",
    };

    internal static DocumentFormat.OpenXml.Wordprocessing.EndnotePositionValues ToOpenXml(this WordEndnotePosition value) =>
        new(GetToken(value, WordEndnotePositionTokens));

    internal static DocumentFormat.OpenXml.Wordprocessing.EndnotePositionValues? ToOpenXml(this WordEndnotePosition? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordEndnotePosition ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.EndnotePositionValues value) =>
        (WordEndnotePosition)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordEndnotePositionTokens, nameof(WordEndnotePosition));

    internal static WordEndnotePosition? ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.EndnotePositionValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordFootnotePositionTokens = {
        "pageBottom",
        "beneathText",
        "sectEnd",
    };

    internal static DocumentFormat.OpenXml.Wordprocessing.FootnotePositionValues ToOpenXml(this WordFootnotePosition value) =>
        new(GetToken(value, WordFootnotePositionTokens));

    internal static DocumentFormat.OpenXml.Wordprocessing.FootnotePositionValues? ToOpenXml(this WordFootnotePosition? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordFootnotePosition ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.FootnotePositionValues value) =>
        (WordFootnotePosition)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordFootnotePositionTokens, nameof(WordFootnotePosition));

    internal static WordFootnotePosition? ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.FootnotePositionValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordHighlightColorTokens = {
        "black",
        "blue",
        "cyan",
        "green",
        "magenta",
        "red",
        "yellow",
        "white",
        "darkBlue",
        "darkCyan",
        "darkGreen",
        "darkMagenta",
        "darkRed",
        "darkYellow",
        "darkGray",
        "lightGray",
        "none",
    };

    internal static DocumentFormat.OpenXml.Wordprocessing.HighlightColorValues ToOpenXml(this WordHighlightColor value) =>
        new(GetToken(value, WordHighlightColorTokens));

    internal static DocumentFormat.OpenXml.Wordprocessing.HighlightColorValues? ToOpenXml(this WordHighlightColor? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordHighlightColor ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.HighlightColorValues value) =>
        (WordHighlightColor)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordHighlightColorTokens, nameof(WordHighlightColor));

    internal static WordHighlightColor? ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.HighlightColorValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordTableHorizontalAlignmentTokens = {
        "left",
        "center",
        "right",
        "inside",
        "outside",
    };

    internal static DocumentFormat.OpenXml.Wordprocessing.HorizontalAlignmentValues ToOpenXml(this WordTableHorizontalAlignment value) =>
        new(GetToken(value, WordTableHorizontalAlignmentTokens));

    internal static DocumentFormat.OpenXml.Wordprocessing.HorizontalAlignmentValues? ToOpenXml(this WordTableHorizontalAlignment? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordTableHorizontalAlignment ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.HorizontalAlignmentValues value) =>
        (WordTableHorizontalAlignment)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordTableHorizontalAlignmentTokens, nameof(WordTableHorizontalAlignment));

    internal static WordTableHorizontalAlignment? ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.HorizontalAlignmentValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordTableHorizontalAnchorTokens = {
        "text",
        "margin",
        "page",
    };

    internal static DocumentFormat.OpenXml.Wordprocessing.HorizontalAnchorValues ToOpenXml(this WordTableHorizontalAnchor value) =>
        new(GetToken(value, WordTableHorizontalAnchorTokens));

    internal static DocumentFormat.OpenXml.Wordprocessing.HorizontalAnchorValues? ToOpenXml(this WordTableHorizontalAnchor? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordTableHorizontalAnchor ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.HorizontalAnchorValues value) =>
        (WordTableHorizontalAnchor)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordTableHorizontalAnchorTokens, nameof(WordTableHorizontalAnchor));

    internal static WordTableHorizontalAnchor? ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.HorizontalAnchorValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordListLevelAlignmentTokens = {
        "left",
        "center",
        "right",
    };

    internal static DocumentFormat.OpenXml.Wordprocessing.LevelJustificationValues ToOpenXml(this WordListLevelAlignment value) =>
        new(GetToken(value, WordListLevelAlignmentTokens));

    internal static DocumentFormat.OpenXml.Wordprocessing.LevelJustificationValues? ToOpenXml(this WordListLevelAlignment? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordListLevelAlignment ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.LevelJustificationValues value) =>
        (WordListLevelAlignment)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordListLevelAlignmentTokens, nameof(WordListLevelAlignment));

    internal static WordListLevelAlignment? ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.LevelJustificationValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordListLevelSuffixTokens = {
        "tab",
        "space",
        "nothing",
    };

    internal static DocumentFormat.OpenXml.Wordprocessing.LevelSuffixValues ToOpenXml(this WordListLevelSuffix value) =>
        new(GetToken(value, WordListLevelSuffixTokens));

    internal static DocumentFormat.OpenXml.Wordprocessing.LevelSuffixValues? ToOpenXml(this WordListLevelSuffix? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordListLevelSuffix ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.LevelSuffixValues value) =>
        (WordListLevelSuffix)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordListLevelSuffixTokens, nameof(WordListLevelSuffix));

    internal static WordListLevelSuffix? ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.LevelSuffixValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordLineSpacingRuleTokens = {
        "auto",
        "exact",
        "atLeast",
    };

    internal static DocumentFormat.OpenXml.Wordprocessing.LineSpacingRuleValues ToOpenXml(this WordLineSpacingRule value) =>
        new(GetToken(value, WordLineSpacingRuleTokens));

    internal static DocumentFormat.OpenXml.Wordprocessing.LineSpacingRuleValues? ToOpenXml(this WordLineSpacingRule? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordLineSpacingRule ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.LineSpacingRuleValues value) =>
        (WordLineSpacingRule)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordLineSpacingRuleTokens, nameof(WordLineSpacingRule));

    internal static WordLineSpacingRule? ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.LineSpacingRuleValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordCellMergeTokens = {
        "continue",
        "restart",
    };

    internal static DocumentFormat.OpenXml.Wordprocessing.MergedCellValues ToOpenXml(this WordCellMerge value) =>
        new(GetToken(value, WordCellMergeTokens));

    internal static DocumentFormat.OpenXml.Wordprocessing.MergedCellValues? ToOpenXml(this WordCellMerge? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordCellMerge ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.MergedCellValues value) =>
        (WordCellMerge)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordCellMergeTokens, nameof(WordCellMerge));

    internal static WordCellMerge? ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.MergedCellValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordNumberFormatTokens = {
        "decimal",
        "upperRoman",
        "lowerRoman",
        "upperLetter",
        "lowerLetter",
        "ordinal",
        "cardinalText",
        "ordinalText",
        "hex",
        "chicago",
        "ideographDigital",
        "japaneseCounting",
        "aiueo",
        "iroha",
        "decimalFullWidth",
        "decimalHalfWidth",
        "japaneseLegal",
        "japaneseDigitalTenThousand",
        "decimalEnclosedCircle",
        "decimalFullWidth2",
        "aiueoFullWidth",
        "irohaFullWidth",
        "decimalZero",
        "bullet",
        "ganada",
        "chosung",
        "decimalEnclosedFullstop",
        "decimalEnclosedParen",
        "decimalEnclosedCircleChinese",
        "ideographEnclosedCircle",
        "ideographTraditional",
        "ideographZodiac",
        "ideographZodiacTraditional",
        "taiwaneseCounting",
        "ideographLegalTraditional",
        "taiwaneseCountingThousand",
        "taiwaneseDigital",
        "chineseCounting",
        "chineseLegalSimplified",
        "chineseCountingThousand",
        "koreanDigital",
        "koreanCounting",
        "koreanLegal",
        "koreanDigital2",
        "vietnameseCounting",
        "russianLower",
        "russianUpper",
        "none",
        "numberInDash",
        "hebrew1",
        "hebrew2",
        "arabicAlpha",
        "arabicAbjad",
        "hindiVowels",
        "hindiConsonants",
        "hindiNumbers",
        "hindiCounting",
        "thaiLetters",
        "thaiNumbers",
        "thaiCounting",
        "bahtText",
        "dollarText",
        "custom",
    };

    internal static DocumentFormat.OpenXml.Wordprocessing.NumberFormatValues ToOpenXml(this WordNumberFormat value) =>
        new(GetToken(value, WordNumberFormatTokens));

    internal static DocumentFormat.OpenXml.Wordprocessing.NumberFormatValues? ToOpenXml(this WordNumberFormat? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordNumberFormat ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.NumberFormatValues value) =>
        (WordNumberFormat)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordNumberFormatTokens, nameof(WordNumberFormat));

    internal static WordNumberFormat? ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.NumberFormatValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordZoomPresetTokens = {
        "none",
        "fullPage",
        "bestFit",
        "textFit",
    };

    internal static DocumentFormat.OpenXml.Wordprocessing.PresetZoomValues ToOpenXml(this WordZoomPreset value) =>
        new(GetToken(value, WordZoomPresetTokens));

    internal static DocumentFormat.OpenXml.Wordprocessing.PresetZoomValues? ToOpenXml(this WordZoomPreset? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordZoomPreset ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.PresetZoomValues value) =>
        (WordZoomPreset)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordZoomPresetTokens, nameof(WordZoomPreset));

    internal static WordZoomPreset? ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.PresetZoomValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordNoteNumberRestartTokens = {
        "continuous",
        "eachSect",
        "eachPage",
    };

    internal static DocumentFormat.OpenXml.Wordprocessing.RestartNumberValues ToOpenXml(this WordNoteNumberRestart value) =>
        new(GetToken(value, WordNoteNumberRestartTokens));

    internal static DocumentFormat.OpenXml.Wordprocessing.RestartNumberValues? ToOpenXml(this WordNoteNumberRestart? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordNoteNumberRestart ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.RestartNumberValues value) =>
        (WordNoteNumberRestart)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordNoteNumberRestartTokens, nameof(WordNoteNumberRestart));

    internal static WordNoteNumberRestart? ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.RestartNumberValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordShadingPatternTokens = {
        "nil",
        "clear",
        "solid",
        "horzStripe",
        "vertStripe",
        "reverseDiagStripe",
        "diagStripe",
        "horzCross",
        "diagCross",
        "thinHorzStripe",
        "thinVertStripe",
        "thinReverseDiagStripe",
        "thinDiagStripe",
        "thinHorzCross",
        "thinDiagCross",
        "pct5",
        "pct10",
        "pct12",
        "pct15",
        "pct20",
        "pct25",
        "pct30",
        "pct35",
        "pct37",
        "pct40",
        "pct45",
        "pct50",
        "pct55",
        "pct60",
        "pct62",
        "pct65",
        "pct70",
        "pct75",
        "pct80",
        "pct85",
        "pct87",
        "pct90",
        "pct95",
    };

    internal static DocumentFormat.OpenXml.Wordprocessing.ShadingPatternValues ToOpenXml(this WordShadingPattern value) =>
        new(GetToken(value, WordShadingPatternTokens));

    internal static DocumentFormat.OpenXml.Wordprocessing.ShadingPatternValues? ToOpenXml(this WordShadingPattern? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordShadingPattern ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.ShadingPatternValues value) =>
        (WordShadingPattern)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordShadingPatternTokens, nameof(WordShadingPattern));

    internal static WordShadingPattern? ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.ShadingPatternValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordTabLeaderTokens = {
        "none",
        "dot",
        "hyphen",
        "underscore",
        "heavy",
        "middleDot",
    };

    internal static DocumentFormat.OpenXml.Wordprocessing.TabStopLeaderCharValues ToOpenXml(this WordTabLeader value) =>
        new(GetToken(value, WordTabLeaderTokens));

    internal static DocumentFormat.OpenXml.Wordprocessing.TabStopLeaderCharValues? ToOpenXml(this WordTabLeader? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordTabLeader ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.TabStopLeaderCharValues value) =>
        (WordTabLeader)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordTabLeaderTokens, nameof(WordTabLeader));

    internal static WordTabLeader? ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.TabStopLeaderCharValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordTabAlignmentTokens = {
        "clear",
        "left",
        "start",
        "center",
        "right",
        "end",
        "decimal",
        "bar",
        "num",
    };

    internal static DocumentFormat.OpenXml.Wordprocessing.TabStopValues ToOpenXml(this WordTabAlignment value) =>
        new(GetToken(value, WordTabAlignmentTokens));

    internal static DocumentFormat.OpenXml.Wordprocessing.TabStopValues? ToOpenXml(this WordTabAlignment? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordTabAlignment ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.TabStopValues value) =>
        (WordTabAlignment)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordTabAlignmentTokens, nameof(WordTabAlignment));

    internal static WordTabAlignment? ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.TabStopValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordTableOverlapTokens = {
        "never",
        "overlap",
    };

    internal static DocumentFormat.OpenXml.Wordprocessing.TableOverlapValues ToOpenXml(this WordTableOverlap value) =>
        new(GetToken(value, WordTableOverlapTokens));

    internal static DocumentFormat.OpenXml.Wordprocessing.TableOverlapValues? ToOpenXml(this WordTableOverlap? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordTableOverlap ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.TableOverlapValues value) =>
        (WordTableOverlap)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordTableOverlapTokens, nameof(WordTableOverlap));

    internal static WordTableOverlap? ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.TableOverlapValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordTableAlignmentTokens = {
        "left",
        "center",
        "right",
    };

    internal static DocumentFormat.OpenXml.Wordprocessing.TableRowAlignmentValues ToOpenXml(this WordTableAlignment value) =>
        new(GetToken(value, WordTableAlignmentTokens));

    internal static DocumentFormat.OpenXml.Wordprocessing.TableRowAlignmentValues? ToOpenXml(this WordTableAlignment? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordTableAlignment ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.TableRowAlignmentValues value) =>
        (WordTableAlignment)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordTableAlignmentTokens, nameof(WordTableAlignment));

    internal static WordTableAlignment? ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.TableRowAlignmentValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordTableWidthUnitTokens = {
        "nil",
        "pct",
        "dxa",
        "auto",
    };

    internal static DocumentFormat.OpenXml.Wordprocessing.TableWidthUnitValues ToOpenXml(this WordTableWidthUnit value) =>
        new(GetToken(value, WordTableWidthUnitTokens));

    internal static DocumentFormat.OpenXml.Wordprocessing.TableWidthUnitValues? ToOpenXml(this WordTableWidthUnit? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordTableWidthUnit ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.TableWidthUnitValues value) =>
        (WordTableWidthUnit)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordTableWidthUnitTokens, nameof(WordTableWidthUnit));

    internal static WordTableWidthUnit? ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.TableWidthUnitValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordThemeColorTokens = {
        "dark1",
        "light1",
        "dark2",
        "light2",
        "accent1",
        "accent2",
        "accent3",
        "accent4",
        "accent5",
        "accent6",
        "hyperlink",
        "followedHyperlink",
        "none",
        "background1",
        "text1",
        "background2",
        "text2",
    };

    internal static DocumentFormat.OpenXml.Wordprocessing.ThemeColorValues ToOpenXml(this WordThemeColor value) =>
        new(GetToken(value, WordThemeColorTokens));

    internal static DocumentFormat.OpenXml.Wordprocessing.ThemeColorValues? ToOpenXml(this WordThemeColor? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordThemeColor ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.ThemeColorValues value) =>
        (WordThemeColor)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordThemeColorTokens, nameof(WordThemeColor));

    internal static WordThemeColor? ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.ThemeColorValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordTableVerticalPositionAlignmentTokens = {
        "inline",
        "top",
        "center",
        "bottom",
        "inside",
        "outside",
    };

    internal static DocumentFormat.OpenXml.Wordprocessing.VerticalAlignmentValues ToOpenXml(this WordTableVerticalPositionAlignment value) =>
        new(GetToken(value, WordTableVerticalPositionAlignmentTokens));

    internal static DocumentFormat.OpenXml.Wordprocessing.VerticalAlignmentValues? ToOpenXml(this WordTableVerticalPositionAlignment? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordTableVerticalPositionAlignment ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.VerticalAlignmentValues value) =>
        (WordTableVerticalPositionAlignment)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordTableVerticalPositionAlignmentTokens, nameof(WordTableVerticalPositionAlignment));

    internal static WordTableVerticalPositionAlignment? ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.VerticalAlignmentValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordTableVerticalAnchorTokens = {
        "text",
        "margin",
        "page",
    };

    internal static DocumentFormat.OpenXml.Wordprocessing.VerticalAnchorValues ToOpenXml(this WordTableVerticalAnchor value) =>
        new(GetToken(value, WordTableVerticalAnchorTokens));

    internal static DocumentFormat.OpenXml.Wordprocessing.VerticalAnchorValues? ToOpenXml(this WordTableVerticalAnchor? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordTableVerticalAnchor ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.VerticalAnchorValues value) =>
        (WordTableVerticalAnchor)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordTableVerticalAnchorTokens, nameof(WordTableVerticalAnchor));

    internal static WordTableVerticalAnchor? ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.VerticalAnchorValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordVerticalTextPositionTokens = {
        "baseline",
        "superscript",
        "subscript",
    };

    internal static DocumentFormat.OpenXml.Wordprocessing.VerticalPositionValues ToOpenXml(this WordVerticalTextPosition value) =>
        new(GetToken(value, WordVerticalTextPositionTokens));

    internal static DocumentFormat.OpenXml.Wordprocessing.VerticalPositionValues? ToOpenXml(this WordVerticalTextPosition? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordVerticalTextPosition ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.VerticalPositionValues value) =>
        (WordVerticalTextPosition)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordVerticalTextPositionTokens, nameof(WordVerticalTextPosition));

    internal static WordVerticalTextPosition? ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.VerticalPositionValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] WordVerticalCharacterAlignmentTokens = {
        "top",
        "center",
        "baseline",
        "bottom",
        "auto",
    };

    internal static DocumentFormat.OpenXml.Wordprocessing.VerticalTextAlignmentValues ToOpenXml(this WordVerticalCharacterAlignment value) =>
        new(GetToken(value, WordVerticalCharacterAlignmentTokens));

    internal static DocumentFormat.OpenXml.Wordprocessing.VerticalTextAlignmentValues? ToOpenXml(this WordVerticalCharacterAlignment? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static WordVerticalCharacterAlignment ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.VerticalTextAlignmentValues value) =>
        (WordVerticalCharacterAlignment)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, WordVerticalCharacterAlignmentTokens, nameof(WordVerticalCharacterAlignment));

    internal static WordVerticalCharacterAlignment? ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.VerticalTextAlignmentValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] OfficeChartLegendPositionTokens = {
        "b",
        "tr",
        "l",
        "r",
        "t",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.LegendPositionValues ToOpenXml(this OfficeChartLegendPosition value) =>
        new(GetToken(value, OfficeChartLegendPositionTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.LegendPositionValues? ToOpenXml(this OfficeChartLegendPosition? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static OfficeChartLegendPosition ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.LegendPositionValues value) =>
        (OfficeChartLegendPosition)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, OfficeChartLegendPositionTokens, nameof(OfficeChartLegendPosition));

    internal static OfficeChartLegendPosition? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.LegendPositionValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] OfficePresetShapeTypeTokens = {
        "line",
        "lineInv",
        "triangle",
        "rtTriangle",
        "rect",
        "diamond",
        "parallelogram",
        "trapezoid",
        "nonIsoscelesTrapezoid",
        "pentagon",
        "hexagon",
        "heptagon",
        "octagon",
        "decagon",
        "dodecagon",
        "star4",
        "star5",
        "star6",
        "star7",
        "star8",
        "star10",
        "star12",
        "star16",
        "star24",
        "star32",
        "roundRect",
        "round1Rect",
        "round2SameRect",
        "round2DiagRect",
        "snipRoundRect",
        "snip1Rect",
        "snip2SameRect",
        "snip2DiagRect",
        "plaque",
        "ellipse",
        "teardrop",
        "homePlate",
        "chevron",
        "pieWedge",
        "pie",
        "blockArc",
        "donut",
        "noSmoking",
        "rightArrow",
        "leftArrow",
        "upArrow",
        "downArrow",
        "stripedRightArrow",
        "notchedRightArrow",
        "bentUpArrow",
        "leftRightArrow",
        "upDownArrow",
        "leftUpArrow",
        "leftRightUpArrow",
        "quadArrow",
        "leftArrowCallout",
        "rightArrowCallout",
        "upArrowCallout",
        "downArrowCallout",
        "leftRightArrowCallout",
        "upDownArrowCallout",
        "quadArrowCallout",
        "bentArrow",
        "uturnArrow",
        "circularArrow",
        "leftCircularArrow",
        "leftRightCircularArrow",
        "curvedRightArrow",
        "curvedLeftArrow",
        "curvedUpArrow",
        "curvedDownArrow",
        "swooshArrow",
        "cube",
        "can",
        "lightningBolt",
        "heart",
        "sun",
        "moon",
        "smileyFace",
        "irregularSeal1",
        "irregularSeal2",
        "foldedCorner",
        "bevel",
        "frame",
        "halfFrame",
        "corner",
        "diagStripe",
        "chord",
        "arc",
        "leftBracket",
        "rightBracket",
        "leftBrace",
        "rightBrace",
        "bracketPair",
        "bracePair",
        "straightConnector1",
        "bentConnector2",
        "bentConnector3",
        "bentConnector4",
        "bentConnector5",
        "curvedConnector2",
        "curvedConnector3",
        "curvedConnector4",
        "curvedConnector5",
        "callout1",
        "callout2",
        "callout3",
        "accentCallout1",
        "accentCallout2",
        "accentCallout3",
        "borderCallout1",
        "borderCallout2",
        "borderCallout3",
        "accentBorderCallout1",
        "accentBorderCallout2",
        "accentBorderCallout3",
        "wedgeRectCallout",
        "wedgeRoundRectCallout",
        "wedgeEllipseCallout",
        "cloudCallout",
        "cloud",
        "ribbon",
        "ribbon2",
        "ellipseRibbon",
        "ellipseRibbon2",
        "leftRightRibbon",
        "verticalScroll",
        "horizontalScroll",
        "wave",
        "doubleWave",
        "plus",
        "flowChartProcess",
        "flowChartDecision",
        "flowChartInputOutput",
        "flowChartPredefinedProcess",
        "flowChartInternalStorage",
        "flowChartDocument",
        "flowChartMultidocument",
        "flowChartTerminator",
        "flowChartPreparation",
        "flowChartManualInput",
        "flowChartManualOperation",
        "flowChartConnector",
        "flowChartPunchedCard",
        "flowChartPunchedTape",
        "flowChartSummingJunction",
        "flowChartOr",
        "flowChartCollate",
        "flowChartSort",
        "flowChartExtract",
        "flowChartMerge",
        "flowChartOfflineStorage",
        "flowChartOnlineStorage",
        "flowChartMagneticTape",
        "flowChartMagneticDisk",
        "flowChartMagneticDrum",
        "flowChartDisplay",
        "flowChartDelay",
        "flowChartAlternateProcess",
        "flowChartOffpageConnector",
        "actionButtonBlank",
        "actionButtonHome",
        "actionButtonHelp",
        "actionButtonInformation",
        "actionButtonForwardNext",
        "actionButtonBackPrevious",
        "actionButtonEnd",
        "actionButtonBeginning",
        "actionButtonReturn",
        "actionButtonDocument",
        "actionButtonSound",
        "actionButtonMovie",
        "gear6",
        "gear9",
        "funnel",
        "mathPlus",
        "mathMinus",
        "mathMultiply",
        "mathDivide",
        "mathEqual",
        "mathNotEqual",
        "cornerTabs",
        "squareTabs",
        "plaqueTabs",
        "chartX",
        "chartStar",
        "chartPlus",
    };

    internal static DocumentFormat.OpenXml.Drawing.ShapeTypeValues ToOpenXml(this OfficePresetShapeType value) =>
        new(GetToken(value, OfficePresetShapeTypeTokens));

    internal static DocumentFormat.OpenXml.Drawing.ShapeTypeValues? ToOpenXml(this OfficePresetShapeType? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static OfficePresetShapeType ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.ShapeTypeValues value) =>
        (OfficePresetShapeType)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, OfficePresetShapeTypeTokens, nameof(OfficePresetShapeType));

    internal static OfficePresetShapeType? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.ShapeTypeValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] OfficePageOrientationTokens = {
        "portrait",
        "landscape",
    };

    internal static DocumentFormat.OpenXml.Wordprocessing.PageOrientationValues ToOpenXml(this OfficePageOrientation value) =>
        new(GetToken(value, OfficePageOrientationTokens));

    internal static DocumentFormat.OpenXml.Wordprocessing.PageOrientationValues? ToOpenXml(this OfficePageOrientation? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static OfficePageOrientation ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.PageOrientationValues value) =>
        (OfficePageOrientation)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, OfficePageOrientationTokens, nameof(OfficePageOrientation));

    internal static OfficePageOrientation? ToOfficeEnum(this DocumentFormat.OpenXml.Wordprocessing.PageOrientationValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static string GetToken<TEnum>(TEnum value, string[] tokens) where TEnum : struct, Enum {
        int index = Convert.ToInt32(value, CultureInfo.InvariantCulture);
        if ((uint)index >= (uint)tokens.Length) throw new ArgumentOutOfRangeException(nameof(value), value, $"Unsupported {typeof(TEnum).Name} value.");
        return tokens[index];
    }

    private static int FindToken(string token, string[] tokens, string enumName) {
        int index = Array.IndexOf(tokens, token);
        if (index < 0) throw new ArgumentOutOfRangeException(nameof(token), token, $"Unsupported {enumName} token.");
        return index;
    }
}
