"""Generate independently encoded ICC image fixtures and LittleCMS reference pixels.

Run with Pillow (validation only). Profiles and their provenance are maintained in
OfficeIMO.Drawing.Tests/TestAssets/IccColorCorpus. No tool is a runtime requirement.
"""
from pathlib import Path
import csv
import ctypes
from PIL import _imagingcms
from PIL import Image, ImageCms

root = Path(__file__).parent
profiles = root.parents[2] / "OfficeIMO.Drawing.Tests/TestAssets/IccColorCorpus"
# A gray gamma-1.8 profile generated by the same independent color engine.
lib = ctypes.CDLL(_imagingcms.__file__)
class XyY(ctypes.Structure):
    _fields_ = [("x", ctypes.c_double), ("y", ctypes.c_double), ("Y", ctypes.c_double)]
lib.cmsBuildGamma.argtypes = [ctypes.c_void_p, ctypes.c_double]; lib.cmsBuildGamma.restype = ctypes.c_void_p
lib.cmsCreateGrayProfile.argtypes = [ctypes.POINTER(XyY), ctypes.c_void_p]; lib.cmsCreateGrayProfile.restype = ctypes.c_void_p
lib.cmsSaveProfileToMem.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.POINTER(ctypes.c_uint32)]
lib.cmsCloseProfile.argtypes = [ctypes.c_void_p]; lib.cmsFreeToneCurve.argtypes = [ctypes.c_void_p]
curve = lib.cmsBuildGamma(None, 1.8)
handle = lib.cmsCreateGrayProfile(ctypes.byref(XyY(0.3457, 0.3585, 1)), curve)
size = ctypes.c_uint32(); assert lib.cmsSaveProfileToMem(handle, None, ctypes.byref(size))
buffer = ctypes.create_string_buffer(size.value); assert lib.cmsSaveProfileToMem(handle, buffer, ctypes.byref(size))
(root / "gray-gamma18.icc").write_bytes(buffer.raw)
lib.cmsCloseProfile(handle); lib.cmsFreeToneCurve(curve)
rows = []
for mode, sample, profile, formats in [
    ("L", 128, "gray-gamma18.icc", ["png", "jpg", "tif"]),
    ("LA", (128, 128), "gray-gamma18.icc", ["png", "tif"]),
    ("RGB", (128, 64, 32), "icc-dci-p3-matrix.icc", ["png", "jpg", "tif"]),
    ("RGBA", (128, 64, 32, 128), "icc-dci-p3-matrix.icc", ["png", "tif"]),
    ("CMYK", (64, 128, 192, 26), "littlecms-cmyk-lut.icc", ["jpg", "tif"]),
]:
    profile_path = (root if profile.startswith("gray-") else profiles) / profile
    icc = profile_path.read_bytes()
    for extension in formats:
        for embedded in (False, True):
            name = f"{mode}-{extension}-{'embedded' if embedded else 'associated'}.{extension}"
            options = {"icc_profile": icc} if embedded else {}
            if extension == "jpg":
                options.update(quality=100, subsampling=0)
            Image.new(mode, (16, 16), sample).save(root / name, **options)
            decoded = Image.open(root / name)
            base = decoded.convert("RGB") if mode == "RGBA" else decoded.convert("L") if mode == "LA" else decoded
            converted = ImageCms.profileToProfile(base, str(profile_path), ImageCms.createProfile("sRGB"),
                                                 renderingIntent=1, outputMode="RGB", flags=0)
            r, g, b = converted.getpixel((8, 8))
            alpha = sample[-1] if mode in ("RGBA", "LA") else 255
            rows.append((name, profile, r, g, b, alpha))
with (root / "expected.csv").open("w", newline="") as stream:
    writer = csv.writer(stream, lineterminator="\n")
    writer.writerow(("file", "profile", "r", "g", "b", "a"))
    writer.writerows(rows)

# A highly compressed, oversized profile exercises extraction limits before ICC parsing.
oversized = bytearray((root / "gray-gamma18.icc").read_bytes())
oversized.extend(bytes(4 * 1024 * 1024 + 4 - len(oversized)))
oversized[:4] = len(oversized).to_bytes(4, "big")
Image.new("L", (1, 1), 128).save(root / "oversized-profile.png", icc_profile=bytes(oversized))

# Nonuniform EXIF orientation catches geometry loss hidden by uniform swatches.
oriented = Image.new("RGB", (16, 32), (255, 0, 0))
for y in range(16, 32):
    for x in range(16): oriented.putpixel((x, y), (0, 0, 255))
exif = Image.Exif(); exif[274] = 6
for progressive in (False, True):
    for embedded in (False, True):
        options = {"icc_profile": (profiles / "littlecms-rgb-matrix.icc").read_bytes()} if embedded else {}
        oriented.save(root / f"oriented-{progressive}-{embedded}.jpg", quality=100, subsampling=0,
                      progressive=progressive, exif=exif, **options)
