using OfficeIMO.Excel;
using OfficeIMO.Excel.LegacyXls;
using OfficeIMO.Excel.LegacyXls.Model;
using Xunit;

namespace OfficeIMO.Tests {
    public partial class Excel {
        [Fact]
        public void LegacyXls_NativeSave_WritesAdditionalBuiltInFormulaFunctions() {
            string openXmlPath = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString("N") + ".xlsx");
            string xlsOutputPath = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString("N") + ".xls");

            try {
                using (ExcelDocument document = ExcelDocument.Create(openXmlPath)) {
                    ExcelSheet sheet = document.AddWorksheet("MoreFunctions");
                    sheet.CellValue(1, 2, 2d);
                    sheet.CellValue(2, 2, 3d);
                    sheet.CellValue(1, 3, 1d);
                    sheet.CellValue(2, 3, 2d);
                    sheet.CellValue(3, 3, 3d);
                    sheet.CellValue(1, 4, 2d);
                    sheet.CellValue(2, 4, 4d);
                    sheet.CellValue(3, 4, 6d);
                    sheet.CellValue(1, 5, -100d);
                    sheet.CellValue(2, 5, 50d);
                    sheet.CellValue(3, 5, 60d);
                    sheet.CellValue(1, 6, 1d);
                    sheet.CellValue(1, 7, 2d);
                    sheet.CellValue(2, 6, 3d);
                    sheet.CellValue(2, 7, 4d);
                    sheet.CellValue(1, 8, 2d);
                    sheet.CellValue(2, 8, 4d);
                    sheet.CellValue(3, 8, 8d);
                    sheet.CellValue(1, 1, true);
                    sheet.CellFormula(1, 1, "EXACT(\"North\",\"North\")");
                    sheet.CellValue(2, 1, false);
                    sheet.CellFormula(2, 1, "EXACT(\"North\",\"north\")");
                    sheet.CellValue(3, 1, 2.5d);
                    sheet.CellFormula(3, 1, "CEILING(2.1,0.5)");
                    sheet.CellValue(4, 1, -100d);
                    sheet.CellFormula(4, 1, "PMT(0,12,1200)");
                    sheet.CellValue(5, 1, 1200d);
                    sheet.CellFormula(5, 1, "PV(0,12,-100)");
                    sheet.CellValue(6, 1, 1200d);
                    sheet.CellFormula(6, 1, "FV(0,12,-100)");
                    sheet.CellValue(7, 1, 12d);
                    sheet.CellFormula(7, 1, "NPER(0,-100,1200)");
                    sheet.CellValue(8, 1, 13d);
                    sheet.CellFormula(8, 1, "SUMSQ(B1:B2)");
                    sheet.CellValue(9, 1, 0.5d);
                    sheet.CellFormula(9, 1, "DEVSQ(B1:B2)");
                    sheet.CellValue(10, 1, Math.Sqrt(6d));
                    sheet.CellFormula(10, 1, "GEOMEAN(B1:B2)");
                    sheet.CellValue(11, 1, 2.4d);
                    sheet.CellFormula(11, 1, "HARMEAN(B1:B2)");
                    sheet.CellValue(12, 1, 2d);
                    sheet.CellFormula(12, 1, "MODE(1,2,2)");
                    sheet.CellValue(13, 1, 2d / 3d);
                    sheet.CellFormula(13, 1, "AVERAGEA(1,TRUE,FALSE)");
                    sheet.CellValue(14, 1, 0d);
                    sheet.CellFormula(14, 1, "MINA(TRUE,FALSE,5)");
                    sheet.CellValue(15, 1, 5d);
                    sheet.CellFormula(15, 1, "MAXA(TRUE,FALSE,5)");
                    sheet.CellValue(16, 1, 23.45d);
                    sheet.CellFormula(16, 1, "TRUNC(23.459,2)");
                    sheet.CellValue(17, 1, Math.PI);
                    sheet.CellFormula(17, 1, "RADIANS(180)");
                    sheet.CellValue(18, 1, 180d);
                    sheet.CellFormula(18, 1, "DEGREES(PI())");
                    sheet.CellValue(19, 1, 1d);
                    sheet.CellFormula(19, 1, "CORREL(C1:C3,D1:D3)");
                    sheet.CellValue(20, 1, 4d / 3d);
                    sheet.CellFormula(20, 1, "COVAR(C1:C3,D1:D3)");
                    sheet.CellValue(21, 1, 0d);
                    sheet.CellFormula(21, 1, "INTERCEPT(D1:D3,C1:C3)");
                    sheet.CellValue(22, 1, 2d);
                    sheet.CellFormula(22, 1, "SLOPE(D1:D3,C1:C3)");
                    sheet.CellValue(23, 1, 14d);
                    sheet.CellFormula(23, 1, "SUMXMY2(C1:C3,D1:D3)");
                    sheet.CellValue(24, 1, -42d);
                    sheet.CellFormula(24, 1, "SUMX2MY2(C1:C3,D1:D3)");
                    sheet.CellValue(25, 1, 70d);
                    sheet.CellFormula(25, 1, "SUMX2PY2(C1:C3,D1:D3)");
                    sheet.CellValue(26, 1, Math.Sqrt(2d / 3d));
                    sheet.CellFormula(26, 1, "STDEVP(C1:C3)");
                    sheet.CellValue(27, 1, 2d / 3d);
                    sheet.CellFormula(27, 1, "VARP(C1:C3)");
                    sheet.CellValue(28, 1, 0.5d);
                    sheet.CellFormula(28, 1, "CHITEST(C1:C3,D1:D3)");
                    sheet.CellValue(29, 1, 8d);
                    sheet.CellFormula(29, 1, "FORECAST(4,D1:D3,C1:C3)");
                    sheet.CellValue(30, 1, 1d);
                    sheet.CellFormula(30, 1, "FTEST(C1:C3,D1:D3)");
                    sheet.CellValue(31, 1, 1d);
                    sheet.CellFormula(31, 1, "PEARSON(C1:C3,D1:D3)");
                    sheet.CellValue(32, 1, 0d);
                    sheet.CellFormula(32, 1, "STEYX(D1:D3,C1:C3)");
                    sheet.CellValue(33, 1, 1d);
                    sheet.CellFormula(33, 1, "RSQ(C1:C3,D1:D3)");
                    sheet.CellValue(34, 1, 2d);
                    sheet.CellFormula(34, 1, "QUARTILE(C1:C3,2)");
                    sheet.CellValue(35, 1, 2d);
                    sheet.CellFormula(35, 1, "PERCENTILE(C1:C3,0.5)");
                    sheet.CellValue(36, 1, 2d);
                    sheet.CellFormula(36, 1, "RANK(2,C1:C3)");
                    sheet.CellValue(37, 1, 2d);
                    sheet.CellFormula(37, 1, "RANK(2,C1:C3,1)");
                    sheet.CellValue(38, 1, 0d);
                    sheet.CellFormula(38, 1, "KURT(C1:C3,4)");
                    sheet.CellValue(39, 1, 0d);
                    sheet.CellFormula(39, 1, "SKEW(C1:C3)");
                    sheet.CellValue(40, 1, 0.5d);
                    sheet.CellFormula(40, 1, "ZTEST(C1:C3,2)");
                    sheet.CellValue(41, 1, 0.5d);
                    sheet.CellFormula(41, 1, "ZTEST(C1:C3,2,1)");
                    sheet.CellValue(42, 1, 0.5d);
                    sheet.CellFormula(42, 1, "PERCENTRANK(C1:C3,2)");
                    sheet.CellValue(43, 1, 0.5d);
                    sheet.CellFormula(43, 1, "PERCENTRANK(C1:C3,2,3)");
                    sheet.CellValue(44, 1, 2d);
                    sheet.CellFormula(44, 1, "TRIMMEAN(C1:C3,0.2)");
                    sheet.CellValue(45, 1, 2.228d);
                    sheet.CellFormula(45, 1, "TINV(0.05,10)");
                    sheet.CellValue(46, 1, 2d / 3d);
                    sheet.CellFormula(46, 1, "AVEDEV(1,2,3)");
                    sheet.CellValue(47, 1, 0.5d);
                    sheet.CellFormula(47, 1, "BETADIST(0.5,2,2)");
                    sheet.CellValue(48, 1, 0.5d);
                    sheet.CellFormula(48, 1, "BETADIST(0.5,2,2,0,1)");
                    sheet.CellValue(49, 1, 1.791759469228055d);
                    sheet.CellFormula(49, 1, "GAMMALN(4)");
                    sheet.CellValue(50, 1, 0.5d);
                    sheet.CellFormula(50, 1, "BETAINV(0.5,2,2)");
                    sheet.CellValue(51, 1, 0.5d);
                    sheet.CellFormula(51, 1, "BETAINV(0.5,2,2,0,1)");
                    sheet.CellValue(52, 1, 0.6875d);
                    sheet.CellFormula(52, 1, "BINOMDIST(2,4,0.5,1)");
                    sheet.CellValue(53, 1, 0.22313016014843d);
                    sheet.CellFormula(53, 1, "CHIDIST(3,2)");
                    sheet.CellValue(54, 1, 5.99146454710798d);
                    sheet.CellFormula(54, 1, "CHIINV(0.05,2)");
                    sheet.CellValue(55, 1, 10d);
                    sheet.CellFormula(55, 1, "COMBIN(5,2)");
                    sheet.CellValue(56, 1, 0.195996398454005d);
                    sheet.CellFormula(56, 1, "CONFIDENCE(0.05,1,100)");
                    sheet.CellValue(57, 1, 3d);
                    sheet.CellFormula(57, 1, "CRITBINOM(6,0.5,0.5)");
                    sheet.CellValue(58, 1, 4d);
                    sheet.CellFormula(58, 1, "EVEN(3)");
                    sheet.CellValue(59, 1, 0.632120558828558d);
                    sheet.CellFormula(59, 1, "EXPONDIST(1,1,1)");
                    sheet.CellValue(60, 1, 0.5d);
                    sheet.CellFormula(60, 1, "FDIST(1,5,5)");
                    sheet.CellValue(61, 1, 1d);
                    sheet.CellFormula(61, 1, "FINV(0.5,5,5)");
                    sheet.CellValue(62, 1, 0.549306144334055d);
                    sheet.CellFormula(62, 1, "FISHER(0.5)");
                    sheet.CellValue(63, 1, 0.5d);
                    sheet.CellFormula(63, 1, "FISHERINV(0.549306144334055)");
                    sheet.CellValue(64, 1, 0.593994150290162d);
                    sheet.CellFormula(64, 1, "GAMMADIST(2,2,1,1)");
                    sheet.CellValue(65, 1, 1.67834699001666d);
                    sheet.CellFormula(65, 1, "GAMMAINV(0.5,2,1)");
                    sheet.CellValue(66, 1, 0.363261093911249d);
                    sheet.CellFormula(66, 1, "HYPGEOMDIST(1,4,8,20)");
                    sheet.CellValue(67, 1, 0.5d);
                    sheet.CellFormula(67, 1, "LOGNORMDIST(1,0,1)");
                    sheet.CellValue(68, 1, 1d);
                    sheet.CellFormula(68, 1, "LOGINV(0.5,0,1)");
                    sheet.CellValue(69, 1, 0.1875d);
                    sheet.CellFormula(69, 1, "NEGBINOMDIST(2,3,0.5)");
                    sheet.CellValue(70, 1, 0.5d);
                    sheet.CellFormula(70, 1, "NORMDIST(0,0,1,1)");
                    sheet.CellValue(71, 1, 0.5d);
                    sheet.CellFormula(71, 1, "NORMSDIST(0)");
                    sheet.CellValue(72, 1, 0d);
                    sheet.CellFormula(72, 1, "NORMINV(0.5,0,1)");
                    sheet.CellValue(73, 1, 0d);
                    sheet.CellFormula(73, 1, "NORMSINV(0.5)");
                    sheet.CellValue(74, 1, 2d);
                    sheet.CellFormula(74, 1, "STANDARDIZE(2,1,0.5)");
                    sheet.CellValue(75, 1, 3d);
                    sheet.CellFormula(75, 1, "ODD(2)");
                    sheet.CellValue(76, 1, 20d);
                    sheet.CellFormula(76, 1, "PERMUT(5,2)");
                    sheet.CellValue(77, 1, 0.423190081126844d);
                    sheet.CellFormula(77, 1, "POISSON(2,3,1)");
                    sheet.CellValue(78, 1, 0.0733880347707404d);
                    sheet.CellFormula(78, 1, "TDIST(2,10,2)");
                    sheet.CellValue(79, 1, 0.632120558828558d);
                    sheet.CellFormula(79, 1, "WEIBULL(1,2,1,1)");
                    sheet.CellValue(80, 1, 0.05d);
                    sheet.CellFormula(80, 1, "TTEST(C1:C3,D1:D3,2,1)");
                    sheet.CellValue(81, 1, 0.5d);
                    sheet.CellFormula(81, 1, "PROB(C1:C3,D1:D3,2)");
                    sheet.CellValue(82, 1, 0.5d);
                    sheet.CellFormula(82, 1, "PROB(C1:C3,D1:D3,2,3)");
                    sheet.CellValue(83, 1, Math.Sqrt(2d / 3d));
                    sheet.CellFormula(83, 1, "STDEVPA(C1:C3)");
                    sheet.CellValue(84, 1, 2d / 3d);
                    sheet.CellFormula(84, 1, "VARPA(C1:C3)");
                    sheet.CellValue(85, 1, 1d);
                    sheet.CellFormula(85, 1, "STDEVA(C1:C3)");
                    sheet.CellValue(86, 1, 1d);
                    sheet.CellFormula(86, 1, "VARA(C1:C3)");
                    sheet.CellValue(87, 1, 2d);
                    sheet.CellFormula(87, 1, "DCOUNT(C1:D3,2,C1:C2)");
                    sheet.CellValue(88, 1, 12d);
                    sheet.CellFormula(88, 1, "DSUM(C1:D3,2,C1:C2)");
                    sheet.CellValue(89, 1, 4d);
                    sheet.CellFormula(89, 1, "DAVERAGE(C1:D3,2,C1:C2)");
                    sheet.CellValue(90, 1, 2d);
                    sheet.CellFormula(90, 1, "DMIN(C1:D3,2,C1:C2)");
                    sheet.CellValue(91, 1, 6d);
                    sheet.CellFormula(91, 1, "DMAX(C1:D3,2,C1:C2)");
                    sheet.CellValue(92, 1, 2d);
                    sheet.CellFormula(92, 1, "DSTDEV(C1:D3,2,C1:C2)");
                    sheet.CellValue(93, 1, 4d);
                    sheet.CellFormula(93, 1, "DVAR(C1:D3,2,C1:C2)");
                    sheet.CellValue(94, 1, 48d);
                    sheet.CellFormula(94, 1, "DPRODUCT(C1:D3,2,C1:C2)");
                    sheet.CellValue(95, 1, Math.Sqrt(8d / 3d));
                    sheet.CellFormula(95, 1, "DSTDEVP(C1:D3,2,C1:C2)");
                    sheet.CellValue(96, 1, 8d / 3d);
                    sheet.CellFormula(96, 1, "DVARP(C1:D3,2,C1:C2)");
                    sheet.CellValue(97, 1, 3d);
                    sheet.CellFormula(97, 1, "DCOUNTA(C1:D3,2,C1:C2)");
                    sheet.CellValue(98, 1, 4d);
                    sheet.CellFormula(98, 1, "DGET(C1:D3,2,C1:C2)");
                    sheet.CellValue(99, 1, "$1.23");
                    sheet.CellFormula(99, 1, "USDOLLAR(1.23,2)");
                    sheet.CellValue(100, 1, 3d);
                    sheet.CellFormula(100, 1, "FINDB(\"ph\",\"Alpha\")");
                    sheet.CellValue(101, 1, 3d);
                    sheet.CellFormula(101, 1, "SEARCHB(\"ph\",\"Alpha\")");
                    sheet.CellValue(102, 1, "AlZZa");
                    sheet.CellFormula(102, 1, "REPLACEB(\"Alpha\",3,2,\"ZZ\")");
                    sheet.CellValue(103, 1, "Al");
                    sheet.CellFormula(103, 1, "LEFTB(\"Alpha\",2)");
                    sheet.CellValue(104, 1, "ha");
                    sheet.CellFormula(104, 1, "RIGHTB(\"Alpha\",2)");
                    sheet.CellValue(105, 1, "lph");
                    sheet.CellFormula(105, 1, "MIDB(\"Alpha\",2,3)");
                    sheet.CellValue(106, 1, 5d);
                    sheet.CellFormula(106, 1, "LENB(\"Alpha\")");
                    sheet.CellValue(107, 1, "Alpha");
                    sheet.CellFormula(107, 1, "ASC(\"Alpha\")");
                    sheet.CellValue(108, 1, "Alpha");
                    sheet.CellFormula(108, 1, "DBCS(\"Alpha\")");
                    sheet.CellValue(109, 1, 1d);
                    sheet.CellFormula(109, 1, "DATEDIF(\"2020-01-01\",\"2021-01-01\",\"Y\")");
                    sheet.CellValue(110, 1, "2026/1/2");
                    sheet.CellFormula(110, 1, "DATESTRING(46024)");
                    sheet.CellValue(111, 1, "123");
                    sheet.CellFormula(111, 1, "NUMBERSTRING(123,1)");
                    sheet.CellValue(112, 1, "IV");
                    sheet.CellFormula(112, 1, "ROMAN(4)");
                    sheet.CellValue(113, 1, "IV");
                    sheet.CellFormula(113, 1, "ROMAN(4,0)");
                    sheet.CellValue(114, 1, 1d);
                    sheet.CellFormula(114, 1, "AREAS(C1:D3)");
                    sheet.CellValue(115, 1, Math.Asin(0.5d));
                    sheet.CellFormula(115, 1, "ASIN(0.5)");
                    sheet.CellValue(116, 1, Math.Acos(0.5d));
                    sheet.CellFormula(116, 1, "ACOS(0.5)");
                    sheet.CellValue(117, 1, Math.PI / 4d);
                    sheet.CellFormula(117, 1, "ATAN2(1,1)");
                    sheet.CellValue(118, 1, "$1.23");
                    sheet.CellFormula(118, 1, "DOLLAR(1.23,2)");
                    sheet.CellValue(119, 1, "1234.57");
                    sheet.CellFormula(119, 1, "FIXED(1234.567,2,TRUE)");
                    sheet.CellValue(120, 1, 4d);
                    sheet.CellFormula(120, 1, "LOOKUP(2,C1:C3,D1:D3)");
                    sheet.CellValue(121, 1, 0.5d);
                    sheet.CellFormula(121, 1, "TIMEVALUE(\"12:00\")");
                    sheet.CellValue(122, 1, 30d);
                    sheet.CellFormula(122, 1, "DAYS360(DATE(2020,1,1),DATE(2020,2,1))");
                    sheet.CellValue(123, 1, 30d);
                    sheet.CellFormula(123, 1, "DAYS360(DATE(2020,1,1),DATE(2020,2,1),TRUE)");
                    sheet.CellValue(124, 1, 3d);
                    sheet.CellFormula(124, 1, "LOG(8,2)");
                    sheet.CellValue(125, 1, 2d);
                    sheet.CellFormula(125, 1, "LOG(100)");
                    sheet.CellValue(126, 1, "A");
                    sheet.CellFormula(126, 1, "CHAR(65)");
                    sheet.CellValue(127, 1, 65d);
                    sheet.CellFormula(127, 1, "CODE(\"A\")");
                    sheet.CellValue(128, 1, 2d);
                    sheet.CellFormula(128, 1, "TYPE(\"Alpha\")");
                    sheet.CellValue(129, 1, "Alpha");
                    sheet.CellFormula(129, 1, "T(\"Alpha\")");
                    sheet.CellValue(130, 1, 1d);
                    sheet.CellFormula(130, 1, "N(TRUE)");
                    sheet.CellValue(131, 1, "AB");
                    sheet.CellFormula(131, 1, "CLEAN(\"A\"&CHAR(10)&\"B\")");
                    sheet.CellValue(132, 1, 120d);
                    sheet.CellFormula(132, 1, "FACT(5)");
                    sheet.CellValue(133, 1, Math.Sinh(1d));
                    sheet.CellFormula(133, 1, "SINH(1)");
                    sheet.CellValue(134, 1, Math.Cosh(1d));
                    sheet.CellFormula(134, 1, "COSH(1)");
                    sheet.CellValue(135, 1, Math.Tanh(1d));
                    sheet.CellFormula(135, 1, "TANH(1)");
                    sheet.CellValue(136, 1, Math.Log(1d + Math.Sqrt(2d)));
                    sheet.CellFormula(136, 1, "ASINH(1)");
                    sheet.CellValue(137, 1, Math.Log(2d + Math.Sqrt(3d)));
                    sheet.CellFormula(137, 1, "ACOSH(2)");
                    sheet.CellValue(138, 1, 0.5d * Math.Log(3d));
                    sheet.CellFormula(138, 1, "ATANH(0.5)");
                    sheet.CellValue(139, 1, 0d);
                    sheet.CellFormula(139, 1, "RATE(12,-100,1200)");
                    sheet.CellValue(140, 1, 0.05d);
                    sheet.CellFormula(140, 1, "MIRR(E1:E3,0.1,0.12)");
                    sheet.CellValue(141, 1, 0.05d);
                    sheet.CellFormula(141, 1, "IRR(E1:E3)");
                    sheet.CellValue(142, 1, 180d);
                    sheet.CellFormula(142, 1, "SLN(1000,100,5)");
                    sheet.CellValue(143, 1, 300d);
                    sheet.CellFormula(143, 1, "SYD(1000,100,5,1)");
                    sheet.CellValue(144, 1, 400d);
                    sheet.CellFormula(144, 1, "DDB(1000,100,5,1)");
                    sheet.CellValue(145, 1, 0d);
                    sheet.CellFormula(145, 1, "IPMT(0,1,12,1200)");
                    sheet.CellValue(146, 1, -100d);
                    sheet.CellFormula(146, 1, "PPMT(0,1,12,1200)");
                    sheet.CellValue(147, 1, 400d);
                    sheet.CellFormula(147, 1, "VDB(1000,100,5,0,1)");
                    sheet.CellValue(148, 1, 369d);
                    sheet.CellFormula(148, 1, "DB(1000,100,5,1)");
                    sheet.CellValue(149, 1, 0d);
                    sheet.CellFormula(149, 1, "ISPMT(0,1,12,1200)");
                    sheet.CellValue(150, 1, "$A$1");
                    sheet.CellFormula(150, 1, "ADDRESS(1,1)");
                    sheet.CellValue(151, 1, 2d);
                    sheet.CellFormula(151, 1, "INDIRECT(\"B1\")");
                    sheet.CellValue(152, 1, "Example");
                    sheet.CellFormula(152, 1, "HYPERLINK(\"https://example.com\",\"Example\")");
                    sheet.CellValue(153, 1, -2d);
                    sheet.CellFormula(153, 1, "MDETERM(F1:G2)");
                    sheet.CellValue(154, 1, 7d);
                    sheet.CellFormula(154, 1, "ERROR.TYPE(NA())");
                    sheet.CellValue(155, 1, 2d);
                    sheet.CellFormula(155, 1, "LINEST(D1:D3,C1:C3)");
                    sheet.CellValue(156, 1, 8d);
                    sheet.CellFormula(156, 1, "TREND(D1:D3,C1:C3,4)");
                    sheet.CellValue(157, 1, 2d);
                    sheet.CellFormula(157, 1, "LOGEST(H1:H3,C1:C3)");
                    sheet.CellValue(158, 1, 16d);
                    sheet.CellFormula(158, 1, "GROWTH(H1:H3,C1:C3,4)");
                    sheet.CellValue(159, 1, -2d);
                    sheet.CellFormula(159, 1, "MINVERSE(F1:G2)");
                    sheet.CellValue(160, 1, 7d);
                    sheet.CellFormula(160, 1, "MMULT(F1:G1,F1:F2)");
                    sheet.CellValue(161, 1, 1d);
                    sheet.CellFormula(161, 1, "TRANSPOSE(F1:G2)");
                    sheet.CellValue(162, 1, "$A$1");
                    sheet.CellFormula(162, 1, "CELL(\"address\",A1)");
                    sheet.CellValue(163, 1, "Windows");
                    sheet.CellFormula(163, 1, "INFO(\"osversion\")");
                    sheet.CellValue(164, 1, 1d);
                    sheet.CellFormula(164, 1, "FREQUENCY(C1:C3,C1:C3)");
                    sheet.CellValue(165, 1, false);
                    sheet.CellFormula(165, 1, "AND(TRUE,TRUE,FALSE)");
                    sheet.CellValue(166, 1, true);
                    sheet.CellFormula(166, 1, "OR(FALSE,FALSE,TRUE)");
                    sheet.CellValue(167, 1, 42d);
                    sheet.CellFormula(167, 1, "GETPIVOTDATA(\"Sales\",A1,\"Region\",\"North\")");
                    sheet.CellValue(168, 1, "North");
                    sheet.CellFormula(168, 1, "PHONETIC(A1)");
                    sheet.CellValue(169, 1, "baht");
                    sheet.CellFormula(169, 1, "BAHTTEXT(123)");
                    sheet.CellValue(170, 1, "weekday");
                    sheet.CellFormula(170, 1, "THAIDAYOFWEEK(1)");
                    sheet.CellValue(171, 1, "digit");
                    sheet.CellFormula(171, 1, "THAIDIGIT(1)");
                    sheet.CellValue(172, 1, "month");
                    sheet.CellFormula(172, 1, "THAIMONTHOFYEAR(1)");
                    sheet.CellValue(173, 1, "sound");
                    sheet.CellFormula(173, 1, "THAINUMSOUND(123)");
                    sheet.CellValue(174, 1, "number");
                    sheet.CellFormula(174, 1, "THAINUMSTRING(123)");
                    sheet.CellValue(175, 1, 5d);
                    sheet.CellFormula(175, 1, "THAISTRINGLENGTH(\"Alpha\")");
                    sheet.CellValue(176, 1, false);
                    sheet.CellFormula(176, 1, "ISTHAIDIGIT(\"1\")");
                    sheet.CellValue(177, 1, 120d);
                    sheet.CellFormula(177, 1, "ROUNDBAHTDOWN(123.45)");
                    sheet.CellValue(178, 1, 130d);
                    sheet.CellFormula(178, 1, "ROUNDBAHTUP(123.45)");
                    sheet.CellValue(179, 1, 2569d);
                    sheet.CellFormula(179, 1, "THAIYEAR(DATE(2026,1,1))");
                    sheet.CellValue(180, 1, "snapshot");
                    sheet.CellFormula(180, 1, "RTD(\"ProgId\",\"Server\",\"Topic\")");
                    sheet.CellValue(181, 1, "Scenario");
                    sheet.CellFormula(181, 1, "SCENARIO.GET(1)");
                    sheet.CellValue(182, 1, "Option");
                    sheet.CellFormula(182, 1, "OPTIONS.LISTS.GET(1)");
                    sheet.CellValue(183, 1, false);
                    sheet.CellFormula(183, 1, "OPEN.DIALOG()");
                    sheet.CellValue(184, 1, false);
                    sheet.CellFormula(184, 1, "SAVE.DIALOG(\"*.xls\")");
                    sheet.CellValue(185, 1, "View");
                    sheet.CellFormula(185, 1, "VIEW.GET(1)");
                    sheet.CellValue(186, 1, "CellInfo");
                    sheet.CellFormula(186, 1, "GET.CELL(1,A1)");
                    sheet.CellValue(187, 1, "Workspace");
                    sheet.CellFormula(187, 1, "GET.WORKSPACE(1)");
                    sheet.CellValue(188, 1, "Window");
                    sheet.CellFormula(188, 1, "GET.WINDOW(1)");
                    sheet.CellValue(189, 1, "Document");
                    sheet.CellFormula(189, 1, "GET.DOCUMENT(1)");
                    sheet.CellValue(190, 1, "Note");
                    sheet.CellFormula(190, 1, "GET.NOTE()");
                    sheet.CellValue(191, 1, "Workbook");
                    sheet.CellFormula(191, 1, "GET.WORKBOOK(1)");
                    sheet.CellValue(192, 1, "Links");
                    sheet.CellFormula(192, 1, "LINKS()");
                    sheet.CellValue(193, 1, "FormulaText");
                    sheet.CellFormula(193, 1, "GET.FORMULA(A1)");
                    sheet.CellValue(194, 1, "NameInfo");
                    sheet.CellFormula(194, 1, "GET.NAME(\"Print_Area\")");
                    sheet.CellValue(195, 1, "Names");
                    sheet.CellFormula(195, 1, "NAMES()");
                    sheet.CellValue(196, 1, "Directory");
                    sheet.CellFormula(196, 1, "DIRECTORY()");
                    sheet.CellValue(197, 1, "Files");
                    sheet.CellFormula(197, 1, "FILES()");
                    sheet.CellValue(198, 1, "Bar");
                    sheet.CellFormula(198, 1, "GET.BAR(1)");
                    sheet.CellValue(199, 1, "LinkInfo");
                    sheet.CellFormula(199, 1, "GET.LINK.INFO(\"Book.xls\",\"Sheet1\",1)");
                    sheet.CellValue(200, 1, "Toolbar");
                    sheet.CellFormula(200, 1, "GET.TOOLBAR(1)");
                    sheet.CellValue(201, 1, "Tool");
                    sheet.CellFormula(201, 1, "GET.TOOL(1)");
                    sheet.CellValue(202, 1, "AbsRef");
                    sheet.CellFormula(202, 1, "ABSREF(1,A1)");
                    sheet.CellValue(203, 1, "RelRef");
                    sheet.CellFormula(203, 1, "RELREF(A1,B1)");
                    sheet.CellValue(204, 1, "Argument");
                    sheet.CellFormula(204, 1, "ARGUMENT()");
                    sheet.CellValue(205, 1, "Caller");
                    sheet.CellFormula(205, 1, "CALLER()");
                    sheet.CellValue(206, 1, "Deref");
                    sheet.CellFormula(206, 1, "DEREF(A1)");
                    sheet.CellValue(207, 1, "Windows");
                    sheet.CellFormula(207, 1, "WINDOWS()");
                    sheet.CellValue(208, 1, "Documents");
                    sheet.CellFormula(208, 1, "DOCUMENTS()");
                    sheet.CellValue(209, 1, "Active");
                    sheet.CellFormula(209, 1, "ACTIVE.CELL()");
                    sheet.CellValue(210, 1, "Selection");
                    sheet.CellFormula(210, 1, "SELECTION()");
                    sheet.CellValue(211, 1, "Result");
                    sheet.CellFormula(211, 1, "RESULT()");
                    sheet.CellValue(212, 1, "Definition");
                    sheet.CellFormula(212, 1, "GET.DEF(\"Print_Area\")");
                    sheet.CellValue(213, 1, "RefText");
                    sheet.CellFormula(213, 1, "REFTEXT(A1)");
                    sheet.CellValue(214, 1, "TextRef");
                    sheet.CellFormula(214, 1, "TEXTREF(\"A1\")");

                    document.Save(xlsOutputPath);
                }

                using LegacyXlsLoadResult result = ExcelDocument.LoadLegacyXlsWithReport(xlsOutputPath);
                result.EnsureNoImportErrors();
                Assert.False(result.HasUnsupportedFeatures, FormatUnsupportedFeatures(result.UnsupportedFeatures));

                LegacyXlsWorksheet worksheet = Assert.Single(result.Workbook.Worksheets);
                AssertBooleanFormula(worksheet, 1, expectedValue: true, "EXACT(\"North\",\"North\")");
                AssertBooleanFormula(worksheet, 2, expectedValue: false, "EXACT(\"North\",\"north\")");
                AssertNumericFormula(worksheet, 3, 2.5d, "CEILING(2.1,0.5)");
                AssertNumericFormula(worksheet, 4, -100d, "PMT(0,12,1200)");
                AssertNumericFormula(worksheet, 5, 1200d, "PV(0,12,-100)");
                AssertNumericFormula(worksheet, 6, 1200d, "FV(0,12,-100)");
                AssertNumericFormula(worksheet, 7, 12d, "NPER(0,-100,1200)");
                AssertNumericFormula(worksheet, 8, 13d, "SUMSQ(B1:B2)");
                AssertNumericFormula(worksheet, 9, 0.5d, "DEVSQ(B1:B2)");
                AssertNumericFormula(worksheet, 10, Math.Sqrt(6d), "GEOMEAN(B1:B2)", precision: 12);
                AssertNumericFormula(worksheet, 11, 2.4d, "HARMEAN(B1:B2)");
                AssertNumericFormula(worksheet, 12, 2d, "MODE(1,2,2)");
                AssertNumericFormula(worksheet, 13, 2d / 3d, "AVERAGEA(1,TRUE,FALSE)", precision: 12);
                AssertNumericFormula(worksheet, 14, 0d, "MINA(TRUE,FALSE,5)");
                AssertNumericFormula(worksheet, 15, 5d, "MAXA(TRUE,FALSE,5)");
                AssertNumericFormula(worksheet, 16, 23.45d, "TRUNC(23.459,2)");
                AssertNumericFormula(worksheet, 17, Math.PI, "RADIANS(180)", precision: 12);
                AssertNumericFormula(worksheet, 18, 180d, "DEGREES(PI())");
                AssertNumericFormula(worksheet, 19, 1d, "CORREL(C1:C3,D1:D3)");
                AssertNumericFormula(worksheet, 20, 4d / 3d, "COVAR(C1:C3,D1:D3)", precision: 12);
                AssertNumericFormula(worksheet, 21, 0d, "INTERCEPT(D1:D3,C1:C3)");
                AssertNumericFormula(worksheet, 22, 2d, "SLOPE(D1:D3,C1:C3)");
                AssertNumericFormula(worksheet, 23, 14d, "SUMXMY2(C1:C3,D1:D3)");
                AssertNumericFormula(worksheet, 24, -42d, "SUMX2MY2(C1:C3,D1:D3)");
                AssertNumericFormula(worksheet, 25, 70d, "SUMX2PY2(C1:C3,D1:D3)");
                AssertNumericFormula(worksheet, 26, Math.Sqrt(2d / 3d), "STDEVP(C1:C3)", precision: 12);
                AssertNumericFormula(worksheet, 27, 2d / 3d, "VARP(C1:C3)", precision: 12);
                AssertNumericFormula(worksheet, 28, 0.5d, "CHITEST(C1:C3,D1:D3)");
                AssertNumericFormula(worksheet, 29, 8d, "FORECAST(4,D1:D3,C1:C3)");
                AssertNumericFormula(worksheet, 30, 1d, "FTEST(C1:C3,D1:D3)");
                AssertNumericFormula(worksheet, 31, 1d, "PEARSON(C1:C3,D1:D3)");
                AssertNumericFormula(worksheet, 32, 0d, "STEYX(D1:D3,C1:C3)");
                AssertNumericFormula(worksheet, 33, 1d, "RSQ(C1:C3,D1:D3)");
                AssertNumericFormula(worksheet, 34, 2d, "QUARTILE(C1:C3,2)");
                AssertNumericFormula(worksheet, 35, 2d, "PERCENTILE(C1:C3,0.5)");
                AssertNumericFormula(worksheet, 36, 2d, "RANK(2,C1:C3)");
                AssertNumericFormula(worksheet, 37, 2d, "RANK(2,C1:C3,1)");
                AssertNumericFormula(worksheet, 38, 0d, "KURT(C1:C3,4)");
                AssertNumericFormula(worksheet, 39, 0d, "SKEW(C1:C3)");
                AssertNumericFormula(worksheet, 40, 0.5d, "ZTEST(C1:C3,2)");
                AssertNumericFormula(worksheet, 41, 0.5d, "ZTEST(C1:C3,2,1)");
                AssertNumericFormula(worksheet, 42, 0.5d, "PERCENTRANK(C1:C3,2)");
                AssertNumericFormula(worksheet, 43, 0.5d, "PERCENTRANK(C1:C3,2,3)");
                AssertNumericFormula(worksheet, 44, 2d, "TRIMMEAN(C1:C3,0.2)");
                AssertNumericFormula(worksheet, 45, 2.228d, "TINV(0.05,10)");
                AssertNumericFormula(worksheet, 46, 2d / 3d, "AVEDEV(1,2,3)", precision: 12);
                AssertNumericFormula(worksheet, 47, 0.5d, "BETADIST(0.5,2,2)");
                AssertNumericFormula(worksheet, 48, 0.5d, "BETADIST(0.5,2,2,0,1)");
                AssertNumericFormula(worksheet, 49, 1.791759469228055d, "GAMMALN(4)", precision: 12);
                AssertNumericFormula(worksheet, 50, 0.5d, "BETAINV(0.5,2,2)");
                AssertNumericFormula(worksheet, 51, 0.5d, "BETAINV(0.5,2,2,0,1)");
                AssertNumericFormula(worksheet, 52, 0.6875d, "BINOMDIST(2,4,0.5,1)");
                AssertNumericFormula(worksheet, 53, 0.22313016014843d, "CHIDIST(3,2)", precision: 12);
                AssertNumericFormula(worksheet, 54, 5.99146454710798d, "CHIINV(0.05,2)", precision: 12);
                AssertNumericFormula(worksheet, 55, 10d, "COMBIN(5,2)");
                AssertNumericFormula(worksheet, 56, 0.195996398454005d, "CONFIDENCE(0.05,1,100)", precision: 12);
                AssertNumericFormula(worksheet, 57, 3d, "CRITBINOM(6,0.5,0.5)");
                AssertNumericFormula(worksheet, 58, 4d, "EVEN(3)");
                AssertNumericFormula(worksheet, 59, 0.632120558828558d, "EXPONDIST(1,1,1)", precision: 12);
                AssertNumericFormula(worksheet, 60, 0.5d, "FDIST(1,5,5)");
                AssertNumericFormula(worksheet, 61, 1d, "FINV(0.5,5,5)");
                AssertNumericFormula(worksheet, 62, 0.549306144334055d, "FISHER(0.5)", precision: 12);
                AssertNumericFormula(worksheet, 63, 0.5d, "FISHERINV(0.549306144334055)");
                AssertNumericFormula(worksheet, 64, 0.593994150290162d, "GAMMADIST(2,2,1,1)", precision: 12);
                AssertNumericFormula(worksheet, 65, 1.67834699001666d, "GAMMAINV(0.5,2,1)", precision: 12);
                AssertNumericFormula(worksheet, 66, 0.363261093911249d, "HYPGEOMDIST(1,4,8,20)", precision: 12);
                AssertNumericFormula(worksheet, 67, 0.5d, "LOGNORMDIST(1,0,1)");
                AssertNumericFormula(worksheet, 68, 1d, "LOGINV(0.5,0,1)");
                AssertNumericFormula(worksheet, 69, 0.1875d, "NEGBINOMDIST(2,3,0.5)");
                AssertNumericFormula(worksheet, 70, 0.5d, "NORMDIST(0,0,1,1)");
                AssertNumericFormula(worksheet, 71, 0.5d, "NORMSDIST(0)");
                AssertNumericFormula(worksheet, 72, 0d, "NORMINV(0.5,0,1)");
                AssertNumericFormula(worksheet, 73, 0d, "NORMSINV(0.5)");
                AssertNumericFormula(worksheet, 74, 2d, "STANDARDIZE(2,1,0.5)");
                AssertNumericFormula(worksheet, 75, 3d, "ODD(2)");
                AssertNumericFormula(worksheet, 76, 20d, "PERMUT(5,2)");
                AssertNumericFormula(worksheet, 77, 0.423190081126844d, "POISSON(2,3,1)", precision: 12);
                AssertNumericFormula(worksheet, 78, 0.0733880347707404d, "TDIST(2,10,2)", precision: 12);
                AssertNumericFormula(worksheet, 79, 0.632120558828558d, "WEIBULL(1,2,1,1)", precision: 12);
                AssertNumericFormula(worksheet, 80, 0.05d, "TTEST(C1:C3,D1:D3,2,1)");
                AssertNumericFormula(worksheet, 81, 0.5d, "PROB(C1:C3,D1:D3,2)");
                AssertNumericFormula(worksheet, 82, 0.5d, "PROB(C1:C3,D1:D3,2,3)");
                AssertNumericFormula(worksheet, 83, Math.Sqrt(2d / 3d), "STDEVPA(C1:C3)", precision: 12);
                AssertNumericFormula(worksheet, 84, 2d / 3d, "VARPA(C1:C3)", precision: 12);
                AssertNumericFormula(worksheet, 85, 1d, "STDEVA(C1:C3)");
                AssertNumericFormula(worksheet, 86, 1d, "VARA(C1:C3)");
                AssertNumericFormula(worksheet, 87, 2d, "DCOUNT(C1:D3,2,C1:C2)");
                AssertNumericFormula(worksheet, 88, 12d, "DSUM(C1:D3,2,C1:C2)");
                AssertNumericFormula(worksheet, 89, 4d, "DAVERAGE(C1:D3,2,C1:C2)");
                AssertNumericFormula(worksheet, 90, 2d, "DMIN(C1:D3,2,C1:C2)");
                AssertNumericFormula(worksheet, 91, 6d, "DMAX(C1:D3,2,C1:C2)");
                AssertNumericFormula(worksheet, 92, 2d, "DSTDEV(C1:D3,2,C1:C2)");
                AssertNumericFormula(worksheet, 93, 4d, "DVAR(C1:D3,2,C1:C2)");
                AssertNumericFormula(worksheet, 94, 48d, "DPRODUCT(C1:D3,2,C1:C2)");
                AssertNumericFormula(worksheet, 95, Math.Sqrt(8d / 3d), "DSTDEVP(C1:D3,2,C1:C2)", precision: 12);
                AssertNumericFormula(worksheet, 96, 8d / 3d, "DVARP(C1:D3,2,C1:C2)", precision: 12);
                AssertNumericFormula(worksheet, 97, 3d, "DCOUNTA(C1:D3,2,C1:C2)");
                AssertNumericFormula(worksheet, 98, 4d, "DGET(C1:D3,2,C1:C2)");
                AssertTextFormula(worksheet, 99, "$1.23", "USDOLLAR(1.23,2)");
                AssertNumericFormula(worksheet, 100, 3d, "FINDB(\"ph\",\"Alpha\")");
                AssertNumericFormula(worksheet, 101, 3d, "SEARCHB(\"ph\",\"Alpha\")");
                AssertTextFormula(worksheet, 102, "AlZZa", "REPLACEB(\"Alpha\",3,2,\"ZZ\")");
                AssertTextFormula(worksheet, 103, "Al", "LEFTB(\"Alpha\",2)");
                AssertTextFormula(worksheet, 104, "ha", "RIGHTB(\"Alpha\",2)");
                AssertTextFormula(worksheet, 105, "lph", "MIDB(\"Alpha\",2,3)");
                AssertNumericFormula(worksheet, 106, 5d, "LENB(\"Alpha\")");
                AssertTextFormula(worksheet, 107, "Alpha", "ASC(\"Alpha\")");
                AssertTextFormula(worksheet, 108, "Alpha", "DBCS(\"Alpha\")");
                AssertNumericFormula(worksheet, 109, 1d, "DATEDIF(\"2020-01-01\",\"2021-01-01\",\"Y\")");
                AssertTextFormula(worksheet, 110, "2026/1/2", "DATESTRING(46024)");
                AssertTextFormula(worksheet, 111, "123", "NUMBERSTRING(123,1)");
                AssertTextFormula(worksheet, 112, "IV", "ROMAN(4)");
                AssertTextFormula(worksheet, 113, "IV", "ROMAN(4,0)");
                AssertNumericFormula(worksheet, 114, 1d, "AREAS(C1:D3)");
                AssertNumericFormula(worksheet, 115, Math.Asin(0.5d), "ASIN(0.5)", precision: 12);
                AssertNumericFormula(worksheet, 116, Math.Acos(0.5d), "ACOS(0.5)", precision: 12);
                AssertNumericFormula(worksheet, 117, Math.PI / 4d, "ATAN2(1,1)", precision: 12);
                AssertTextFormula(worksheet, 118, "$1.23", "DOLLAR(1.23,2)");
                AssertTextFormula(worksheet, 119, "1234.57", "FIXED(1234.567,2,TRUE)");
                AssertNumericFormula(worksheet, 120, 4d, "LOOKUP(2,C1:C3,D1:D3)");
                AssertNumericFormula(worksheet, 121, 0.5d, "TIMEVALUE(\"12:00\")");
                AssertNumericFormula(worksheet, 122, 30d, "DAYS360(DATE(2020,1,1),DATE(2020,2,1))");
                AssertNumericFormula(worksheet, 123, 30d, "DAYS360(DATE(2020,1,1),DATE(2020,2,1),TRUE)");
                AssertNumericFormula(worksheet, 124, 3d, "LOG(8,2)");
                AssertNumericFormula(worksheet, 125, 2d, "LOG(100)");
                AssertTextFormula(worksheet, 126, "A", "CHAR(65)");
                AssertNumericFormula(worksheet, 127, 65d, "CODE(\"A\")");
                AssertNumericFormula(worksheet, 128, 2d, "TYPE(\"Alpha\")");
                AssertTextFormula(worksheet, 129, "Alpha", "T(\"Alpha\")");
                AssertNumericFormula(worksheet, 130, 1d, "N(TRUE)");
                AssertTextFormula(worksheet, 131, "AB", "CLEAN(\"A\"&CHAR(10)&\"B\")");
                AssertNumericFormula(worksheet, 132, 120d, "FACT(5)");
                AssertNumericFormula(worksheet, 133, Math.Sinh(1d), "SINH(1)", precision: 12);
                AssertNumericFormula(worksheet, 134, Math.Cosh(1d), "COSH(1)", precision: 12);
                AssertNumericFormula(worksheet, 135, Math.Tanh(1d), "TANH(1)", precision: 12);
                AssertNumericFormula(worksheet, 136, Math.Log(1d + Math.Sqrt(2d)), "ASINH(1)", precision: 12);
                AssertNumericFormula(worksheet, 137, Math.Log(2d + Math.Sqrt(3d)), "ACOSH(2)", precision: 12);
                AssertNumericFormula(worksheet, 138, 0.5d * Math.Log(3d), "ATANH(0.5)", precision: 12);
                AssertNumericFormula(worksheet, 139, 0d, "RATE(12,-100,1200)");
                AssertNumericFormula(worksheet, 140, 0.05d, "MIRR(E1:E3,0.1,0.12)");
                AssertNumericFormula(worksheet, 141, 0.05d, "IRR(E1:E3)");
                AssertNumericFormula(worksheet, 142, 180d, "SLN(1000,100,5)");
                AssertNumericFormula(worksheet, 143, 300d, "SYD(1000,100,5,1)");
                AssertNumericFormula(worksheet, 144, 400d, "DDB(1000,100,5,1)");
                AssertNumericFormula(worksheet, 145, 0d, "IPMT(0,1,12,1200)");
                AssertNumericFormula(worksheet, 146, -100d, "PPMT(0,1,12,1200)");
                AssertNumericFormula(worksheet, 147, 400d, "VDB(1000,100,5,0,1)");
                AssertNumericFormula(worksheet, 148, 369d, "DB(1000,100,5,1)");
                AssertNumericFormula(worksheet, 149, 0d, "ISPMT(0,1,12,1200)");
                AssertTextFormula(worksheet, 150, "$A$1", "ADDRESS(1,1)");
                AssertNumericFormula(worksheet, 151, 2d, "INDIRECT(\"B1\")");
                AssertTextFormula(worksheet, 152, "Example", "HYPERLINK(\"https://example.com\",\"Example\")");
                AssertNumericFormula(worksheet, 153, -2d, "MDETERM(F1:G2)");
                AssertNumericFormula(worksheet, 154, 7d, "ERROR.TYPE(NA())");
                AssertNumericFormula(worksheet, 155, 2d, "LINEST(D1:D3,C1:C3)");
                AssertNumericFormula(worksheet, 156, 8d, "TREND(D1:D3,C1:C3,4)");
                AssertNumericFormula(worksheet, 157, 2d, "LOGEST(H1:H3,C1:C3)");
                AssertNumericFormula(worksheet, 158, 16d, "GROWTH(H1:H3,C1:C3,4)");
                AssertNumericFormula(worksheet, 159, -2d, "MINVERSE(F1:G2)");
                AssertNumericFormula(worksheet, 160, 7d, "MMULT(F1:G1,F1:F2)");
                AssertNumericFormula(worksheet, 161, 1d, "TRANSPOSE(F1:G2)");
                AssertTextFormula(worksheet, 162, "$A$1", "CELL(\"address\",A1)");
                AssertTextFormula(worksheet, 163, "Windows", "INFO(\"osversion\")");
                AssertNumericFormula(worksheet, 164, 1d, "FREQUENCY(C1:C3,C1:C3)");
                AssertBooleanFormula(worksheet, 165, false, "AND(TRUE,TRUE,FALSE)");
                AssertBooleanFormula(worksheet, 166, true, "OR(FALSE,FALSE,TRUE)");
                AssertNumericFormula(worksheet, 167, 42d, "GETPIVOTDATA(\"Sales\",A1,\"Region\",\"North\")");
                AssertTextFormula(worksheet, 168, "North", "PHONETIC(A1)");
                AssertTextFormula(worksheet, 169, "baht", "BAHTTEXT(123)");
                AssertTextFormula(worksheet, 170, "weekday", "THAIDAYOFWEEK(1)");
                AssertTextFormula(worksheet, 171, "digit", "THAIDIGIT(1)");
                AssertTextFormula(worksheet, 172, "month", "THAIMONTHOFYEAR(1)");
                AssertTextFormula(worksheet, 173, "sound", "THAINUMSOUND(123)");
                AssertTextFormula(worksheet, 174, "number", "THAINUMSTRING(123)");
                AssertNumericFormula(worksheet, 175, 5d, "THAISTRINGLENGTH(\"Alpha\")");
                AssertBooleanFormula(worksheet, 176, false, "ISTHAIDIGIT(\"1\")");
                AssertNumericFormula(worksheet, 177, 120d, "ROUNDBAHTDOWN(123.45)");
                AssertNumericFormula(worksheet, 178, 130d, "ROUNDBAHTUP(123.45)");
                AssertNumericFormula(worksheet, 179, 2569d, "THAIYEAR(DATE(2026,1,1))");
                AssertTextFormula(worksheet, 180, "snapshot", "RTD(\"ProgId\",\"Server\",\"Topic\")");
                AssertTextFormula(worksheet, 181, "Scenario", "SCENARIO.GET(1)");
                AssertTextFormula(worksheet, 182, "Option", "OPTIONS.LISTS.GET(1)");
                AssertBooleanFormula(worksheet, 183, false, "OPEN.DIALOG()");
                AssertBooleanFormula(worksheet, 184, false, "SAVE.DIALOG(\"*.xls\")");
                AssertTextFormula(worksheet, 185, "View", "VIEW.GET(1)");
                AssertTextFormula(worksheet, 186, "CellInfo", "GET.CELL(1,A1)");
                AssertTextFormula(worksheet, 187, "Workspace", "GET.WORKSPACE(1)");
                AssertTextFormula(worksheet, 188, "Window", "GET.WINDOW(1)");
                AssertTextFormula(worksheet, 189, "Document", "GET.DOCUMENT(1)");
                AssertTextFormula(worksheet, 190, "Note", "GET.NOTE()");
                AssertTextFormula(worksheet, 191, "Workbook", "GET.WORKBOOK(1)");
                AssertTextFormula(worksheet, 192, "Links", "LINKS()");
                AssertTextFormula(worksheet, 193, "FormulaText", "GET.FORMULA(A1)");
                AssertTextFormula(worksheet, 194, "NameInfo", "GET.NAME(\"Print_Area\")");
                AssertTextFormula(worksheet, 195, "Names", "NAMES()");
                AssertTextFormula(worksheet, 196, "Directory", "DIRECTORY()");
                AssertTextFormula(worksheet, 197, "Files", "FILES()");
                AssertTextFormula(worksheet, 198, "Bar", "GET.BAR(1)");
                AssertTextFormula(worksheet, 199, "LinkInfo", "GET.LINK.INFO(\"Book.xls\",\"Sheet1\",1)");
                AssertTextFormula(worksheet, 200, "Toolbar", "GET.TOOLBAR(1)");
                AssertTextFormula(worksheet, 201, "Tool", "GET.TOOL(1)");
                AssertTextFormula(worksheet, 202, "AbsRef", "ABSREF(1,A1)");
                AssertTextFormula(worksheet, 203, "RelRef", "RELREF(A1,B1)");
                AssertTextFormula(worksheet, 204, "Argument", "ARGUMENT()");
                AssertTextFormula(worksheet, 205, "Caller", "CALLER()");
                AssertTextFormula(worksheet, 206, "Deref", "DEREF(A1)");
                AssertTextFormula(worksheet, 207, "Windows", "WINDOWS()");
                AssertTextFormula(worksheet, 208, "Documents", "DOCUMENTS()");
                AssertTextFormula(worksheet, 209, "Active", "ACTIVE.CELL()");
                AssertTextFormula(worksheet, 210, "Selection", "SELECTION()");
                AssertTextFormula(worksheet, 211, "Result", "RESULT()");
                AssertTextFormula(worksheet, 212, "Definition", "GET.DEF(\"Print_Area\")");
                AssertTextFormula(worksheet, 213, "RefText", "REFTEXT(A1)");
                AssertTextFormula(worksheet, 214, "TextRef", "TEXTREF(\"A1\")");

                AssertFunctionToken(result.Workbook, "SUMXMY2", 0x012f);
                AssertFunctionToken(result.Workbook, "SUMX2MY2", 0x0130);
                AssertFunctionToken(result.Workbook, "SUMX2PY2", 0x0131);
                AssertFunctionToken(result.Workbook, "CHITEST", 0x0132);
                AssertFunctionToken(result.Workbook, "AREAS", 0x004b);
                AssertFunctionToken(result.Workbook, "CORREL", 0x0133);
                AssertFunctionToken(result.Workbook, "COVAR", 0x0134);
                AssertFunctionToken(result.Workbook, "FORECAST", 0x0135);
                AssertFunctionToken(result.Workbook, "FTEST", 0x0136);
                AssertFunctionToken(result.Workbook, "INTERCEPT", 0x0137);
                AssertFunctionToken(result.Workbook, "PEARSON", 0x0138);
                AssertFunctionToken(result.Workbook, "RSQ", 0x0139);
                AssertFunctionToken(result.Workbook, "STEYX", 0x013a);
                AssertFunctionToken(result.Workbook, "SLOPE", 0x013b);
                AssertFunctionToken(result.Workbook, "QUARTILE", 0x0147);
                AssertFunctionToken(result.Workbook, "PERCENTILE", 0x0148);
                AssertFunctionToken(result.Workbook, "RANK", 0x00d8);
                AssertFunctionToken(result.Workbook, "KURT", 0x0142);
                AssertFunctionToken(result.Workbook, "SKEW", 0x0143);
                AssertFunctionToken(result.Workbook, "ZTEST", 0x0144);
                AssertFunctionToken(result.Workbook, "PERCENTRANK", 0x0149);
                AssertFunctionToken(result.Workbook, "TRIMMEAN", 0x014b);
                AssertFunctionToken(result.Workbook, "TINV", 0x014c);
                AssertFunctionToken(result.Workbook, "STDEVP", 0x00c1);
                AssertFunctionToken(result.Workbook, "VARP", 0x00c2);
                AssertFunctionToken(result.Workbook, "AVEDEV", 0x010d);
                AssertFunctionToken(result.Workbook, "BETADIST", 0x010e);
                AssertFunctionToken(result.Workbook, "GAMMALN", 0x010f);
                AssertFunctionToken(result.Workbook, "BETAINV", 0x0110);
                AssertFunctionToken(result.Workbook, "BINOMDIST", 0x0111);
                AssertFunctionToken(result.Workbook, "CHIDIST", 0x0112);
                AssertFunctionToken(result.Workbook, "CHIINV", 0x0113);
                AssertFunctionToken(result.Workbook, "COMBIN", 0x0114);
                AssertFunctionToken(result.Workbook, "CONFIDENCE", 0x0115);
                AssertFunctionToken(result.Workbook, "CRITBINOM", 0x0116);
                AssertFunctionToken(result.Workbook, "EVEN", 0x0117);
                AssertFunctionToken(result.Workbook, "EXPONDIST", 0x0118);
                AssertFunctionToken(result.Workbook, "FDIST", 0x0119);
                AssertFunctionToken(result.Workbook, "FINV", 0x011a);
                AssertFunctionToken(result.Workbook, "FISHER", 0x011b);
                AssertFunctionToken(result.Workbook, "FISHERINV", 0x011c);
                AssertFunctionToken(result.Workbook, "GAMMADIST", 0x011e);
                AssertFunctionToken(result.Workbook, "GAMMAINV", 0x011f);
                AssertFunctionToken(result.Workbook, "HYPGEOMDIST", 0x0121);
                AssertFunctionToken(result.Workbook, "LOGNORMDIST", 0x0122);
                AssertFunctionToken(result.Workbook, "LOGINV", 0x0123);
                AssertFunctionToken(result.Workbook, "NEGBINOMDIST", 0x0124);
                AssertFunctionToken(result.Workbook, "NORMDIST", 0x0125);
                AssertFunctionToken(result.Workbook, "NORMSDIST", 0x0126);
                AssertFunctionToken(result.Workbook, "NORMINV", 0x0127);
                AssertFunctionToken(result.Workbook, "NORMSINV", 0x0128);
                AssertFunctionToken(result.Workbook, "STANDARDIZE", 0x0129);
                AssertFunctionToken(result.Workbook, "ODD", 0x012a);
                AssertFunctionToken(result.Workbook, "PERMUT", 0x012b);
                AssertFunctionToken(result.Workbook, "POISSON", 0x012c);
                AssertFunctionToken(result.Workbook, "TDIST", 0x012d);
                AssertFunctionToken(result.Workbook, "WEIBULL", 0x012e);
                AssertFunctionToken(result.Workbook, "TTEST", 0x013c);
                AssertFunctionToken(result.Workbook, "PROB", 0x013d);
                AssertFunctionToken(result.Workbook, "STDEVPA", 0x016c);
                AssertFunctionToken(result.Workbook, "VARPA", 0x016d);
                AssertFunctionToken(result.Workbook, "STDEVA", 0x016e);
                AssertFunctionToken(result.Workbook, "VARA", 0x016f);
                AssertFunctionToken(result.Workbook, "DCOUNT", 0x0028);
                AssertFunctionToken(result.Workbook, "DSUM", 0x0029);
                AssertFunctionToken(result.Workbook, "DAVERAGE", 0x002a);
                AssertFunctionToken(result.Workbook, "DMIN", 0x002b);
                AssertFunctionToken(result.Workbook, "DMAX", 0x002c);
                AssertFunctionToken(result.Workbook, "DSTDEV", 0x002d);
                AssertFunctionToken(result.Workbook, "DVAR", 0x002f);
                AssertFunctionToken(result.Workbook, "DPRODUCT", 0x00bd);
                AssertFunctionToken(result.Workbook, "DSTDEVP", 0x00c3);
                AssertFunctionToken(result.Workbook, "DVARP", 0x00c4);
                AssertFunctionToken(result.Workbook, "DCOUNTA", 0x00c7);
                AssertFunctionToken(result.Workbook, "DGET", 0x00eb);
                AssertFunctionToken(result.Workbook, "USDOLLAR", 0x00cc);
                AssertFunctionToken(result.Workbook, "FINDB", 0x00cd);
                AssertFunctionToken(result.Workbook, "SEARCHB", 0x00ce);
                AssertFunctionToken(result.Workbook, "REPLACEB", 0x00cf);
                AssertFunctionToken(result.Workbook, "LEFTB", 0x00d0);
                AssertFunctionToken(result.Workbook, "RIGHTB", 0x00d1);
                AssertFunctionToken(result.Workbook, "MIDB", 0x00d2);
                AssertFunctionToken(result.Workbook, "LENB", 0x00d3);
                AssertFunctionToken(result.Workbook, "ASC", 0x00d6);
                AssertFunctionToken(result.Workbook, "DBCS", 0x00d7);
                AssertFunctionToken(result.Workbook, "DATEDIF", 0x015f);
                AssertFunctionToken(result.Workbook, "DATESTRING", 0x0160);
                AssertFunctionToken(result.Workbook, "NUMBERSTRING", 0x0161);
                AssertFunctionToken(result.Workbook, "ROMAN", 0x0162);
                AssertVariableFunctionToken(result.Workbook, "SCENARIO.GET", 0x015c, 1);
                AssertVariableFunctionToken(result.Workbook, "OPTIONS.LISTS.GET", 0x015d, 1);
                AssertVariableFunctionToken(result.Workbook, "OPEN.DIALOG", 0x0163, 0);
                AssertVariableFunctionToken(result.Workbook, "SAVE.DIALOG", 0x0164, 1);
                AssertVariableFunctionToken(result.Workbook, "VIEW.GET", 0x0165, 1);
                AssertVariableFunctionToken(result.Workbook, "GET.CELL", 0x00b9, 2);
                AssertVariableFunctionToken(result.Workbook, "GET.WORKSPACE", 0x00ba, 1);
                AssertVariableFunctionToken(result.Workbook, "GET.WINDOW", 0x00bb, 1);
                AssertVariableFunctionToken(result.Workbook, "GET.DOCUMENT", 0x00bc, 1);
                AssertVariableFunctionToken(result.Workbook, "GET.NOTE", 0x00bf, 0);
                AssertVariableFunctionToken(result.Workbook, "GET.WORKBOOK", 0x010c, 1);
                AssertVariableFunctionToken(result.Workbook, "LINKS", 0x0067, 0);
                AssertVariableFunctionToken(result.Workbook, "GET.FORMULA", 0x006a, 1);
                AssertVariableFunctionToken(result.Workbook, "GET.NAME", 0x006b, 1);
                AssertVariableFunctionToken(result.Workbook, "NAMES", 0x007a, 0);
                AssertVariableFunctionToken(result.Workbook, "DIRECTORY", 0x007b, 0);
                AssertVariableFunctionToken(result.Workbook, "FILES", 0x00a6, 0);
                AssertVariableFunctionToken(result.Workbook, "GET.BAR", 0x00b6, 1);
                AssertVariableFunctionToken(result.Workbook, "GET.LINK.INFO", 0x00f2, 3);
                AssertVariableFunctionToken(result.Workbook, "GET.TOOLBAR", 0x0102, 1);
                AssertVariableFunctionToken(result.Workbook, "GET.TOOL", 0x0103, 1);
                AssertVariableFunctionToken(result.Workbook, "ABSREF", 0x004f, 2);
                AssertVariableFunctionToken(result.Workbook, "RELREF", 0x0050, 2);
                AssertVariableFunctionToken(result.Workbook, "ARGUMENT", 0x0051, 0);
                AssertVariableFunctionToken(result.Workbook, "CALLER", 0x0059, 0);
                AssertVariableFunctionToken(result.Workbook, "DEREF", 0x005a, 1);
                AssertVariableFunctionToken(result.Workbook, "WINDOWS", 0x005b, 0);
                AssertVariableFunctionToken(result.Workbook, "DOCUMENTS", 0x005d, 0);
                AssertVariableFunctionToken(result.Workbook, "ACTIVE.CELL", 0x005e, 0);
                AssertVariableFunctionToken(result.Workbook, "SELECTION", 0x005f, 0);
                AssertVariableFunctionToken(result.Workbook, "RESULT", 0x0060, 0);
                AssertVariableFunctionToken(result.Workbook, "GET.DEF", 0x0091, 1);
                AssertVariableFunctionToken(result.Workbook, "REFTEXT", 0x0092, 1);
                AssertVariableFunctionToken(result.Workbook, "TEXTREF", 0x0093, 1);
                AssertFunctionToken(result.Workbook, "ASIN", 0x0062);
                AssertFunctionToken(result.Workbook, "ACOS", 0x0063);
                AssertFunctionToken(result.Workbook, "ATAN2", 0x0061);
                AssertFunctionToken(result.Workbook, "DOLLAR", 0x000d);
                AssertFunctionToken(result.Workbook, "FIXED", 0x000e);
                AssertFunctionToken(result.Workbook, "LOOKUP", 0x001c);
                AssertFunctionToken(result.Workbook, "TIMEVALUE", 0x008d);
                AssertFunctionToken(result.Workbook, "DAYS360", 0x00dc);
                AssertFunctionToken(result.Workbook, "LOG", 0x006d);
                AssertFunctionToken(result.Workbook, "CHAR", 0x006f);
                AssertFunctionToken(result.Workbook, "CODE", 0x0079);
                AssertFunctionToken(result.Workbook, "TYPE", 0x0056);
                AssertFunctionToken(result.Workbook, "T", 0x0082);
                AssertFunctionToken(result.Workbook, "N", 0x0083);
                AssertFunctionToken(result.Workbook, "CLEAN", 0x00a2);
                AssertFunctionToken(result.Workbook, "FACT", 0x00b8);
                AssertFunctionToken(result.Workbook, "SINH", 0x00e5);
                AssertFunctionToken(result.Workbook, "COSH", 0x00e6);
                AssertFunctionToken(result.Workbook, "TANH", 0x00e7);
                AssertFunctionToken(result.Workbook, "ASINH", 0x00e8);
                AssertFunctionToken(result.Workbook, "ACOSH", 0x00e9);
                AssertFunctionToken(result.Workbook, "ATANH", 0x00ea);
                AssertFunctionToken(result.Workbook, "RATE", 0x003c);
                AssertFunctionToken(result.Workbook, "MIRR", 0x003d);
                AssertFunctionToken(result.Workbook, "IRR", 0x003e);
                AssertFunctionToken(result.Workbook, "SLN", 0x008e);
                AssertFunctionToken(result.Workbook, "SYD", 0x008f);
                AssertFunctionToken(result.Workbook, "DDB", 0x0090);
                AssertFunctionToken(result.Workbook, "IPMT", 0x00a7);
                AssertFunctionToken(result.Workbook, "PPMT", 0x00a8);
                AssertFunctionToken(result.Workbook, "VDB", 0x00de);
                AssertFunctionToken(result.Workbook, "DB", 0x00f7);
                AssertFunctionToken(result.Workbook, "ISPMT", 0x015e);
                AssertFunctionToken(result.Workbook, "ADDRESS", 0x00db);
                AssertFunctionToken(result.Workbook, "INDIRECT", 0x0094);
                AssertVariableFunctionToken(result.Workbook, "GETPIVOTDATA", 0x0166, 4);
                AssertFunctionToken(result.Workbook, "HYPERLINK", 0x0167);
                AssertFunctionToken(result.Workbook, "PHONETIC", 0x0168);
                AssertFunctionToken(result.Workbook, "BAHTTEXT", 0x0170);
                AssertFunctionToken(result.Workbook, "THAIDAYOFWEEK", 0x0171);
                AssertFunctionToken(result.Workbook, "THAIDIGIT", 0x0172);
                AssertFunctionToken(result.Workbook, "THAIMONTHOFYEAR", 0x0173);
                AssertFunctionToken(result.Workbook, "THAINUMSOUND", 0x0174);
                AssertFunctionToken(result.Workbook, "THAINUMSTRING", 0x0175);
                AssertFunctionToken(result.Workbook, "THAISTRINGLENGTH", 0x0176);
                AssertFunctionToken(result.Workbook, "ISTHAIDIGIT", 0x0177);
                AssertFunctionToken(result.Workbook, "ROUNDBAHTDOWN", 0x0178);
                AssertFunctionToken(result.Workbook, "ROUNDBAHTUP", 0x0179);
                AssertFunctionToken(result.Workbook, "THAIYEAR", 0x017a);
                AssertVariableFunctionToken(result.Workbook, "RTD", 0x017b, 3);
                AssertFunctionToken(result.Workbook, "MDETERM", 0x00a3);
                AssertFunctionToken(result.Workbook, "ERROR.TYPE", 0x0105);
                AssertFunctionToken(result.Workbook, "LINEST", 0x0031);
                AssertFunctionToken(result.Workbook, "TREND", 0x0032);
                AssertFunctionToken(result.Workbook, "LOGEST", 0x0033);
                AssertFunctionToken(result.Workbook, "GROWTH", 0x0034);
                AssertFunctionToken(result.Workbook, "MINVERSE", 0x00a4);
                AssertFunctionToken(result.Workbook, "MMULT", 0x00a5);
                AssertFunctionToken(result.Workbook, "TRANSPOSE", 0x0053);
                AssertFunctionToken(result.Workbook, "CELL", 0x007d);
                AssertFunctionToken(result.Workbook, "INFO", 0x00f4);
                AssertFunctionToken(result.Workbook, "FREQUENCY", 0x00fc);
                AssertVariableFunctionToken(result.Workbook, "AND", 0x0024, 3);
                AssertVariableFunctionToken(result.Workbook, "OR", 0x0025, 3);
            } finally {
                TryDelete(openXmlPath);
                TryDelete(xlsOutputPath);
            }
        }

        [Fact]
        public void LegacyXls_NativeSave_WritesVariableArityStdevFormula() {
            string openXmlPath = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString("N") + ".xlsx");
            string xlsOutputPath = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString("N") + ".xls");

            try {
                using (ExcelDocument document = ExcelDocument.Create(openXmlPath)) {
                    ExcelSheet sheet = document.AddWorksheet("VariableStdev");
                    sheet.CellValue(1, 1, 1d);
                    sheet.CellFormula(1, 1, "STDEV(1,2,3)");

                    document.Save(xlsOutputPath);
                }

                using LegacyXlsLoadResult result = ExcelDocument.LoadLegacyXlsWithReport(xlsOutputPath);
                result.EnsureNoImportErrors();
                Assert.False(result.HasUnsupportedFeatures, FormatUnsupportedFeatures(result.UnsupportedFeatures));

                LegacyXlsWorksheet worksheet = Assert.Single(result.Workbook.Worksheets);
                AssertNumericFormula(worksheet, 1, 1d, "STDEV(1,2,3)");
                Assert.Contains(result.Workbook.FormulaTokenRecords, record =>
                    record.TokenName == "PtgFuncVar"
                    && string.Equals(record.FunctionName, "STDEV", StringComparison.Ordinal)
                    && record.FunctionId == 0x000c);
            } finally {
                TryDelete(openXmlPath);
                TryDelete(xlsOutputPath);
            }
        }

        [Fact]
        public void LegacyXls_NativeSave_WritesRowAndColumnWithOmittedReferenceArguments() {
            string openXmlPath = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString("N") + ".xlsx");
            string xlsOutputPath = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString("N") + ".xls");

            try {
                using (ExcelDocument document = ExcelDocument.Create(openXmlPath)) {
                    ExcelSheet sheet = document.AddWorksheet("OmittedRefs");
                    sheet.CellValue(2, 1, 2d);
                    sheet.CellFormula(2, 1, "ROW()");
                    sheet.CellValue(3, 1, 1d);
                    sheet.CellFormula(3, 1, "COLUMN()");

                    document.Save(xlsOutputPath);
                }

                using LegacyXlsLoadResult result = ExcelDocument.LoadLegacyXlsWithReport(xlsOutputPath);
                result.EnsureNoImportErrors();
                Assert.False(result.HasUnsupportedFeatures, FormatUnsupportedFeatures(result.UnsupportedFeatures));

                LegacyXlsWorksheet worksheet = Assert.Single(result.Workbook.Worksheets);
                AssertNumericFormula(worksheet, 2, 2d, "ROW()");
                AssertNumericFormula(worksheet, 3, 1d, "COLUMN()");

                Assert.Equal(2, result.Workbook.FormulaTokenRecords.Count(record => record.TokenName == "PtgMissArg"));
                AssertFunctionToken(result.Workbook, "ROW", 0x0008);
                AssertFunctionToken(result.Workbook, "COLUMN", 0x0009);
            } finally {
                TryDelete(openXmlPath);
                TryDelete(xlsOutputPath);
            }
        }

        [Fact]
        public void LegacyXls_NativeSave_WritesTwoArgumentIfFormula() {
            string openXmlPath = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString("N") + ".xlsx");
            string xlsOutputPath = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString("N") + ".xls");

            try {
                using (ExcelDocument document = ExcelDocument.Create(openXmlPath)) {
                    ExcelSheet sheet = document.AddWorksheet("If2");
                    sheet.CellValue(1, 1, 5d);
                    sheet.CellValue(2, 1, 10d);
                    sheet.CellFormula(2, 1, "IF(A1>2,10)");

                    document.Save(xlsOutputPath);
                }

                using LegacyXlsLoadResult result = ExcelDocument.LoadLegacyXlsWithReport(xlsOutputPath);
                result.EnsureNoImportErrors();
                Assert.False(result.HasUnsupportedFeatures, FormatUnsupportedFeatures(result.UnsupportedFeatures));

                LegacyXlsWorksheet worksheet = Assert.Single(result.Workbook.Worksheets);
                AssertNumericFormula(worksheet, 2, 10d, "IF(A1>2,10)");
                Assert.Contains(result.Workbook.FormulaTokenRecords, record =>
                    record.TokenName == "PtgFuncVar"
                    && string.Equals(record.FunctionName, "IF", StringComparison.Ordinal)
                    && record.FunctionId == 0x0001
                    && record.FunctionParameterCount == 2);
            } finally {
                TryDelete(openXmlPath);
                TryDelete(xlsOutputPath);
            }
        }

        private static void AssertFunctionToken(LegacyXlsWorkbook workbook, string functionName, ushort functionId) {
            Assert.Contains(workbook.FormulaTokenRecords, record =>
                string.Equals(record.FunctionName, functionName, StringComparison.Ordinal)
                && record.FunctionId == functionId);
        }

        private static void AssertVariableFunctionToken(LegacyXlsWorkbook workbook, string functionName, ushort functionId, int parameterCount) {
            Assert.Contains(workbook.FormulaTokenRecords, record =>
                record.TokenName == "PtgFuncVar"
                && string.Equals(record.FunctionName, functionName, StringComparison.Ordinal)
                && record.FunctionId == functionId
                && record.FunctionParameterCount == parameterCount);
        }
    }
}
