#:project ../../OfficeIMO.Pdf/OfficeIMO.Pdf.csproj
#:project ../../OfficeIMO.Security/OfficeIMO.Security.csproj
// Creates the samples the PDF page tools load, in Apps/OfficeIMO.Web.Converter/wwwroot/samples:
//   page-tools-sample.pdf          six numbered pages, so selections are easy to follow (extract, delete, reorder, rotate, split, merge)
//   page-tools-sample-changed.pdf  the same document with page 3 edited (the "changed version" for Compare PDFs)
//   protected-sample.pdf           the six-page sample with the published test password "officeimo-sample" (Unlock PDF)
// Run from the Website folder:  dotnet run scripts/create-page-tools-sample.cs
using OfficeIMO.Pdf;
using OfficeIMO.Security;

string folder = Path.GetFullPath(Path.Combine("Apps", "OfficeIMO.Web.Converter", "wwwroot", "samples"));
(string Title, string Body)[] pages = [
    ("Cover", "Quarterly operations review. This sample has six numbered pages so you can see which pages a tool keeps, removes, rotates, or moves."),
    ("Summary", "Requests completed: 248. Service availability: 99.95%. Customer satisfaction: 4.8 out of 5."),
    ("Delivery", "The reporting rollout finished two weeks early, and the oldest support queue is now under target."),
    ("Risks", "Two suppliers renew contracts next quarter. Both renewals have an owner and a review date."),
    ("Next steps", "Publish the service handbook, confirm the recovery exercise, and review the September forecast."),
    ("Appendix", "Generated by OfficeIMO.Pdf for the officeimo.com browser tools. Not real company data.")
];

Write(Path.Combine(folder, "page-tools-sample.pdf"), pages);

const string SamplePassword = "officeimo-sample";
PdfSecurityMutationResult protectedSample = PdfDocument.Load(Path.Combine(folder, "page-tools-sample.pdf")).Security.Encrypt(
    new PdfStandardEncryptionOptions(SamplePassword) {
        OwnerPassword = SamplePassword,
        Algorithm = PdfStandardEncryptionAlgorithm.Aes256,
        AesCryptographyProvider = OfficeManagedAesCryptographyProvider.Default
    });
File.WriteAllBytes(Path.Combine(folder, "protected-sample.pdf"), protectedSample.Pdf);
Console.WriteLine($"Wrote {Path.Combine(folder, "protected-sample.pdf")} (password: {SamplePassword})");

pages[2] =("Delivery", "The reporting rollout slipped by one week. The oldest support queue is still above target and has a recovery plan.");
Write(Path.Combine(folder, "page-tools-sample-changed.pdf"), pages);

static void Write(string path, (string Title, string Body)[] pages) {
    PdfDocument.Create(document => document
        .Settings(options => {
            options.PageSize = PageSizes.A4;
            options.Margins = PageMargins.Uniform(56);
        })
        .Content(content => {
            for (int index = 0; index < pages.Length; index++) {
                if (index > 0) content.PageBreak();
                content.H1($"{index + 1}", PdfAlign.Left, PdfColor.FromRgb(20, 93, 245));
                content.H2(pages[index].Title);
                content.Paragraph(paragraph => paragraph.Text(pages[index].Body));
            }
        }))
        .Meta(title: "OfficeIMO page tools sample", author: "OfficeIMO")
        .Save(path);
    Console.WriteLine($"Wrote {path}");
}
