#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Creates one /browser/<tool>/ page per tool in data/browser_tools.json.

.DESCRIPTION
    The tool pages only carry front matter (title, description, SEO title, tool id); the browser-tool layout
    renders everything else from data/browser_tools.json. Run this after adding or renaming a tool.
    With -Verify the script changes nothing and fails when a page is missing, stale, or orphaned.

.EXAMPLE
    ./scripts/Sync-BrowserToolPages.ps1
    ./scripts/Sync-BrowserToolPages.ps1 -Verify
#>
param(
    [string]$SiteRoot = (Split-Path -Parent $PSScriptRoot),
    [switch]$Verify
)

$ErrorActionPreference = 'Stop'
$catalogPath = Join-Path $SiteRoot 'data/browser_tools.json'
$pagesRoot = Join-Path $SiteRoot 'content/browser'
$catalog = Get-Content -LiteralPath $catalogPath -Raw | ConvertFrom-Json

function ConvertTo-YamlString([string]$Value) {
    '"' + ($Value -replace '\\', '\\' -replace '"', '\"') + '"'
}

$expected = [ordered]@{}
foreach ($tool in $catalog.tools) {
    if ($tool.id -notmatch '^[a-z0-9]+(-[a-z0-9]+)*$') { throw "Tool id '$($tool.id)' must be lowercase words separated by hyphens." }
    $description = if ($tool.seoDescription) { $tool.seoDescription } else { $tool.summary }
    $lines = @(
        '---'
        "title: $(ConvertTo-YamlString $tool.title)"
        "description: $(ConvertTo-YamlString $description)"
        'layout: browser-tool'
        "meta.tool: $(ConvertTo-YamlString $tool.id)"
        "meta.seo_title: $(ConvertTo-YamlString $tool.seoTitle)"
        '---'
        ''
        "<!-- Generated by scripts/Sync-BrowserToolPages.ps1 from data/browser_tools.json. Edit the data file, then run the script. -->"
        ''
    )
    $expected["$($tool.id).md"] = ($lines -join "`n")
}

$problems = [System.Collections.Generic.List[string]]::new()
if (-not (Test-Path -LiteralPath $pagesRoot)) {
    if ($Verify) { throw "Missing $pagesRoot. Run scripts/Sync-BrowserToolPages.ps1." }
    New-Item -ItemType Directory -Path $pagesRoot | Out-Null
}

foreach ($entry in $expected.GetEnumerator()) {
    $path = Join-Path $pagesRoot $entry.Key
    $current = if (Test-Path -LiteralPath $path) { (Get-Content -LiteralPath $path -Raw) -replace "`r`n", "`n" } else { $null }
    if ($current -eq $entry.Value) { continue }
    if ($Verify) { $problems.Add("content/browser/$($entry.Key) is missing or out of date.") ; continue }
    [System.IO.File]::WriteAllText($path, $entry.Value, [System.Text.UTF8Encoding]::new($false))
    Write-Host "Wrote content/browser/$($entry.Key)"
}

foreach ($file in Get-ChildItem -LiteralPath $pagesRoot -Filter '*.md' -File) {
    if ($expected.Contains($file.Name)) { continue }
    if ($Verify) { $problems.Add("content/browser/$($file.Name) has no tool in data/browser_tools.json."); continue }
    Remove-Item -LiteralPath $file.FullName
    Write-Host "Removed content/browser/$($file.Name)"
}

if ($problems.Count -gt 0) {
    $problems | ForEach-Object { Write-Host $_ -ForegroundColor Red }
    throw 'Browser tool pages are out of sync. Run scripts/Sync-BrowserToolPages.ps1.'
}
if ($Verify) { Write-Host "Browser tool pages match data/browser_tools.json ($($expected.Count) tools)." -ForegroundColor Green }
