namespace OfficeIMO.Bibliography;

/// <summary>Bounded bibliography parsing options.</summary>
public sealed class BibliographyReadOptions {
    /// <summary>Maximum encoded input bytes. Defaults to 64 MiB.</summary>
    public long MaximumInputBytes { get; set; } = 64L * 1024 * 1024;
    /// <summary>Maximum decoded UTF-16 characters. Defaults to 64 MiB.</summary>
    public int MaximumInputCharacters { get; set; } = 64 * 1024 * 1024;
    /// <summary>Maximum records. Defaults to 250,000.</summary>
    public int MaximumItemCount { get; set; } = 250_000;
    /// <summary>Maximum fields, contributors, identifiers, dates, keywords, and notes across all records.</summary>
    public int MaximumValueCount { get; set; } = 2_000_000;
    /// <summary>Maximum decoded length of one value. Defaults to 4 MiB.</summary>
    public int MaximumValueLength { get; set; } = 4 * 1024 * 1024;
    /// <summary>Maximum parser diagnostics before parsing stops. Defaults to 10,000.</summary>
    public int MaximumDiagnosticCount { get; set; } = 10_000;
    /// <summary>Maximum nested BibTeX braces or JSON/XML depth. Defaults to 128.</summary>
    public int MaximumNestingDepth { get; set; } = 128;

    internal void Validate() {
        if (MaximumInputBytes <= 0) throw new ArgumentOutOfRangeException(nameof(MaximumInputBytes));
        if (MaximumInputCharacters <= 0) throw new ArgumentOutOfRangeException(nameof(MaximumInputCharacters));
        if (MaximumItemCount <= 0) throw new ArgumentOutOfRangeException(nameof(MaximumItemCount));
        if (MaximumValueCount <= 0) throw new ArgumentOutOfRangeException(nameof(MaximumValueCount));
        if (MaximumValueLength <= 0) throw new ArgumentOutOfRangeException(nameof(MaximumValueLength));
        if (MaximumDiagnosticCount <= 0) throw new ArgumentOutOfRangeException(nameof(MaximumDiagnosticCount));
        if (MaximumNestingDepth <= 0) throw new ArgumentOutOfRangeException(nameof(MaximumNestingDepth));
    }
}

/// <summary>Bibliography writer mode.</summary>
public enum BibliographyWriterMode {
    /// <summary>Return the exact original source when the document is unchanged and the source format matches.</summary>
    Preserve = 0,
    /// <summary>Write deterministic normalized syntax.</summary>
    Canonical
}

/// <summary>Options for deterministic bibliography writing.</summary>
public sealed class BibliographyWriteOptions {
    /// <summary>Destination format. Null means the document source format.</summary>
    public BibliographyFormat? Format { get; set; }
    /// <summary>Preserve or canonical mode.</summary>
    public BibliographyWriterMode Mode { get; set; } = BibliographyWriterMode.Preserve;
    /// <summary>Line ending used by generated output. Defaults to LF.</summary>
    public string LineEnding { get; set; } = "\n";
    /// <summary>Encoding used for generated bytes. Defaults to UTF-8 without a BOM.</summary>
    public Encoding Encoding { get; set; } = new UTF8Encoding(false);
    /// <summary>Throw when conversion diagnostics report an approximation or omission.</summary>
    public bool RequireNoLoss { get; set; }

    internal void Validate() {
        if (LineEnding != "\n" && LineEnding != "\r" && LineEnding != "\r\n") throw new ArgumentException("LineEnding must be LF, CR, or CRLF.", nameof(LineEnding));
        if (Encoding == null) throw new ArgumentNullException(nameof(Encoding));
    }
}

/// <summary>Result of loading bibliography data.</summary>
public sealed class BibliographyReadResult {
    internal BibliographyReadResult(BibliographyDocument document, IReadOnlyList<BibliographyDiagnostic> diagnostics) {
        Document = document;
        Diagnostics = diagnostics;
    }

    /// <summary>Parsed document.</summary>
    public BibliographyDocument Document { get; }
    /// <summary>Parser and recovery diagnostics.</summary>
    public IReadOnlyList<BibliographyDiagnostic> Diagnostics { get; }
    /// <summary>True when an error diagnostic exists.</summary>
    public bool HasErrors => Diagnostics.Any(static diagnostic => diagnostic.Severity == BibliographyDiagnosticSeverity.Error);
    /// <summary>True because all untyped fields and unchanged source text remain available.</summary>
    public bool IsSourcePreserving => true;
}

/// <summary>Result of writing or converting bibliography data.</summary>
public sealed class BibliographyWriteResult {
    internal BibliographyWriteResult(string content, byte[] bytes, BibliographyFormat format, bool usedOriginalSource, BibliographyConversionReport report) {
        Content = content;
        Bytes = bytes;
        Format = format;
        UsedOriginalSource = usedOriginalSource;
        Report = report;
    }

    /// <summary>Written text.</summary>
    public string Content { get; }
    /// <summary>Encoded output bytes.</summary>
    public byte[] Bytes { get; }
    /// <summary>Destination format.</summary>
    public BibliographyFormat Format { get; }
    /// <summary>True when the exact original source was returned.</summary>
    public bool UsedOriginalSource { get; }
    /// <summary>Deterministic conversion evidence.</summary>
    public BibliographyConversionReport Report { get; }
}
