using OfficeIMO.Drawing;

namespace OfficeIMO.Html;

internal sealed class HtmlRenderBoxStyle {
    internal string Display = "block";
    internal bool DisplayWasSpecified;
    internal bool PaintVisible = true;
    internal string Position = "static";
    internal string FloatSide = "none";
    internal string ClearSide = "none";
    internal string UnsupportedFloat = string.Empty;
    internal string UnsupportedClear = string.Empty;
    internal string CaptionSide = "top";
    internal string UnsupportedCaptionSide = string.Empty;
    internal string TableLayout = "auto";
    internal string UnsupportedTableLayout = string.Empty;
    internal string BorderCollapse = "separate";
    internal string UnsupportedBorderCollapse = string.Empty;
    internal double BorderSpacingX;
    internal double BorderSpacingY;
    internal string UnsupportedBorderSpacing = string.Empty;
    internal string Top = "auto";
    internal string Right = "auto";
    internal string Bottom = "auto";
    internal string Left = "auto";
    internal string ZIndex = "auto";
    internal string FlexDirection = "row";
    internal string FlexWrap = "nowrap";
    internal string JustifyContent = "normal";
    internal string AlignItems = "normal";
    internal string AlignContent = "normal";
    internal string AlignSelf = "auto";
    internal double FlexGrow;
    internal double FlexShrink = 1D;
    internal string FlexBasis = "auto";
    internal int Order;
    internal double RowGap;
    internal double ColumnGap;
    internal string UnsupportedRowGap = string.Empty;
    internal string UnsupportedColumnGap = string.Empty;
    internal bool ColumnGapWasSpecified;
    internal int? ColumnCount;
    internal double? ColumnWidth;
    internal string ColumnFill = "balance";
    internal string ColumnSpan = "none";
    internal double ColumnRuleWidth = 3D;
    internal string ColumnRuleStyle = "none";
    internal OfficeColor? ColumnRuleColor;
    internal string UnsupportedColumns = string.Empty;
    internal string UnsupportedColumnFill = string.Empty;
    internal string UnsupportedColumnSpan = string.Empty;
    internal string UnsupportedColumnRule = string.Empty;
    internal string GridTemplateColumns = "none";
    internal string GridTemplateRows = "none";
    internal string GridTemplateAreas = "none";
    internal string GridAutoColumns = "auto";
    internal string GridAutoRows = "auto";
    internal string GridAutoFlow = "row";
    internal string GridColumnStart = "auto";
    internal string GridColumnEnd = "auto";
    internal string GridRowStart = "auto";
    internal string GridRowEnd = "auto";
    internal string GridArea = "auto";
    internal string JustifyItems = "normal";
    internal string JustifySelf = "auto";
    internal bool MarginTopAuto;
    internal bool MarginRightAuto;
    internal bool MarginBottomAuto;
    internal bool MarginLeftAuto;
    internal double MarginTop;
    internal double MarginRight;
    internal double MarginBottom;
    internal double MarginLeft;
    internal double PaddingTop;
    internal double PaddingRight;
    internal double PaddingBottom;
    internal double PaddingLeft;
    internal HtmlRenderBorderEdges Borders = HtmlRenderBorderEdges.Uniform(0D, "none", OfficeColor.Black);
    internal double BorderWidth {
        get => Borders.MaximumLayoutWidth;
        set => Borders = Borders.WithUniformWidth(value);
    }
    internal OfficeColor BorderColor {
        get => Borders.Top.Color;
        set => Borders = Borders.WithUniformColor(value);
    }
    internal string BorderStyle {
        get => Borders.IsUniform ? Borders.Top.Style : "mixed";
        set => Borders = Borders.WithUniformStyle(value);
    }
    internal double BorderTopWidth => Borders.Top.LayoutWidth;
    internal double BorderRightWidth => Borders.Right.LayoutWidth;
    internal double BorderBottomWidth => Borders.Bottom.LayoutWidth;
    internal double BorderLeftWidth => Borders.Left.LayoutWidth;
    internal bool HasBorderLayout => Borders.HasLayout;
    internal HtmlRenderBorderInsets BorderInsets => Borders.Insets;
    internal bool BorderDeclared;
    internal string UnsupportedBorderPaint = string.Empty;
    internal string BorderRadius = "0";
    internal string BorderTopLeftRadius = string.Empty;
    internal string BorderTopRightRadius = string.Empty;
    internal string BorderBottomRightRadius = string.Empty;
    internal string BorderBottomLeftRadius = string.Empty;
    internal OfficeColor? BackgroundColor;
    internal int BackgroundImageLayerCount;
    internal bool HasDeclaredBackgroundImage;
    internal int UnsupportedBackgroundImageLayerCount;
    internal int GradientStopLimitExceededCount;
    internal IReadOnlyList<HtmlRenderBackgroundLayer> BackgroundImageLayers = Array.Empty<HtmlRenderBackgroundLayer>();
    internal OfficeFontInfo Font;
    internal OfficeColor Color = OfficeColor.Black;
    internal OfficeTextAlignment Alignment;
    internal double LineHeight;
    internal double? ExplicitWidth;
    internal double? ExplicitHeight;
    internal double? MinWidth;
    internal double? MaxWidth;
    internal double? MinHeight;
    internal double? MaxHeight;
    internal string ObjectFit = "fill";
    internal string ObjectPosition = "50% 50%";
    internal double? AspectRatio;
    internal bool AspectRatioPrefersIntrinsic = true;
    internal string UnsupportedReplacedElementLayout = string.Empty;
    internal bool BorderBox;
    internal bool PreserveWhitespace;
    internal string ListStyleType = string.Empty;
    internal string TextTransform = "none";
    internal string Direction = "ltr";
    internal string OverflowWrap = "normal";
    internal string WordBreak = "normal";
    internal string OverflowX = "visible";
    internal string OverflowY = "visible";
    internal string OverflowClipMarginBox = "padding-box";
    internal double OverflowClipMargin;
    internal string UnsupportedOverflowX = string.Empty;
    internal string UnsupportedOverflowY = string.Empty;
    internal string UnsupportedOverflowClipMargin = string.Empty;
    internal string Transform = "none";
    internal string TransformOrigin = "50% 50%";
    internal bool OpacityWasSpecified;
    internal string UnsupportedOpacity = string.Empty;
    internal int BoxShadowLayerCount;
    internal IReadOnlyList<HtmlCssBoxShadow> BoxShadows = Array.Empty<HtmlCssBoxShadow>();
    internal string UnsupportedBoxShadow = string.Empty;
    internal double OutlineWidth;
    internal double OutlineOffset;
    internal OfficeColor OutlineColor = OfficeColor.Black;
    internal string OutlineStyle = "none";
    internal string UnsupportedOutlinePaint = string.Empty;
    internal HtmlPageBreakTarget BreakBefore;
    internal HtmlPageBreakTarget BreakAfter;
    internal bool AvoidBreakInside;
    internal int Orphans = 2;
    internal int Widows = 2;
    internal string? PageName;
    internal string SemanticRole = "block";
    internal double Opacity = 1D;

    internal double HorizontalInsets => BorderLeftWidth + BorderRightWidth + PaddingLeft + PaddingRight;
    internal double VerticalInsets => BorderTopWidth + BorderBottomWidth + PaddingTop + PaddingBottom;

    internal HtmlRenderBoxStyle Clone() => (HtmlRenderBoxStyle)MemberwiseClone();
}
