using OfficeIMO.Drawing;

namespace OfficeIMO.Html;

internal sealed class HtmlRenderBoxStyle {
    internal string Display = "block";
    internal string Position = "static";
    internal string Top = "auto";
    internal string Right = "auto";
    internal string Bottom = "auto";
    internal string Left = "auto";
    internal string ZIndex = "auto";
    internal string FlexDirection = "row";
    internal string FlexWrap = "nowrap";
    internal string JustifyContent = "normal";
    internal string AlignItems = "normal";
    internal string AlignContent = "normal";
    internal string AlignSelf = "auto";
    internal double FlexGrow;
    internal double FlexShrink = 1D;
    internal string FlexBasis = "auto";
    internal int Order;
    internal double RowGap;
    internal double ColumnGap;
    internal string UnsupportedRowGap = string.Empty;
    internal string UnsupportedColumnGap = string.Empty;
    internal string GridTemplateColumns = "none";
    internal string GridTemplateRows = "none";
    internal string GridAutoColumns = "auto";
    internal string GridAutoRows = "auto";
    internal string GridAutoFlow = "row";
    internal string GridColumnStart = "auto";
    internal string GridColumnEnd = "auto";
    internal string GridRowStart = "auto";
    internal string GridRowEnd = "auto";
    internal string JustifyItems = "normal";
    internal string JustifySelf = "auto";
    internal bool MarginTopAuto;
    internal bool MarginRightAuto;
    internal bool MarginBottomAuto;
    internal bool MarginLeftAuto;
    internal double MarginTop;
    internal double MarginRight;
    internal double MarginBottom;
    internal double MarginLeft;
    internal double PaddingTop;
    internal double PaddingRight;
    internal double PaddingBottom;
    internal double PaddingLeft;
    internal double BorderWidth;
    internal OfficeColor BorderColor = OfficeColor.Black;
    internal OfficeColor? BackgroundColor;
    internal int BackgroundImageLayerCount;
    internal bool HasDeclaredBackgroundImage;
    internal int UnsupportedBackgroundImageLayerCount;
    internal int GradientStopLimitExceededCount;
    internal IReadOnlyList<HtmlRenderBackgroundLayer> BackgroundImageLayers = Array.Empty<HtmlRenderBackgroundLayer>();
    internal OfficeFontInfo Font;
    internal OfficeColor Color = OfficeColor.Black;
    internal OfficeTextAlignment Alignment;
    internal double LineHeight;
    internal double? ExplicitWidth;
    internal double? ExplicitHeight;
    internal double? MinWidth;
    internal double? MaxWidth;
    internal double? MinHeight;
    internal double? MaxHeight;
    internal bool BorderBox;
    internal bool PreserveWhitespace;
    internal string TextTransform = "none";
    internal HtmlPageBreakTarget BreakBefore;
    internal HtmlPageBreakTarget BreakAfter;
    internal bool AvoidBreakInside;
    internal int Orphans = 2;
    internal int Widows = 2;
    internal string? PageName;
    internal string SemanticRole = "block";
    internal double Opacity = 1D;

    internal double HorizontalInsets => BorderWidth * 2D + PaddingLeft + PaddingRight;
    internal double VerticalInsets => BorderWidth * 2D + PaddingTop + PaddingBottom;

    internal HtmlRenderBoxStyle Clone() => (HtmlRenderBoxStyle)MemberwiseClone();
}
