using OfficeIMO.Reader;

namespace OfficeIMO.AI;

/// <summary>Terminal engine state; cancellation is surfaced through OperationCanceledException.</summary>
public enum OfficeAiResultStatus {
    /// <summary>All selected evidence was processed; semantic correctness still requires assessment.</summary>
    Completed,
    /// <summary>Some selected evidence could not be processed or source diagnostics limit completeness.</summary>
    Partial,
    /// <summary>No supported answer or usable extraction was produced.</summary>
    InsufficientEvidence,
    /// <summary>The provider returned output that failed the document contract.</summary>
    InvalidResponse
}

/// <summary>Deterministically checked source reference; semantic entailment is deliberately not implied.</summary>
public sealed record OfficeAiCitation(string EvidenceId, int? Page, string? Quote, bool QuoteMatched);

/// <summary>Model-authored text with validated source references; interpretation still requires review.</summary>
public sealed record OfficeAiClaim(string Text, IReadOnlyList<OfficeAiCitation> Citations);

/// <summary>Explicit field outcome, including ambiguous and conflicting observations.</summary>
public enum OfficeAiFieldStatus {
    /// <summary>A source-linked raw value was found and normalized.</summary>
    Present,
    /// <summary>No value was found in processed evidence.</summary>
    Missing,
    /// <summary>Evidence admits more than one interpretation.</summary>
    Ambiguous,
    /// <summary>Batches contain differing source-linked values.</summary>
    Conflicting,
    /// <summary>The observed value cannot be normalized to the requested type.</summary>
    Invalid,
    /// <summary>No validated value is available and some selected evidence was not processed.</summary>
    NotEvaluated
}

/// <summary>Raw and locally normalized extraction; normalized values use invariant transport syntax.</summary>
public sealed record OfficeAiField(string Name, OfficeAiFieldType Type, OfficeAiFieldStatus Status,
    string? RawValue, string? NormalizedValue, IReadOnlyList<OfficeAiCitation> Citations);

/// <summary>AI-proposed block expressed in Reader's model, with evidence kept separately.</summary>
public sealed record OfficeAiBlock(OfficeDocumentBlock Block, IReadOnlyList<OfficeAiCitation> Citations);

/// <summary>AI-proposed table in Reader's model; it is a review candidate, not verified source structure.</summary>
public sealed record OfficeAiTable(ReaderTable Table, IReadOnlyList<OfficeAiCitation> Citations);

/// <summary>Snapshot-bound output from one document operation.</summary>
public sealed record OfficeAiResult {
    /// <summary>Stable result schema identifier.</summary>
    public string Schema => "officeimo.ai.result.v1";
    /// <summary>Operation identity generated by the engine.</summary>
    public required string RequestId { get; init; }
    /// <summary>Fingerprint of the original captured source.</summary>
    public required string SourceHash { get; init; }
    /// <summary>Fingerprint of the exact evidence projection used by this operation.</summary>
    public required string SnapshotHash { get; init; }
    /// <summary>Operation that produced this result.</summary>
    public OfficeAiOperation Operation { get; init; }
    /// <summary>Actual execution profile captured before inference.</summary>
    public required OfficeAiExecutionProfile Profile { get; init; }
    /// <summary>Terminal operation outcome.</summary>
    public OfficeAiResultStatus Status { get; init; }
    /// <summary>Claims with validated evidence references.</summary>
    public IReadOnlyList<OfficeAiClaim> Claims { get; init; } = Array.Empty<OfficeAiClaim>();
    /// <summary>Exactly the requested named field outcomes.</summary>
    public IReadOnlyList<OfficeAiField> Fields { get; init; } = Array.Empty<OfficeAiField>();
    /// <summary>Proposed structural blocks.</summary>
    public IReadOnlyList<OfficeAiBlock> Blocks { get; init; } = Array.Empty<OfficeAiBlock>();
    /// <summary>Proposed rectangular tables.</summary>
    public IReadOnlyList<OfficeAiTable> Tables { get; init; } = Array.Empty<OfficeAiTable>();
    /// <summary>Identifiers actually supplied in successfully validated model requests.</summary>
    public IReadOnlyList<string> ProcessedEvidenceIds { get; init; } = Array.Empty<string>();
    /// <summary>Selected identifiers omitted due to request bounds or validation failures.</summary>
    public IReadOnlyList<string> OmittedEvidenceIds { get; init; } = Array.Empty<string>();
    /// <summary>Known selected pages for which no text/image evidence was available.</summary>
    public IReadOnlyList<int> EmptyPages { get; init; } = Array.Empty<int>();
    /// <summary>Non-content diagnostic codes; raw provider errors and document text are excluded.</summary>
    public IReadOnlyList<string> Diagnostics { get; init; } = Array.Empty<string>();
    /// <summary>All model-authored interpretation requires review; quote matches do not prove semantic support.</summary>
    public bool RequiresReview => true;
    /// <summary>Input tokens only when every completed model request reports them.</summary>
    public long? InputTokens { get; init; }
    /// <summary>Output tokens only when every completed model request reports them.</summary>
    public long? OutputTokens { get; init; }
}
