// <auto-generated/>
// Generated by Build/Generate-PowerPointOpenXmlValueTypes.ps1. Do not edit by hand.
using System.Globalization;

namespace OfficeIMO.PowerPoint;

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.Charts.BuiltInUnitValues.</summary>
public enum PowerPointChartDisplayUnit {
    /// <summary>Represents the Open XML value <c>hundreds</c>.</summary>
    Hundreds,
    /// <summary>Represents the Open XML value <c>thousands</c>.</summary>
    Thousands,
    /// <summary>Represents the Open XML value <c>tenThousands</c>.</summary>
    TenThousands,
    /// <summary>Represents the Open XML value <c>hundredThousands</c>.</summary>
    HundredThousands,
    /// <summary>Represents the Open XML value <c>millions</c>.</summary>
    Millions,
    /// <summary>Represents the Open XML value <c>tenMillions</c>.</summary>
    TenMillions,
    /// <summary>Represents the Open XML value <c>hundredMillions</c>.</summary>
    HundredMillions,
    /// <summary>Represents the Open XML value <c>billions</c>.</summary>
    Billions,
    /// <summary>Represents the Open XML value <c>trillions</c>.</summary>
    Trillions,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.Charts.CrossBetweenValues.</summary>
public enum PowerPointChartAxisCrossBetween {
    /// <summary>Represents the Open XML value <c>between</c>.</summary>
    Between,
    /// <summary>Represents the Open XML value <c>midCat</c>.</summary>
    MidpointCategory,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.Charts.CrossesValues.</summary>
public enum PowerPointChartAxisCrossing {
    /// <summary>Represents the Open XML value <c>autoZero</c>.</summary>
    AutoZero,
    /// <summary>Represents the Open XML value <c>max</c>.</summary>
    Maximum,
    /// <summary>Represents the Open XML value <c>min</c>.</summary>
    Minimum,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.Charts.DataLabelPositionValues.</summary>
public enum PowerPointChartDataLabelPosition {
    /// <summary>Represents the Open XML value <c>bestFit</c>.</summary>
    BestFit,
    /// <summary>Represents the Open XML value <c>b</c>.</summary>
    Bottom,
    /// <summary>Represents the Open XML value <c>ctr</c>.</summary>
    Center,
    /// <summary>Represents the Open XML value <c>inBase</c>.</summary>
    InsideBase,
    /// <summary>Represents the Open XML value <c>inEnd</c>.</summary>
    InsideEnd,
    /// <summary>Represents the Open XML value <c>l</c>.</summary>
    Left,
    /// <summary>Represents the Open XML value <c>outEnd</c>.</summary>
    OutsideEnd,
    /// <summary>Represents the Open XML value <c>r</c>.</summary>
    Right,
    /// <summary>Represents the Open XML value <c>t</c>.</summary>
    Top,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.Charts.GroupingValues.</summary>
public enum PowerPointChartGrouping {
    /// <summary>Represents the Open XML value <c>percentStacked</c>.</summary>
    PercentStacked,
    /// <summary>Represents the Open XML value <c>standard</c>.</summary>
    Standard,
    /// <summary>Represents the Open XML value <c>stacked</c>.</summary>
    Stacked,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.Charts.LegendPositionValues.</summary>
public enum PowerPointChartLegendPosition {
    /// <summary>Represents the Open XML value <c>b</c>.</summary>
    Bottom,
    /// <summary>Represents the Open XML value <c>tr</c>.</summary>
    TopRight,
    /// <summary>Represents the Open XML value <c>l</c>.</summary>
    Left,
    /// <summary>Represents the Open XML value <c>r</c>.</summary>
    Right,
    /// <summary>Represents the Open XML value <c>t</c>.</summary>
    Top,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.Charts.MarkerStyleValues.</summary>
public enum PowerPointChartMarkerStyle {
    /// <summary>Represents the Open XML value <c>auto</c>.</summary>
    Auto,
    /// <summary>Represents the Open XML value <c>circle</c>.</summary>
    Circle,
    /// <summary>Represents the Open XML value <c>dash</c>.</summary>
    Dash,
    /// <summary>Represents the Open XML value <c>diamond</c>.</summary>
    Diamond,
    /// <summary>Represents the Open XML value <c>dot</c>.</summary>
    Dot,
    /// <summary>Represents the Open XML value <c>none</c>.</summary>
    None,
    /// <summary>Represents the Open XML value <c>picture</c>.</summary>
    Picture,
    /// <summary>Represents the Open XML value <c>plus</c>.</summary>
    Plus,
    /// <summary>Represents the Open XML value <c>square</c>.</summary>
    Square,
    /// <summary>Represents the Open XML value <c>star</c>.</summary>
    Star,
    /// <summary>Represents the Open XML value <c>triangle</c>.</summary>
    Triangle,
    /// <summary>Represents the Open XML value <c>x</c>.</summary>
    X,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.Charts.TickLabelPositionValues.</summary>
public enum PowerPointChartTickLabelPosition {
    /// <summary>Represents the Open XML value <c>high</c>.</summary>
    High,
    /// <summary>Represents the Open XML value <c>low</c>.</summary>
    Low,
    /// <summary>Represents the Open XML value <c>nextTo</c>.</summary>
    NextTo,
    /// <summary>Represents the Open XML value <c>none</c>.</summary>
    None,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.Charts.TrendlineValues.</summary>
public enum PowerPointChartTrendlineType {
    /// <summary>Represents the Open XML value <c>exp</c>.</summary>
    Exponential,
    /// <summary>Represents the Open XML value <c>linear</c>.</summary>
    Linear,
    /// <summary>Represents the Open XML value <c>log</c>.</summary>
    Logarithmic,
    /// <summary>Represents the Open XML value <c>movingAvg</c>.</summary>
    MovingAverage,
    /// <summary>Represents the Open XML value <c>poly</c>.</summary>
    Polynomial,
    /// <summary>Represents the Open XML value <c>power</c>.</summary>
    Power,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.LineEndLengthValues.</summary>
public enum PowerPointLineEndLength {
    /// <summary>Represents the Open XML value <c>sm</c>.</summary>
    Small,
    /// <summary>Represents the Open XML value <c>med</c>.</summary>
    Medium,
    /// <summary>Represents the Open XML value <c>lg</c>.</summary>
    Large,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.LineEndValues.</summary>
public enum PowerPointLineEndType {
    /// <summary>Represents the Open XML value <c>none</c>.</summary>
    None,
    /// <summary>Represents the Open XML value <c>triangle</c>.</summary>
    Triangle,
    /// <summary>Represents the Open XML value <c>stealth</c>.</summary>
    Stealth,
    /// <summary>Represents the Open XML value <c>diamond</c>.</summary>
    Diamond,
    /// <summary>Represents the Open XML value <c>oval</c>.</summary>
    Oval,
    /// <summary>Represents the Open XML value <c>arrow</c>.</summary>
    Arrow,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.LineEndWidthValues.</summary>
public enum PowerPointLineEndWidth {
    /// <summary>Represents the Open XML value <c>sm</c>.</summary>
    Small,
    /// <summary>Represents the Open XML value <c>med</c>.</summary>
    Medium,
    /// <summary>Represents the Open XML value <c>lg</c>.</summary>
    Large,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.PresetLineDashValues.</summary>
public enum PowerPointLineDashStyle {
    /// <summary>Represents the Open XML value <c>solid</c>.</summary>
    Solid,
    /// <summary>Represents the Open XML value <c>dot</c>.</summary>
    Dot,
    /// <summary>Represents the Open XML value <c>dash</c>.</summary>
    Dash,
    /// <summary>Represents the Open XML value <c>lgDash</c>.</summary>
    LargeDash,
    /// <summary>Represents the Open XML value <c>dashDot</c>.</summary>
    DashDot,
    /// <summary>Represents the Open XML value <c>lgDashDot</c>.</summary>
    LargeDashDot,
    /// <summary>Represents the Open XML value <c>lgDashDotDot</c>.</summary>
    LargeDashDotDot,
    /// <summary>Represents the Open XML value <c>sysDash</c>.</summary>
    SystemDash,
    /// <summary>Represents the Open XML value <c>sysDot</c>.</summary>
    SystemDot,
    /// <summary>Represents the Open XML value <c>sysDashDot</c>.</summary>
    SystemDashDot,
    /// <summary>Represents the Open XML value <c>sysDashDotDot</c>.</summary>
    SystemDashDotDot,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.RectangleAlignmentValues.</summary>
public enum PowerPointRectangleAlignment {
    /// <summary>Represents the Open XML value <c>tl</c>.</summary>
    TopLeft,
    /// <summary>Represents the Open XML value <c>t</c>.</summary>
    Top,
    /// <summary>Represents the Open XML value <c>tr</c>.</summary>
    TopRight,
    /// <summary>Represents the Open XML value <c>l</c>.</summary>
    Left,
    /// <summary>Represents the Open XML value <c>ctr</c>.</summary>
    Center,
    /// <summary>Represents the Open XML value <c>r</c>.</summary>
    Right,
    /// <summary>Represents the Open XML value <c>bl</c>.</summary>
    BottomLeft,
    /// <summary>Represents the Open XML value <c>b</c>.</summary>
    Bottom,
    /// <summary>Represents the Open XML value <c>br</c>.</summary>
    BottomRight,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.ShapeTypeValues.</summary>
public enum PowerPointShapeType {
    /// <summary>Represents the Open XML value <c>line</c>.</summary>
    Line,
    /// <summary>Represents the Open XML value <c>lineInv</c>.</summary>
    LineInverse,
    /// <summary>Represents the Open XML value <c>triangle</c>.</summary>
    Triangle,
    /// <summary>Represents the Open XML value <c>rtTriangle</c>.</summary>
    RightTriangle,
    /// <summary>Represents the Open XML value <c>rect</c>.</summary>
    Rectangle,
    /// <summary>Represents the Open XML value <c>diamond</c>.</summary>
    Diamond,
    /// <summary>Represents the Open XML value <c>parallelogram</c>.</summary>
    Parallelogram,
    /// <summary>Represents the Open XML value <c>trapezoid</c>.</summary>
    Trapezoid,
    /// <summary>Represents the Open XML value <c>nonIsoscelesTrapezoid</c>.</summary>
    NonIsoscelesTrapezoid,
    /// <summary>Represents the Open XML value <c>pentagon</c>.</summary>
    Pentagon,
    /// <summary>Represents the Open XML value <c>hexagon</c>.</summary>
    Hexagon,
    /// <summary>Represents the Open XML value <c>heptagon</c>.</summary>
    Heptagon,
    /// <summary>Represents the Open XML value <c>octagon</c>.</summary>
    Octagon,
    /// <summary>Represents the Open XML value <c>decagon</c>.</summary>
    Decagon,
    /// <summary>Represents the Open XML value <c>dodecagon</c>.</summary>
    Dodecagon,
    /// <summary>Represents the Open XML value <c>star4</c>.</summary>
    Star4,
    /// <summary>Represents the Open XML value <c>star5</c>.</summary>
    Star5,
    /// <summary>Represents the Open XML value <c>star6</c>.</summary>
    Star6,
    /// <summary>Represents the Open XML value <c>star7</c>.</summary>
    Star7,
    /// <summary>Represents the Open XML value <c>star8</c>.</summary>
    Star8,
    /// <summary>Represents the Open XML value <c>star10</c>.</summary>
    Star10,
    /// <summary>Represents the Open XML value <c>star12</c>.</summary>
    Star12,
    /// <summary>Represents the Open XML value <c>star16</c>.</summary>
    Star16,
    /// <summary>Represents the Open XML value <c>star24</c>.</summary>
    Star24,
    /// <summary>Represents the Open XML value <c>star32</c>.</summary>
    Star32,
    /// <summary>Represents the Open XML value <c>roundRect</c>.</summary>
    RoundRectangle,
    /// <summary>Represents the Open XML value <c>round1Rect</c>.</summary>
    Round1Rectangle,
    /// <summary>Represents the Open XML value <c>round2SameRect</c>.</summary>
    Round2SameRectangle,
    /// <summary>Represents the Open XML value <c>round2DiagRect</c>.</summary>
    Round2DiagonalRectangle,
    /// <summary>Represents the Open XML value <c>snipRoundRect</c>.</summary>
    SnipRoundRectangle,
    /// <summary>Represents the Open XML value <c>snip1Rect</c>.</summary>
    Snip1Rectangle,
    /// <summary>Represents the Open XML value <c>snip2SameRect</c>.</summary>
    Snip2SameRectangle,
    /// <summary>Represents the Open XML value <c>snip2DiagRect</c>.</summary>
    Snip2DiagonalRectangle,
    /// <summary>Represents the Open XML value <c>plaque</c>.</summary>
    Plaque,
    /// <summary>Represents the Open XML value <c>ellipse</c>.</summary>
    Ellipse,
    /// <summary>Represents the Open XML value <c>teardrop</c>.</summary>
    Teardrop,
    /// <summary>Represents the Open XML value <c>homePlate</c>.</summary>
    HomePlate,
    /// <summary>Represents the Open XML value <c>chevron</c>.</summary>
    Chevron,
    /// <summary>Represents the Open XML value <c>pieWedge</c>.</summary>
    PieWedge,
    /// <summary>Represents the Open XML value <c>pie</c>.</summary>
    Pie,
    /// <summary>Represents the Open XML value <c>blockArc</c>.</summary>
    BlockArc,
    /// <summary>Represents the Open XML value <c>donut</c>.</summary>
    Donut,
    /// <summary>Represents the Open XML value <c>noSmoking</c>.</summary>
    NoSmoking,
    /// <summary>Represents the Open XML value <c>rightArrow</c>.</summary>
    RightArrow,
    /// <summary>Represents the Open XML value <c>leftArrow</c>.</summary>
    LeftArrow,
    /// <summary>Represents the Open XML value <c>upArrow</c>.</summary>
    UpArrow,
    /// <summary>Represents the Open XML value <c>downArrow</c>.</summary>
    DownArrow,
    /// <summary>Represents the Open XML value <c>stripedRightArrow</c>.</summary>
    StripedRightArrow,
    /// <summary>Represents the Open XML value <c>notchedRightArrow</c>.</summary>
    NotchedRightArrow,
    /// <summary>Represents the Open XML value <c>bentUpArrow</c>.</summary>
    BentUpArrow,
    /// <summary>Represents the Open XML value <c>leftRightArrow</c>.</summary>
    LeftRightArrow,
    /// <summary>Represents the Open XML value <c>upDownArrow</c>.</summary>
    UpDownArrow,
    /// <summary>Represents the Open XML value <c>leftUpArrow</c>.</summary>
    LeftUpArrow,
    /// <summary>Represents the Open XML value <c>leftRightUpArrow</c>.</summary>
    LeftRightUpArrow,
    /// <summary>Represents the Open XML value <c>quadArrow</c>.</summary>
    QuadArrow,
    /// <summary>Represents the Open XML value <c>leftArrowCallout</c>.</summary>
    LeftArrowCallout,
    /// <summary>Represents the Open XML value <c>rightArrowCallout</c>.</summary>
    RightArrowCallout,
    /// <summary>Represents the Open XML value <c>upArrowCallout</c>.</summary>
    UpArrowCallout,
    /// <summary>Represents the Open XML value <c>downArrowCallout</c>.</summary>
    DownArrowCallout,
    /// <summary>Represents the Open XML value <c>leftRightArrowCallout</c>.</summary>
    LeftRightArrowCallout,
    /// <summary>Represents the Open XML value <c>upDownArrowCallout</c>.</summary>
    UpDownArrowCallout,
    /// <summary>Represents the Open XML value <c>quadArrowCallout</c>.</summary>
    QuadArrowCallout,
    /// <summary>Represents the Open XML value <c>bentArrow</c>.</summary>
    BentArrow,
    /// <summary>Represents the Open XML value <c>uturnArrow</c>.</summary>
    UTurnArrow,
    /// <summary>Represents the Open XML value <c>circularArrow</c>.</summary>
    CircularArrow,
    /// <summary>Represents the Open XML value <c>leftCircularArrow</c>.</summary>
    LeftCircularArrow,
    /// <summary>Represents the Open XML value <c>leftRightCircularArrow</c>.</summary>
    LeftRightCircularArrow,
    /// <summary>Represents the Open XML value <c>curvedRightArrow</c>.</summary>
    CurvedRightArrow,
    /// <summary>Represents the Open XML value <c>curvedLeftArrow</c>.</summary>
    CurvedLeftArrow,
    /// <summary>Represents the Open XML value <c>curvedUpArrow</c>.</summary>
    CurvedUpArrow,
    /// <summary>Represents the Open XML value <c>curvedDownArrow</c>.</summary>
    CurvedDownArrow,
    /// <summary>Represents the Open XML value <c>swooshArrow</c>.</summary>
    SwooshArrow,
    /// <summary>Represents the Open XML value <c>cube</c>.</summary>
    Cube,
    /// <summary>Represents the Open XML value <c>can</c>.</summary>
    Can,
    /// <summary>Represents the Open XML value <c>lightningBolt</c>.</summary>
    LightningBolt,
    /// <summary>Represents the Open XML value <c>heart</c>.</summary>
    Heart,
    /// <summary>Represents the Open XML value <c>sun</c>.</summary>
    Sun,
    /// <summary>Represents the Open XML value <c>moon</c>.</summary>
    Moon,
    /// <summary>Represents the Open XML value <c>smileyFace</c>.</summary>
    SmileyFace,
    /// <summary>Represents the Open XML value <c>irregularSeal1</c>.</summary>
    IrregularSeal1,
    /// <summary>Represents the Open XML value <c>irregularSeal2</c>.</summary>
    IrregularSeal2,
    /// <summary>Represents the Open XML value <c>foldedCorner</c>.</summary>
    FoldedCorner,
    /// <summary>Represents the Open XML value <c>bevel</c>.</summary>
    Bevel,
    /// <summary>Represents the Open XML value <c>frame</c>.</summary>
    Frame,
    /// <summary>Represents the Open XML value <c>halfFrame</c>.</summary>
    HalfFrame,
    /// <summary>Represents the Open XML value <c>corner</c>.</summary>
    Corner,
    /// <summary>Represents the Open XML value <c>diagStripe</c>.</summary>
    DiagonalStripe,
    /// <summary>Represents the Open XML value <c>chord</c>.</summary>
    Chord,
    /// <summary>Represents the Open XML value <c>arc</c>.</summary>
    Arc,
    /// <summary>Represents the Open XML value <c>leftBracket</c>.</summary>
    LeftBracket,
    /// <summary>Represents the Open XML value <c>rightBracket</c>.</summary>
    RightBracket,
    /// <summary>Represents the Open XML value <c>leftBrace</c>.</summary>
    LeftBrace,
    /// <summary>Represents the Open XML value <c>rightBrace</c>.</summary>
    RightBrace,
    /// <summary>Represents the Open XML value <c>bracketPair</c>.</summary>
    BracketPair,
    /// <summary>Represents the Open XML value <c>bracePair</c>.</summary>
    BracePair,
    /// <summary>Represents the Open XML value <c>straightConnector1</c>.</summary>
    StraightConnector1,
    /// <summary>Represents the Open XML value <c>bentConnector2</c>.</summary>
    BentConnector2,
    /// <summary>Represents the Open XML value <c>bentConnector3</c>.</summary>
    BentConnector3,
    /// <summary>Represents the Open XML value <c>bentConnector4</c>.</summary>
    BentConnector4,
    /// <summary>Represents the Open XML value <c>bentConnector5</c>.</summary>
    BentConnector5,
    /// <summary>Represents the Open XML value <c>curvedConnector2</c>.</summary>
    CurvedConnector2,
    /// <summary>Represents the Open XML value <c>curvedConnector3</c>.</summary>
    CurvedConnector3,
    /// <summary>Represents the Open XML value <c>curvedConnector4</c>.</summary>
    CurvedConnector4,
    /// <summary>Represents the Open XML value <c>curvedConnector5</c>.</summary>
    CurvedConnector5,
    /// <summary>Represents the Open XML value <c>callout1</c>.</summary>
    Callout1,
    /// <summary>Represents the Open XML value <c>callout2</c>.</summary>
    Callout2,
    /// <summary>Represents the Open XML value <c>callout3</c>.</summary>
    Callout3,
    /// <summary>Represents the Open XML value <c>accentCallout1</c>.</summary>
    AccentCallout1,
    /// <summary>Represents the Open XML value <c>accentCallout2</c>.</summary>
    AccentCallout2,
    /// <summary>Represents the Open XML value <c>accentCallout3</c>.</summary>
    AccentCallout3,
    /// <summary>Represents the Open XML value <c>borderCallout1</c>.</summary>
    BorderCallout1,
    /// <summary>Represents the Open XML value <c>borderCallout2</c>.</summary>
    BorderCallout2,
    /// <summary>Represents the Open XML value <c>borderCallout3</c>.</summary>
    BorderCallout3,
    /// <summary>Represents the Open XML value <c>accentBorderCallout1</c>.</summary>
    AccentBorderCallout1,
    /// <summary>Represents the Open XML value <c>accentBorderCallout2</c>.</summary>
    AccentBorderCallout2,
    /// <summary>Represents the Open XML value <c>accentBorderCallout3</c>.</summary>
    AccentBorderCallout3,
    /// <summary>Represents the Open XML value <c>wedgeRectCallout</c>.</summary>
    WedgeRectangleCallout,
    /// <summary>Represents the Open XML value <c>wedgeRoundRectCallout</c>.</summary>
    WedgeRoundRectangleCallout,
    /// <summary>Represents the Open XML value <c>wedgeEllipseCallout</c>.</summary>
    WedgeEllipseCallout,
    /// <summary>Represents the Open XML value <c>cloudCallout</c>.</summary>
    CloudCallout,
    /// <summary>Represents the Open XML value <c>cloud</c>.</summary>
    Cloud,
    /// <summary>Represents the Open XML value <c>ribbon</c>.</summary>
    Ribbon,
    /// <summary>Represents the Open XML value <c>ribbon2</c>.</summary>
    Ribbon2,
    /// <summary>Represents the Open XML value <c>ellipseRibbon</c>.</summary>
    EllipseRibbon,
    /// <summary>Represents the Open XML value <c>ellipseRibbon2</c>.</summary>
    EllipseRibbon2,
    /// <summary>Represents the Open XML value <c>leftRightRibbon</c>.</summary>
    LeftRightRibbon,
    /// <summary>Represents the Open XML value <c>verticalScroll</c>.</summary>
    VerticalScroll,
    /// <summary>Represents the Open XML value <c>horizontalScroll</c>.</summary>
    HorizontalScroll,
    /// <summary>Represents the Open XML value <c>wave</c>.</summary>
    Wave,
    /// <summary>Represents the Open XML value <c>doubleWave</c>.</summary>
    DoubleWave,
    /// <summary>Represents the Open XML value <c>plus</c>.</summary>
    Plus,
    /// <summary>Represents the Open XML value <c>flowChartProcess</c>.</summary>
    FlowChartProcess,
    /// <summary>Represents the Open XML value <c>flowChartDecision</c>.</summary>
    FlowChartDecision,
    /// <summary>Represents the Open XML value <c>flowChartInputOutput</c>.</summary>
    FlowChartInputOutput,
    /// <summary>Represents the Open XML value <c>flowChartPredefinedProcess</c>.</summary>
    FlowChartPredefinedProcess,
    /// <summary>Represents the Open XML value <c>flowChartInternalStorage</c>.</summary>
    FlowChartInternalStorage,
    /// <summary>Represents the Open XML value <c>flowChartDocument</c>.</summary>
    FlowChartDocument,
    /// <summary>Represents the Open XML value <c>flowChartMultidocument</c>.</summary>
    FlowChartMultidocument,
    /// <summary>Represents the Open XML value <c>flowChartTerminator</c>.</summary>
    FlowChartTerminator,
    /// <summary>Represents the Open XML value <c>flowChartPreparation</c>.</summary>
    FlowChartPreparation,
    /// <summary>Represents the Open XML value <c>flowChartManualInput</c>.</summary>
    FlowChartManualInput,
    /// <summary>Represents the Open XML value <c>flowChartManualOperation</c>.</summary>
    FlowChartManualOperation,
    /// <summary>Represents the Open XML value <c>flowChartConnector</c>.</summary>
    FlowChartConnector,
    /// <summary>Represents the Open XML value <c>flowChartPunchedCard</c>.</summary>
    FlowChartPunchedCard,
    /// <summary>Represents the Open XML value <c>flowChartPunchedTape</c>.</summary>
    FlowChartPunchedTape,
    /// <summary>Represents the Open XML value <c>flowChartSummingJunction</c>.</summary>
    FlowChartSummingJunction,
    /// <summary>Represents the Open XML value <c>flowChartOr</c>.</summary>
    FlowChartOr,
    /// <summary>Represents the Open XML value <c>flowChartCollate</c>.</summary>
    FlowChartCollate,
    /// <summary>Represents the Open XML value <c>flowChartSort</c>.</summary>
    FlowChartSort,
    /// <summary>Represents the Open XML value <c>flowChartExtract</c>.</summary>
    FlowChartExtract,
    /// <summary>Represents the Open XML value <c>flowChartMerge</c>.</summary>
    FlowChartMerge,
    /// <summary>Represents the Open XML value <c>flowChartOfflineStorage</c>.</summary>
    FlowChartOfflineStorage,
    /// <summary>Represents the Open XML value <c>flowChartOnlineStorage</c>.</summary>
    FlowChartOnlineStorage,
    /// <summary>Represents the Open XML value <c>flowChartMagneticTape</c>.</summary>
    FlowChartMagneticTape,
    /// <summary>Represents the Open XML value <c>flowChartMagneticDisk</c>.</summary>
    FlowChartMagneticDisk,
    /// <summary>Represents the Open XML value <c>flowChartMagneticDrum</c>.</summary>
    FlowChartMagneticDrum,
    /// <summary>Represents the Open XML value <c>flowChartDisplay</c>.</summary>
    FlowChartDisplay,
    /// <summary>Represents the Open XML value <c>flowChartDelay</c>.</summary>
    FlowChartDelay,
    /// <summary>Represents the Open XML value <c>flowChartAlternateProcess</c>.</summary>
    FlowChartAlternateProcess,
    /// <summary>Represents the Open XML value <c>flowChartOffpageConnector</c>.</summary>
    FlowChartOffpageConnector,
    /// <summary>Represents the Open XML value <c>actionButtonBlank</c>.</summary>
    ActionButtonBlank,
    /// <summary>Represents the Open XML value <c>actionButtonHome</c>.</summary>
    ActionButtonHome,
    /// <summary>Represents the Open XML value <c>actionButtonHelp</c>.</summary>
    ActionButtonHelp,
    /// <summary>Represents the Open XML value <c>actionButtonInformation</c>.</summary>
    ActionButtonInformation,
    /// <summary>Represents the Open XML value <c>actionButtonForwardNext</c>.</summary>
    ActionButtonForwardNext,
    /// <summary>Represents the Open XML value <c>actionButtonBackPrevious</c>.</summary>
    ActionButtonBackPrevious,
    /// <summary>Represents the Open XML value <c>actionButtonEnd</c>.</summary>
    ActionButtonEnd,
    /// <summary>Represents the Open XML value <c>actionButtonBeginning</c>.</summary>
    ActionButtonBeginning,
    /// <summary>Represents the Open XML value <c>actionButtonReturn</c>.</summary>
    ActionButtonReturn,
    /// <summary>Represents the Open XML value <c>actionButtonDocument</c>.</summary>
    ActionButtonDocument,
    /// <summary>Represents the Open XML value <c>actionButtonSound</c>.</summary>
    ActionButtonSound,
    /// <summary>Represents the Open XML value <c>actionButtonMovie</c>.</summary>
    ActionButtonMovie,
    /// <summary>Represents the Open XML value <c>gear6</c>.</summary>
    Gear6,
    /// <summary>Represents the Open XML value <c>gear9</c>.</summary>
    Gear9,
    /// <summary>Represents the Open XML value <c>funnel</c>.</summary>
    Funnel,
    /// <summary>Represents the Open XML value <c>mathPlus</c>.</summary>
    MathPlus,
    /// <summary>Represents the Open XML value <c>mathMinus</c>.</summary>
    MathMinus,
    /// <summary>Represents the Open XML value <c>mathMultiply</c>.</summary>
    MathMultiply,
    /// <summary>Represents the Open XML value <c>mathDivide</c>.</summary>
    MathDivide,
    /// <summary>Represents the Open XML value <c>mathEqual</c>.</summary>
    MathEqual,
    /// <summary>Represents the Open XML value <c>mathNotEqual</c>.</summary>
    MathNotEqual,
    /// <summary>Represents the Open XML value <c>cornerTabs</c>.</summary>
    CornerTabs,
    /// <summary>Represents the Open XML value <c>squareTabs</c>.</summary>
    SquareTabs,
    /// <summary>Represents the Open XML value <c>plaqueTabs</c>.</summary>
    PlaqueTabs,
    /// <summary>Represents the Open XML value <c>chartX</c>.</summary>
    ChartX,
    /// <summary>Represents the Open XML value <c>chartStar</c>.</summary>
    ChartStar,
    /// <summary>Represents the Open XML value <c>chartPlus</c>.</summary>
    ChartPlus,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.TextAlignmentTypeValues.</summary>
public enum PowerPointTextAlignment {
    /// <summary>Represents the Open XML value <c>l</c>.</summary>
    Left,
    /// <summary>Represents the Open XML value <c>ctr</c>.</summary>
    Center,
    /// <summary>Represents the Open XML value <c>r</c>.</summary>
    Right,
    /// <summary>Represents the Open XML value <c>just</c>.</summary>
    Justified,
    /// <summary>Represents the Open XML value <c>justLow</c>.</summary>
    JustifiedLow,
    /// <summary>Represents the Open XML value <c>dist</c>.</summary>
    Distributed,
    /// <summary>Represents the Open XML value <c>thaiDist</c>.</summary>
    ThaiDistributed,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.TextAnchoringTypeValues.</summary>
public enum PowerPointTextVerticalAlignment {
    /// <summary>Represents the Open XML value <c>t</c>.</summary>
    Top,
    /// <summary>Represents the Open XML value <c>ctr</c>.</summary>
    Center,
    /// <summary>Represents the Open XML value <c>b</c>.</summary>
    Bottom,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.TextAutoNumberSchemeValues.</summary>
public enum PowerPointNumberingScheme {
    /// <summary>Represents the Open XML value <c>alphaLcParenBoth</c>.</summary>
    AlphaLowerCharacterParenBoth,
    /// <summary>Represents the Open XML value <c>alphaUcParenBoth</c>.</summary>
    AlphaUpperCharacterParenBoth,
    /// <summary>Represents the Open XML value <c>alphaLcParenR</c>.</summary>
    AlphaLowerCharacterParenR,
    /// <summary>Represents the Open XML value <c>alphaUcParenR</c>.</summary>
    AlphaUpperCharacterParenR,
    /// <summary>Represents the Open XML value <c>alphaLcPeriod</c>.</summary>
    AlphaLowerCharacterPeriod,
    /// <summary>Represents the Open XML value <c>alphaUcPeriod</c>.</summary>
    AlphaUpperCharacterPeriod,
    /// <summary>Represents the Open XML value <c>arabicParenBoth</c>.</summary>
    ArabicParenBoth,
    /// <summary>Represents the Open XML value <c>arabicParenR</c>.</summary>
    ArabicParenR,
    /// <summary>Represents the Open XML value <c>arabicPeriod</c>.</summary>
    ArabicPeriod,
    /// <summary>Represents the Open XML value <c>arabicPlain</c>.</summary>
    ArabicPlain,
    /// <summary>Represents the Open XML value <c>romanLcParenBoth</c>.</summary>
    RomanLowerCharacterParenBoth,
    /// <summary>Represents the Open XML value <c>romanUcParenBoth</c>.</summary>
    RomanUpperCharacterParenBoth,
    /// <summary>Represents the Open XML value <c>romanLcParenR</c>.</summary>
    RomanLowerCharacterParenR,
    /// <summary>Represents the Open XML value <c>romanUcParenR</c>.</summary>
    RomanUpperCharacterParenR,
    /// <summary>Represents the Open XML value <c>romanLcPeriod</c>.</summary>
    RomanLowerCharacterPeriod,
    /// <summary>Represents the Open XML value <c>romanUcPeriod</c>.</summary>
    RomanUpperCharacterPeriod,
    /// <summary>Represents the Open XML value <c>circleNumDbPlain</c>.</summary>
    CircleNumberDoubleBytePlain,
    /// <summary>Represents the Open XML value <c>circleNumWdBlackPlain</c>.</summary>
    CircleNumberWingdingsBlackPlain,
    /// <summary>Represents the Open XML value <c>circleNumWdWhitePlain</c>.</summary>
    CircleNumberWingdingsWhitePlain,
    /// <summary>Represents the Open XML value <c>arabicDbPeriod</c>.</summary>
    ArabicDoubleBytePeriod,
    /// <summary>Represents the Open XML value <c>arabicDbPlain</c>.</summary>
    ArabicDoubleBytePlain,
    /// <summary>Represents the Open XML value <c>ea1ChsPeriod</c>.</summary>
    EastAsianSimplifiedChinesePeriod,
    /// <summary>Represents the Open XML value <c>ea1ChsPlain</c>.</summary>
    EastAsianSimplifiedChinesePlain,
    /// <summary>Represents the Open XML value <c>ea1ChtPeriod</c>.</summary>
    EastAsianTraditionalChinesePeriod,
    /// <summary>Represents the Open XML value <c>ea1ChtPlain</c>.</summary>
    EastAsianTraditionalChinesePlain,
    /// <summary>Represents the Open XML value <c>ea1JpnChsDbPeriod</c>.</summary>
    EastAsianJapaneseDoubleBytePeriod,
    /// <summary>Represents the Open XML value <c>ea1JpnKorPlain</c>.</summary>
    EastAsianJapaneseKoreanPlain,
    /// <summary>Represents the Open XML value <c>ea1JpnKorPeriod</c>.</summary>
    EastAsianJapaneseKoreanPeriod,
    /// <summary>Represents the Open XML value <c>arabic1Minus</c>.</summary>
    Arabic1Minus,
    /// <summary>Represents the Open XML value <c>arabic2Minus</c>.</summary>
    Arabic2Minus,
    /// <summary>Represents the Open XML value <c>hebrew2Minus</c>.</summary>
    Hebrew2Minus,
    /// <summary>Represents the Open XML value <c>thaiAlphaPeriod</c>.</summary>
    ThaiAlphaPeriod,
    /// <summary>Represents the Open XML value <c>thaiAlphaParenR</c>.</summary>
    ThaiAlphaParenthesisRight,
    /// <summary>Represents the Open XML value <c>thaiAlphaParenBoth</c>.</summary>
    ThaiAlphaParenthesisBoth,
    /// <summary>Represents the Open XML value <c>thaiNumPeriod</c>.</summary>
    ThaiNumberPeriod,
    /// <summary>Represents the Open XML value <c>thaiNumParenR</c>.</summary>
    ThaiNumberParenthesisRight,
    /// <summary>Represents the Open XML value <c>thaiNumParenBoth</c>.</summary>
    ThaiNumberParenthesisBoth,
    /// <summary>Represents the Open XML value <c>hindiAlphaPeriod</c>.</summary>
    HindiAlphaPeriod,
    /// <summary>Represents the Open XML value <c>hindiNumPeriod</c>.</summary>
    HindiNumPeriod,
    /// <summary>Represents the Open XML value <c>hindiNumParenR</c>.</summary>
    HindiNumberParenthesisRight,
    /// <summary>Represents the Open XML value <c>hindiAlpha1Period</c>.</summary>
    HindiAlpha1Period,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.TextUnderlineValues.</summary>
public enum PowerPointUnderlineStyle {
    /// <summary>Represents the Open XML value <c>none</c>.</summary>
    None,
    /// <summary>Represents the Open XML value <c>words</c>.</summary>
    Words,
    /// <summary>Represents the Open XML value <c>sng</c>.</summary>
    Single,
    /// <summary>Represents the Open XML value <c>dbl</c>.</summary>
    Double,
    /// <summary>Represents the Open XML value <c>heavy</c>.</summary>
    Heavy,
    /// <summary>Represents the Open XML value <c>dotted</c>.</summary>
    Dotted,
    /// <summary>Represents the Open XML value <c>dottedHeavy</c>.</summary>
    HeavyDotted,
    /// <summary>Represents the Open XML value <c>dash</c>.</summary>
    Dash,
    /// <summary>Represents the Open XML value <c>dashHeavy</c>.</summary>
    DashHeavy,
    /// <summary>Represents the Open XML value <c>dashLong</c>.</summary>
    DashLong,
    /// <summary>Represents the Open XML value <c>dashLongHeavy</c>.</summary>
    DashLongHeavy,
    /// <summary>Represents the Open XML value <c>dotDash</c>.</summary>
    DotDash,
    /// <summary>Represents the Open XML value <c>dotDashHeavy</c>.</summary>
    DotDashHeavy,
    /// <summary>Represents the Open XML value <c>dotDotDash</c>.</summary>
    DotDotDash,
    /// <summary>Represents the Open XML value <c>dotDotDashHeavy</c>.</summary>
    DotDotDashHeavy,
    /// <summary>Represents the Open XML value <c>wavy</c>.</summary>
    Wavy,
    /// <summary>Represents the Open XML value <c>wavyHeavy</c>.</summary>
    WavyHeavy,
    /// <summary>Represents the Open XML value <c>wavyDbl</c>.</summary>
    WavyDouble,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.TextVerticalValues.</summary>
public enum PowerPointTextDirection {
    /// <summary>Represents the Open XML value <c>horz</c>.</summary>
    Horizontal,
    /// <summary>Represents the Open XML value <c>vert</c>.</summary>
    Vertical,
    /// <summary>Represents the Open XML value <c>vert270</c>.</summary>
    Vertical270,
    /// <summary>Represents the Open XML value <c>wordArtVert</c>.</summary>
    WordArtVertical,
    /// <summary>Represents the Open XML value <c>eaVert</c>.</summary>
    EastAsianVetical,
    /// <summary>Represents the Open XML value <c>mongolianVert</c>.</summary>
    MongolianVertical,
    /// <summary>Represents the Open XML value <c>wordArtVertRtl</c>.</summary>
    WordArtLeftToRight,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Presentation.CommandValues.</summary>
public enum PowerPointAnimationCommand {
    /// <summary>Represents the Open XML value <c>evt</c>.</summary>
    Event,
    /// <summary>Represents the Open XML value <c>call</c>.</summary>
    Call,
    /// <summary>Represents the Open XML value <c>verb</c>.</summary>
    Verb,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Presentation.DirectionValues.</summary>
public enum PowerPointPlaceholderDirection {
    /// <summary>Represents the Open XML value <c>horz</c>.</summary>
    Horizontal,
    /// <summary>Represents the Open XML value <c>vert</c>.</summary>
    Vertical,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Presentation.OleObjectFollowColorSchemeValues.</summary>
public enum PowerPointOleFollowColorScheme {
    /// <summary>Represents the Open XML value <c>none</c>.</summary>
    None,
    /// <summary>Represents the Open XML value <c>full</c>.</summary>
    Full,
    /// <summary>Represents the Open XML value <c>textAndBackground</c>.</summary>
    TextAndBackground,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Presentation.PlaceholderSizeValues.</summary>
public enum PowerPointPlaceholderSize {
    /// <summary>Represents the Open XML value <c>full</c>.</summary>
    Full,
    /// <summary>Represents the Open XML value <c>half</c>.</summary>
    Half,
    /// <summary>Represents the Open XML value <c>quarter</c>.</summary>
    Quarter,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Presentation.PlaceholderValues.</summary>
public enum PowerPointPlaceholderType {
    /// <summary>Represents the Open XML value <c>title</c>.</summary>
    Title,
    /// <summary>Represents the Open XML value <c>body</c>.</summary>
    Body,
    /// <summary>Represents the Open XML value <c>ctrTitle</c>.</summary>
    CenteredTitle,
    /// <summary>Represents the Open XML value <c>subTitle</c>.</summary>
    SubTitle,
    /// <summary>Represents the Open XML value <c>dt</c>.</summary>
    DateAndTime,
    /// <summary>Represents the Open XML value <c>sldNum</c>.</summary>
    SlideNumber,
    /// <summary>Represents the Open XML value <c>ftr</c>.</summary>
    Footer,
    /// <summary>Represents the Open XML value <c>hdr</c>.</summary>
    Header,
    /// <summary>Represents the Open XML value <c>obj</c>.</summary>
    Object,
    /// <summary>Represents the Open XML value <c>chart</c>.</summary>
    Chart,
    /// <summary>Represents the Open XML value <c>tbl</c>.</summary>
    Table,
    /// <summary>Represents the Open XML value <c>clipArt</c>.</summary>
    ClipArt,
    /// <summary>Represents the Open XML value <c>dgm</c>.</summary>
    Diagram,
    /// <summary>Represents the Open XML value <c>media</c>.</summary>
    Media,
    /// <summary>Represents the Open XML value <c>sldImg</c>.</summary>
    SlideImage,
    /// <summary>Represents the Open XML value <c>pic</c>.</summary>
    Picture,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Presentation.SlideSizeValues.</summary>
public enum PowerPointSlideSizeType {
    /// <summary>Represents the Open XML value <c>screen4x3</c>.</summary>
    Screen4x3,
    /// <summary>Represents the Open XML value <c>letter</c>.</summary>
    Letter,
    /// <summary>Represents the Open XML value <c>A4</c>.</summary>
    A4,
    /// <summary>Represents the Open XML value <c>35mm</c>.</summary>
    Film35mm,
    /// <summary>Represents the Open XML value <c>overhead</c>.</summary>
    Overhead,
    /// <summary>Represents the Open XML value <c>banner</c>.</summary>
    Banner,
    /// <summary>Represents the Open XML value <c>custom</c>.</summary>
    Custom,
    /// <summary>Represents the Open XML value <c>ledger</c>.</summary>
    Ledger,
    /// <summary>Represents the Open XML value <c>A3</c>.</summary>
    A3,
    /// <summary>Represents the Open XML value <c>B4ISO</c>.</summary>
    B4ISO,
    /// <summary>Represents the Open XML value <c>B5ISO</c>.</summary>
    B5ISO,
    /// <summary>Represents the Open XML value <c>B4JIS</c>.</summary>
    B4JIS,
    /// <summary>Represents the Open XML value <c>B5JIS</c>.</summary>
    B5JIS,
    /// <summary>Represents the Open XML value <c>hagakiCard</c>.</summary>
    HagakiCard,
    /// <summary>Represents the Open XML value <c>screen16x9</c>.</summary>
    Screen16x9,
    /// <summary>Represents the Open XML value <c>screen16x10</c>.</summary>
    Screen16x10,
}

internal static class PowerPointOpenXmlValueTypeExtensions {
    private static readonly string[] PowerPointChartDisplayUnitTokens = {
        "hundreds",
        "thousands",
        "tenThousands",
        "hundredThousands",
        "millions",
        "tenMillions",
        "hundredMillions",
        "billions",
        "trillions",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.BuiltInUnitValues ToOpenXml(this PowerPointChartDisplayUnit value) =>
        new(GetToken(value, PowerPointChartDisplayUnitTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.BuiltInUnitValues? ToOpenXml(this PowerPointChartDisplayUnit? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointChartDisplayUnit ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.BuiltInUnitValues value) =>
        (PowerPointChartDisplayUnit)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointChartDisplayUnitTokens, nameof(PowerPointChartDisplayUnit));

    internal static PowerPointChartDisplayUnit? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.BuiltInUnitValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointChartAxisCrossBetweenTokens = {
        "between",
        "midCat",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.CrossBetweenValues ToOpenXml(this PowerPointChartAxisCrossBetween value) =>
        new(GetToken(value, PowerPointChartAxisCrossBetweenTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.CrossBetweenValues? ToOpenXml(this PowerPointChartAxisCrossBetween? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointChartAxisCrossBetween ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.CrossBetweenValues value) =>
        (PowerPointChartAxisCrossBetween)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointChartAxisCrossBetweenTokens, nameof(PowerPointChartAxisCrossBetween));

    internal static PowerPointChartAxisCrossBetween? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.CrossBetweenValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointChartAxisCrossingTokens = {
        "autoZero",
        "max",
        "min",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.CrossesValues ToOpenXml(this PowerPointChartAxisCrossing value) =>
        new(GetToken(value, PowerPointChartAxisCrossingTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.CrossesValues? ToOpenXml(this PowerPointChartAxisCrossing? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointChartAxisCrossing ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.CrossesValues value) =>
        (PowerPointChartAxisCrossing)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointChartAxisCrossingTokens, nameof(PowerPointChartAxisCrossing));

    internal static PowerPointChartAxisCrossing? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.CrossesValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointChartDataLabelPositionTokens = {
        "bestFit",
        "b",
        "ctr",
        "inBase",
        "inEnd",
        "l",
        "outEnd",
        "r",
        "t",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.DataLabelPositionValues ToOpenXml(this PowerPointChartDataLabelPosition value) =>
        new(GetToken(value, PowerPointChartDataLabelPositionTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.DataLabelPositionValues? ToOpenXml(this PowerPointChartDataLabelPosition? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointChartDataLabelPosition ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.DataLabelPositionValues value) =>
        (PowerPointChartDataLabelPosition)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointChartDataLabelPositionTokens, nameof(PowerPointChartDataLabelPosition));

    internal static PowerPointChartDataLabelPosition? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.DataLabelPositionValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointChartGroupingTokens = {
        "percentStacked",
        "standard",
        "stacked",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.GroupingValues ToOpenXml(this PowerPointChartGrouping value) =>
        new(GetToken(value, PowerPointChartGroupingTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.GroupingValues? ToOpenXml(this PowerPointChartGrouping? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointChartGrouping ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.GroupingValues value) =>
        (PowerPointChartGrouping)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointChartGroupingTokens, nameof(PowerPointChartGrouping));

    internal static PowerPointChartGrouping? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.GroupingValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointChartLegendPositionTokens = {
        "b",
        "tr",
        "l",
        "r",
        "t",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.LegendPositionValues ToOpenXml(this PowerPointChartLegendPosition value) =>
        new(GetToken(value, PowerPointChartLegendPositionTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.LegendPositionValues? ToOpenXml(this PowerPointChartLegendPosition? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointChartLegendPosition ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.LegendPositionValues value) =>
        (PowerPointChartLegendPosition)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointChartLegendPositionTokens, nameof(PowerPointChartLegendPosition));

    internal static PowerPointChartLegendPosition? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.LegendPositionValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointChartMarkerStyleTokens = {
        "auto",
        "circle",
        "dash",
        "diamond",
        "dot",
        "none",
        "picture",
        "plus",
        "square",
        "star",
        "triangle",
        "x",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.MarkerStyleValues ToOpenXml(this PowerPointChartMarkerStyle value) =>
        new(GetToken(value, PowerPointChartMarkerStyleTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.MarkerStyleValues? ToOpenXml(this PowerPointChartMarkerStyle? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointChartMarkerStyle ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.MarkerStyleValues value) =>
        (PowerPointChartMarkerStyle)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointChartMarkerStyleTokens, nameof(PowerPointChartMarkerStyle));

    internal static PowerPointChartMarkerStyle? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.MarkerStyleValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointChartTickLabelPositionTokens = {
        "high",
        "low",
        "nextTo",
        "none",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.TickLabelPositionValues ToOpenXml(this PowerPointChartTickLabelPosition value) =>
        new(GetToken(value, PowerPointChartTickLabelPositionTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.TickLabelPositionValues? ToOpenXml(this PowerPointChartTickLabelPosition? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointChartTickLabelPosition ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.TickLabelPositionValues value) =>
        (PowerPointChartTickLabelPosition)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointChartTickLabelPositionTokens, nameof(PowerPointChartTickLabelPosition));

    internal static PowerPointChartTickLabelPosition? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.TickLabelPositionValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointChartTrendlineTypeTokens = {
        "exp",
        "linear",
        "log",
        "movingAvg",
        "poly",
        "power",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.TrendlineValues ToOpenXml(this PowerPointChartTrendlineType value) =>
        new(GetToken(value, PowerPointChartTrendlineTypeTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.TrendlineValues? ToOpenXml(this PowerPointChartTrendlineType? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointChartTrendlineType ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.TrendlineValues value) =>
        (PowerPointChartTrendlineType)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointChartTrendlineTypeTokens, nameof(PowerPointChartTrendlineType));

    internal static PowerPointChartTrendlineType? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.TrendlineValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointLineEndLengthTokens = {
        "sm",
        "med",
        "lg",
    };

    internal static DocumentFormat.OpenXml.Drawing.LineEndLengthValues ToOpenXml(this PowerPointLineEndLength value) =>
        new(GetToken(value, PowerPointLineEndLengthTokens));

    internal static DocumentFormat.OpenXml.Drawing.LineEndLengthValues? ToOpenXml(this PowerPointLineEndLength? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointLineEndLength ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.LineEndLengthValues value) =>
        (PowerPointLineEndLength)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointLineEndLengthTokens, nameof(PowerPointLineEndLength));

    internal static PowerPointLineEndLength? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.LineEndLengthValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointLineEndTypeTokens = {
        "none",
        "triangle",
        "stealth",
        "diamond",
        "oval",
        "arrow",
    };

    internal static DocumentFormat.OpenXml.Drawing.LineEndValues ToOpenXml(this PowerPointLineEndType value) =>
        new(GetToken(value, PowerPointLineEndTypeTokens));

    internal static DocumentFormat.OpenXml.Drawing.LineEndValues? ToOpenXml(this PowerPointLineEndType? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointLineEndType ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.LineEndValues value) =>
        (PowerPointLineEndType)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointLineEndTypeTokens, nameof(PowerPointLineEndType));

    internal static PowerPointLineEndType? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.LineEndValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointLineEndWidthTokens = {
        "sm",
        "med",
        "lg",
    };

    internal static DocumentFormat.OpenXml.Drawing.LineEndWidthValues ToOpenXml(this PowerPointLineEndWidth value) =>
        new(GetToken(value, PowerPointLineEndWidthTokens));

    internal static DocumentFormat.OpenXml.Drawing.LineEndWidthValues? ToOpenXml(this PowerPointLineEndWidth? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointLineEndWidth ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.LineEndWidthValues value) =>
        (PowerPointLineEndWidth)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointLineEndWidthTokens, nameof(PowerPointLineEndWidth));

    internal static PowerPointLineEndWidth? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.LineEndWidthValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointLineDashStyleTokens = {
        "solid",
        "dot",
        "dash",
        "lgDash",
        "dashDot",
        "lgDashDot",
        "lgDashDotDot",
        "sysDash",
        "sysDot",
        "sysDashDot",
        "sysDashDotDot",
    };

    internal static DocumentFormat.OpenXml.Drawing.PresetLineDashValues ToOpenXml(this PowerPointLineDashStyle value) =>
        new(GetToken(value, PowerPointLineDashStyleTokens));

    internal static DocumentFormat.OpenXml.Drawing.PresetLineDashValues? ToOpenXml(this PowerPointLineDashStyle? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointLineDashStyle ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.PresetLineDashValues value) =>
        (PowerPointLineDashStyle)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointLineDashStyleTokens, nameof(PowerPointLineDashStyle));

    internal static PowerPointLineDashStyle? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.PresetLineDashValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointRectangleAlignmentTokens = {
        "tl",
        "t",
        "tr",
        "l",
        "ctr",
        "r",
        "bl",
        "b",
        "br",
    };

    internal static DocumentFormat.OpenXml.Drawing.RectangleAlignmentValues ToOpenXml(this PowerPointRectangleAlignment value) =>
        new(GetToken(value, PowerPointRectangleAlignmentTokens));

    internal static DocumentFormat.OpenXml.Drawing.RectangleAlignmentValues? ToOpenXml(this PowerPointRectangleAlignment? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointRectangleAlignment ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.RectangleAlignmentValues value) =>
        (PowerPointRectangleAlignment)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointRectangleAlignmentTokens, nameof(PowerPointRectangleAlignment));

    internal static PowerPointRectangleAlignment? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.RectangleAlignmentValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointShapeTypeTokens = {
        "line",
        "lineInv",
        "triangle",
        "rtTriangle",
        "rect",
        "diamond",
        "parallelogram",
        "trapezoid",
        "nonIsoscelesTrapezoid",
        "pentagon",
        "hexagon",
        "heptagon",
        "octagon",
        "decagon",
        "dodecagon",
        "star4",
        "star5",
        "star6",
        "star7",
        "star8",
        "star10",
        "star12",
        "star16",
        "star24",
        "star32",
        "roundRect",
        "round1Rect",
        "round2SameRect",
        "round2DiagRect",
        "snipRoundRect",
        "snip1Rect",
        "snip2SameRect",
        "snip2DiagRect",
        "plaque",
        "ellipse",
        "teardrop",
        "homePlate",
        "chevron",
        "pieWedge",
        "pie",
        "blockArc",
        "donut",
        "noSmoking",
        "rightArrow",
        "leftArrow",
        "upArrow",
        "downArrow",
        "stripedRightArrow",
        "notchedRightArrow",
        "bentUpArrow",
        "leftRightArrow",
        "upDownArrow",
        "leftUpArrow",
        "leftRightUpArrow",
        "quadArrow",
        "leftArrowCallout",
        "rightArrowCallout",
        "upArrowCallout",
        "downArrowCallout",
        "leftRightArrowCallout",
        "upDownArrowCallout",
        "quadArrowCallout",
        "bentArrow",
        "uturnArrow",
        "circularArrow",
        "leftCircularArrow",
        "leftRightCircularArrow",
        "curvedRightArrow",
        "curvedLeftArrow",
        "curvedUpArrow",
        "curvedDownArrow",
        "swooshArrow",
        "cube",
        "can",
        "lightningBolt",
        "heart",
        "sun",
        "moon",
        "smileyFace",
        "irregularSeal1",
        "irregularSeal2",
        "foldedCorner",
        "bevel",
        "frame",
        "halfFrame",
        "corner",
        "diagStripe",
        "chord",
        "arc",
        "leftBracket",
        "rightBracket",
        "leftBrace",
        "rightBrace",
        "bracketPair",
        "bracePair",
        "straightConnector1",
        "bentConnector2",
        "bentConnector3",
        "bentConnector4",
        "bentConnector5",
        "curvedConnector2",
        "curvedConnector3",
        "curvedConnector4",
        "curvedConnector5",
        "callout1",
        "callout2",
        "callout3",
        "accentCallout1",
        "accentCallout2",
        "accentCallout3",
        "borderCallout1",
        "borderCallout2",
        "borderCallout3",
        "accentBorderCallout1",
        "accentBorderCallout2",
        "accentBorderCallout3",
        "wedgeRectCallout",
        "wedgeRoundRectCallout",
        "wedgeEllipseCallout",
        "cloudCallout",
        "cloud",
        "ribbon",
        "ribbon2",
        "ellipseRibbon",
        "ellipseRibbon2",
        "leftRightRibbon",
        "verticalScroll",
        "horizontalScroll",
        "wave",
        "doubleWave",
        "plus",
        "flowChartProcess",
        "flowChartDecision",
        "flowChartInputOutput",
        "flowChartPredefinedProcess",
        "flowChartInternalStorage",
        "flowChartDocument",
        "flowChartMultidocument",
        "flowChartTerminator",
        "flowChartPreparation",
        "flowChartManualInput",
        "flowChartManualOperation",
        "flowChartConnector",
        "flowChartPunchedCard",
        "flowChartPunchedTape",
        "flowChartSummingJunction",
        "flowChartOr",
        "flowChartCollate",
        "flowChartSort",
        "flowChartExtract",
        "flowChartMerge",
        "flowChartOfflineStorage",
        "flowChartOnlineStorage",
        "flowChartMagneticTape",
        "flowChartMagneticDisk",
        "flowChartMagneticDrum",
        "flowChartDisplay",
        "flowChartDelay",
        "flowChartAlternateProcess",
        "flowChartOffpageConnector",
        "actionButtonBlank",
        "actionButtonHome",
        "actionButtonHelp",
        "actionButtonInformation",
        "actionButtonForwardNext",
        "actionButtonBackPrevious",
        "actionButtonEnd",
        "actionButtonBeginning",
        "actionButtonReturn",
        "actionButtonDocument",
        "actionButtonSound",
        "actionButtonMovie",
        "gear6",
        "gear9",
        "funnel",
        "mathPlus",
        "mathMinus",
        "mathMultiply",
        "mathDivide",
        "mathEqual",
        "mathNotEqual",
        "cornerTabs",
        "squareTabs",
        "plaqueTabs",
        "chartX",
        "chartStar",
        "chartPlus",
    };

    internal static DocumentFormat.OpenXml.Drawing.ShapeTypeValues ToOpenXml(this PowerPointShapeType value) =>
        new(GetToken(value, PowerPointShapeTypeTokens));

    internal static DocumentFormat.OpenXml.Drawing.ShapeTypeValues? ToOpenXml(this PowerPointShapeType? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointShapeType ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.ShapeTypeValues value) =>
        (PowerPointShapeType)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointShapeTypeTokens, nameof(PowerPointShapeType));

    internal static PowerPointShapeType? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.ShapeTypeValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointTextAlignmentTokens = {
        "l",
        "ctr",
        "r",
        "just",
        "justLow",
        "dist",
        "thaiDist",
    };

    internal static DocumentFormat.OpenXml.Drawing.TextAlignmentTypeValues ToOpenXml(this PowerPointTextAlignment value) =>
        new(GetToken(value, PowerPointTextAlignmentTokens));

    internal static DocumentFormat.OpenXml.Drawing.TextAlignmentTypeValues? ToOpenXml(this PowerPointTextAlignment? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointTextAlignment ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.TextAlignmentTypeValues value) =>
        (PowerPointTextAlignment)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointTextAlignmentTokens, nameof(PowerPointTextAlignment));

    internal static PowerPointTextAlignment? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.TextAlignmentTypeValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointTextVerticalAlignmentTokens = {
        "t",
        "ctr",
        "b",
    };

    internal static DocumentFormat.OpenXml.Drawing.TextAnchoringTypeValues ToOpenXml(this PowerPointTextVerticalAlignment value) =>
        new(GetToken(value, PowerPointTextVerticalAlignmentTokens));

    internal static DocumentFormat.OpenXml.Drawing.TextAnchoringTypeValues? ToOpenXml(this PowerPointTextVerticalAlignment? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointTextVerticalAlignment ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.TextAnchoringTypeValues value) =>
        (PowerPointTextVerticalAlignment)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointTextVerticalAlignmentTokens, nameof(PowerPointTextVerticalAlignment));

    internal static PowerPointTextVerticalAlignment? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.TextAnchoringTypeValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointNumberingSchemeTokens = {
        "alphaLcParenBoth",
        "alphaUcParenBoth",
        "alphaLcParenR",
        "alphaUcParenR",
        "alphaLcPeriod",
        "alphaUcPeriod",
        "arabicParenBoth",
        "arabicParenR",
        "arabicPeriod",
        "arabicPlain",
        "romanLcParenBoth",
        "romanUcParenBoth",
        "romanLcParenR",
        "romanUcParenR",
        "romanLcPeriod",
        "romanUcPeriod",
        "circleNumDbPlain",
        "circleNumWdBlackPlain",
        "circleNumWdWhitePlain",
        "arabicDbPeriod",
        "arabicDbPlain",
        "ea1ChsPeriod",
        "ea1ChsPlain",
        "ea1ChtPeriod",
        "ea1ChtPlain",
        "ea1JpnChsDbPeriod",
        "ea1JpnKorPlain",
        "ea1JpnKorPeriod",
        "arabic1Minus",
        "arabic2Minus",
        "hebrew2Minus",
        "thaiAlphaPeriod",
        "thaiAlphaParenR",
        "thaiAlphaParenBoth",
        "thaiNumPeriod",
        "thaiNumParenR",
        "thaiNumParenBoth",
        "hindiAlphaPeriod",
        "hindiNumPeriod",
        "hindiNumParenR",
        "hindiAlpha1Period",
    };

    internal static DocumentFormat.OpenXml.Drawing.TextAutoNumberSchemeValues ToOpenXml(this PowerPointNumberingScheme value) =>
        new(GetToken(value, PowerPointNumberingSchemeTokens));

    internal static DocumentFormat.OpenXml.Drawing.TextAutoNumberSchemeValues? ToOpenXml(this PowerPointNumberingScheme? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointNumberingScheme ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.TextAutoNumberSchemeValues value) =>
        (PowerPointNumberingScheme)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointNumberingSchemeTokens, nameof(PowerPointNumberingScheme));

    internal static PowerPointNumberingScheme? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.TextAutoNumberSchemeValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointUnderlineStyleTokens = {
        "none",
        "words",
        "sng",
        "dbl",
        "heavy",
        "dotted",
        "dottedHeavy",
        "dash",
        "dashHeavy",
        "dashLong",
        "dashLongHeavy",
        "dotDash",
        "dotDashHeavy",
        "dotDotDash",
        "dotDotDashHeavy",
        "wavy",
        "wavyHeavy",
        "wavyDbl",
    };

    internal static DocumentFormat.OpenXml.Drawing.TextUnderlineValues ToOpenXml(this PowerPointUnderlineStyle value) =>
        new(GetToken(value, PowerPointUnderlineStyleTokens));

    internal static DocumentFormat.OpenXml.Drawing.TextUnderlineValues? ToOpenXml(this PowerPointUnderlineStyle? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointUnderlineStyle ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.TextUnderlineValues value) =>
        (PowerPointUnderlineStyle)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointUnderlineStyleTokens, nameof(PowerPointUnderlineStyle));

    internal static PowerPointUnderlineStyle? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.TextUnderlineValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointTextDirectionTokens = {
        "horz",
        "vert",
        "vert270",
        "wordArtVert",
        "eaVert",
        "mongolianVert",
        "wordArtVertRtl",
    };

    internal static DocumentFormat.OpenXml.Drawing.TextVerticalValues ToOpenXml(this PowerPointTextDirection value) =>
        new(GetToken(value, PowerPointTextDirectionTokens));

    internal static DocumentFormat.OpenXml.Drawing.TextVerticalValues? ToOpenXml(this PowerPointTextDirection? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointTextDirection ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.TextVerticalValues value) =>
        (PowerPointTextDirection)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointTextDirectionTokens, nameof(PowerPointTextDirection));

    internal static PowerPointTextDirection? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.TextVerticalValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointAnimationCommandTokens = {
        "evt",
        "call",
        "verb",
    };

    internal static DocumentFormat.OpenXml.Presentation.CommandValues ToOpenXml(this PowerPointAnimationCommand value) =>
        new(GetToken(value, PowerPointAnimationCommandTokens));

    internal static DocumentFormat.OpenXml.Presentation.CommandValues? ToOpenXml(this PowerPointAnimationCommand? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointAnimationCommand ToOfficeEnum(this DocumentFormat.OpenXml.Presentation.CommandValues value) =>
        (PowerPointAnimationCommand)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointAnimationCommandTokens, nameof(PowerPointAnimationCommand));

    internal static PowerPointAnimationCommand? ToOfficeEnum(this DocumentFormat.OpenXml.Presentation.CommandValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointPlaceholderDirectionTokens = {
        "horz",
        "vert",
    };

    internal static DocumentFormat.OpenXml.Presentation.DirectionValues ToOpenXml(this PowerPointPlaceholderDirection value) =>
        new(GetToken(value, PowerPointPlaceholderDirectionTokens));

    internal static DocumentFormat.OpenXml.Presentation.DirectionValues? ToOpenXml(this PowerPointPlaceholderDirection? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointPlaceholderDirection ToOfficeEnum(this DocumentFormat.OpenXml.Presentation.DirectionValues value) =>
        (PowerPointPlaceholderDirection)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointPlaceholderDirectionTokens, nameof(PowerPointPlaceholderDirection));

    internal static PowerPointPlaceholderDirection? ToOfficeEnum(this DocumentFormat.OpenXml.Presentation.DirectionValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointOleFollowColorSchemeTokens = {
        "none",
        "full",
        "textAndBackground",
    };

    internal static DocumentFormat.OpenXml.Presentation.OleObjectFollowColorSchemeValues ToOpenXml(this PowerPointOleFollowColorScheme value) =>
        new(GetToken(value, PowerPointOleFollowColorSchemeTokens));

    internal static DocumentFormat.OpenXml.Presentation.OleObjectFollowColorSchemeValues? ToOpenXml(this PowerPointOleFollowColorScheme? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointOleFollowColorScheme ToOfficeEnum(this DocumentFormat.OpenXml.Presentation.OleObjectFollowColorSchemeValues value) =>
        (PowerPointOleFollowColorScheme)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointOleFollowColorSchemeTokens, nameof(PowerPointOleFollowColorScheme));

    internal static PowerPointOleFollowColorScheme? ToOfficeEnum(this DocumentFormat.OpenXml.Presentation.OleObjectFollowColorSchemeValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointPlaceholderSizeTokens = {
        "full",
        "half",
        "quarter",
    };

    internal static DocumentFormat.OpenXml.Presentation.PlaceholderSizeValues ToOpenXml(this PowerPointPlaceholderSize value) =>
        new(GetToken(value, PowerPointPlaceholderSizeTokens));

    internal static DocumentFormat.OpenXml.Presentation.PlaceholderSizeValues? ToOpenXml(this PowerPointPlaceholderSize? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointPlaceholderSize ToOfficeEnum(this DocumentFormat.OpenXml.Presentation.PlaceholderSizeValues value) =>
        (PowerPointPlaceholderSize)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointPlaceholderSizeTokens, nameof(PowerPointPlaceholderSize));

    internal static PowerPointPlaceholderSize? ToOfficeEnum(this DocumentFormat.OpenXml.Presentation.PlaceholderSizeValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointPlaceholderTypeTokens = {
        "title",
        "body",
        "ctrTitle",
        "subTitle",
        "dt",
        "sldNum",
        "ftr",
        "hdr",
        "obj",
        "chart",
        "tbl",
        "clipArt",
        "dgm",
        "media",
        "sldImg",
        "pic",
    };

    internal static DocumentFormat.OpenXml.Presentation.PlaceholderValues ToOpenXml(this PowerPointPlaceholderType value) =>
        new(GetToken(value, PowerPointPlaceholderTypeTokens));

    internal static DocumentFormat.OpenXml.Presentation.PlaceholderValues? ToOpenXml(this PowerPointPlaceholderType? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointPlaceholderType ToOfficeEnum(this DocumentFormat.OpenXml.Presentation.PlaceholderValues value) =>
        (PowerPointPlaceholderType)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointPlaceholderTypeTokens, nameof(PowerPointPlaceholderType));

    internal static PowerPointPlaceholderType? ToOfficeEnum(this DocumentFormat.OpenXml.Presentation.PlaceholderValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointSlideSizeTypeTokens = {
        "screen4x3",
        "letter",
        "A4",
        "35mm",
        "overhead",
        "banner",
        "custom",
        "ledger",
        "A3",
        "B4ISO",
        "B5ISO",
        "B4JIS",
        "B5JIS",
        "hagakiCard",
        "screen16x9",
        "screen16x10",
    };

    internal static DocumentFormat.OpenXml.Presentation.SlideSizeValues ToOpenXml(this PowerPointSlideSizeType value) =>
        new(GetToken(value, PowerPointSlideSizeTypeTokens));

    internal static DocumentFormat.OpenXml.Presentation.SlideSizeValues? ToOpenXml(this PowerPointSlideSizeType? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointSlideSizeType ToOfficeEnum(this DocumentFormat.OpenXml.Presentation.SlideSizeValues value) =>
        (PowerPointSlideSizeType)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointSlideSizeTypeTokens, nameof(PowerPointSlideSizeType));

    internal static PowerPointSlideSizeType? ToOfficeEnum(this DocumentFormat.OpenXml.Presentation.SlideSizeValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static string GetToken<TEnum>(TEnum value, string[] tokens) where TEnum : struct, Enum {
        int index = Convert.ToInt32(value, CultureInfo.InvariantCulture);
        if ((uint)index >= (uint)tokens.Length) throw new ArgumentOutOfRangeException(nameof(value), value, $"Unsupported {typeof(TEnum).Name} value.");
        return tokens[index];
    }

    private static int FindToken(string token, string[] tokens, string enumName) {
        int index = Array.IndexOf(tokens, token);
        if (index < 0) throw new ArgumentOutOfRangeException(nameof(token), token, $"Unsupported {enumName} token.");
        return index;
    }
}
