// <auto-generated/>
// Generated by Build/Generate-PowerPointOpenXmlValueTypes.ps1. Do not edit by hand.
using System.Globalization;

namespace OfficeIMO.PowerPoint;

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.Charts.GroupingValues.</summary>
public enum PowerPointChartGrouping {
    /// <summary>Represents the Open XML value <c>percentStacked</c>.</summary>
    PercentStacked,
    /// <summary>Represents the Open XML value <c>standard</c>.</summary>
    Standard,
    /// <summary>Represents the Open XML value <c>stacked</c>.</summary>
    Stacked,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.LineEndLengthValues.</summary>
public enum PowerPointLineEndLength {
    /// <summary>Represents the Open XML value <c>sm</c>.</summary>
    Small,
    /// <summary>Represents the Open XML value <c>med</c>.</summary>
    Medium,
    /// <summary>Represents the Open XML value <c>lg</c>.</summary>
    Large,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.LineEndWidthValues.</summary>
public enum PowerPointLineEndWidth {
    /// <summary>Represents the Open XML value <c>sm</c>.</summary>
    Small,
    /// <summary>Represents the Open XML value <c>med</c>.</summary>
    Medium,
    /// <summary>Represents the Open XML value <c>lg</c>.</summary>
    Large,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.PresetLineDashValues.</summary>
public enum PowerPointLineDashStyle {
    /// <summary>Represents the Open XML value <c>solid</c>.</summary>
    Solid,
    /// <summary>Represents the Open XML value <c>dot</c>.</summary>
    Dot,
    /// <summary>Represents the Open XML value <c>dash</c>.</summary>
    Dash,
    /// <summary>Represents the Open XML value <c>lgDash</c>.</summary>
    LargeDash,
    /// <summary>Represents the Open XML value <c>dashDot</c>.</summary>
    DashDot,
    /// <summary>Represents the Open XML value <c>lgDashDot</c>.</summary>
    LargeDashDot,
    /// <summary>Represents the Open XML value <c>lgDashDotDot</c>.</summary>
    LargeDashDotDot,
    /// <summary>Represents the Open XML value <c>sysDash</c>.</summary>
    SystemDash,
    /// <summary>Represents the Open XML value <c>sysDot</c>.</summary>
    SystemDot,
    /// <summary>Represents the Open XML value <c>sysDashDot</c>.</summary>
    SystemDashDot,
    /// <summary>Represents the Open XML value <c>sysDashDotDot</c>.</summary>
    SystemDashDotDot,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.RectangleAlignmentValues.</summary>
public enum PowerPointRectangleAlignment {
    /// <summary>Represents the Open XML value <c>tl</c>.</summary>
    TopLeft,
    /// <summary>Represents the Open XML value <c>t</c>.</summary>
    Top,
    /// <summary>Represents the Open XML value <c>tr</c>.</summary>
    TopRight,
    /// <summary>Represents the Open XML value <c>l</c>.</summary>
    Left,
    /// <summary>Represents the Open XML value <c>ctr</c>.</summary>
    Center,
    /// <summary>Represents the Open XML value <c>r</c>.</summary>
    Right,
    /// <summary>Represents the Open XML value <c>bl</c>.</summary>
    BottomLeft,
    /// <summary>Represents the Open XML value <c>b</c>.</summary>
    Bottom,
    /// <summary>Represents the Open XML value <c>br</c>.</summary>
    BottomRight,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.TextAlignmentTypeValues.</summary>
public enum PowerPointTextAlignment {
    /// <summary>Represents the Open XML value <c>l</c>.</summary>
    Left,
    /// <summary>Represents the Open XML value <c>ctr</c>.</summary>
    Center,
    /// <summary>Represents the Open XML value <c>r</c>.</summary>
    Right,
    /// <summary>Represents the Open XML value <c>just</c>.</summary>
    Justified,
    /// <summary>Represents the Open XML value <c>justLow</c>.</summary>
    JustifiedLow,
    /// <summary>Represents the Open XML value <c>dist</c>.</summary>
    Distributed,
    /// <summary>Represents the Open XML value <c>thaiDist</c>.</summary>
    ThaiDistributed,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.TextAnchoringTypeValues.</summary>
public enum PowerPointTextVerticalAlignment {
    /// <summary>Represents the Open XML value <c>t</c>.</summary>
    Top,
    /// <summary>Represents the Open XML value <c>ctr</c>.</summary>
    Center,
    /// <summary>Represents the Open XML value <c>b</c>.</summary>
    Bottom,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.TextAutoNumberSchemeValues.</summary>
public enum PowerPointNumberingScheme {
    /// <summary>Represents the Open XML value <c>alphaLcParenBoth</c>.</summary>
    AlphaLowerCharacterParenBoth,
    /// <summary>Represents the Open XML value <c>alphaUcParenBoth</c>.</summary>
    AlphaUpperCharacterParenBoth,
    /// <summary>Represents the Open XML value <c>alphaLcParenR</c>.</summary>
    AlphaLowerCharacterParenR,
    /// <summary>Represents the Open XML value <c>alphaUcParenR</c>.</summary>
    AlphaUpperCharacterParenR,
    /// <summary>Represents the Open XML value <c>alphaLcPeriod</c>.</summary>
    AlphaLowerCharacterPeriod,
    /// <summary>Represents the Open XML value <c>alphaUcPeriod</c>.</summary>
    AlphaUpperCharacterPeriod,
    /// <summary>Represents the Open XML value <c>arabicParenBoth</c>.</summary>
    ArabicParenBoth,
    /// <summary>Represents the Open XML value <c>arabicParenR</c>.</summary>
    ArabicParenR,
    /// <summary>Represents the Open XML value <c>arabicPeriod</c>.</summary>
    ArabicPeriod,
    /// <summary>Represents the Open XML value <c>arabicPlain</c>.</summary>
    ArabicPlain,
    /// <summary>Represents the Open XML value <c>romanLcParenBoth</c>.</summary>
    RomanLowerCharacterParenBoth,
    /// <summary>Represents the Open XML value <c>romanUcParenBoth</c>.</summary>
    RomanUpperCharacterParenBoth,
    /// <summary>Represents the Open XML value <c>romanLcParenR</c>.</summary>
    RomanLowerCharacterParenR,
    /// <summary>Represents the Open XML value <c>romanUcParenR</c>.</summary>
    RomanUpperCharacterParenR,
    /// <summary>Represents the Open XML value <c>romanLcPeriod</c>.</summary>
    RomanLowerCharacterPeriod,
    /// <summary>Represents the Open XML value <c>romanUcPeriod</c>.</summary>
    RomanUpperCharacterPeriod,
    /// <summary>Represents the Open XML value <c>circleNumDbPlain</c>.</summary>
    CircleNumberDoubleBytePlain,
    /// <summary>Represents the Open XML value <c>circleNumWdBlackPlain</c>.</summary>
    CircleNumberWingdingsBlackPlain,
    /// <summary>Represents the Open XML value <c>circleNumWdWhitePlain</c>.</summary>
    CircleNumberWingdingsWhitePlain,
    /// <summary>Represents the Open XML value <c>arabicDbPeriod</c>.</summary>
    ArabicDoubleBytePeriod,
    /// <summary>Represents the Open XML value <c>arabicDbPlain</c>.</summary>
    ArabicDoubleBytePlain,
    /// <summary>Represents the Open XML value <c>ea1ChsPeriod</c>.</summary>
    EastAsianSimplifiedChinesePeriod,
    /// <summary>Represents the Open XML value <c>ea1ChsPlain</c>.</summary>
    EastAsianSimplifiedChinesePlain,
    /// <summary>Represents the Open XML value <c>ea1ChtPeriod</c>.</summary>
    EastAsianTraditionalChinesePeriod,
    /// <summary>Represents the Open XML value <c>ea1ChtPlain</c>.</summary>
    EastAsianTraditionalChinesePlain,
    /// <summary>Represents the Open XML value <c>ea1JpnChsDbPeriod</c>.</summary>
    EastAsianJapaneseDoubleBytePeriod,
    /// <summary>Represents the Open XML value <c>ea1JpnKorPlain</c>.</summary>
    EastAsianJapaneseKoreanPlain,
    /// <summary>Represents the Open XML value <c>ea1JpnKorPeriod</c>.</summary>
    EastAsianJapaneseKoreanPeriod,
    /// <summary>Represents the Open XML value <c>arabic1Minus</c>.</summary>
    Arabic1Minus,
    /// <summary>Represents the Open XML value <c>arabic2Minus</c>.</summary>
    Arabic2Minus,
    /// <summary>Represents the Open XML value <c>hebrew2Minus</c>.</summary>
    Hebrew2Minus,
    /// <summary>Represents the Open XML value <c>thaiAlphaPeriod</c>.</summary>
    ThaiAlphaPeriod,
    /// <summary>Represents the Open XML value <c>thaiAlphaParenR</c>.</summary>
    ThaiAlphaParenthesisRight,
    /// <summary>Represents the Open XML value <c>thaiAlphaParenBoth</c>.</summary>
    ThaiAlphaParenthesisBoth,
    /// <summary>Represents the Open XML value <c>thaiNumPeriod</c>.</summary>
    ThaiNumberPeriod,
    /// <summary>Represents the Open XML value <c>thaiNumParenR</c>.</summary>
    ThaiNumberParenthesisRight,
    /// <summary>Represents the Open XML value <c>thaiNumParenBoth</c>.</summary>
    ThaiNumberParenthesisBoth,
    /// <summary>Represents the Open XML value <c>hindiAlphaPeriod</c>.</summary>
    HindiAlphaPeriod,
    /// <summary>Represents the Open XML value <c>hindiNumPeriod</c>.</summary>
    HindiNumPeriod,
    /// <summary>Represents the Open XML value <c>hindiNumParenR</c>.</summary>
    HindiNumberParenthesisRight,
    /// <summary>Represents the Open XML value <c>hindiAlpha1Period</c>.</summary>
    HindiAlpha1Period,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.TextUnderlineValues.</summary>
public enum PowerPointUnderlineStyle {
    /// <summary>Represents the Open XML value <c>none</c>.</summary>
    None,
    /// <summary>Represents the Open XML value <c>words</c>.</summary>
    Words,
    /// <summary>Represents the Open XML value <c>sng</c>.</summary>
    Single,
    /// <summary>Represents the Open XML value <c>dbl</c>.</summary>
    Double,
    /// <summary>Represents the Open XML value <c>heavy</c>.</summary>
    Heavy,
    /// <summary>Represents the Open XML value <c>dotted</c>.</summary>
    Dotted,
    /// <summary>Represents the Open XML value <c>dottedHeavy</c>.</summary>
    HeavyDotted,
    /// <summary>Represents the Open XML value <c>dash</c>.</summary>
    Dash,
    /// <summary>Represents the Open XML value <c>dashHeavy</c>.</summary>
    DashHeavy,
    /// <summary>Represents the Open XML value <c>dashLong</c>.</summary>
    DashLong,
    /// <summary>Represents the Open XML value <c>dashLongHeavy</c>.</summary>
    DashLongHeavy,
    /// <summary>Represents the Open XML value <c>dotDash</c>.</summary>
    DotDash,
    /// <summary>Represents the Open XML value <c>dotDashHeavy</c>.</summary>
    DotDashHeavy,
    /// <summary>Represents the Open XML value <c>dotDotDash</c>.</summary>
    DotDotDash,
    /// <summary>Represents the Open XML value <c>dotDotDashHeavy</c>.</summary>
    DotDotDashHeavy,
    /// <summary>Represents the Open XML value <c>wavy</c>.</summary>
    Wavy,
    /// <summary>Represents the Open XML value <c>wavyHeavy</c>.</summary>
    WavyHeavy,
    /// <summary>Represents the Open XML value <c>wavyDbl</c>.</summary>
    WavyDouble,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.TextVerticalValues.</summary>
public enum PowerPointTextDirection {
    /// <summary>Represents the Open XML value <c>horz</c>.</summary>
    Horizontal,
    /// <summary>Represents the Open XML value <c>vert</c>.</summary>
    Vertical,
    /// <summary>Represents the Open XML value <c>vert270</c>.</summary>
    Vertical270,
    /// <summary>Represents the Open XML value <c>wordArtVert</c>.</summary>
    WordArtVertical,
    /// <summary>Represents the Open XML value <c>eaVert</c>.</summary>
    EastAsianVetical,
    /// <summary>Represents the Open XML value <c>mongolianVert</c>.</summary>
    MongolianVertical,
    /// <summary>Represents the Open XML value <c>wordArtVertRtl</c>.</summary>
    WordArtLeftToRight,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Presentation.CommandValues.</summary>
public enum PowerPointAnimationCommand {
    /// <summary>Represents the Open XML value <c>evt</c>.</summary>
    Event,
    /// <summary>Represents the Open XML value <c>call</c>.</summary>
    Call,
    /// <summary>Represents the Open XML value <c>verb</c>.</summary>
    Verb,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Presentation.DirectionValues.</summary>
public enum PowerPointPlaceholderDirection {
    /// <summary>Represents the Open XML value <c>horz</c>.</summary>
    Horizontal,
    /// <summary>Represents the Open XML value <c>vert</c>.</summary>
    Vertical,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Presentation.OleObjectFollowColorSchemeValues.</summary>
public enum PowerPointOleFollowColorScheme {
    /// <summary>Represents the Open XML value <c>none</c>.</summary>
    None,
    /// <summary>Represents the Open XML value <c>full</c>.</summary>
    Full,
    /// <summary>Represents the Open XML value <c>textAndBackground</c>.</summary>
    TextAndBackground,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Presentation.PlaceholderSizeValues.</summary>
public enum PowerPointPlaceholderSize {
    /// <summary>Represents the Open XML value <c>full</c>.</summary>
    Full,
    /// <summary>Represents the Open XML value <c>half</c>.</summary>
    Half,
    /// <summary>Represents the Open XML value <c>quarter</c>.</summary>
    Quarter,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Presentation.PlaceholderValues.</summary>
public enum PowerPointPlaceholderType {
    /// <summary>Represents the Open XML value <c>title</c>.</summary>
    Title,
    /// <summary>Represents the Open XML value <c>body</c>.</summary>
    Body,
    /// <summary>Represents the Open XML value <c>ctrTitle</c>.</summary>
    CenteredTitle,
    /// <summary>Represents the Open XML value <c>subTitle</c>.</summary>
    SubTitle,
    /// <summary>Represents the Open XML value <c>dt</c>.</summary>
    DateAndTime,
    /// <summary>Represents the Open XML value <c>sldNum</c>.</summary>
    SlideNumber,
    /// <summary>Represents the Open XML value <c>ftr</c>.</summary>
    Footer,
    /// <summary>Represents the Open XML value <c>hdr</c>.</summary>
    Header,
    /// <summary>Represents the Open XML value <c>obj</c>.</summary>
    Object,
    /// <summary>Represents the Open XML value <c>chart</c>.</summary>
    Chart,
    /// <summary>Represents the Open XML value <c>tbl</c>.</summary>
    Table,
    /// <summary>Represents the Open XML value <c>clipArt</c>.</summary>
    ClipArt,
    /// <summary>Represents the Open XML value <c>dgm</c>.</summary>
    Diagram,
    /// <summary>Represents the Open XML value <c>media</c>.</summary>
    Media,
    /// <summary>Represents the Open XML value <c>sldImg</c>.</summary>
    SlideImage,
    /// <summary>Represents the Open XML value <c>pic</c>.</summary>
    Picture,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Presentation.SlideSizeValues.</summary>
public enum PowerPointSlideSizeType {
    /// <summary>Represents the Open XML value <c>screen4x3</c>.</summary>
    Screen4x3,
    /// <summary>Represents the Open XML value <c>letter</c>.</summary>
    Letter,
    /// <summary>Represents the Open XML value <c>A4</c>.</summary>
    A4,
    /// <summary>Represents the Open XML value <c>35mm</c>.</summary>
    Film35mm,
    /// <summary>Represents the Open XML value <c>overhead</c>.</summary>
    Overhead,
    /// <summary>Represents the Open XML value <c>banner</c>.</summary>
    Banner,
    /// <summary>Represents the Open XML value <c>custom</c>.</summary>
    Custom,
    /// <summary>Represents the Open XML value <c>ledger</c>.</summary>
    Ledger,
    /// <summary>Represents the Open XML value <c>A3</c>.</summary>
    A3,
    /// <summary>Represents the Open XML value <c>B4ISO</c>.</summary>
    B4ISO,
    /// <summary>Represents the Open XML value <c>B5ISO</c>.</summary>
    B5ISO,
    /// <summary>Represents the Open XML value <c>B4JIS</c>.</summary>
    B4JIS,
    /// <summary>Represents the Open XML value <c>B5JIS</c>.</summary>
    B5JIS,
    /// <summary>Represents the Open XML value <c>hagakiCard</c>.</summary>
    HagakiCard,
    /// <summary>Represents the Open XML value <c>screen16x9</c>.</summary>
    Screen16x9,
    /// <summary>Represents the Open XML value <c>screen16x10</c>.</summary>
    Screen16x10,
}

internal static class PowerPointOpenXmlValueTypeExtensions {
    private static readonly string[] PowerPointChartGroupingTokens = {
        "percentStacked",
        "standard",
        "stacked",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.GroupingValues ToOpenXml(this PowerPointChartGrouping value) =>
        new(GetToken(value, PowerPointChartGroupingTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.GroupingValues? ToOpenXml(this PowerPointChartGrouping? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointChartGrouping ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.GroupingValues value) =>
        (PowerPointChartGrouping)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointChartGroupingTokens, nameof(PowerPointChartGrouping));

    internal static PowerPointChartGrouping? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.GroupingValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointLineEndLengthTokens = {
        "sm",
        "med",
        "lg",
    };

    internal static DocumentFormat.OpenXml.Drawing.LineEndLengthValues ToOpenXml(this PowerPointLineEndLength value) =>
        new(GetToken(value, PowerPointLineEndLengthTokens));

    internal static DocumentFormat.OpenXml.Drawing.LineEndLengthValues? ToOpenXml(this PowerPointLineEndLength? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointLineEndLength ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.LineEndLengthValues value) =>
        (PowerPointLineEndLength)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointLineEndLengthTokens, nameof(PowerPointLineEndLength));

    internal static PowerPointLineEndLength? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.LineEndLengthValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointLineEndWidthTokens = {
        "sm",
        "med",
        "lg",
    };

    internal static DocumentFormat.OpenXml.Drawing.LineEndWidthValues ToOpenXml(this PowerPointLineEndWidth value) =>
        new(GetToken(value, PowerPointLineEndWidthTokens));

    internal static DocumentFormat.OpenXml.Drawing.LineEndWidthValues? ToOpenXml(this PowerPointLineEndWidth? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointLineEndWidth ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.LineEndWidthValues value) =>
        (PowerPointLineEndWidth)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointLineEndWidthTokens, nameof(PowerPointLineEndWidth));

    internal static PowerPointLineEndWidth? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.LineEndWidthValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointLineDashStyleTokens = {
        "solid",
        "dot",
        "dash",
        "lgDash",
        "dashDot",
        "lgDashDot",
        "lgDashDotDot",
        "sysDash",
        "sysDot",
        "sysDashDot",
        "sysDashDotDot",
    };

    internal static DocumentFormat.OpenXml.Drawing.PresetLineDashValues ToOpenXml(this PowerPointLineDashStyle value) =>
        new(GetToken(value, PowerPointLineDashStyleTokens));

    internal static DocumentFormat.OpenXml.Drawing.PresetLineDashValues? ToOpenXml(this PowerPointLineDashStyle? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointLineDashStyle ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.PresetLineDashValues value) =>
        (PowerPointLineDashStyle)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointLineDashStyleTokens, nameof(PowerPointLineDashStyle));

    internal static PowerPointLineDashStyle? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.PresetLineDashValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointRectangleAlignmentTokens = {
        "tl",
        "t",
        "tr",
        "l",
        "ctr",
        "r",
        "bl",
        "b",
        "br",
    };

    internal static DocumentFormat.OpenXml.Drawing.RectangleAlignmentValues ToOpenXml(this PowerPointRectangleAlignment value) =>
        new(GetToken(value, PowerPointRectangleAlignmentTokens));

    internal static DocumentFormat.OpenXml.Drawing.RectangleAlignmentValues? ToOpenXml(this PowerPointRectangleAlignment? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointRectangleAlignment ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.RectangleAlignmentValues value) =>
        (PowerPointRectangleAlignment)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointRectangleAlignmentTokens, nameof(PowerPointRectangleAlignment));

    internal static PowerPointRectangleAlignment? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.RectangleAlignmentValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointTextAlignmentTokens = {
        "l",
        "ctr",
        "r",
        "just",
        "justLow",
        "dist",
        "thaiDist",
    };

    internal static DocumentFormat.OpenXml.Drawing.TextAlignmentTypeValues ToOpenXml(this PowerPointTextAlignment value) =>
        new(GetToken(value, PowerPointTextAlignmentTokens));

    internal static DocumentFormat.OpenXml.Drawing.TextAlignmentTypeValues? ToOpenXml(this PowerPointTextAlignment? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointTextAlignment ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.TextAlignmentTypeValues value) =>
        (PowerPointTextAlignment)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointTextAlignmentTokens, nameof(PowerPointTextAlignment));

    internal static PowerPointTextAlignment? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.TextAlignmentTypeValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointTextVerticalAlignmentTokens = {
        "t",
        "ctr",
        "b",
    };

    internal static DocumentFormat.OpenXml.Drawing.TextAnchoringTypeValues ToOpenXml(this PowerPointTextVerticalAlignment value) =>
        new(GetToken(value, PowerPointTextVerticalAlignmentTokens));

    internal static DocumentFormat.OpenXml.Drawing.TextAnchoringTypeValues? ToOpenXml(this PowerPointTextVerticalAlignment? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointTextVerticalAlignment ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.TextAnchoringTypeValues value) =>
        (PowerPointTextVerticalAlignment)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointTextVerticalAlignmentTokens, nameof(PowerPointTextVerticalAlignment));

    internal static PowerPointTextVerticalAlignment? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.TextAnchoringTypeValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointNumberingSchemeTokens = {
        "alphaLcParenBoth",
        "alphaUcParenBoth",
        "alphaLcParenR",
        "alphaUcParenR",
        "alphaLcPeriod",
        "alphaUcPeriod",
        "arabicParenBoth",
        "arabicParenR",
        "arabicPeriod",
        "arabicPlain",
        "romanLcParenBoth",
        "romanUcParenBoth",
        "romanLcParenR",
        "romanUcParenR",
        "romanLcPeriod",
        "romanUcPeriod",
        "circleNumDbPlain",
        "circleNumWdBlackPlain",
        "circleNumWdWhitePlain",
        "arabicDbPeriod",
        "arabicDbPlain",
        "ea1ChsPeriod",
        "ea1ChsPlain",
        "ea1ChtPeriod",
        "ea1ChtPlain",
        "ea1JpnChsDbPeriod",
        "ea1JpnKorPlain",
        "ea1JpnKorPeriod",
        "arabic1Minus",
        "arabic2Minus",
        "hebrew2Minus",
        "thaiAlphaPeriod",
        "thaiAlphaParenR",
        "thaiAlphaParenBoth",
        "thaiNumPeriod",
        "thaiNumParenR",
        "thaiNumParenBoth",
        "hindiAlphaPeriod",
        "hindiNumPeriod",
        "hindiNumParenR",
        "hindiAlpha1Period",
    };

    internal static DocumentFormat.OpenXml.Drawing.TextAutoNumberSchemeValues ToOpenXml(this PowerPointNumberingScheme value) =>
        new(GetToken(value, PowerPointNumberingSchemeTokens));

    internal static DocumentFormat.OpenXml.Drawing.TextAutoNumberSchemeValues? ToOpenXml(this PowerPointNumberingScheme? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointNumberingScheme ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.TextAutoNumberSchemeValues value) =>
        (PowerPointNumberingScheme)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointNumberingSchemeTokens, nameof(PowerPointNumberingScheme));

    internal static PowerPointNumberingScheme? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.TextAutoNumberSchemeValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointUnderlineStyleTokens = {
        "none",
        "words",
        "sng",
        "dbl",
        "heavy",
        "dotted",
        "dottedHeavy",
        "dash",
        "dashHeavy",
        "dashLong",
        "dashLongHeavy",
        "dotDash",
        "dotDashHeavy",
        "dotDotDash",
        "dotDotDashHeavy",
        "wavy",
        "wavyHeavy",
        "wavyDbl",
    };

    internal static DocumentFormat.OpenXml.Drawing.TextUnderlineValues ToOpenXml(this PowerPointUnderlineStyle value) =>
        new(GetToken(value, PowerPointUnderlineStyleTokens));

    internal static DocumentFormat.OpenXml.Drawing.TextUnderlineValues? ToOpenXml(this PowerPointUnderlineStyle? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointUnderlineStyle ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.TextUnderlineValues value) =>
        (PowerPointUnderlineStyle)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointUnderlineStyleTokens, nameof(PowerPointUnderlineStyle));

    internal static PowerPointUnderlineStyle? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.TextUnderlineValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointTextDirectionTokens = {
        "horz",
        "vert",
        "vert270",
        "wordArtVert",
        "eaVert",
        "mongolianVert",
        "wordArtVertRtl",
    };

    internal static DocumentFormat.OpenXml.Drawing.TextVerticalValues ToOpenXml(this PowerPointTextDirection value) =>
        new(GetToken(value, PowerPointTextDirectionTokens));

    internal static DocumentFormat.OpenXml.Drawing.TextVerticalValues? ToOpenXml(this PowerPointTextDirection? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointTextDirection ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.TextVerticalValues value) =>
        (PowerPointTextDirection)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointTextDirectionTokens, nameof(PowerPointTextDirection));

    internal static PowerPointTextDirection? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.TextVerticalValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointAnimationCommandTokens = {
        "evt",
        "call",
        "verb",
    };

    internal static DocumentFormat.OpenXml.Presentation.CommandValues ToOpenXml(this PowerPointAnimationCommand value) =>
        new(GetToken(value, PowerPointAnimationCommandTokens));

    internal static DocumentFormat.OpenXml.Presentation.CommandValues? ToOpenXml(this PowerPointAnimationCommand? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointAnimationCommand ToOfficeEnum(this DocumentFormat.OpenXml.Presentation.CommandValues value) =>
        (PowerPointAnimationCommand)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointAnimationCommandTokens, nameof(PowerPointAnimationCommand));

    internal static PowerPointAnimationCommand? ToOfficeEnum(this DocumentFormat.OpenXml.Presentation.CommandValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointPlaceholderDirectionTokens = {
        "horz",
        "vert",
    };

    internal static DocumentFormat.OpenXml.Presentation.DirectionValues ToOpenXml(this PowerPointPlaceholderDirection value) =>
        new(GetToken(value, PowerPointPlaceholderDirectionTokens));

    internal static DocumentFormat.OpenXml.Presentation.DirectionValues? ToOpenXml(this PowerPointPlaceholderDirection? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointPlaceholderDirection ToOfficeEnum(this DocumentFormat.OpenXml.Presentation.DirectionValues value) =>
        (PowerPointPlaceholderDirection)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointPlaceholderDirectionTokens, nameof(PowerPointPlaceholderDirection));

    internal static PowerPointPlaceholderDirection? ToOfficeEnum(this DocumentFormat.OpenXml.Presentation.DirectionValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointOleFollowColorSchemeTokens = {
        "none",
        "full",
        "textAndBackground",
    };

    internal static DocumentFormat.OpenXml.Presentation.OleObjectFollowColorSchemeValues ToOpenXml(this PowerPointOleFollowColorScheme value) =>
        new(GetToken(value, PowerPointOleFollowColorSchemeTokens));

    internal static DocumentFormat.OpenXml.Presentation.OleObjectFollowColorSchemeValues? ToOpenXml(this PowerPointOleFollowColorScheme? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointOleFollowColorScheme ToOfficeEnum(this DocumentFormat.OpenXml.Presentation.OleObjectFollowColorSchemeValues value) =>
        (PowerPointOleFollowColorScheme)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointOleFollowColorSchemeTokens, nameof(PowerPointOleFollowColorScheme));

    internal static PowerPointOleFollowColorScheme? ToOfficeEnum(this DocumentFormat.OpenXml.Presentation.OleObjectFollowColorSchemeValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointPlaceholderSizeTokens = {
        "full",
        "half",
        "quarter",
    };

    internal static DocumentFormat.OpenXml.Presentation.PlaceholderSizeValues ToOpenXml(this PowerPointPlaceholderSize value) =>
        new(GetToken(value, PowerPointPlaceholderSizeTokens));

    internal static DocumentFormat.OpenXml.Presentation.PlaceholderSizeValues? ToOpenXml(this PowerPointPlaceholderSize? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointPlaceholderSize ToOfficeEnum(this DocumentFormat.OpenXml.Presentation.PlaceholderSizeValues value) =>
        (PowerPointPlaceholderSize)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointPlaceholderSizeTokens, nameof(PowerPointPlaceholderSize));

    internal static PowerPointPlaceholderSize? ToOfficeEnum(this DocumentFormat.OpenXml.Presentation.PlaceholderSizeValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointPlaceholderTypeTokens = {
        "title",
        "body",
        "ctrTitle",
        "subTitle",
        "dt",
        "sldNum",
        "ftr",
        "hdr",
        "obj",
        "chart",
        "tbl",
        "clipArt",
        "dgm",
        "media",
        "sldImg",
        "pic",
    };

    internal static DocumentFormat.OpenXml.Presentation.PlaceholderValues ToOpenXml(this PowerPointPlaceholderType value) =>
        new(GetToken(value, PowerPointPlaceholderTypeTokens));

    internal static DocumentFormat.OpenXml.Presentation.PlaceholderValues? ToOpenXml(this PowerPointPlaceholderType? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointPlaceholderType ToOfficeEnum(this DocumentFormat.OpenXml.Presentation.PlaceholderValues value) =>
        (PowerPointPlaceholderType)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointPlaceholderTypeTokens, nameof(PowerPointPlaceholderType));

    internal static PowerPointPlaceholderType? ToOfficeEnum(this DocumentFormat.OpenXml.Presentation.PlaceholderValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] PowerPointSlideSizeTypeTokens = {
        "screen4x3",
        "letter",
        "A4",
        "35mm",
        "overhead",
        "banner",
        "custom",
        "ledger",
        "A3",
        "B4ISO",
        "B5ISO",
        "B4JIS",
        "B5JIS",
        "hagakiCard",
        "screen16x9",
        "screen16x10",
    };

    internal static DocumentFormat.OpenXml.Presentation.SlideSizeValues ToOpenXml(this PowerPointSlideSizeType value) =>
        new(GetToken(value, PowerPointSlideSizeTypeTokens));

    internal static DocumentFormat.OpenXml.Presentation.SlideSizeValues? ToOpenXml(this PowerPointSlideSizeType? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static PowerPointSlideSizeType ToOfficeEnum(this DocumentFormat.OpenXml.Presentation.SlideSizeValues value) =>
        (PowerPointSlideSizeType)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, PowerPointSlideSizeTypeTokens, nameof(PowerPointSlideSizeType));

    internal static PowerPointSlideSizeType? ToOfficeEnum(this DocumentFormat.OpenXml.Presentation.SlideSizeValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] OfficeChartDisplayUnitTokens = {
        "hundreds",
        "thousands",
        "tenThousands",
        "hundredThousands",
        "millions",
        "tenMillions",
        "hundredMillions",
        "billions",
        "trillions",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.BuiltInUnitValues ToOpenXml(this OfficeChartDisplayUnit value) =>
        new(GetToken(value, OfficeChartDisplayUnitTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.BuiltInUnitValues? ToOpenXml(this OfficeChartDisplayUnit? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static OfficeChartDisplayUnit ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.BuiltInUnitValues value) =>
        (OfficeChartDisplayUnit)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, OfficeChartDisplayUnitTokens, nameof(OfficeChartDisplayUnit));

    internal static OfficeChartDisplayUnit? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.BuiltInUnitValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] OfficeChartAxisCrossBetweenTokens = {
        "between",
        "midCat",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.CrossBetweenValues ToOpenXml(this OfficeChartAxisCrossBetween value) =>
        new(GetToken(value, OfficeChartAxisCrossBetweenTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.CrossBetweenValues? ToOpenXml(this OfficeChartAxisCrossBetween? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static OfficeChartAxisCrossBetween ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.CrossBetweenValues value) =>
        (OfficeChartAxisCrossBetween)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, OfficeChartAxisCrossBetweenTokens, nameof(OfficeChartAxisCrossBetween));

    internal static OfficeChartAxisCrossBetween? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.CrossBetweenValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] OfficeChartAxisCrossingPositionTokens = {
        "autoZero",
        "max",
        "min",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.CrossesValues ToOpenXml(this OfficeChartAxisCrossingPosition value) =>
        new(GetToken(value, OfficeChartAxisCrossingPositionTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.CrossesValues? ToOpenXml(this OfficeChartAxisCrossingPosition? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static OfficeChartAxisCrossingPosition ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.CrossesValues value) =>
        (OfficeChartAxisCrossingPosition)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, OfficeChartAxisCrossingPositionTokens, nameof(OfficeChartAxisCrossingPosition));

    internal static OfficeChartAxisCrossingPosition? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.CrossesValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] OfficeChartDataLabelPositionTokens = {
        "bestFit",
        "b",
        "ctr",
        "inBase",
        "inEnd",
        "l",
        "outEnd",
        "r",
        "t",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.DataLabelPositionValues ToOpenXml(this OfficeChartDataLabelPosition value) =>
        new(GetToken(value, OfficeChartDataLabelPositionTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.DataLabelPositionValues? ToOpenXml(this OfficeChartDataLabelPosition? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static OfficeChartDataLabelPosition ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.DataLabelPositionValues value) =>
        (OfficeChartDataLabelPosition)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, OfficeChartDataLabelPositionTokens, nameof(OfficeChartDataLabelPosition));

    internal static OfficeChartDataLabelPosition? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.DataLabelPositionValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] OfficeChartLegendPositionTokens = {
        "b",
        "tr",
        "l",
        "r",
        "t",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.LegendPositionValues ToOpenXml(this OfficeChartLegendPosition value) =>
        new(GetToken(value, OfficeChartLegendPositionTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.LegendPositionValues? ToOpenXml(this OfficeChartLegendPosition? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static OfficeChartLegendPosition ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.LegendPositionValues value) =>
        (OfficeChartLegendPosition)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, OfficeChartLegendPositionTokens, nameof(OfficeChartLegendPosition));

    internal static OfficeChartLegendPosition? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.LegendPositionValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] OfficeChartMarkerShapeTokens = {
        "auto",
        "circle",
        "dash",
        "diamond",
        "dot",
        "none",
        "picture",
        "plus",
        "square",
        "star",
        "triangle",
        "x",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.MarkerStyleValues ToOpenXml(this OfficeChartMarkerShape value) =>
        new(GetToken(value, OfficeChartMarkerShapeTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.MarkerStyleValues? ToOpenXml(this OfficeChartMarkerShape? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static OfficeChartMarkerShape ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.MarkerStyleValues value) =>
        (OfficeChartMarkerShape)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, OfficeChartMarkerShapeTokens, nameof(OfficeChartMarkerShape));

    internal static OfficeChartMarkerShape? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.MarkerStyleValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] OfficeChartAxisTickLabelPositionTokens = {
        "high",
        "low",
        "nextTo",
        "none",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.TickLabelPositionValues ToOpenXml(this OfficeChartAxisTickLabelPosition value) =>
        new(GetToken(value, OfficeChartAxisTickLabelPositionTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.TickLabelPositionValues? ToOpenXml(this OfficeChartAxisTickLabelPosition? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static OfficeChartAxisTickLabelPosition ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.TickLabelPositionValues value) =>
        (OfficeChartAxisTickLabelPosition)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, OfficeChartAxisTickLabelPositionTokens, nameof(OfficeChartAxisTickLabelPosition));

    internal static OfficeChartAxisTickLabelPosition? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.TickLabelPositionValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] OfficeChartTrendlineTypeTokens = {
        "exp",
        "linear",
        "log",
        "movingAvg",
        "poly",
        "power",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.TrendlineValues ToOpenXml(this OfficeChartTrendlineType value) =>
        new(GetToken(value, OfficeChartTrendlineTypeTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.TrendlineValues? ToOpenXml(this OfficeChartTrendlineType? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static OfficeChartTrendlineType ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.TrendlineValues value) =>
        (OfficeChartTrendlineType)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, OfficeChartTrendlineTypeTokens, nameof(OfficeChartTrendlineType));

    internal static OfficeChartTrendlineType? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.TrendlineValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] OfficeLineMarkerKindTokens = {
        "none",
        "triangle",
        "stealth",
        "diamond",
        "oval",
        "arrow",
    };

    internal static DocumentFormat.OpenXml.Drawing.LineEndValues ToOpenXml(this OfficeLineMarkerKind value) =>
        new(GetToken(value, OfficeLineMarkerKindTokens));

    internal static DocumentFormat.OpenXml.Drawing.LineEndValues? ToOpenXml(this OfficeLineMarkerKind? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static OfficeLineMarkerKind ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.LineEndValues value) =>
        (OfficeLineMarkerKind)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, OfficeLineMarkerKindTokens, nameof(OfficeLineMarkerKind));

    internal static OfficeLineMarkerKind? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.LineEndValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] OfficePresetShapeTypeTokens = {
        "line",
        "lineInv",
        "triangle",
        "rtTriangle",
        "rect",
        "diamond",
        "parallelogram",
        "trapezoid",
        "nonIsoscelesTrapezoid",
        "pentagon",
        "hexagon",
        "heptagon",
        "octagon",
        "decagon",
        "dodecagon",
        "star4",
        "star5",
        "star6",
        "star7",
        "star8",
        "star10",
        "star12",
        "star16",
        "star24",
        "star32",
        "roundRect",
        "round1Rect",
        "round2SameRect",
        "round2DiagRect",
        "snipRoundRect",
        "snip1Rect",
        "snip2SameRect",
        "snip2DiagRect",
        "plaque",
        "ellipse",
        "teardrop",
        "homePlate",
        "chevron",
        "pieWedge",
        "pie",
        "blockArc",
        "donut",
        "noSmoking",
        "rightArrow",
        "leftArrow",
        "upArrow",
        "downArrow",
        "stripedRightArrow",
        "notchedRightArrow",
        "bentUpArrow",
        "leftRightArrow",
        "upDownArrow",
        "leftUpArrow",
        "leftRightUpArrow",
        "quadArrow",
        "leftArrowCallout",
        "rightArrowCallout",
        "upArrowCallout",
        "downArrowCallout",
        "leftRightArrowCallout",
        "upDownArrowCallout",
        "quadArrowCallout",
        "bentArrow",
        "uturnArrow",
        "circularArrow",
        "leftCircularArrow",
        "leftRightCircularArrow",
        "curvedRightArrow",
        "curvedLeftArrow",
        "curvedUpArrow",
        "curvedDownArrow",
        "swooshArrow",
        "cube",
        "can",
        "lightningBolt",
        "heart",
        "sun",
        "moon",
        "smileyFace",
        "irregularSeal1",
        "irregularSeal2",
        "foldedCorner",
        "bevel",
        "frame",
        "halfFrame",
        "corner",
        "diagStripe",
        "chord",
        "arc",
        "leftBracket",
        "rightBracket",
        "leftBrace",
        "rightBrace",
        "bracketPair",
        "bracePair",
        "straightConnector1",
        "bentConnector2",
        "bentConnector3",
        "bentConnector4",
        "bentConnector5",
        "curvedConnector2",
        "curvedConnector3",
        "curvedConnector4",
        "curvedConnector5",
        "callout1",
        "callout2",
        "callout3",
        "accentCallout1",
        "accentCallout2",
        "accentCallout3",
        "borderCallout1",
        "borderCallout2",
        "borderCallout3",
        "accentBorderCallout1",
        "accentBorderCallout2",
        "accentBorderCallout3",
        "wedgeRectCallout",
        "wedgeRoundRectCallout",
        "wedgeEllipseCallout",
        "cloudCallout",
        "cloud",
        "ribbon",
        "ribbon2",
        "ellipseRibbon",
        "ellipseRibbon2",
        "leftRightRibbon",
        "verticalScroll",
        "horizontalScroll",
        "wave",
        "doubleWave",
        "plus",
        "flowChartProcess",
        "flowChartDecision",
        "flowChartInputOutput",
        "flowChartPredefinedProcess",
        "flowChartInternalStorage",
        "flowChartDocument",
        "flowChartMultidocument",
        "flowChartTerminator",
        "flowChartPreparation",
        "flowChartManualInput",
        "flowChartManualOperation",
        "flowChartConnector",
        "flowChartPunchedCard",
        "flowChartPunchedTape",
        "flowChartSummingJunction",
        "flowChartOr",
        "flowChartCollate",
        "flowChartSort",
        "flowChartExtract",
        "flowChartMerge",
        "flowChartOfflineStorage",
        "flowChartOnlineStorage",
        "flowChartMagneticTape",
        "flowChartMagneticDisk",
        "flowChartMagneticDrum",
        "flowChartDisplay",
        "flowChartDelay",
        "flowChartAlternateProcess",
        "flowChartOffpageConnector",
        "actionButtonBlank",
        "actionButtonHome",
        "actionButtonHelp",
        "actionButtonInformation",
        "actionButtonForwardNext",
        "actionButtonBackPrevious",
        "actionButtonEnd",
        "actionButtonBeginning",
        "actionButtonReturn",
        "actionButtonDocument",
        "actionButtonSound",
        "actionButtonMovie",
        "gear6",
        "gear9",
        "funnel",
        "mathPlus",
        "mathMinus",
        "mathMultiply",
        "mathDivide",
        "mathEqual",
        "mathNotEqual",
        "cornerTabs",
        "squareTabs",
        "plaqueTabs",
        "chartX",
        "chartStar",
        "chartPlus",
    };

    internal static DocumentFormat.OpenXml.Drawing.ShapeTypeValues ToOpenXml(this OfficePresetShapeType value) =>
        new(GetToken(value, OfficePresetShapeTypeTokens));

    internal static DocumentFormat.OpenXml.Drawing.ShapeTypeValues? ToOpenXml(this OfficePresetShapeType? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static OfficePresetShapeType ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.ShapeTypeValues value) =>
        (OfficePresetShapeType)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, OfficePresetShapeTypeTokens, nameof(OfficePresetShapeType));

    internal static OfficePresetShapeType? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.ShapeTypeValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static string GetToken<TEnum>(TEnum value, string[] tokens) where TEnum : struct, Enum {
        int index = Convert.ToInt32(value, CultureInfo.InvariantCulture);
        if ((uint)index >= (uint)tokens.Length) throw new ArgumentOutOfRangeException(nameof(value), value, $"Unsupported {typeof(TEnum).Name} value.");
        return tokens[index];
    }

    private static int FindToken(string token, string[] tokens, string enumName) {
        int index = Array.IndexOf(tokens, token);
        if (index < 0) throw new ArgumentOutOfRangeException(nameof(token), token, $"Unsupported {enumName} token.");
        return index;
    }
}
