namespace OfficeIMO.Email;

/// <summary>Result of creating a signed or encrypted S/MIME message.</summary>
public sealed class EmailSmimeCreationResult {
    private readonly byte[] _message;
    private readonly byte[] _protectedMimeEntity;
    private readonly byte[] _encodedCms;

    internal EmailSmimeCreationResult(EmailProtectionKind protectionKind, byte[] message, byte[] protectedMimeEntity,
        byte[] encodedCms, IReadOnlyList<EmailDiagnostic> diagnostics) {
        ProtectionKind = protectionKind;
        _message = (byte[])message.Clone();
        _protectedMimeEntity = (byte[])protectedMimeEntity.Clone();
        _encodedCms = (byte[])encodedCms.Clone();
        Diagnostics = diagnostics;
    }

    /// <summary>Protection wrapper written to the resulting message.</summary>
    public EmailProtectionKind ProtectionKind { get; }

    /// <summary>Complete RFC 5322 message bytes, including transport headers.</summary>
    public byte[] Message => (byte[])_message.Clone();

    /// <summary>Protected MIME entity placed after the transport headers.</summary>
    public byte[] ProtectedMimeEntity => (byte[])_protectedMimeEntity.Clone();

    /// <summary>CMS SignedData or EnvelopedData generated by the supplied security provider.</summary>
    public byte[] EncodedCms => (byte[])_encodedCms.Clone();

    /// <summary>Email serialization diagnostics produced while creating the protected entity.</summary>
    public IReadOnlyList<EmailDiagnostic> Diagnostics { get; }
}
