using System;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using HtmlTinkerX;
using PdfCore = OfficeIMO.Pdf;

namespace OfficeIMO.Html.Pdf.Browser;

/// <summary>Connects HtmlTinkerX browser capture to the canonical OfficeIMO PDF document model.</summary>
public static class HtmlBrowserPdfOfficeExtensions {
    /// <summary>
    /// Opens an HtmlTinkerX browser capture as an OfficeIMO PDF document and preserves browser diagnostics
    /// as a typed source-stage conversion report.
    /// </summary>
    public static PdfCore.PdfDocumentConversionResult ToPdfDocumentResult(
        this HtmlBrowserPdfResult captureResult,
        PdfCore.PdfLoadOptions? readOptions = null,
        CancellationToken cancellationToken = default) {
        if (captureResult == null) throw new ArgumentNullException(nameof(captureResult));
        cancellationToken.ThrowIfCancellationRequested();

        using Stream stream = captureResult.OpenRead();
        PdfCore.PdfDocument document = PdfCore.PdfDocument.Load(stream, readOptions);
        cancellationToken.ThrowIfCancellationRequested();
        return CreateResult(captureResult, document);
    }

    /// <summary>
    /// Asynchronously opens an HtmlTinkerX browser capture as an OfficeIMO PDF document and preserves browser
    /// diagnostics as a typed source-stage conversion report.
    /// </summary>
    public static async Task<PdfCore.PdfDocumentConversionResult> ToPdfDocumentResultAsync(
        this HtmlBrowserPdfResult captureResult,
        PdfCore.PdfLoadOptions? readOptions = null,
        CancellationToken cancellationToken = default) {
        if (captureResult == null) throw new ArgumentNullException(nameof(captureResult));
        cancellationToken.ThrowIfCancellationRequested();

        using Stream stream = captureResult.OpenRead();
        PdfCore.PdfDocument document = await PdfCore.PdfDocument
            .LoadAsync(stream, readOptions, cancellationToken)
            .ConfigureAwait(false);
        return CreateResult(captureResult, document);
    }

    /// <summary>
    /// Captures a URL or HTML source through HtmlTinkerX and opens the generated bytes as an OfficeIMO PDF document.
    /// </summary>
    public static async Task<PdfCore.PdfDocument> CapturePdfDocumentAsync(
        this HtmlBrowserPdfRenderer renderer,
        HtmlBrowserPdfRequest request,
        PdfCore.PdfLoadOptions? readOptions = null,
        CancellationToken cancellationToken = default) =>
        (await renderer.CapturePdfDocumentResultAsync(request, readOptions, cancellationToken).ConfigureAwait(false)).Value;

    /// <summary>
    /// Captures a URL or HTML source through HtmlTinkerX, opens the generated bytes as an OfficeIMO PDF document,
    /// and retains browser diagnostics in the returned conversion result.
    /// </summary>
    public static async Task<PdfCore.PdfDocumentConversionResult> CapturePdfDocumentResultAsync(
        this HtmlBrowserPdfRenderer renderer,
        HtmlBrowserPdfRequest request,
        PdfCore.PdfLoadOptions? readOptions = null,
        CancellationToken cancellationToken = default) {
        if (renderer == null) throw new ArgumentNullException(nameof(renderer));
        if (request == null) throw new ArgumentNullException(nameof(request));

        HtmlBrowserPdfResult captureResult = await renderer
            .CaptureAsync(request, cancellationToken)
            .ConfigureAwait(false);
        return await captureResult
            .ToPdfDocumentResultAsync(readOptions, cancellationToken)
            .ConfigureAwait(false);
    }

    private static PdfCore.PdfDocumentConversionResult CreateResult(
        HtmlBrowserPdfResult captureResult,
        PdfCore.PdfDocument document) =>
        new PdfCore.PdfDocumentConversionResult(document, new PdfCore.PdfConversionReport())
            .WithSourceConversionReport(new HtmlBrowserPdfCaptureReport(
                captureResult.Diagnostics,
                captureResult.Tagged));
}
