using System.Text.Json.Serialization;

namespace OfficeIMO.Workflows;

/// <summary>Local archive conversion with separate source, output and durable checkpoint directories.</summary>
public sealed record OfficePdfArchiveRequest {
    /// <summary>Source directory; descendants are discovered incrementally without following links.</summary>
    public required string InputDirectory { get; set; }
    /// <summary>Separate destination directory. Relative paths retain the full source name plus .pdf.</summary>
    public required string OutputDirectory { get; set; }
    /// <summary>Private durable state directory, outside both source and output trees.</summary>
    public required string CheckpointDirectory { get; set; }
    /// <summary>Maximum simultaneously executing files, from 1 through 8.</summary>
    public int MaximumConcurrency { get; set; } = 2;
    /// <summary>Maximum selected files in one run; discovery never materializes the archive in memory.</summary>
    public int MaximumFiles { get; set; } = 1_000_000;
    /// <summary>Maximum input bytes per document.</summary>
    public long MaximumInputBytes { get; set; } = 64L * 1024 * 1024;
    /// <summary>Maximum PDF output bytes per document.</summary>
    public long MaximumOutputBytes { get; set; } = 256L * 1024 * 1024;
    /// <summary>Literal text encoding, or null for Unicode BOM detection and strict UTF-8.</summary>
    public string? TextEncoding { get; set; }
    /// <summary>Literal text tab columns, from 1 through 32.</summary>
    public int TabSize { get; set; } = 8;
    /// <summary>Decoded and expanded literal text limit.</summary>
    public int MaximumTextCharacters { get; set; } = 16 * 1024 * 1024;
    /// <summary>Maximum pages generated by literal text conversion.</summary>
    public int MaximumTextPages { get; set; } = 10_000;
    /// <summary>Explicit acceptance of known legacy import loss. Default false.</summary>
    public bool AllowLegacyImportLoss { get; set; }
    /// <summary>Retry recorded failures. Completed files still require source and output hash verification.</summary>
    public bool RetryFailed { get; set; }
}

/// <summary>One archive outcome; callbacks may arrive concurrently and contain operational paths.</summary>
public sealed record OfficePdfArchiveItemResult(string InputPath, string OutputPath, OfficeWorkflowStatus Status,
    bool Reused, string Summary, IReadOnlyList<OfficeWorkflowDiagnostic> Diagnostics);

/// <summary>Bounded summary. Completed outputs survive cancellation and item failures.</summary>
public sealed record OfficePdfArchiveResult(long Selected, long Completed, long Reused, long Failed, bool Cancelled);

internal sealed record OfficePdfArchivePlan(string Schema, string ConfigurationSha256);
internal sealed record OfficePdfArchiveReceipt(string Schema, string ConfigurationSha256, string InputSha256,
    string? OutputSha256, OfficeWorkflowStatus Status, string Summary, OfficePdfArchiveStoredDiagnostic[] Diagnostics, int DiagnosticCount);
internal sealed record OfficePdfArchiveStoredDiagnostic(string Code, string Message, OfficeWorkflowDiagnosticSeverity Severity,
    string? Stage, string? Source, string? LossKind);

[JsonSourceGenerationOptions(UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow)]
[JsonSerializable(typeof(OfficePdfArchiveRequest))]
[JsonSerializable(typeof(OfficePdfArchiveResult))]
[JsonSerializable(typeof(OfficePdfArchivePlan))]
[JsonSerializable(typeof(OfficePdfArchiveReceipt))]
internal partial class OfficePdfArchiveJsonContext : JsonSerializerContext { }
