using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using OfficeIMO.Visio;
using Xunit;

namespace OfficeIMO.Tests {
    public class VisioShowcaseSummaryTests {
        [Fact]
        public void ShowcaseSummaryWritesMarkdownJsonAndHtmlArtifactLists() {
            string folderPath = Path.Combine(Path.GetTempPath(), "OfficeIMO-Visio-Showcase-Summary-" + Guid.NewGuid());
            string nativePreviewPath = Path.Combine(folderPath, "Native Preview");
            string desktopPreviewPath = Path.Combine(folderPath, "Preview");
            string structuralProofPath = Path.Combine(folderPath, "Structural Proof");
            Directory.CreateDirectory(nativePreviewPath);
            Directory.CreateDirectory(desktopPreviewPath);
            Directory.CreateDirectory(structuralProofPath);
            string packagePath = Path.Combine(folderPath, "sample.vsdx");
            string previewPath = Path.Combine(nativePreviewPath, "sample-page1.native.png");
            string desktopPreviewFilePath = Path.Combine(desktopPreviewPath, "sample-page1.png");
            string inspectionPath = Path.Combine(structuralProofPath, "sample.inspection.txt");
            string stencilProfilePath = Path.Combine(structuralProofPath, "sample.stencil-profile.txt");
            string visualQualityPath = Path.Combine(structuralProofPath, "sample.visual-quality.txt");
            string stencilProfileText = "profile.totalShapes=3\nprofile.connectorCount=1\nprofile.totalConnectionPoints=7\nprofile.connectionPointShapeCount=2\nprofile.stencilFamilyCount=2\nprofile.stencilBackedShapeCount=2\nprofile.basicGeometryShapeCount=3\nprofile.masterBackedShapeCount=0\nprofile.packageBackedShapeCount=0\nprofile.generatedMasterBackedShapeCount=0\nprofile.semanticOnlyShapeCount=1\nprofile.shapeDataKeys=Owner,Sla\nprofile.connectorShapeDataKeys=Decision\nprofile.semanticKinds=BackgroundSurface\nprofile.stencilCatalogs=Flowchart,Security and Identity\nprofile.usageCount=2\n";
            string visualQualityText = "quality.isClean=true\nquality.issueCount=0\nquality.errorCount=0\nquality.warningCount=0\nquality.informationCount=0\nquality.issueKinds=\n";
            File.WriteAllBytes(packagePath, new byte[] { 1, 2, 3 });
            File.WriteAllBytes(previewPath, new byte[] { 4, 5, 6, 7 });
            File.WriteAllBytes(desktopPreviewFilePath, new byte[] { 8, 9, 10, 11, 12 });
            File.WriteAllBytes(inspectionPath, new byte[] { 13, 14, 15 });
            File.WriteAllText(stencilProfilePath, stencilProfileText, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
            File.WriteAllText(visualQualityPath, visualQualityText, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

            VisioShowcaseSummary summary = VisioShowcaseSummary.Create(
                folderPath,
                new[] { packagePath },
                new[] { previewPath, desktopPreviewFilePath },
                new DateTimeOffset(2026, 6, 5, 12, 0, 0, TimeSpan.Zero),
                new[] { inspectionPath, stencilProfilePath, visualQualityPath });
            VisioShowcaseValidationReport report = summary.ValidateArtifacts(requirePreviewsPerDiagram: true, requireProofsPerDiagram: true);
            Assert.True(report.IsClean, report.ToString());
            summary.EnsureArtifactsValid(requirePreviewsPerDiagram: true, requireProofsPerDiagram: true);
            summary.SaveArtifacts();

            VisioShowcaseArtifact package = Assert.Single(summary.Packages);
            Assert.Equal(2, summary.Previews.Count);
            Assert.Equal(3, summary.Proofs.Count);
            Assert.Equal(new[] { "Flowchart", "Security and Identity" }, summary.StencilCatalogs);
            Assert.Equal(2, summary.StencilCatalogCoverage.Count);
            Assert.Equal("Flowchart", summary.StencilCatalogCoverage[0].Catalog);
            Assert.Equal(new[] { "sample" }, summary.StencilCatalogCoverage[0].DiagramNames);
            Assert.Equal("Security and Identity", summary.StencilCatalogCoverage[1].Catalog);
            Assert.Equal(1, summary.StencilCatalogCoverage[1].DiagramCount);
            Assert.Equal(3, summary.ProofTotals.TotalShapeCount);
            Assert.Equal(1, summary.ProofTotals.ConnectorCount);
            Assert.Equal(2, summary.ProofTotals.StencilUsageCount);
            Assert.Equal(7, summary.ProofTotals.TotalConnectionPointCount);
            Assert.Equal(2, summary.ProofTotals.ConnectionPointShapeCount);
            Assert.Equal(2, summary.ProofTotals.StencilFamilyCount);
            Assert.Equal(2, summary.ProofTotals.StencilBackedShapeCount);
            Assert.Equal(3, summary.ProofTotals.BasicGeometryShapeCount);
            Assert.Equal(0, summary.ProofTotals.MasterBackedShapeCount);
            Assert.Equal(0, summary.ProofTotals.PackageBackedShapeCount);
            Assert.Equal(0, summary.ProofTotals.GeneratedMasterBackedShapeCount);
            Assert.Equal(1, summary.ProofTotals.SemanticOnlyShapeCount);
            Assert.Equal(new[] { "Flowchart", "Security and Identity" }, summary.ProofTotals.StencilCatalogs);
            Assert.Equal(new[] { "Owner", "Sla" }, summary.ProofTotals.ShapeDataKeys);
            Assert.Equal(new[] { "Decision" }, summary.ProofTotals.ConnectorShapeDataKeys);
            Assert.Equal(new[] { "BackgroundSurface" }, summary.ProofTotals.SemanticKinds);
            Assert.Equal(1, summary.EvidenceTotals.DiagramCount);
            Assert.Equal(0, summary.EvidenceTotals.NativeSvgPreviewDiagramCount);
            Assert.Equal(1, summary.EvidenceTotals.NativePngPreviewDiagramCount);
            Assert.Equal(0, summary.EvidenceTotals.CompleteNativePreviewDiagramCount);
            Assert.Equal(0, summary.EvidenceTotals.DesktopSvgPreviewDiagramCount);
            Assert.Equal(1, summary.EvidenceTotals.DesktopPngPreviewDiagramCount);
            Assert.Equal(0, summary.EvidenceTotals.CompleteDesktopPreviewDiagramCount);
            Assert.Equal(1, summary.EvidenceTotals.InspectionProofDiagramCount);
            Assert.Equal(1, summary.EvidenceTotals.StencilProfileProofDiagramCount);
            Assert.Equal(1, summary.EvidenceTotals.VisualQualityProofDiagramCount);
            Assert.Equal(1, summary.EvidenceTotals.CleanVisualQualityDiagramCount);
            Assert.Equal(0, summary.EvidenceTotals.VisualQualityIssueDiagramCount);
            Assert.Equal(0, summary.EvidenceTotals.VisualQualityIssueCount);
            Assert.Equal(0, summary.EvidenceTotals.VisualQualityErrorCount);
            Assert.Equal(0, summary.EvidenceTotals.VisualQualityWarningCount);
            Assert.Equal(0, summary.EvidenceTotals.VisualQualityInformationCount);
            Assert.Equal(1, summary.EvidenceTotals.CompleteStructuralProofDiagramCount);
            Assert.Equal(1, summary.EvidenceTotals.CompleteReviewProofDiagramCount);
            Assert.Equal(0, summary.EvidenceTotals.CompleteNativeEvidenceDiagramCount);
            Assert.Equal(0, summary.EvidenceTotals.CompleteDesktopEvidenceDiagramCount);
            Assert.Equal(0, summary.EvidenceTotals.CompletePreviewEvidenceDiagramCount);
            Assert.Equal(new[] { "sample" }, summary.EvidenceTotals.DiagramsMissingNativeSvgPreview);
            Assert.Equal(new[] { "sample" }, summary.EvidenceTotals.DiagramsMissingCompleteNativePreview);
            Assert.Empty(summary.EvidenceTotals.DiagramsMissingInspectionProof);
            Assert.Empty(summary.EvidenceTotals.DiagramsMissingStencilProfileProof);
            Assert.Empty(summary.EvidenceTotals.DiagramsMissingVisualQualityProof);
            Assert.Empty(summary.EvidenceTotals.DiagramsWithVisualQualityIssues);
            Assert.Empty(summary.EvidenceTotals.DiagramsMissingCompleteStructuralProof);
            Assert.Empty(summary.EvidenceTotals.DiagramsMissingCompleteReviewProof);
            VisioShowcaseDiagram diagram = Assert.Single(summary.Diagrams);
            Assert.False(diagram.Evidence.HasNativeSvgPreview);
            Assert.True(diagram.Evidence.HasNativePngPreview);
            Assert.False(diagram.Evidence.HasDesktopSvgPreview);
            Assert.True(diagram.Evidence.HasDesktopPngPreview);
            Assert.True(diagram.Evidence.HasInspectionProof);
            Assert.True(diagram.Evidence.HasStencilProfileProof);
            Assert.True(diagram.Evidence.HasVisualQualityProof);
            Assert.True(diagram.VisualQualitySummary.HasProof);
            Assert.True(diagram.VisualQualitySummary.IsClean);
            Assert.Equal(0, diagram.VisualQualitySummary.IssueCount);
            Assert.Equal(0, diagram.VisualQualitySummary.ErrorCount);
            Assert.Equal(0, diagram.VisualQualitySummary.WarningCount);
            Assert.Equal(0, diagram.VisualQualitySummary.InformationCount);
            Assert.Empty(diagram.VisualQualitySummary.IssueKinds);
            Assert.False(diagram.Evidence.HasCompleteNativePreview);
            Assert.False(diagram.Evidence.HasCompleteDesktopPreview);
            Assert.True(diagram.Evidence.HasCompleteStructuralProof);
            Assert.True(diagram.Evidence.HasCompleteReviewProof);
            Assert.False(diagram.Evidence.HasCompletePreviewEvidence);
            VisioShowcaseArtifact preview = summary.Previews.Single(item => item.Kind == VisioShowcaseArtifactKind.NativePreview);
            VisioShowcaseArtifact desktopPreview = summary.Previews.Single(item => item.Kind == VisioShowcaseArtifactKind.DesktopPreview);
            VisioShowcaseArtifact inspection = summary.Proofs.Single(item => item.Kind == VisioShowcaseArtifactKind.Inspection);
            VisioShowcaseArtifact stencilProfile = summary.Proofs.Single(item => item.Kind == VisioShowcaseArtifactKind.StencilProfile);
            VisioShowcaseArtifact visualQuality = summary.Proofs.Single(item => item.Kind == VisioShowcaseArtifactKind.VisualQuality);
            Assert.Equal("sample.vsdx", package.RelativePath);
            Assert.Equal("039058c6f2c0cb492c533b0a4d14ef77cc0f78abccced5287d84a1a2011cfb81", package.Sha256);
            Assert.Equal("sample", diagram.Name);
            Assert.Equal(package, diagram.Package);
            Assert.Equal(2, diagram.Previews.Count);
            Assert.Equal(3, diagram.Proofs.Count);
            Assert.Equal(3, diagram.ProofSummary.TotalShapeCount);
            Assert.Equal(1, diagram.ProofSummary.ConnectorCount);
            Assert.Equal(7, diagram.ProofSummary.TotalConnectionPointCount);
            Assert.Equal(2, diagram.ProofSummary.ConnectionPointShapeCount);
            Assert.Equal(2, diagram.ProofSummary.StencilFamilyCount);
            Assert.Equal(2, diagram.ProofSummary.StencilBackedShapeCount);
            Assert.Equal(3, diagram.ProofSummary.BasicGeometryShapeCount);
            Assert.Equal(0, diagram.ProofSummary.MasterBackedShapeCount);
            Assert.Equal(0, diagram.ProofSummary.PackageBackedShapeCount);
            Assert.Equal(0, diagram.ProofSummary.GeneratedMasterBackedShapeCount);
            Assert.Equal(1, diagram.ProofSummary.SemanticOnlyShapeCount);
            Assert.Equal(2, diagram.ProofSummary.StencilCatalogCount);
            Assert.Equal(2, diagram.ProofSummary.StencilUsageCount);
            Assert.Equal(new[] { "Flowchart", "Security and Identity" }, diagram.ProofSummary.StencilCatalogs);
            Assert.Equal(new[] { "Owner", "Sla" }, diagram.ProofSummary.ShapeDataKeys);
            Assert.Equal(new[] { "Decision" }, diagram.ProofSummary.ConnectorShapeDataKeys);
            Assert.Equal(new[] { "BackgroundSurface" }, diagram.ProofSummary.SemanticKinds);
            Assert.Equal(VisioShowcaseArtifactKind.NativePreview, preview.Kind);
            Assert.Equal("Native Preview/sample-page1.native.png", preview.RelativePath);
            Assert.Equal("c6d44cf418f610e3fe9e1d9294ff43def81c6cdcad6cbb1820cff48d3aa4355d", preview.Sha256);
            Assert.Equal("Preview/sample-page1.png", desktopPreview.RelativePath);
            Assert.Equal("bd420fe3805369a34abadcc6b32fd58d81c8ef3befe97c9a67532efef7d7b1c8", desktopPreview.Sha256);
            Assert.Equal("Structural Proof/sample.inspection.txt", inspection.RelativePath);
            Assert.Equal("d41470f8fe2547d6c4d4802d484fe7ff5a5bbecd5612eeeb1360df0c4781d95e", inspection.Sha256);
            Assert.Equal("Structural Proof/sample.stencil-profile.txt", stencilProfile.RelativePath);
            Assert.Equal("eae46dafce8a0a423160efc71e4161bc8321fc915c5e6490cb713d51ac6993d1", stencilProfile.Sha256);
            Assert.Equal("Structural Proof/sample.visual-quality.txt", visualQuality.RelativePath);
            Assert.Equal("4c0f30cee2cc7ae626fa3ea8243baffbe432b0d66af60703f849e602bd680a1f", visualQuality.Sha256);

            string markdown = File.ReadAllText(Path.Combine(folderPath, VisioShowcaseSummary.MarkdownFileName));
            Assert.Contains("Machine-readable summary: `showcase-summary.json`", markdown);
            Assert.Contains("Diagrams: 1", markdown);
            Assert.Contains("VSDX files: 1", markdown);
            Assert.Contains("Preview files: 2", markdown);
            Assert.Contains("Structural proof files: 3", markdown);
            Assert.Contains("Stencil catalogs: 2 (Flowchart, Security and Identity)", markdown);
            Assert.Contains("Proof total shapes: 3", markdown);
            Assert.Contains("Proof total connectors: 1", markdown);
            Assert.Contains("Proof stencil-backed shapes: 2", markdown);
            Assert.Contains("Proof connection points: 7", markdown);
            Assert.Contains("Complete native evidence: 0/1", markdown);
            Assert.Contains("Complete structural proof: 1/1", markdown);
            Assert.Contains("Complete review proof: 1/1", markdown);
            Assert.Contains("Clean visual quality: 1/1", markdown);
            Assert.Contains("Visual quality issues: 0 (0 errors, 0 warnings)", markdown);
            Assert.Contains("Total artifacts: 6", markdown);
            Assert.Contains("Browsable gallery: `showcase-gallery.html`", markdown);
            Assert.Contains("## Evidence Coverage", markdown);
            Assert.Contains("- Native SVG previews: 0/1", markdown);
            Assert.Contains("- Native PNG previews: 1/1", markdown);
            Assert.Contains("- Complete native preview evidence: 0/1", markdown);
            Assert.Contains("- Visual-quality proofs: 1/1", markdown);
            Assert.Contains("- Clean visual-quality proofs: 1/1", markdown);
            Assert.Contains("- Visual-quality issues: 0 total, 0 errors, 0 warnings, 0 informational", markdown);
            Assert.Contains("- Complete structural proof: 1/1", markdown);
            Assert.Contains("- Complete review proof: 1/1", markdown);
            Assert.Contains("## Proof Totals", markdown);
            Assert.Contains("- 3 shapes, 1 connectors, 2 stencil-backed shapes, 3 basic geometry shapes, 7 connection points, 2 distinct shape-data keys, 1 distinct connector-data keys, 1 semantic kinds", markdown);
            Assert.Contains("## Stencil Catalog Coverage", markdown);
            Assert.Contains("- Flowchart: 1 diagrams (sample)", markdown);
            Assert.Contains("- Security and Identity: 1 diagrams (sample)", markdown);
            Assert.Contains("## Diagram Proof Summary", markdown);
            Assert.Contains("- sample: 2 stencil catalogs (Flowchart, Security and Identity), 2 stencil usage groups, 3 shapes, 1 connectors, 2 shape-data keys, 1 connector-data keys, 2 stencil-backed shapes, 3 basic geometry shapes, 7 connection points", markdown);
            Assert.Contains("sha256: 039058c6f2c0cb492c533b0a4d14ef77cc0f78abccced5287d84a1a2011cfb81", markdown);
            Assert.Contains("sha256: c6d44cf418f610e3fe9e1d9294ff43def81c6cdcad6cbb1820cff48d3aa4355d", markdown);
            Assert.Contains("sha256: bd420fe3805369a34abadcc6b32fd58d81c8ef3befe97c9a67532efef7d7b1c8", markdown);
            Assert.Contains("sha256: d41470f8fe2547d6c4d4802d484fe7ff5a5bbecd5612eeeb1360df0c4781d95e", markdown);
            Assert.Contains("sha256: eae46dafce8a0a423160efc71e4161bc8321fc915c5e6490cb713d51ac6993d1", markdown);
            Assert.Contains("sha256: 4c0f30cee2cc7ae626fa3ea8243baffbe432b0d66af60703f849e602bd680a1f", markdown);

            string html = File.ReadAllText(Path.Combine(folderPath, VisioShowcaseSummary.HtmlFileName));
            Assert.Contains("OfficeIMO Visio Showcase", html);
            Assert.Contains("<nav class=\"gallery-nav\" aria-label=\"Showcase sections\">", html);
            Assert.Contains("href=\"#evidence-coverage\"", html);
            Assert.Contains("href=\"#proof-totals\"", html);
            Assert.Contains("href=\"#review-index\"", html);
            Assert.Contains("href=\"#stencil-coverage\"", html);
            Assert.Contains("<h2 id=\"evidence-coverage\">Evidence Coverage</h2>", html);
            Assert.Contains("<tr><td>Native SVG preview</td><td>0/1</td><td>sample</td></tr>", html);
            Assert.Contains("<tr><td>Native PNG preview</td><td>1/1</td><td>None</td></tr>", html);
            Assert.Contains("<tr><td>Complete native preview</td><td>0/1</td><td>sample</td></tr>", html);
            Assert.Contains("<tr><td>Inspection proof</td><td>1/1</td><td>None</td></tr>", html);
            Assert.Contains("<tr><td>Stencil-profile proof</td><td>1/1</td><td>None</td></tr>", html);
            Assert.Contains("<tr><td>Visual-quality proof</td><td>1/1</td><td>None</td></tr>", html);
            Assert.Contains("<tr><td>Clean visual quality</td><td>1/1</td><td>None</td></tr>", html);
            Assert.Contains("<tr><td>Complete structural proof</td><td>1/1</td><td>None</td></tr>", html);
            Assert.Contains("<tr><td>Complete review proof</td><td>1/1</td><td>None</td></tr>", html);
            Assert.Contains("<strong>0</strong><span>Complete native evidence</span>", html);
            Assert.Contains("<strong>1</strong><span>Complete structural proof</span>", html);
            Assert.Contains("<strong>1</strong><span>Complete review proof</span>", html);
            Assert.Contains("<strong>1</strong><span>Clean visual quality</span>", html);
            Assert.Contains("<strong>0</strong><span>Visual quality issues</span>", html);
            Assert.Contains("<h2 id=\"proof-totals\">Proof Totals</h2>", html);
            Assert.Contains("<tr><td>Shapes</td><td>3</td></tr>", html);
            Assert.Contains("<tr><td>Connectors</td><td>1</td></tr>", html);
            Assert.Contains("<tr><td>Stencil-backed shapes</td><td>2</td></tr>", html);
            Assert.Contains("<tr><td>Basic geometry shapes</td><td>3</td></tr>", html);
            Assert.Contains("<tr><td>Connection points</td><td>7</td></tr>", html);
            Assert.Contains("<tr><td>Distinct Shape Data keys</td><td>2</td></tr>", html);
            Assert.Contains("<tr><td>Distinct connector Shape Data keys</td><td>1</td></tr>", html);
            Assert.Contains("<tr><td>Semantic kinds</td><td>1</td></tr>", html);
            Assert.Contains("<h2 id=\"review-index\">Review Index</h2>", html);
            Assert.Contains("<h2 id=\"stencil-coverage\">Stencil Coverage</h2>", html);
            Assert.Contains("<h2 id=\"diagram-review-cards\">Diagram Review Cards</h2>", html);
            Assert.Contains("<h2 id=\"packages\">Packages</h2>", html);
            Assert.Contains("<h2 id=\"previews\">Previews</h2>", html);
            Assert.Contains("<h2 id=\"structural-proofs\">Structural Proofs</h2>", html);
            Assert.Contains("href=\"#diagram-sample-vsdx\"", html);
            Assert.Contains("<article class=\"diagram-card\" id=\"diagram-sample-vsdx\">", html);
            Assert.Contains("2 previews", html);
            Assert.Contains("3 proofs", html);
            Assert.Contains("<strong>2</strong><span>Stencil catalogs</span>", html);
            Assert.Contains("<strong>3</strong><span>Proof shapes</span>", html);
            Assert.Contains("<strong>1</strong><span>Proof connectors</span>", html);
            Assert.Contains("<strong>2</strong><span>Stencil-backed shapes</span>", html);
            Assert.Contains("<strong>7</strong><span>Connection points</span>", html);
            Assert.Contains("<th>Stencil Catalogs</th>", html);
            Assert.Contains("<th>Stencil Catalog</th><th>Diagrams</th><th>Diagram Names</th>", html);
            Assert.Contains("<tr><td>Flowchart</td><td>1</td><td>sample</td></tr>", html);
            Assert.Contains("2 stencil catalogs / 2 stencil usage groups", html);
            Assert.Contains("<span class=\"catalog\">Flowchart</span>", html);
            Assert.Contains("<span class=\"catalog\">Security and Identity</span>", html);
            Assert.Contains("3 shapes / 1 connectors / 2 shape-data keys", html);
            Assert.Contains("2 stencil-backed / 3 basic geometry / 7 connection points", html);
            Assert.Contains("href=\"sample.vsdx\"", html);
            Assert.Contains("src=\"Native%20Preview/sample-page1.native.png\"", html);
            Assert.Contains("href=\"Preview/sample-page1.png\"", html);
            Assert.Contains("href=\"Structural%20Proof/sample.inspection.txt\"", html);
            Assert.Contains("href=\"Structural%20Proof/sample.stencil-profile.txt\"", html);
            Assert.Contains("href=\"Structural%20Proof/sample.visual-quality.txt\"", html);
            Assert.Contains("href=\"showcase-summary.json\"", html);
            Assert.Contains("<th>SHA-256</th>", html);
            Assert.Contains("title=\"039058c6f2c0cb492c533b0a4d14ef77cc0f78abccced5287d84a1a2011cfb81\">039058c6f2c0</code>", html);
            Assert.Contains("title=\"c6d44cf418f610e3fe9e1d9294ff43def81c6cdcad6cbb1820cff48d3aa4355d\">c6d44cf418f6</code>", html);
            Assert.Contains("title=\"bd420fe3805369a34abadcc6b32fd58d81c8ef3befe97c9a67532efef7d7b1c8\">bd420fe38053</code>", html);
            Assert.Contains("title=\"d41470f8fe2547d6c4d4802d484fe7ff5a5bbecd5612eeeb1360df0c4781d95e\">d41470f8fe25</code>", html);
            Assert.Contains("title=\"eae46dafce8a0a423160efc71e4161bc8321fc915c5e6490cb713d51ac6993d1\">eae46dafce8a</code>", html);
            Assert.Contains("title=\"4c0f30cee2cc7ae626fa3ea8243baffbe432b0d66af60703f849e602bd680a1f\">4c0f30cee2cc</code>", html);

            using JsonDocument json = JsonDocument.Parse(File.ReadAllText(Path.Combine(folderPath, VisioShowcaseSummary.JsonFileName)));
            JsonElement root = json.RootElement;
            Assert.Equal(VisioShowcaseSummary.JsonSchemaVersion, root.GetProperty("schemaVersion").GetInt32());
            Assert.Equal(1, root.GetProperty("diagramCount").GetInt32());
            Assert.Equal(1, root.GetProperty("packageCount").GetInt32());
            Assert.Equal(2, root.GetProperty("previewCount").GetInt32());
            Assert.Equal(3, root.GetProperty("proofCount").GetInt32());
            Assert.Equal(2, root.GetProperty("stencilCatalogCount").GetInt32());
            JsonElement summaryStencilCatalogs = root.GetProperty("stencilCatalogs");
            Assert.Equal(2, summaryStencilCatalogs.GetArrayLength());
            Assert.Equal("Flowchart", summaryStencilCatalogs[0].GetString());
            Assert.Equal("Security and Identity", summaryStencilCatalogs[1].GetString());
            JsonElement proofTotals = root.GetProperty("proofTotals");
            Assert.Equal(3, proofTotals.GetProperty("totalShapeCount").GetInt32());
            Assert.Equal(1, proofTotals.GetProperty("connectorCount").GetInt32());
            Assert.Equal(2, proofTotals.GetProperty("stencilUsageCount").GetInt32());
            Assert.Equal(7, proofTotals.GetProperty("totalConnectionPointCount").GetInt32());
            Assert.Equal(2, proofTotals.GetProperty("connectionPointShapeCount").GetInt32());
            Assert.Equal(2, proofTotals.GetProperty("stencilFamilyCount").GetInt32());
            Assert.Equal(2, proofTotals.GetProperty("stencilBackedShapeCount").GetInt32());
            Assert.Equal(3, proofTotals.GetProperty("basicGeometryShapeCount").GetInt32());
            Assert.Equal(0, proofTotals.GetProperty("masterBackedShapeCount").GetInt32());
            Assert.Equal(0, proofTotals.GetProperty("packageBackedShapeCount").GetInt32());
            Assert.Equal(0, proofTotals.GetProperty("generatedMasterBackedShapeCount").GetInt32());
            Assert.Equal(1, proofTotals.GetProperty("semanticOnlyShapeCount").GetInt32());
            Assert.Equal(2, proofTotals.GetProperty("stencilCatalogCount").GetInt32());
            Assert.Equal(2, proofTotals.GetProperty("shapeDataKeyCount").GetInt32());
            Assert.Equal(1, proofTotals.GetProperty("connectorShapeDataKeyCount").GetInt32());
            Assert.Equal(1, proofTotals.GetProperty("semanticKindCount").GetInt32());
            Assert.Equal("Flowchart", proofTotals.GetProperty("stencilCatalogs")[0].GetString());
            Assert.Equal("Security and Identity", proofTotals.GetProperty("stencilCatalogs")[1].GetString());
            Assert.Equal("Owner", proofTotals.GetProperty("shapeDataKeys")[0].GetString());
            Assert.Equal("Sla", proofTotals.GetProperty("shapeDataKeys")[1].GetString());
            Assert.Equal("Decision", proofTotals.GetProperty("connectorShapeDataKeys")[0].GetString());
            Assert.Equal("BackgroundSurface", proofTotals.GetProperty("semanticKinds")[0].GetString());
            JsonElement evidenceTotals = root.GetProperty("evidenceTotals");
            Assert.Equal(1, evidenceTotals.GetProperty("diagramCount").GetInt32());
            Assert.Equal(0, evidenceTotals.GetProperty("nativeSvgPreviewDiagramCount").GetInt32());
            Assert.Equal(1, evidenceTotals.GetProperty("nativePngPreviewDiagramCount").GetInt32());
            Assert.Equal(0, evidenceTotals.GetProperty("completeNativePreviewDiagramCount").GetInt32());
            Assert.Equal(0, evidenceTotals.GetProperty("desktopSvgPreviewDiagramCount").GetInt32());
            Assert.Equal(1, evidenceTotals.GetProperty("desktopPngPreviewDiagramCount").GetInt32());
            Assert.Equal(0, evidenceTotals.GetProperty("completeDesktopPreviewDiagramCount").GetInt32());
            Assert.Equal(1, evidenceTotals.GetProperty("inspectionProofDiagramCount").GetInt32());
            Assert.Equal(1, evidenceTotals.GetProperty("stencilProfileProofDiagramCount").GetInt32());
            Assert.Equal(1, evidenceTotals.GetProperty("visualQualityProofDiagramCount").GetInt32());
            Assert.Equal(1, evidenceTotals.GetProperty("cleanVisualQualityDiagramCount").GetInt32());
            Assert.Equal(0, evidenceTotals.GetProperty("visualQualityIssueDiagramCount").GetInt32());
            Assert.Equal(0, evidenceTotals.GetProperty("visualQualityIssueCount").GetInt32());
            Assert.Equal(0, evidenceTotals.GetProperty("visualQualityErrorCount").GetInt32());
            Assert.Equal(0, evidenceTotals.GetProperty("visualQualityWarningCount").GetInt32());
            Assert.Equal(0, evidenceTotals.GetProperty("visualQualityInformationCount").GetInt32());
            Assert.Equal(1, evidenceTotals.GetProperty("completeStructuralProofDiagramCount").GetInt32());
            Assert.Equal(1, evidenceTotals.GetProperty("completeReviewProofDiagramCount").GetInt32());
            Assert.Equal(0, evidenceTotals.GetProperty("completeNativeEvidenceDiagramCount").GetInt32());
            Assert.Equal(0, evidenceTotals.GetProperty("completeDesktopEvidenceDiagramCount").GetInt32());
            Assert.Equal(0, evidenceTotals.GetProperty("completePreviewEvidenceDiagramCount").GetInt32());
            Assert.Equal("sample", evidenceTotals.GetProperty("diagramsMissingNativeSvgPreview")[0].GetString());
            Assert.Equal("sample", evidenceTotals.GetProperty("diagramsMissingCompleteNativePreview")[0].GetString());
            Assert.Equal(0, evidenceTotals.GetProperty("diagramsMissingInspectionProof").GetArrayLength());
            Assert.Equal(0, evidenceTotals.GetProperty("diagramsMissingStencilProfileProof").GetArrayLength());
            Assert.Equal(0, evidenceTotals.GetProperty("diagramsMissingVisualQualityProof").GetArrayLength());
            Assert.Equal(0, evidenceTotals.GetProperty("diagramsWithVisualQualityIssues").GetArrayLength());
            Assert.Equal(0, evidenceTotals.GetProperty("diagramsMissingCompleteReviewProof").GetArrayLength());
            JsonElement stencilCatalogCoverage = root.GetProperty("stencilCatalogCoverage");
            Assert.Equal(2, stencilCatalogCoverage.GetArrayLength());
            Assert.Equal("Flowchart", stencilCatalogCoverage[0].GetProperty("catalog").GetString());
            Assert.Equal(1, stencilCatalogCoverage[0].GetProperty("diagramCount").GetInt32());
            Assert.Equal("sample", stencilCatalogCoverage[0].GetProperty("diagrams")[0].GetString());
            Assert.Equal("Security and Identity", stencilCatalogCoverage[1].GetProperty("catalog").GetString());
            Assert.Equal(6, root.GetProperty("artifactCount").GetInt32());
            JsonElement diagrams = root.GetProperty("diagrams");
            Assert.Equal(1, diagrams.GetArrayLength());
            Assert.Equal("sample", diagrams[0].GetProperty("name").GetString());
            JsonElement proofSummary = diagrams[0].GetProperty("proofSummary");
            Assert.Equal(3, proofSummary.GetProperty("totalShapeCount").GetInt32());
            Assert.Equal(1, proofSummary.GetProperty("connectorCount").GetInt32());
            Assert.Equal(2, proofSummary.GetProperty("stencilCatalogCount").GetInt32());
            Assert.Equal(2, proofSummary.GetProperty("stencilUsageCount").GetInt32());
            Assert.Equal(2, proofSummary.GetProperty("shapeDataKeyCount").GetInt32());
            Assert.Equal(1, proofSummary.GetProperty("connectorShapeDataKeyCount").GetInt32());
            Assert.Equal(1, proofSummary.GetProperty("semanticKindCount").GetInt32());
            Assert.Equal(7, proofSummary.GetProperty("totalConnectionPointCount").GetInt32());
            Assert.Equal(2, proofSummary.GetProperty("connectionPointShapeCount").GetInt32());
            Assert.Equal(2, proofSummary.GetProperty("stencilFamilyCount").GetInt32());
            Assert.Equal(2, proofSummary.GetProperty("stencilBackedShapeCount").GetInt32());
            Assert.Equal(3, proofSummary.GetProperty("basicGeometryShapeCount").GetInt32());
            Assert.Equal(0, proofSummary.GetProperty("masterBackedShapeCount").GetInt32());
            Assert.Equal(0, proofSummary.GetProperty("packageBackedShapeCount").GetInt32());
            Assert.Equal(0, proofSummary.GetProperty("generatedMasterBackedShapeCount").GetInt32());
            Assert.Equal(1, proofSummary.GetProperty("semanticOnlyShapeCount").GetInt32());
            JsonElement stencilCatalogs = proofSummary.GetProperty("stencilCatalogs");
            Assert.Equal(2, stencilCatalogs.GetArrayLength());
            Assert.Equal("Flowchart", stencilCatalogs[0].GetString());
            Assert.Equal("Security and Identity", stencilCatalogs[1].GetString());
            JsonElement shapeDataKeys = proofSummary.GetProperty("shapeDataKeys");
            Assert.Equal("Owner", shapeDataKeys[0].GetString());
            Assert.Equal("Sla", shapeDataKeys[1].GetString());
            Assert.Equal("Decision", proofSummary.GetProperty("connectorShapeDataKeys")[0].GetString());
            Assert.Equal("BackgroundSurface", proofSummary.GetProperty("semanticKinds")[0].GetString());
            JsonElement visualQualitySummary = diagrams[0].GetProperty("visualQualitySummary");
            Assert.True(visualQualitySummary.GetProperty("hasProof").GetBoolean());
            Assert.True(visualQualitySummary.GetProperty("isClean").GetBoolean());
            Assert.Equal(0, visualQualitySummary.GetProperty("issueCount").GetInt32());
            Assert.Equal(0, visualQualitySummary.GetProperty("errorCount").GetInt32());
            Assert.Equal(0, visualQualitySummary.GetProperty("warningCount").GetInt32());
            Assert.Equal(0, visualQualitySummary.GetProperty("informationCount").GetInt32());
            Assert.Equal(0, visualQualitySummary.GetProperty("issueKinds").GetArrayLength());
            JsonElement evidence = diagrams[0].GetProperty("evidence");
            Assert.False(evidence.GetProperty("hasNativeSvgPreview").GetBoolean());
            Assert.True(evidence.GetProperty("hasNativePngPreview").GetBoolean());
            Assert.False(evidence.GetProperty("hasDesktopSvgPreview").GetBoolean());
            Assert.True(evidence.GetProperty("hasDesktopPngPreview").GetBoolean());
            Assert.True(evidence.GetProperty("hasInspectionProof").GetBoolean());
            Assert.True(evidence.GetProperty("hasStencilProfileProof").GetBoolean());
            Assert.True(evidence.GetProperty("hasVisualQualityProof").GetBoolean());
            Assert.False(evidence.GetProperty("hasCompleteNativePreview").GetBoolean());
            Assert.False(evidence.GetProperty("hasCompleteDesktopPreview").GetBoolean());
            Assert.True(evidence.GetProperty("hasCompleteStructuralProof").GetBoolean());
            Assert.True(evidence.GetProperty("hasCompleteReviewProof").GetBoolean());
            Assert.False(evidence.GetProperty("hasCompletePreviewEvidence").GetBoolean());
            Assert.Equal("sample.vsdx", diagrams[0].GetProperty("package").GetProperty("relativePath").GetString());
            Assert.Equal("039058c6f2c0cb492c533b0a4d14ef77cc0f78abccced5287d84a1a2011cfb81", diagrams[0].GetProperty("package").GetProperty("sha256").GetString());
            Assert.Equal(2, diagrams[0].GetProperty("previewCount").GetInt32());
            JsonElement diagramPreviews = diagrams[0].GetProperty("previews");
            Assert.Equal(2, diagramPreviews.GetArrayLength());
            Assert.Equal("Native Preview/sample-page1.native.png", diagramPreviews[0].GetProperty("relativePath").GetString());
            Assert.Equal("c6d44cf418f610e3fe9e1d9294ff43def81c6cdcad6cbb1820cff48d3aa4355d", diagramPreviews[0].GetProperty("sha256").GetString());
            Assert.Equal("Preview/sample-page1.png", diagramPreviews[1].GetProperty("relativePath").GetString());
            Assert.Equal("bd420fe3805369a34abadcc6b32fd58d81c8ef3befe97c9a67532efef7d7b1c8", diagramPreviews[1].GetProperty("sha256").GetString());
            Assert.Equal(3, diagrams[0].GetProperty("proofCount").GetInt32());
            JsonElement diagramProofs = diagrams[0].GetProperty("proofs");
            Assert.Equal(3, diagramProofs.GetArrayLength());
            Assert.Equal("Structural Proof/sample.inspection.txt", diagramProofs[0].GetProperty("relativePath").GetString());
            Assert.Equal("d41470f8fe2547d6c4d4802d484fe7ff5a5bbecd5612eeeb1360df0c4781d95e", diagramProofs[0].GetProperty("sha256").GetString());
            Assert.Equal("Structural Proof/sample.stencil-profile.txt", diagramProofs[1].GetProperty("relativePath").GetString());
            Assert.Equal("eae46dafce8a0a423160efc71e4161bc8321fc915c5e6490cb713d51ac6993d1", diagramProofs[1].GetProperty("sha256").GetString());
            Assert.Equal("Structural Proof/sample.visual-quality.txt", diagramProofs[2].GetProperty("relativePath").GetString());
            Assert.Equal("4c0f30cee2cc7ae626fa3ea8243baffbe432b0d66af60703f849e602bd680a1f", diagramProofs[2].GetProperty("sha256").GetString());
            JsonElement artifacts = root.GetProperty("artifacts");
            Assert.Equal(6, artifacts.GetArrayLength());
            Assert.Equal("Package", artifacts[0].GetProperty("kind").GetString());
            Assert.Equal("sample.vsdx", artifacts[0].GetProperty("relativePath").GetString());
            Assert.Equal(3, artifacts[0].GetProperty("sizeBytes").GetInt64());
            Assert.Equal("039058c6f2c0cb492c533b0a4d14ef77cc0f78abccced5287d84a1a2011cfb81", artifacts[0].GetProperty("sha256").GetString());
            Assert.Equal("NativePreview", artifacts[1].GetProperty("kind").GetString());
            Assert.Equal("png", artifacts[1].GetProperty("format").GetString());
            Assert.Equal(4, artifacts[1].GetProperty("sizeBytes").GetInt64());
            Assert.Equal("c6d44cf418f610e3fe9e1d9294ff43def81c6cdcad6cbb1820cff48d3aa4355d", artifacts[1].GetProperty("sha256").GetString());
            Assert.Equal("DesktopPreview", artifacts[2].GetProperty("kind").GetString());
            Assert.Equal("Preview/sample-page1.png", artifacts[2].GetProperty("relativePath").GetString());
            Assert.Equal(5, artifacts[2].GetProperty("sizeBytes").GetInt64());
            Assert.Equal("bd420fe3805369a34abadcc6b32fd58d81c8ef3befe97c9a67532efef7d7b1c8", artifacts[2].GetProperty("sha256").GetString());
            Assert.Equal("Inspection", artifacts[3].GetProperty("kind").GetString());
            Assert.Equal("Structural Proof/sample.inspection.txt", artifacts[3].GetProperty("relativePath").GetString());
            Assert.Equal(3, artifacts[3].GetProperty("sizeBytes").GetInt64());
            Assert.Equal("d41470f8fe2547d6c4d4802d484fe7ff5a5bbecd5612eeeb1360df0c4781d95e", artifacts[3].GetProperty("sha256").GetString());
            Assert.Equal("StencilProfile", artifacts[4].GetProperty("kind").GetString());
            Assert.Equal("Structural Proof/sample.stencil-profile.txt", artifacts[4].GetProperty("relativePath").GetString());
            Assert.Equal(543, artifacts[4].GetProperty("sizeBytes").GetInt64());
            Assert.Equal("eae46dafce8a0a423160efc71e4161bc8321fc915c5e6490cb713d51ac6993d1", artifacts[4].GetProperty("sha256").GetString());
            Assert.Equal("VisualQuality", artifacts[5].GetProperty("kind").GetString());
            Assert.Equal("Structural Proof/sample.visual-quality.txt", artifacts[5].GetProperty("relativePath").GetString());
            Assert.Equal(133, artifacts[5].GetProperty("sizeBytes").GetInt64());
            Assert.Equal("4c0f30cee2cc7ae626fa3ea8243baffbe432b0d66af60703f849e602bd680a1f", artifacts[5].GetProperty("sha256").GetString());
        }

        [Fact]
        public void ShowcaseSummaryValidationDetectsModifiedArtifactBytes() {
            string folderPath = Path.Combine(Path.GetTempPath(), "OfficeIMO-Visio-Showcase-Validation-" + Guid.NewGuid());
            string nativePreviewPath = Path.Combine(folderPath, "Native Preview");
            Directory.CreateDirectory(nativePreviewPath);
            string packagePath = Path.Combine(folderPath, "sample.vsdx");
            string previewPath = Path.Combine(nativePreviewPath, "sample-page1.native.png");
            File.WriteAllBytes(packagePath, new byte[] { 1, 2, 3 });
            File.WriteAllBytes(previewPath, new byte[] { 4, 5, 6, 7 });

            VisioShowcaseSummary summary = VisioShowcaseSummary.Create(folderPath, new[] { packagePath }, new[] { previewPath });
            summary.EnsureArtifactsValid(requirePreviewsPerDiagram: true);

            File.WriteAllBytes(previewPath, new byte[] { 7, 6, 5, 4 });

            VisioShowcaseValidationReport report = summary.ValidateArtifacts(requirePreviewsPerDiagram: true);
            Assert.False(report.IsClean);
            Assert.Contains(report.Issues, issue =>
                issue.Kind == "ArtifactHashMismatch" &&
                issue.RelativePath == "Native Preview/sample-page1.native.png");

            VisioShowcaseValidationException exception = Assert.Throws<VisioShowcaseValidationException>(() =>
                summary.EnsureArtifactsValid(requirePreviewsPerDiagram: true));
            Assert.Contains(exception.Issues, issue => issue.Kind == "ArtifactHashMismatch");
        }

    }
}
