using System;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using OfficeIMO.Visio;
using Xunit;

namespace OfficeIMO.Tests {
    public class VisioRegressionTests {
        [Fact]
        public void PageNameURoundTrips() {
            string filePath = Path.Combine(Path.GetTempPath(), Guid.NewGuid() + ".vsdx");

            VisioDocument document = VisioDocument.Create(filePath);
            VisioPage page = document.AddPage("Page-1");
            page.NameU = "FlowPage";
            page.Shapes.Add(new VisioShape("1", 1, 1, 2, 1, "Rectangle"));

            document.Save();

            VisioDocument loaded = VisioDocument.Load(filePath);
            Assert.Equal("FlowPage", loaded.Pages[0].NameU);
        }

        [Fact]
        public void SnapSettingRoundTripsThroughPageSheet() {
            string filePath = Path.Combine(Path.GetTempPath(), Guid.NewGuid() + ".vsdx");

            VisioDocument document = VisioDocument.Create(filePath);
            VisioPage page = document.AddPage("Page-1");
            page.Grid(true, false);
            page.Shapes.Add(new VisioShape("1", 1, 1, 2, 1, "Rectangle"));

            document.Save();

            XNamespace ns = "http://schemas.microsoft.com/office/visio/2012/main";
            using (ZipArchive archive = ZipFile.OpenRead(filePath)) {
                using Stream stream = archive.GetEntry("visio/pages/pages.xml")!.Open();
                XDocument pages = XDocument.Load(stream);
                XElement inhibitSnap = pages.Root!
                    .Element(ns + "Page")!
                    .Element(ns + "PageSheet")!
                    .Elements(ns + "Cell")
                    .First(cell => (string?)cell.Attribute("N") == "InhibitSnap");
                Assert.Equal("1", (string?)inhibitSnap.Attribute("V"));
            }

            VisioDocument loaded = VisioDocument.Load(filePath);
            Assert.False(loaded.Pages[0].Snap);
        }

        [Fact]
        public void DirectMasterOverloadUsesPageDefaultUnit() {
            VisioDocument document = VisioDocument.Create(Path.Combine(Path.GetTempPath(), Guid.NewGuid() + ".vsdx"));
            VisioPage page = document.AddPage("Metric", 21, 29.7, VisioMeasurementUnit.Centimeters);
            VisioMaster master = new("1", "MetricRect", new VisioShape("1", 0, 0, 1, 1, string.Empty) { NameU = "MetricRect" });

            VisioShape shape = page.AddShape("shape-1", master, 2, 3, 4, 5, "Metric");

            Assert.Equal(2d.ToInches(VisioMeasurementUnit.Centimeters), shape.PinX, 6);
            Assert.Equal(3d.ToInches(VisioMeasurementUnit.Centimeters), shape.PinY, 6);
            Assert.Equal(4d.ToInches(VisioMeasurementUnit.Centimeters), shape.Width, 6);
            Assert.Equal(5d.ToInches(VisioMeasurementUnit.Centimeters), shape.Height, 6);
            Assert.Equal("MetricRect", shape.NameU);
        }

        [Fact]
        public void AutoGeneratedIdsSkipExistingShapeAndConnectorIds() {
            VisioPage page = new("Page-1");
            VisioShape start = new("1", 1, 1, 1, 1, "Start");
            VisioShape end = new("3", 4, 1, 1, 1, "End");
            page.Shapes.Add(start);
            page.Shapes.Add(end);
            page.Connectors.Add(new VisioConnector("4", start, end));

            VisioShape autoShape = page.AddRectangle(2, 2, 1, 1, "Auto");
            VisioConnector autoConnector = page.AddConnector(start, autoShape);

            Assert.Equal("2", autoShape.Id);
            Assert.Equal("5", autoConnector.Id);
        }

        [Fact]
        public void LoadPreservesExplicitZeroGeometryOnMasterBackedShapes() {
            string filePath = Path.Combine(Path.GetTempPath(), Guid.NewGuid() + ".vsdx");

            VisioDocument document = VisioDocument.Create(filePath);
            document.UseMastersByDefault = true;
            VisioPage page = document.AddPage("Page-1");
            page.Shapes.Add(new VisioShape("1") {
                NameU = "Rectangle",
                PinX = 2,
                PinY = 2
            });

            document.Save();

            RewritePage(filePath, pageDoc => {
                XNamespace ns = "http://schemas.microsoft.com/office/visio/2012/main";
                XElement shape = pageDoc.Root!.Element(ns + "Shapes")!.Element(ns + "Shape")!;
                UpsertCell(shape, ns, "Width", "0");
                UpsertCell(shape, ns, "Height", "0");
                UpsertCell(shape, ns, "LocPinX", "0");
                UpsertCell(shape, ns, "LocPinY", "0");
            });

            VisioDocument loaded = VisioDocument.Load(filePath);
            VisioShape shape = Assert.Single(loaded.Pages[0].Shapes);

            Assert.Equal(0, shape.Width);
            Assert.Equal(0, shape.Height);
            Assert.Equal(0, shape.LocPinX);
            Assert.Equal(0, shape.LocPinY);
        }

        [Fact]
        public void LoadRecognizesOneDConnectorsEvenWithCustomNames() {
            string filePath = Path.Combine(Path.GetTempPath(), Guid.NewGuid() + ".vsdx");

            VisioDocument document = VisioDocument.Create(filePath);
            VisioPage page = document.AddPage("Page-1");
            VisioShape start = new("1", 1, 1, 1, 1, "Start");
            VisioShape end = new("2", 4, 1, 1, 1, "End");
            page.Shapes.Add(start);
            page.Shapes.Add(end);
            page.Connectors.Add(new VisioConnector("3", start, end) { Kind = ConnectorKind.Straight });

            document.Save();

            RewritePage(filePath, pageDoc => {
                XNamespace ns = "http://schemas.microsoft.com/office/visio/2012/main";
                XElement connectorShape = pageDoc.Root!
                    .Element(ns + "Shapes")!
                    .Elements(ns + "Shape")
                    .Last();
                connectorShape.SetAttributeValue("Name", "Edge-42");
                connectorShape.SetAttributeValue("NameU", "Edge-42");
            });

            VisioDocument loaded = VisioDocument.Load(filePath);

            Assert.Equal(2, loaded.Pages[0].Shapes.Count);
            Assert.Single(loaded.Pages[0].Connectors);
        }

        [Fact]
        public void LoadParsesGuardWrappedNumericShapeCells() {
            string filePath = Path.Combine(Path.GetTempPath(), Guid.NewGuid() + ".vsdx");

            VisioDocument document = VisioDocument.Create(filePath);
            VisioPage page = document.AddPage("Page-1");
            page.Shapes.Add(new VisioShape("1", 1, 1, 2, 1, "Rectangle"));

            document.Save();

            RewritePage(filePath, pageDoc => {
                XNamespace ns = "http://schemas.microsoft.com/office/visio/2012/main";
                XElement shape = pageDoc.Root!.Element(ns + "Shapes")!.Element(ns + "Shape")!;
                UpsertCell(shape, ns, "Width", "GUARD(2.5)");
                UpsertCell(shape, ns, "Height", "GUARD(1.5)");
                UpsertCell(shape, ns, "PinX", "GUARD(3.25)");
                UpsertCell(shape, ns, "PinY", "GUARD(4.75)");
            });

            VisioDocument loaded = VisioDocument.Load(filePath);
            VisioShape shape = Assert.Single(loaded.Pages[0].Shapes);

            Assert.Equal(2.5, shape.Width, 6);
            Assert.Equal(1.5, shape.Height, 6);
            Assert.Equal(3.25, shape.PinX, 6);
            Assert.Equal(4.75, shape.PinY, 6);
        }

        [Fact]
        public void LoadParsesGuardWrappedConnectorArrowCells() {
            string filePath = Path.Combine(Path.GetTempPath(), Guid.NewGuid() + ".vsdx");

            VisioDocument document = VisioDocument.Create(filePath);
            VisioPage page = document.AddPage("Page-1");
            VisioShape start = new("1", 1, 1, 1, 1, "Start");
            VisioShape end = new("2", 4, 1, 1, 1, "End");
            page.Shapes.Add(start);
            page.Shapes.Add(end);
            page.Connectors.Add(new VisioConnector("3", start, end) {
                Kind = ConnectorKind.Straight,
                BeginArrow = EndArrow.Arrow,
                EndArrow = EndArrow.Triangle
            });

            document.Save();

            RewritePage(filePath, pageDoc => {
                XNamespace ns = "http://schemas.microsoft.com/office/visio/2012/main";
                XElement connectorShape = pageDoc.Root!
                    .Element(ns + "Shapes")!
                    .Elements(ns + "Shape")
                    .Last();
                connectorShape.SetAttributeValue("Name", "Edge-43");
                connectorShape.SetAttributeValue("NameU", "Edge-43");
                UpsertCell(connectorShape, ns, "OneD", "GUARD(1)");
                UpsertCell(connectorShape, ns, "BeginArrow", "GUARD(1)");
                UpsertCell(connectorShape, ns, "EndArrow", "GUARD(13)");
            });

            VisioDocument loaded = VisioDocument.Load(filePath);
            VisioConnector connector = Assert.Single(loaded.Pages[0].Connectors);

            Assert.Equal(EndArrow.Arrow, connector.BeginArrow);
            Assert.Equal(EndArrow.Triangle, connector.EndArrow);
        }

        [Fact]
        public void LoadParsesGuardWrappedStylePatternCells() {
            string filePath = Path.Combine(Path.GetTempPath(), Guid.NewGuid() + ".vsdx");

            VisioDocument document = VisioDocument.Create(filePath);
            VisioPage page = document.AddPage("Page-1");
            VisioShape start = new("1", 1, 1, 2, 1, "Start");
            VisioShape end = new("2", 4, 1, 2, 1, "End");
            page.Shapes.Add(start);
            page.Shapes.Add(end);
            page.Connectors.Add(new VisioConnector("3", start, end) { Kind = ConnectorKind.Straight });

            document.Save();

            RewritePage(filePath, pageDoc => {
                XNamespace ns = "http://schemas.microsoft.com/office/visio/2012/main";
                XElement shape = pageDoc.Root!.Element(ns + "Shapes")!.Elements(ns + "Shape").First();
                UpsertCell(shape, ns, "LinePattern", "GUARD(4)");
                UpsertCell(shape, ns, "FillPattern", "GUARD(6)");

                XElement connectorShape = pageDoc.Root!
                    .Element(ns + "Shapes")!
                    .Elements(ns + "Shape")
                    .Last();
                UpsertCell(connectorShape, ns, "LinePattern", "GUARD(2)");
            });

            VisioDocument loaded = VisioDocument.Load(filePath);
            VisioShape shape = loaded.Pages[0].Shapes[0];
            VisioConnector connector = Assert.Single(loaded.Pages[0].Connectors);

            Assert.Equal(4, shape.LinePattern);
            Assert.Equal(6, shape.FillPattern);
            Assert.Equal(2, connector.LinePattern);
        }

        [Fact]
        public void LoadParsesGuardWrappedColorCells() {
            string filePath = Path.Combine(Path.GetTempPath(), Guid.NewGuid() + ".vsdx");

            VisioDocument document = VisioDocument.Create(filePath);
            VisioPage page = document.AddPage("Page-1");
            VisioShape start = new("1", 1, 1, 2, 1, "Start");
            VisioShape end = new("2", 4, 1, 2, 1, "End");
            page.Shapes.Add(start);
            page.Shapes.Add(end);
            page.Connectors.Add(new VisioConnector("3", start, end) { Kind = ConnectorKind.Straight });

            document.Save();

            RewritePage(filePath, pageDoc => {
                XNamespace ns = "http://schemas.microsoft.com/office/visio/2012/main";
                XElement shape = pageDoc.Root!.Element(ns + "Shapes")!.Elements(ns + "Shape").First();
                UpsertCell(shape, ns, "LineColor", "GUARD(#112233)");
                UpsertCell(shape, ns, "FillForegnd", "GUARD(RGB(10,20,30))");

                XElement connectorShape = pageDoc.Root!
                    .Element(ns + "Shapes")!
                    .Elements(ns + "Shape")
                    .Last();
                UpsertCell(connectorShape, ns, "LineColor", "GUARD(#445566)");
            });

            VisioDocument loaded = VisioDocument.Load(filePath);
            VisioShape shape = loaded.Pages[0].Shapes[0];
            VisioConnector connector = Assert.Single(loaded.Pages[0].Connectors);

            Assert.Equal(SixLabors.ImageSharp.Color.FromRgb(0x11, 0x22, 0x33), shape.LineColor);
            Assert.Equal(SixLabors.ImageSharp.Color.FromRgb(10, 20, 30), shape.FillColor);
            Assert.Equal(SixLabors.ImageSharp.Color.FromRgb(0x44, 0x55, 0x66), connector.LineColor);
        }

        [Fact]
        public void LoadParsesNumericVisioColorCells() {
            string filePath = Path.Combine(Path.GetTempPath(), Guid.NewGuid() + ".vsdx");

            VisioDocument document = VisioDocument.Create(filePath);
            VisioPage page = document.AddPage("Page-1");
            VisioShape start = new("1", 1, 1, 2, 1, "Start");
            VisioShape end = new("2", 4, 1, 2, 1, "End");
            page.Shapes.Add(start);
            page.Shapes.Add(end);
            page.Connectors.Add(new VisioConnector("3", start, end) { Kind = ConnectorKind.Straight });

            document.Save();

            RewritePage(filePath, pageDoc => {
                XNamespace ns = "http://schemas.microsoft.com/office/visio/2012/main";
                XElement shape = pageDoc.Root!.Element(ns + "Shapes")!.Elements(ns + "Shape").First();
                UpsertCell(shape, ns, "LineColor", "0");
                UpsertCell(shape, ns, "FillForegnd", "1");

                XElement connectorShape = pageDoc.Root!
                    .Element(ns + "Shapes")!
                    .Elements(ns + "Shape")
                    .Last();
                UpsertCell(connectorShape, ns, "LineColor", "1");
            });

            VisioDocument loaded = VisioDocument.Load(filePath);
            VisioShape shape = loaded.Pages[0].Shapes[0];
            VisioConnector connector = Assert.Single(loaded.Pages[0].Connectors);

            Assert.Equal(SixLabors.ImageSharp.Color.Black, shape.LineColor);
            Assert.Equal(SixLabors.ImageSharp.Color.White, shape.FillColor);
            Assert.Equal(SixLabors.ImageSharp.Color.White, connector.LineColor);
        }
        private static void RewritePage(string vsdxPath, Action<XDocument> transform) {
            using FileStream stream = File.Open(vsdxPath, FileMode.Open, FileAccess.ReadWrite);
            using ZipArchive archive = new(stream, ZipArchiveMode.Update);
            ZipArchiveEntry pageEntry = archive.GetEntry("visio/pages/page1.xml")!;
            XDocument pageDoc;
            using (Stream pageStream = pageEntry.Open()) {
                pageDoc = XDocument.Load(pageStream);
            }

            transform(pageDoc);
            pageEntry.Delete();
            ZipArchiveEntry replacement = archive.CreateEntry("visio/pages/page1.xml");
            using Stream replacementStream = replacement.Open();
            using StreamWriter writer = new(replacementStream, new UTF8Encoding(false));
            writer.Write(pageDoc.Declaration + Environment.NewLine + pageDoc.ToString(SaveOptions.DisableFormatting));
        }

        private static void UpsertCell(XElement shape, XNamespace ns, string name, string value) {
            XElement? existing = shape.Elements(ns + "Cell").FirstOrDefault(cell => (string?)cell.Attribute("N") == name);
            if (existing != null) {
                existing.SetAttributeValue("V", value);
                return;
            }

            shape.AddFirst(new XElement(ns + "Cell",
                new XAttribute("N", name),
                new XAttribute("V", value)));
        }
    }
}
