// <auto-generated/>
// Generated by Build/Generate-ExcelOpenXmlValueTypes.ps1. Do not edit by hand.
using System.Globalization;

namespace OfficeIMO.Excel;

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.Charts.BuiltInUnitValues.</summary>
public enum ExcelChartDisplayUnit {
    /// <summary>Represents the Open XML value <c>hundreds</c>.</summary>
    Hundreds,
    /// <summary>Represents the Open XML value <c>thousands</c>.</summary>
    Thousands,
    /// <summary>Represents the Open XML value <c>tenThousands</c>.</summary>
    TenThousands,
    /// <summary>Represents the Open XML value <c>hundredThousands</c>.</summary>
    HundredThousands,
    /// <summary>Represents the Open XML value <c>millions</c>.</summary>
    Millions,
    /// <summary>Represents the Open XML value <c>tenMillions</c>.</summary>
    TenMillions,
    /// <summary>Represents the Open XML value <c>hundredMillions</c>.</summary>
    HundredMillions,
    /// <summary>Represents the Open XML value <c>billions</c>.</summary>
    Billions,
    /// <summary>Represents the Open XML value <c>trillions</c>.</summary>
    Trillions,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.Charts.CrossBetweenValues.</summary>
public enum ExcelChartAxisCrossBetween {
    /// <summary>Represents the Open XML value <c>between</c>.</summary>
    Between,
    /// <summary>Represents the Open XML value <c>midCat</c>.</summary>
    MidpointCategory,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.Charts.CrossesValues.</summary>
public enum ExcelChartAxisCrossing {
    /// <summary>Represents the Open XML value <c>autoZero</c>.</summary>
    AutoZero,
    /// <summary>Represents the Open XML value <c>max</c>.</summary>
    Maximum,
    /// <summary>Represents the Open XML value <c>min</c>.</summary>
    Minimum,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.Charts.DataLabelPositionValues.</summary>
public enum ExcelChartDataLabelPosition {
    /// <summary>Represents the Open XML value <c>bestFit</c>.</summary>
    BestFit,
    /// <summary>Represents the Open XML value <c>b</c>.</summary>
    Bottom,
    /// <summary>Represents the Open XML value <c>ctr</c>.</summary>
    Center,
    /// <summary>Represents the Open XML value <c>inBase</c>.</summary>
    InsideBase,
    /// <summary>Represents the Open XML value <c>inEnd</c>.</summary>
    InsideEnd,
    /// <summary>Represents the Open XML value <c>l</c>.</summary>
    Left,
    /// <summary>Represents the Open XML value <c>outEnd</c>.</summary>
    OutsideEnd,
    /// <summary>Represents the Open XML value <c>r</c>.</summary>
    Right,
    /// <summary>Represents the Open XML value <c>t</c>.</summary>
    Top,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.Charts.LegendPositionValues.</summary>
public enum ExcelChartLegendPosition {
    /// <summary>Represents the Open XML value <c>b</c>.</summary>
    Bottom,
    /// <summary>Represents the Open XML value <c>tr</c>.</summary>
    TopRight,
    /// <summary>Represents the Open XML value <c>l</c>.</summary>
    Left,
    /// <summary>Represents the Open XML value <c>r</c>.</summary>
    Right,
    /// <summary>Represents the Open XML value <c>t</c>.</summary>
    Top,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.Charts.MarkerStyleValues.</summary>
public enum ExcelChartMarkerStyle {
    /// <summary>Represents the Open XML value <c>auto</c>.</summary>
    Auto,
    /// <summary>Represents the Open XML value <c>circle</c>.</summary>
    Circle,
    /// <summary>Represents the Open XML value <c>dash</c>.</summary>
    Dash,
    /// <summary>Represents the Open XML value <c>diamond</c>.</summary>
    Diamond,
    /// <summary>Represents the Open XML value <c>dot</c>.</summary>
    Dot,
    /// <summary>Represents the Open XML value <c>none</c>.</summary>
    None,
    /// <summary>Represents the Open XML value <c>picture</c>.</summary>
    Picture,
    /// <summary>Represents the Open XML value <c>plus</c>.</summary>
    Plus,
    /// <summary>Represents the Open XML value <c>square</c>.</summary>
    Square,
    /// <summary>Represents the Open XML value <c>star</c>.</summary>
    Star,
    /// <summary>Represents the Open XML value <c>triangle</c>.</summary>
    Triangle,
    /// <summary>Represents the Open XML value <c>x</c>.</summary>
    X,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.Charts.TickLabelPositionValues.</summary>
public enum ExcelChartTickLabelPosition {
    /// <summary>Represents the Open XML value <c>high</c>.</summary>
    High,
    /// <summary>Represents the Open XML value <c>low</c>.</summary>
    Low,
    /// <summary>Represents the Open XML value <c>nextTo</c>.</summary>
    NextTo,
    /// <summary>Represents the Open XML value <c>none</c>.</summary>
    None,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Drawing.Charts.TrendlineValues.</summary>
public enum ExcelChartTrendlineType {
    /// <summary>Represents the Open XML value <c>exp</c>.</summary>
    Exponential,
    /// <summary>Represents the Open XML value <c>linear</c>.</summary>
    Linear,
    /// <summary>Represents the Open XML value <c>log</c>.</summary>
    Logarithmic,
    /// <summary>Represents the Open XML value <c>movingAvg</c>.</summary>
    MovingAverage,
    /// <summary>Represents the Open XML value <c>poly</c>.</summary>
    Polynomial,
    /// <summary>Represents the Open XML value <c>power</c>.</summary>
    Power,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Office2010.Excel.SparklineTypeValues.</summary>
public enum ExcelSparklineType {
    /// <summary>Represents the Open XML value <c>line</c>.</summary>
    Line,
    /// <summary>Represents the Open XML value <c>column</c>.</summary>
    Column,
    /// <summary>Represents the Open XML value <c>stacked</c>.</summary>
    Stacked,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Spreadsheet.BorderStyleValues.</summary>
public enum ExcelBorderStyle {
    /// <summary>Represents the Open XML value <c>none</c>.</summary>
    None,
    /// <summary>Represents the Open XML value <c>thin</c>.</summary>
    Thin,
    /// <summary>Represents the Open XML value <c>medium</c>.</summary>
    Medium,
    /// <summary>Represents the Open XML value <c>dashed</c>.</summary>
    Dashed,
    /// <summary>Represents the Open XML value <c>dotted</c>.</summary>
    Dotted,
    /// <summary>Represents the Open XML value <c>thick</c>.</summary>
    Thick,
    /// <summary>Represents the Open XML value <c>double</c>.</summary>
    Double,
    /// <summary>Represents the Open XML value <c>hair</c>.</summary>
    Hair,
    /// <summary>Represents the Open XML value <c>mediumDashed</c>.</summary>
    MediumDashed,
    /// <summary>Represents the Open XML value <c>dashDot</c>.</summary>
    DashDot,
    /// <summary>Represents the Open XML value <c>mediumDashDot</c>.</summary>
    MediumDashDot,
    /// <summary>Represents the Open XML value <c>dashDotDot</c>.</summary>
    DashDotDot,
    /// <summary>Represents the Open XML value <c>mediumDashDotDot</c>.</summary>
    MediumDashDotDot,
    /// <summary>Represents the Open XML value <c>slantDashDot</c>.</summary>
    SlantDashDot,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Spreadsheet.CellValues.</summary>
public enum ExcelCellValueType {
    /// <summary>Represents the Open XML value <c>b</c>.</summary>
    Boolean,
    /// <summary>Represents the Open XML value <c>n</c>.</summary>
    Number,
    /// <summary>Represents the Open XML value <c>e</c>.</summary>
    Error,
    /// <summary>Represents the Open XML value <c>s</c>.</summary>
    SharedString,
    /// <summary>Represents the Open XML value <c>str</c>.</summary>
    String,
    /// <summary>Represents the Open XML value <c>inlineStr</c>.</summary>
    InlineString,
    /// <summary>Represents the Open XML value <c>d</c>.</summary>
    Date,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Spreadsheet.ConditionalFormatValues.</summary>
public enum ExcelConditionalFormatType {
    /// <summary>Represents the Open XML value <c>expression</c>.</summary>
    Expression,
    /// <summary>Represents the Open XML value <c>cellIs</c>.</summary>
    CellIs,
    /// <summary>Represents the Open XML value <c>colorScale</c>.</summary>
    ColorScale,
    /// <summary>Represents the Open XML value <c>dataBar</c>.</summary>
    DataBar,
    /// <summary>Represents the Open XML value <c>iconSet</c>.</summary>
    IconSet,
    /// <summary>Represents the Open XML value <c>top10</c>.</summary>
    Top10,
    /// <summary>Represents the Open XML value <c>uniqueValues</c>.</summary>
    UniqueValues,
    /// <summary>Represents the Open XML value <c>duplicateValues</c>.</summary>
    DuplicateValues,
    /// <summary>Represents the Open XML value <c>containsText</c>.</summary>
    ContainsText,
    /// <summary>Represents the Open XML value <c>notContainsText</c>.</summary>
    NotContainsText,
    /// <summary>Represents the Open XML value <c>beginsWith</c>.</summary>
    BeginsWith,
    /// <summary>Represents the Open XML value <c>endsWith</c>.</summary>
    EndsWith,
    /// <summary>Represents the Open XML value <c>containsBlanks</c>.</summary>
    ContainsBlanks,
    /// <summary>Represents the Open XML value <c>notContainsBlanks</c>.</summary>
    NotContainsBlanks,
    /// <summary>Represents the Open XML value <c>containsErrors</c>.</summary>
    ContainsErrors,
    /// <summary>Represents the Open XML value <c>notContainsErrors</c>.</summary>
    NotContainsErrors,
    /// <summary>Represents the Open XML value <c>timePeriod</c>.</summary>
    TimePeriod,
    /// <summary>Represents the Open XML value <c>aboveAverage</c>.</summary>
    AboveAverage,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Spreadsheet.ConditionalFormattingOperatorValues.</summary>
public enum ExcelConditionalFormattingOperator {
    /// <summary>Represents the Open XML value <c>lessThan</c>.</summary>
    LessThan,
    /// <summary>Represents the Open XML value <c>lessThanOrEqual</c>.</summary>
    LessThanOrEqual,
    /// <summary>Represents the Open XML value <c>equal</c>.</summary>
    Equal,
    /// <summary>Represents the Open XML value <c>notEqual</c>.</summary>
    NotEqual,
    /// <summary>Represents the Open XML value <c>greaterThanOrEqual</c>.</summary>
    GreaterThanOrEqual,
    /// <summary>Represents the Open XML value <c>greaterThan</c>.</summary>
    GreaterThan,
    /// <summary>Represents the Open XML value <c>between</c>.</summary>
    Between,
    /// <summary>Represents the Open XML value <c>notBetween</c>.</summary>
    NotBetween,
    /// <summary>Represents the Open XML value <c>containsText</c>.</summary>
    ContainsText,
    /// <summary>Represents the Open XML value <c>notContains</c>.</summary>
    NotContains,
    /// <summary>Represents the Open XML value <c>beginsWith</c>.</summary>
    BeginsWith,
    /// <summary>Represents the Open XML value <c>endsWith</c>.</summary>
    EndsWith,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Spreadsheet.DataConsolidateFunctionValues.</summary>
public enum ExcelPivotDataFunction {
    /// <summary>Represents the Open XML value <c>average</c>.</summary>
    Average,
    /// <summary>Represents the Open XML value <c>count</c>.</summary>
    Count,
    /// <summary>Represents the Open XML value <c>countNums</c>.</summary>
    CountNumbers,
    /// <summary>Represents the Open XML value <c>max</c>.</summary>
    Maximum,
    /// <summary>Represents the Open XML value <c>min</c>.</summary>
    Minimum,
    /// <summary>Represents the Open XML value <c>product</c>.</summary>
    Product,
    /// <summary>Represents the Open XML value <c>stdDev</c>.</summary>
    StandardDeviation,
    /// <summary>Represents the Open XML value <c>stdDevp</c>.</summary>
    StandardDeviationP,
    /// <summary>Represents the Open XML value <c>sum</c>.</summary>
    Sum,
    /// <summary>Represents the Open XML value <c>var</c>.</summary>
    Variance,
    /// <summary>Represents the Open XML value <c>varp</c>.</summary>
    VarianceP,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Spreadsheet.DataValidationErrorStyleValues.</summary>
public enum ExcelDataValidationErrorStyle {
    /// <summary>Represents the Open XML value <c>stop</c>.</summary>
    Stop,
    /// <summary>Represents the Open XML value <c>warning</c>.</summary>
    Warning,
    /// <summary>Represents the Open XML value <c>information</c>.</summary>
    Information,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Spreadsheet.DataValidationOperatorValues.</summary>
public enum ExcelDataValidationOperator {
    /// <summary>Represents the Open XML value <c>between</c>.</summary>
    Between,
    /// <summary>Represents the Open XML value <c>notBetween</c>.</summary>
    NotBetween,
    /// <summary>Represents the Open XML value <c>equal</c>.</summary>
    Equal,
    /// <summary>Represents the Open XML value <c>notEqual</c>.</summary>
    NotEqual,
    /// <summary>Represents the Open XML value <c>lessThan</c>.</summary>
    LessThan,
    /// <summary>Represents the Open XML value <c>lessThanOrEqual</c>.</summary>
    LessThanOrEqual,
    /// <summary>Represents the Open XML value <c>greaterThan</c>.</summary>
    GreaterThan,
    /// <summary>Represents the Open XML value <c>greaterThanOrEqual</c>.</summary>
    GreaterThanOrEqual,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Spreadsheet.FieldSortValues.</summary>
public enum ExcelPivotFieldSort {
    /// <summary>Represents the Open XML value <c>manual</c>.</summary>
    Manual,
    /// <summary>Represents the Open XML value <c>ascending</c>.</summary>
    Ascending,
    /// <summary>Represents the Open XML value <c>descending</c>.</summary>
    Descending,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Spreadsheet.GroupByValues.</summary>
public enum ExcelPivotGroupBy {
    /// <summary>Represents the Open XML value <c>range</c>.</summary>
    Range,
    /// <summary>Represents the Open XML value <c>seconds</c>.</summary>
    Seconds,
    /// <summary>Represents the Open XML value <c>minutes</c>.</summary>
    Minutes,
    /// <summary>Represents the Open XML value <c>hours</c>.</summary>
    Hours,
    /// <summary>Represents the Open XML value <c>days</c>.</summary>
    Days,
    /// <summary>Represents the Open XML value <c>months</c>.</summary>
    Months,
    /// <summary>Represents the Open XML value <c>quarters</c>.</summary>
    Quarters,
    /// <summary>Represents the Open XML value <c>years</c>.</summary>
    Years,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Spreadsheet.HorizontalAlignmentValues.</summary>
public enum ExcelHorizontalAlignment {
    /// <summary>Represents the Open XML value <c>general</c>.</summary>
    General,
    /// <summary>Represents the Open XML value <c>left</c>.</summary>
    Left,
    /// <summary>Represents the Open XML value <c>center</c>.</summary>
    Center,
    /// <summary>Represents the Open XML value <c>right</c>.</summary>
    Right,
    /// <summary>Represents the Open XML value <c>fill</c>.</summary>
    Fill,
    /// <summary>Represents the Open XML value <c>justify</c>.</summary>
    Justify,
    /// <summary>Represents the Open XML value <c>centerContinuous</c>.</summary>
    CenterContinuous,
    /// <summary>Represents the Open XML value <c>distributed</c>.</summary>
    Distributed,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Spreadsheet.IconSetValues.</summary>
public enum ExcelIconSet {
    /// <summary>Represents the Open XML value <c>3Arrows</c>.</summary>
    ThreeArrows,
    /// <summary>Represents the Open XML value <c>3ArrowsGray</c>.</summary>
    ThreeArrowsGray,
    /// <summary>Represents the Open XML value <c>3Flags</c>.</summary>
    ThreeFlags,
    /// <summary>Represents the Open XML value <c>3TrafficLights1</c>.</summary>
    ThreeTrafficLights1,
    /// <summary>Represents the Open XML value <c>3TrafficLights2</c>.</summary>
    ThreeTrafficLights2,
    /// <summary>Represents the Open XML value <c>3Signs</c>.</summary>
    ThreeSigns,
    /// <summary>Represents the Open XML value <c>3Symbols</c>.</summary>
    ThreeSymbols,
    /// <summary>Represents the Open XML value <c>3Symbols2</c>.</summary>
    ThreeSymbols2,
    /// <summary>Represents the Open XML value <c>4Arrows</c>.</summary>
    FourArrows,
    /// <summary>Represents the Open XML value <c>4ArrowsGray</c>.</summary>
    FourArrowsGray,
    /// <summary>Represents the Open XML value <c>4RedToBlack</c>.</summary>
    FourRedToBlack,
    /// <summary>Represents the Open XML value <c>4Rating</c>.</summary>
    FourRating,
    /// <summary>Represents the Open XML value <c>4TrafficLights</c>.</summary>
    FourTrafficLights,
    /// <summary>Represents the Open XML value <c>5Arrows</c>.</summary>
    FiveArrows,
    /// <summary>Represents the Open XML value <c>5ArrowsGray</c>.</summary>
    FiveArrowsGray,
    /// <summary>Represents the Open XML value <c>5Rating</c>.</summary>
    FiveRating,
    /// <summary>Represents the Open XML value <c>5Quarters</c>.</summary>
    FiveQuarters,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Spreadsheet.PivotFilterValues.</summary>
public enum ExcelPivotFilterType {
    /// <summary>Represents the Open XML value <c>unknown</c>.</summary>
    Unknown,
    /// <summary>Represents the Open XML value <c>count</c>.</summary>
    Count,
    /// <summary>Represents the Open XML value <c>percent</c>.</summary>
    Percent,
    /// <summary>Represents the Open XML value <c>sum</c>.</summary>
    Sum,
    /// <summary>Represents the Open XML value <c>captionEqual</c>.</summary>
    CaptionEqual,
    /// <summary>Represents the Open XML value <c>captionNotEqual</c>.</summary>
    CaptionNotEqual,
    /// <summary>Represents the Open XML value <c>captionBeginsWith</c>.</summary>
    CaptionBeginsWith,
    /// <summary>Represents the Open XML value <c>captionNotBeginsWith</c>.</summary>
    CaptionNotBeginsWith,
    /// <summary>Represents the Open XML value <c>captionEndsWith</c>.</summary>
    CaptionEndsWith,
    /// <summary>Represents the Open XML value <c>captionNotEndsWith</c>.</summary>
    CaptionNotEndsWith,
    /// <summary>Represents the Open XML value <c>captionContains</c>.</summary>
    CaptionContains,
    /// <summary>Represents the Open XML value <c>captionNotContains</c>.</summary>
    CaptionNotContains,
    /// <summary>Represents the Open XML value <c>captionGreaterThan</c>.</summary>
    CaptionGreaterThan,
    /// <summary>Represents the Open XML value <c>captionGreaterThanOrEqual</c>.</summary>
    CaptionGreaterThanOrEqual,
    /// <summary>Represents the Open XML value <c>captionLessThan</c>.</summary>
    CaptionLessThan,
    /// <summary>Represents the Open XML value <c>captionLessThanOrEqual</c>.</summary>
    CaptionLessThanOrEqual,
    /// <summary>Represents the Open XML value <c>captionBetween</c>.</summary>
    CaptionBetween,
    /// <summary>Represents the Open XML value <c>captionNotBetween</c>.</summary>
    CaptionNotBetween,
    /// <summary>Represents the Open XML value <c>valueEqual</c>.</summary>
    ValueEqual,
    /// <summary>Represents the Open XML value <c>valueNotEqual</c>.</summary>
    ValueNotEqual,
    /// <summary>Represents the Open XML value <c>valueGreaterThan</c>.</summary>
    ValueGreaterThan,
    /// <summary>Represents the Open XML value <c>valueGreaterThanOrEqual</c>.</summary>
    ValueGreaterThanOrEqual,
    /// <summary>Represents the Open XML value <c>valueLessThan</c>.</summary>
    ValueLessThan,
    /// <summary>Represents the Open XML value <c>valueLessThanOrEqual</c>.</summary>
    ValueLessThanOrEqual,
    /// <summary>Represents the Open XML value <c>valueBetween</c>.</summary>
    ValueBetween,
    /// <summary>Represents the Open XML value <c>valueNotBetween</c>.</summary>
    ValueNotBetween,
    /// <summary>Represents the Open XML value <c>dateEqual</c>.</summary>
    DateEqual,
    /// <summary>Represents the Open XML value <c>dateNotEqual</c>.</summary>
    DateNotEqual,
    /// <summary>Represents the Open XML value <c>dateOlderThan</c>.</summary>
    DateOlderThan,
    /// <summary>Represents the Open XML value <c>dateOlderThanOrEqual</c>.</summary>
    DateOlderThanOrEqual,
    /// <summary>Represents the Open XML value <c>dateNewerThan</c>.</summary>
    DateNewerThan,
    /// <summary>Represents the Open XML value <c>dateNewerThanOrEqual</c>.</summary>
    DateNewerThanOrEqual,
    /// <summary>Represents the Open XML value <c>dateBetween</c>.</summary>
    DateBetween,
    /// <summary>Represents the Open XML value <c>dateNotBetween</c>.</summary>
    DateNotBetween,
    /// <summary>Represents the Open XML value <c>tomorrow</c>.</summary>
    Tomorrow,
    /// <summary>Represents the Open XML value <c>today</c>.</summary>
    Today,
    /// <summary>Represents the Open XML value <c>yesterday</c>.</summary>
    Yesterday,
    /// <summary>Represents the Open XML value <c>nextWeek</c>.</summary>
    NextWeek,
    /// <summary>Represents the Open XML value <c>thisWeek</c>.</summary>
    ThisWeek,
    /// <summary>Represents the Open XML value <c>lastWeek</c>.</summary>
    LastWeek,
    /// <summary>Represents the Open XML value <c>nextMonth</c>.</summary>
    NextMonth,
    /// <summary>Represents the Open XML value <c>thisMonth</c>.</summary>
    ThisMonth,
    /// <summary>Represents the Open XML value <c>lastMonth</c>.</summary>
    LastMonth,
    /// <summary>Represents the Open XML value <c>nextQuarter</c>.</summary>
    NextQuarter,
    /// <summary>Represents the Open XML value <c>thisQuarter</c>.</summary>
    ThisQuarter,
    /// <summary>Represents the Open XML value <c>lastQuarter</c>.</summary>
    LastQuarter,
    /// <summary>Represents the Open XML value <c>nextYear</c>.</summary>
    NextYear,
    /// <summary>Represents the Open XML value <c>thisYear</c>.</summary>
    ThisYear,
    /// <summary>Represents the Open XML value <c>lastYear</c>.</summary>
    LastYear,
    /// <summary>Represents the Open XML value <c>yearToDate</c>.</summary>
    YearToDate,
    /// <summary>Represents the Open XML value <c>Q1</c>.</summary>
    Quarter1,
    /// <summary>Represents the Open XML value <c>Q2</c>.</summary>
    Quarter2,
    /// <summary>Represents the Open XML value <c>Q3</c>.</summary>
    Quarter3,
    /// <summary>Represents the Open XML value <c>Q4</c>.</summary>
    Quarter4,
    /// <summary>Represents the Open XML value <c>M1</c>.</summary>
    January,
    /// <summary>Represents the Open XML value <c>M2</c>.</summary>
    February,
    /// <summary>Represents the Open XML value <c>M3</c>.</summary>
    March,
    /// <summary>Represents the Open XML value <c>M4</c>.</summary>
    April,
    /// <summary>Represents the Open XML value <c>M5</c>.</summary>
    May,
    /// <summary>Represents the Open XML value <c>M6</c>.</summary>
    June,
    /// <summary>Represents the Open XML value <c>M7</c>.</summary>
    July,
    /// <summary>Represents the Open XML value <c>M8</c>.</summary>
    August,
    /// <summary>Represents the Open XML value <c>M9</c>.</summary>
    September,
    /// <summary>Represents the Open XML value <c>M10</c>.</summary>
    October,
    /// <summary>Represents the Open XML value <c>M11</c>.</summary>
    November,
    /// <summary>Represents the Open XML value <c>M12</c>.</summary>
    December,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Spreadsheet.PivotTableAxisValues.</summary>
public enum ExcelPivotTableAxis {
    /// <summary>Represents the Open XML value <c>axisRow</c>.</summary>
    AxisRow,
    /// <summary>Represents the Open XML value <c>axisCol</c>.</summary>
    AxisColumn,
    /// <summary>Represents the Open XML value <c>axisPage</c>.</summary>
    AxisPage,
    /// <summary>Represents the Open XML value <c>axisValues</c>.</summary>
    AxisValues,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Spreadsheet.ShowDataAsValues.</summary>
public enum ExcelPivotShowDataAs {
    /// <summary>Represents the Open XML value <c>normal</c>.</summary>
    Normal,
    /// <summary>Represents the Open XML value <c>difference</c>.</summary>
    Difference,
    /// <summary>Represents the Open XML value <c>percent</c>.</summary>
    Percent,
    /// <summary>Represents the Open XML value <c>percentDiff</c>.</summary>
    PercentageDifference,
    /// <summary>Represents the Open XML value <c>runTotal</c>.</summary>
    RunTotal,
    /// <summary>Represents the Open XML value <c>percentOfRow</c>.</summary>
    PercentOfRow,
    /// <summary>Represents the Open XML value <c>percentOfCol</c>.</summary>
    PercentOfColumn,
    /// <summary>Represents the Open XML value <c>percentOfTotal</c>.</summary>
    PercentOfTotal,
    /// <summary>Represents the Open XML value <c>index</c>.</summary>
    Index,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Spreadsheet.TimePeriodValues.</summary>
public enum ExcelConditionalTimePeriod {
    /// <summary>Represents the Open XML value <c>today</c>.</summary>
    Today,
    /// <summary>Represents the Open XML value <c>yesterday</c>.</summary>
    Yesterday,
    /// <summary>Represents the Open XML value <c>tomorrow</c>.</summary>
    Tomorrow,
    /// <summary>Represents the Open XML value <c>last7Days</c>.</summary>
    Last7Days,
    /// <summary>Represents the Open XML value <c>thisMonth</c>.</summary>
    ThisMonth,
    /// <summary>Represents the Open XML value <c>lastMonth</c>.</summary>
    LastMonth,
    /// <summary>Represents the Open XML value <c>nextMonth</c>.</summary>
    NextMonth,
    /// <summary>Represents the Open XML value <c>thisWeek</c>.</summary>
    ThisWeek,
    /// <summary>Represents the Open XML value <c>lastWeek</c>.</summary>
    LastWeek,
    /// <summary>Represents the Open XML value <c>nextWeek</c>.</summary>
    NextWeek,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Spreadsheet.TotalsRowFunctionValues.</summary>
public enum ExcelTableTotalsFunction {
    /// <summary>Represents the Open XML value <c>none</c>.</summary>
    None,
    /// <summary>Represents the Open XML value <c>sum</c>.</summary>
    Sum,
    /// <summary>Represents the Open XML value <c>min</c>.</summary>
    Minimum,
    /// <summary>Represents the Open XML value <c>max</c>.</summary>
    Maximum,
    /// <summary>Represents the Open XML value <c>average</c>.</summary>
    Average,
    /// <summary>Represents the Open XML value <c>count</c>.</summary>
    Count,
    /// <summary>Represents the Open XML value <c>countNums</c>.</summary>
    CountNumbers,
    /// <summary>Represents the Open XML value <c>stdDev</c>.</summary>
    StandardDeviation,
    /// <summary>Represents the Open XML value <c>var</c>.</summary>
    Variance,
    /// <summary>Represents the Open XML value <c>custom</c>.</summary>
    Custom,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Spreadsheet.UnderlineValues.</summary>
public enum ExcelUnderlineStyle {
    /// <summary>Represents the Open XML value <c>single</c>.</summary>
    Single,
    /// <summary>Represents the Open XML value <c>double</c>.</summary>
    Double,
    /// <summary>Represents the Open XML value <c>singleAccounting</c>.</summary>
    SingleAccounting,
    /// <summary>Represents the Open XML value <c>doubleAccounting</c>.</summary>
    DoubleAccounting,
    /// <summary>Represents the Open XML value <c>none</c>.</summary>
    None,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Spreadsheet.VerticalAlignmentRunValues.</summary>
public enum ExcelVerticalTextAlignment {
    /// <summary>Represents the Open XML value <c>baseline</c>.</summary>
    Baseline,
    /// <summary>Represents the Open XML value <c>superscript</c>.</summary>
    Superscript,
    /// <summary>Represents the Open XML value <c>subscript</c>.</summary>
    Subscript,
}

/// <summary>Defines OfficeIMO values corresponding to DocumentFormat.OpenXml.Spreadsheet.VerticalAlignmentValues.</summary>
public enum ExcelVerticalAlignment {
    /// <summary>Represents the Open XML value <c>top</c>.</summary>
    Top,
    /// <summary>Represents the Open XML value <c>center</c>.</summary>
    Center,
    /// <summary>Represents the Open XML value <c>bottom</c>.</summary>
    Bottom,
    /// <summary>Represents the Open XML value <c>justify</c>.</summary>
    Justify,
    /// <summary>Represents the Open XML value <c>distributed</c>.</summary>
    Distributed,
}

internal static class ExcelOpenXmlValueTypeExtensions {
    private static readonly string[] ExcelChartDisplayUnitTokens = {
        "hundreds",
        "thousands",
        "tenThousands",
        "hundredThousands",
        "millions",
        "tenMillions",
        "hundredMillions",
        "billions",
        "trillions",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.BuiltInUnitValues ToOpenXml(this ExcelChartDisplayUnit value) =>
        new(GetToken(value, ExcelChartDisplayUnitTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.BuiltInUnitValues? ToOpenXml(this ExcelChartDisplayUnit? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static ExcelChartDisplayUnit ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.BuiltInUnitValues value) =>
        (ExcelChartDisplayUnit)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, ExcelChartDisplayUnitTokens, nameof(ExcelChartDisplayUnit));

    internal static ExcelChartDisplayUnit? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.BuiltInUnitValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] ExcelChartAxisCrossBetweenTokens = {
        "between",
        "midCat",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.CrossBetweenValues ToOpenXml(this ExcelChartAxisCrossBetween value) =>
        new(GetToken(value, ExcelChartAxisCrossBetweenTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.CrossBetweenValues? ToOpenXml(this ExcelChartAxisCrossBetween? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static ExcelChartAxisCrossBetween ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.CrossBetweenValues value) =>
        (ExcelChartAxisCrossBetween)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, ExcelChartAxisCrossBetweenTokens, nameof(ExcelChartAxisCrossBetween));

    internal static ExcelChartAxisCrossBetween? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.CrossBetweenValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] ExcelChartAxisCrossingTokens = {
        "autoZero",
        "max",
        "min",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.CrossesValues ToOpenXml(this ExcelChartAxisCrossing value) =>
        new(GetToken(value, ExcelChartAxisCrossingTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.CrossesValues? ToOpenXml(this ExcelChartAxisCrossing? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static ExcelChartAxisCrossing ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.CrossesValues value) =>
        (ExcelChartAxisCrossing)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, ExcelChartAxisCrossingTokens, nameof(ExcelChartAxisCrossing));

    internal static ExcelChartAxisCrossing? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.CrossesValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] ExcelChartDataLabelPositionTokens = {
        "bestFit",
        "b",
        "ctr",
        "inBase",
        "inEnd",
        "l",
        "outEnd",
        "r",
        "t",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.DataLabelPositionValues ToOpenXml(this ExcelChartDataLabelPosition value) =>
        new(GetToken(value, ExcelChartDataLabelPositionTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.DataLabelPositionValues? ToOpenXml(this ExcelChartDataLabelPosition? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static ExcelChartDataLabelPosition ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.DataLabelPositionValues value) =>
        (ExcelChartDataLabelPosition)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, ExcelChartDataLabelPositionTokens, nameof(ExcelChartDataLabelPosition));

    internal static ExcelChartDataLabelPosition? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.DataLabelPositionValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] ExcelChartLegendPositionTokens = {
        "b",
        "tr",
        "l",
        "r",
        "t",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.LegendPositionValues ToOpenXml(this ExcelChartLegendPosition value) =>
        new(GetToken(value, ExcelChartLegendPositionTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.LegendPositionValues? ToOpenXml(this ExcelChartLegendPosition? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static ExcelChartLegendPosition ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.LegendPositionValues value) =>
        (ExcelChartLegendPosition)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, ExcelChartLegendPositionTokens, nameof(ExcelChartLegendPosition));

    internal static ExcelChartLegendPosition? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.LegendPositionValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] ExcelChartMarkerStyleTokens = {
        "auto",
        "circle",
        "dash",
        "diamond",
        "dot",
        "none",
        "picture",
        "plus",
        "square",
        "star",
        "triangle",
        "x",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.MarkerStyleValues ToOpenXml(this ExcelChartMarkerStyle value) =>
        new(GetToken(value, ExcelChartMarkerStyleTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.MarkerStyleValues? ToOpenXml(this ExcelChartMarkerStyle? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static ExcelChartMarkerStyle ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.MarkerStyleValues value) =>
        (ExcelChartMarkerStyle)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, ExcelChartMarkerStyleTokens, nameof(ExcelChartMarkerStyle));

    internal static ExcelChartMarkerStyle? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.MarkerStyleValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] ExcelChartTickLabelPositionTokens = {
        "high",
        "low",
        "nextTo",
        "none",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.TickLabelPositionValues ToOpenXml(this ExcelChartTickLabelPosition value) =>
        new(GetToken(value, ExcelChartTickLabelPositionTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.TickLabelPositionValues? ToOpenXml(this ExcelChartTickLabelPosition? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static ExcelChartTickLabelPosition ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.TickLabelPositionValues value) =>
        (ExcelChartTickLabelPosition)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, ExcelChartTickLabelPositionTokens, nameof(ExcelChartTickLabelPosition));

    internal static ExcelChartTickLabelPosition? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.TickLabelPositionValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] ExcelChartTrendlineTypeTokens = {
        "exp",
        "linear",
        "log",
        "movingAvg",
        "poly",
        "power",
    };

    internal static DocumentFormat.OpenXml.Drawing.Charts.TrendlineValues ToOpenXml(this ExcelChartTrendlineType value) =>
        new(GetToken(value, ExcelChartTrendlineTypeTokens));

    internal static DocumentFormat.OpenXml.Drawing.Charts.TrendlineValues? ToOpenXml(this ExcelChartTrendlineType? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static ExcelChartTrendlineType ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.TrendlineValues value) =>
        (ExcelChartTrendlineType)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, ExcelChartTrendlineTypeTokens, nameof(ExcelChartTrendlineType));

    internal static ExcelChartTrendlineType? ToOfficeEnum(this DocumentFormat.OpenXml.Drawing.Charts.TrendlineValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] ExcelSparklineTypeTokens = {
        "line",
        "column",
        "stacked",
    };

    internal static DocumentFormat.OpenXml.Office2010.Excel.SparklineTypeValues ToOpenXml(this ExcelSparklineType value) =>
        new(GetToken(value, ExcelSparklineTypeTokens));

    internal static DocumentFormat.OpenXml.Office2010.Excel.SparklineTypeValues? ToOpenXml(this ExcelSparklineType? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static ExcelSparklineType ToOfficeEnum(this DocumentFormat.OpenXml.Office2010.Excel.SparklineTypeValues value) =>
        (ExcelSparklineType)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, ExcelSparklineTypeTokens, nameof(ExcelSparklineType));

    internal static ExcelSparklineType? ToOfficeEnum(this DocumentFormat.OpenXml.Office2010.Excel.SparklineTypeValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] ExcelBorderStyleTokens = {
        "none",
        "thin",
        "medium",
        "dashed",
        "dotted",
        "thick",
        "double",
        "hair",
        "mediumDashed",
        "dashDot",
        "mediumDashDot",
        "dashDotDot",
        "mediumDashDotDot",
        "slantDashDot",
    };

    internal static DocumentFormat.OpenXml.Spreadsheet.BorderStyleValues ToOpenXml(this ExcelBorderStyle value) =>
        new(GetToken(value, ExcelBorderStyleTokens));

    internal static DocumentFormat.OpenXml.Spreadsheet.BorderStyleValues? ToOpenXml(this ExcelBorderStyle? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static ExcelBorderStyle ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.BorderStyleValues value) =>
        (ExcelBorderStyle)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, ExcelBorderStyleTokens, nameof(ExcelBorderStyle));

    internal static ExcelBorderStyle? ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.BorderStyleValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] ExcelCellValueTypeTokens = {
        "b",
        "n",
        "e",
        "s",
        "str",
        "inlineStr",
        "d",
    };

    internal static DocumentFormat.OpenXml.Spreadsheet.CellValues ToOpenXml(this ExcelCellValueType value) =>
        new(GetToken(value, ExcelCellValueTypeTokens));

    internal static DocumentFormat.OpenXml.Spreadsheet.CellValues? ToOpenXml(this ExcelCellValueType? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static ExcelCellValueType ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.CellValues value) =>
        (ExcelCellValueType)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, ExcelCellValueTypeTokens, nameof(ExcelCellValueType));

    internal static ExcelCellValueType? ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.CellValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] ExcelConditionalFormatTypeTokens = {
        "expression",
        "cellIs",
        "colorScale",
        "dataBar",
        "iconSet",
        "top10",
        "uniqueValues",
        "duplicateValues",
        "containsText",
        "notContainsText",
        "beginsWith",
        "endsWith",
        "containsBlanks",
        "notContainsBlanks",
        "containsErrors",
        "notContainsErrors",
        "timePeriod",
        "aboveAverage",
    };

    internal static DocumentFormat.OpenXml.Spreadsheet.ConditionalFormatValues ToOpenXml(this ExcelConditionalFormatType value) =>
        new(GetToken(value, ExcelConditionalFormatTypeTokens));

    internal static DocumentFormat.OpenXml.Spreadsheet.ConditionalFormatValues? ToOpenXml(this ExcelConditionalFormatType? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static ExcelConditionalFormatType ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.ConditionalFormatValues value) =>
        (ExcelConditionalFormatType)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, ExcelConditionalFormatTypeTokens, nameof(ExcelConditionalFormatType));

    internal static ExcelConditionalFormatType? ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.ConditionalFormatValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] ExcelConditionalFormattingOperatorTokens = {
        "lessThan",
        "lessThanOrEqual",
        "equal",
        "notEqual",
        "greaterThanOrEqual",
        "greaterThan",
        "between",
        "notBetween",
        "containsText",
        "notContains",
        "beginsWith",
        "endsWith",
    };

    internal static DocumentFormat.OpenXml.Spreadsheet.ConditionalFormattingOperatorValues ToOpenXml(this ExcelConditionalFormattingOperator value) =>
        new(GetToken(value, ExcelConditionalFormattingOperatorTokens));

    internal static DocumentFormat.OpenXml.Spreadsheet.ConditionalFormattingOperatorValues? ToOpenXml(this ExcelConditionalFormattingOperator? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static ExcelConditionalFormattingOperator ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.ConditionalFormattingOperatorValues value) =>
        (ExcelConditionalFormattingOperator)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, ExcelConditionalFormattingOperatorTokens, nameof(ExcelConditionalFormattingOperator));

    internal static ExcelConditionalFormattingOperator? ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.ConditionalFormattingOperatorValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] ExcelPivotDataFunctionTokens = {
        "average",
        "count",
        "countNums",
        "max",
        "min",
        "product",
        "stdDev",
        "stdDevp",
        "sum",
        "var",
        "varp",
    };

    internal static DocumentFormat.OpenXml.Spreadsheet.DataConsolidateFunctionValues ToOpenXml(this ExcelPivotDataFunction value) =>
        new(GetToken(value, ExcelPivotDataFunctionTokens));

    internal static DocumentFormat.OpenXml.Spreadsheet.DataConsolidateFunctionValues? ToOpenXml(this ExcelPivotDataFunction? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static ExcelPivotDataFunction ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.DataConsolidateFunctionValues value) =>
        (ExcelPivotDataFunction)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, ExcelPivotDataFunctionTokens, nameof(ExcelPivotDataFunction));

    internal static ExcelPivotDataFunction? ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.DataConsolidateFunctionValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] ExcelDataValidationErrorStyleTokens = {
        "stop",
        "warning",
        "information",
    };

    internal static DocumentFormat.OpenXml.Spreadsheet.DataValidationErrorStyleValues ToOpenXml(this ExcelDataValidationErrorStyle value) =>
        new(GetToken(value, ExcelDataValidationErrorStyleTokens));

    internal static DocumentFormat.OpenXml.Spreadsheet.DataValidationErrorStyleValues? ToOpenXml(this ExcelDataValidationErrorStyle? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static ExcelDataValidationErrorStyle ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.DataValidationErrorStyleValues value) =>
        (ExcelDataValidationErrorStyle)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, ExcelDataValidationErrorStyleTokens, nameof(ExcelDataValidationErrorStyle));

    internal static ExcelDataValidationErrorStyle? ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.DataValidationErrorStyleValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] ExcelDataValidationOperatorTokens = {
        "between",
        "notBetween",
        "equal",
        "notEqual",
        "lessThan",
        "lessThanOrEqual",
        "greaterThan",
        "greaterThanOrEqual",
    };

    internal static DocumentFormat.OpenXml.Spreadsheet.DataValidationOperatorValues ToOpenXml(this ExcelDataValidationOperator value) =>
        new(GetToken(value, ExcelDataValidationOperatorTokens));

    internal static DocumentFormat.OpenXml.Spreadsheet.DataValidationOperatorValues? ToOpenXml(this ExcelDataValidationOperator? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static ExcelDataValidationOperator ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.DataValidationOperatorValues value) =>
        (ExcelDataValidationOperator)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, ExcelDataValidationOperatorTokens, nameof(ExcelDataValidationOperator));

    internal static ExcelDataValidationOperator? ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.DataValidationOperatorValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] ExcelPivotFieldSortTokens = {
        "manual",
        "ascending",
        "descending",
    };

    internal static DocumentFormat.OpenXml.Spreadsheet.FieldSortValues ToOpenXml(this ExcelPivotFieldSort value) =>
        new(GetToken(value, ExcelPivotFieldSortTokens));

    internal static DocumentFormat.OpenXml.Spreadsheet.FieldSortValues? ToOpenXml(this ExcelPivotFieldSort? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static ExcelPivotFieldSort ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.FieldSortValues value) =>
        (ExcelPivotFieldSort)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, ExcelPivotFieldSortTokens, nameof(ExcelPivotFieldSort));

    internal static ExcelPivotFieldSort? ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.FieldSortValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] ExcelPivotGroupByTokens = {
        "range",
        "seconds",
        "minutes",
        "hours",
        "days",
        "months",
        "quarters",
        "years",
    };

    internal static DocumentFormat.OpenXml.Spreadsheet.GroupByValues ToOpenXml(this ExcelPivotGroupBy value) =>
        new(GetToken(value, ExcelPivotGroupByTokens));

    internal static DocumentFormat.OpenXml.Spreadsheet.GroupByValues? ToOpenXml(this ExcelPivotGroupBy? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static ExcelPivotGroupBy ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.GroupByValues value) =>
        (ExcelPivotGroupBy)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, ExcelPivotGroupByTokens, nameof(ExcelPivotGroupBy));

    internal static ExcelPivotGroupBy? ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.GroupByValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] ExcelHorizontalAlignmentTokens = {
        "general",
        "left",
        "center",
        "right",
        "fill",
        "justify",
        "centerContinuous",
        "distributed",
    };

    internal static DocumentFormat.OpenXml.Spreadsheet.HorizontalAlignmentValues ToOpenXml(this ExcelHorizontalAlignment value) =>
        new(GetToken(value, ExcelHorizontalAlignmentTokens));

    internal static DocumentFormat.OpenXml.Spreadsheet.HorizontalAlignmentValues? ToOpenXml(this ExcelHorizontalAlignment? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static ExcelHorizontalAlignment ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.HorizontalAlignmentValues value) =>
        (ExcelHorizontalAlignment)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, ExcelHorizontalAlignmentTokens, nameof(ExcelHorizontalAlignment));

    internal static ExcelHorizontalAlignment? ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.HorizontalAlignmentValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] ExcelIconSetTokens = {
        "3Arrows",
        "3ArrowsGray",
        "3Flags",
        "3TrafficLights1",
        "3TrafficLights2",
        "3Signs",
        "3Symbols",
        "3Symbols2",
        "4Arrows",
        "4ArrowsGray",
        "4RedToBlack",
        "4Rating",
        "4TrafficLights",
        "5Arrows",
        "5ArrowsGray",
        "5Rating",
        "5Quarters",
    };

    internal static DocumentFormat.OpenXml.Spreadsheet.IconSetValues ToOpenXml(this ExcelIconSet value) =>
        new(GetToken(value, ExcelIconSetTokens));

    internal static DocumentFormat.OpenXml.Spreadsheet.IconSetValues? ToOpenXml(this ExcelIconSet? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static ExcelIconSet ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.IconSetValues value) =>
        (ExcelIconSet)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, ExcelIconSetTokens, nameof(ExcelIconSet));

    internal static ExcelIconSet? ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.IconSetValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] ExcelPivotFilterTypeTokens = {
        "unknown",
        "count",
        "percent",
        "sum",
        "captionEqual",
        "captionNotEqual",
        "captionBeginsWith",
        "captionNotBeginsWith",
        "captionEndsWith",
        "captionNotEndsWith",
        "captionContains",
        "captionNotContains",
        "captionGreaterThan",
        "captionGreaterThanOrEqual",
        "captionLessThan",
        "captionLessThanOrEqual",
        "captionBetween",
        "captionNotBetween",
        "valueEqual",
        "valueNotEqual",
        "valueGreaterThan",
        "valueGreaterThanOrEqual",
        "valueLessThan",
        "valueLessThanOrEqual",
        "valueBetween",
        "valueNotBetween",
        "dateEqual",
        "dateNotEqual",
        "dateOlderThan",
        "dateOlderThanOrEqual",
        "dateNewerThan",
        "dateNewerThanOrEqual",
        "dateBetween",
        "dateNotBetween",
        "tomorrow",
        "today",
        "yesterday",
        "nextWeek",
        "thisWeek",
        "lastWeek",
        "nextMonth",
        "thisMonth",
        "lastMonth",
        "nextQuarter",
        "thisQuarter",
        "lastQuarter",
        "nextYear",
        "thisYear",
        "lastYear",
        "yearToDate",
        "Q1",
        "Q2",
        "Q3",
        "Q4",
        "M1",
        "M2",
        "M3",
        "M4",
        "M5",
        "M6",
        "M7",
        "M8",
        "M9",
        "M10",
        "M11",
        "M12",
    };

    internal static DocumentFormat.OpenXml.Spreadsheet.PivotFilterValues ToOpenXml(this ExcelPivotFilterType value) =>
        new(GetToken(value, ExcelPivotFilterTypeTokens));

    internal static DocumentFormat.OpenXml.Spreadsheet.PivotFilterValues? ToOpenXml(this ExcelPivotFilterType? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static ExcelPivotFilterType ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.PivotFilterValues value) =>
        (ExcelPivotFilterType)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, ExcelPivotFilterTypeTokens, nameof(ExcelPivotFilterType));

    internal static ExcelPivotFilterType? ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.PivotFilterValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] ExcelPivotTableAxisTokens = {
        "axisRow",
        "axisCol",
        "axisPage",
        "axisValues",
    };

    internal static DocumentFormat.OpenXml.Spreadsheet.PivotTableAxisValues ToOpenXml(this ExcelPivotTableAxis value) =>
        new(GetToken(value, ExcelPivotTableAxisTokens));

    internal static DocumentFormat.OpenXml.Spreadsheet.PivotTableAxisValues? ToOpenXml(this ExcelPivotTableAxis? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static ExcelPivotTableAxis ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.PivotTableAxisValues value) =>
        (ExcelPivotTableAxis)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, ExcelPivotTableAxisTokens, nameof(ExcelPivotTableAxis));

    internal static ExcelPivotTableAxis? ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.PivotTableAxisValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] ExcelPivotShowDataAsTokens = {
        "normal",
        "difference",
        "percent",
        "percentDiff",
        "runTotal",
        "percentOfRow",
        "percentOfCol",
        "percentOfTotal",
        "index",
    };

    internal static DocumentFormat.OpenXml.Spreadsheet.ShowDataAsValues ToOpenXml(this ExcelPivotShowDataAs value) =>
        new(GetToken(value, ExcelPivotShowDataAsTokens));

    internal static DocumentFormat.OpenXml.Spreadsheet.ShowDataAsValues? ToOpenXml(this ExcelPivotShowDataAs? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static ExcelPivotShowDataAs ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.ShowDataAsValues value) =>
        (ExcelPivotShowDataAs)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, ExcelPivotShowDataAsTokens, nameof(ExcelPivotShowDataAs));

    internal static ExcelPivotShowDataAs? ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.ShowDataAsValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] ExcelConditionalTimePeriodTokens = {
        "today",
        "yesterday",
        "tomorrow",
        "last7Days",
        "thisMonth",
        "lastMonth",
        "nextMonth",
        "thisWeek",
        "lastWeek",
        "nextWeek",
    };

    internal static DocumentFormat.OpenXml.Spreadsheet.TimePeriodValues ToOpenXml(this ExcelConditionalTimePeriod value) =>
        new(GetToken(value, ExcelConditionalTimePeriodTokens));

    internal static DocumentFormat.OpenXml.Spreadsheet.TimePeriodValues? ToOpenXml(this ExcelConditionalTimePeriod? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static ExcelConditionalTimePeriod ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.TimePeriodValues value) =>
        (ExcelConditionalTimePeriod)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, ExcelConditionalTimePeriodTokens, nameof(ExcelConditionalTimePeriod));

    internal static ExcelConditionalTimePeriod? ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.TimePeriodValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] ExcelTableTotalsFunctionTokens = {
        "none",
        "sum",
        "min",
        "max",
        "average",
        "count",
        "countNums",
        "stdDev",
        "var",
        "custom",
    };

    internal static DocumentFormat.OpenXml.Spreadsheet.TotalsRowFunctionValues ToOpenXml(this ExcelTableTotalsFunction value) =>
        new(GetToken(value, ExcelTableTotalsFunctionTokens));

    internal static DocumentFormat.OpenXml.Spreadsheet.TotalsRowFunctionValues? ToOpenXml(this ExcelTableTotalsFunction? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static ExcelTableTotalsFunction ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.TotalsRowFunctionValues value) =>
        (ExcelTableTotalsFunction)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, ExcelTableTotalsFunctionTokens, nameof(ExcelTableTotalsFunction));

    internal static ExcelTableTotalsFunction? ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.TotalsRowFunctionValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] ExcelUnderlineStyleTokens = {
        "single",
        "double",
        "singleAccounting",
        "doubleAccounting",
        "none",
    };

    internal static DocumentFormat.OpenXml.Spreadsheet.UnderlineValues ToOpenXml(this ExcelUnderlineStyle value) =>
        new(GetToken(value, ExcelUnderlineStyleTokens));

    internal static DocumentFormat.OpenXml.Spreadsheet.UnderlineValues? ToOpenXml(this ExcelUnderlineStyle? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static ExcelUnderlineStyle ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.UnderlineValues value) =>
        (ExcelUnderlineStyle)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, ExcelUnderlineStyleTokens, nameof(ExcelUnderlineStyle));

    internal static ExcelUnderlineStyle? ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.UnderlineValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] ExcelVerticalTextAlignmentTokens = {
        "baseline",
        "superscript",
        "subscript",
    };

    internal static DocumentFormat.OpenXml.Spreadsheet.VerticalAlignmentRunValues ToOpenXml(this ExcelVerticalTextAlignment value) =>
        new(GetToken(value, ExcelVerticalTextAlignmentTokens));

    internal static DocumentFormat.OpenXml.Spreadsheet.VerticalAlignmentRunValues? ToOpenXml(this ExcelVerticalTextAlignment? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static ExcelVerticalTextAlignment ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.VerticalAlignmentRunValues value) =>
        (ExcelVerticalTextAlignment)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, ExcelVerticalTextAlignmentTokens, nameof(ExcelVerticalTextAlignment));

    internal static ExcelVerticalTextAlignment? ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.VerticalAlignmentRunValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static readonly string[] ExcelVerticalAlignmentTokens = {
        "top",
        "center",
        "bottom",
        "justify",
        "distributed",
    };

    internal static DocumentFormat.OpenXml.Spreadsheet.VerticalAlignmentValues ToOpenXml(this ExcelVerticalAlignment value) =>
        new(GetToken(value, ExcelVerticalAlignmentTokens));

    internal static DocumentFormat.OpenXml.Spreadsheet.VerticalAlignmentValues? ToOpenXml(this ExcelVerticalAlignment? value) =>
        value.HasValue ? value.Value.ToOpenXml() : null;

    internal static ExcelVerticalAlignment ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.VerticalAlignmentValues value) =>
        (ExcelVerticalAlignment)FindToken(((DocumentFormat.OpenXml.IEnumValue)value).Value, ExcelVerticalAlignmentTokens, nameof(ExcelVerticalAlignment));

    internal static ExcelVerticalAlignment? ToOfficeEnum(this DocumentFormat.OpenXml.Spreadsheet.VerticalAlignmentValues? value) =>
        value.HasValue ? value.Value.ToOfficeEnum() : null;

    private static string GetToken<TEnum>(TEnum value, string[] tokens) where TEnum : struct, Enum {
        int index = Convert.ToInt32(value, CultureInfo.InvariantCulture);
        if ((uint)index >= (uint)tokens.Length) throw new ArgumentOutOfRangeException(nameof(value), value, $"Unsupported {typeof(TEnum).Name} value.");
        return tokens[index];
    }

    private static int FindToken(string token, string[] tokens, string enumName) {
        int index = Array.IndexOf(tokens, token);
        if (index < 0) throw new ArgumentOutOfRangeException(nameof(token), token, $"Unsupported {enumName} token.");
        return index;
    }
}
