using System.Collections.Immutable;
using System.Security.Cryptography;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace OfficeIMO.Data.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class RowMapperGenerator : IIncrementalGenerator {
    private const string GenerateAttributeName = "OfficeIMO.Data.GenerateRowMapperAttribute";
    private const string ColumnAttributeName = "OfficeIMO.Data.DataColumnAttribute";

    private static readonly DiagnosticDescriptor MissingConstructor = new(
        "ODATA001",
        "Generated row mapping requires a parameterless constructor",
        "Type '{0}' must expose a public parameterless constructor for RowMapper<T>",
        "OfficeIMO.Data",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor NoWritableProperties = new(
        "ODATA002",
        "Generated row mapping has no writable properties",
        "Type '{0}' has no public instance properties with public setters",
        "OfficeIMO.Data",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor UnsupportedModelShape = new(
        "ODATA003",
        "Generated row mapping requires a supported model shape",
        "Type '{0}' must be a concrete, top-level, non-generic, non-ref-like class or struct to generate a RowMapper<T> configuration",
        "OfficeIMO.Data",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        IncrementalValuesProvider<INamedTypeSymbol> models = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                GenerateAttributeName,
                static (node, _) => node is TypeDeclarationSyntax,
                static (attributeContext, _) => (INamedTypeSymbol)attributeContext.TargetSymbol)
            .WithComparer(SymbolEqualityComparer.Default);

        context.RegisterSourceOutput(models, static (productionContext, model) =>
            Emit(productionContext, model));
    }

    private static void Emit(SourceProductionContext context, INamedTypeSymbol model) {
        if (model.ContainingType is not null ||
            model.TypeParameters.Length != 0 ||
            model.IsAbstract ||
            model.IsRefLikeType ||
            IsFileLocal(model) ||
            model.TypeKind is not TypeKind.Class and not TypeKind.Struct) {
            context.ReportDiagnostic(Diagnostic.Create(
                UnsupportedModelShape,
                model.Locations.FirstOrDefault(),
                model.ToDisplayString()));
            return;
        }

        if (!HasPublicParameterlessConstructor(model)) {
            context.ReportDiagnostic(Diagnostic.Create(
                MissingConstructor,
                model.Locations.FirstOrDefault(),
                model.ToDisplayString()));
            return;
        }

        ImmutableArray<IPropertySymbol> properties = GetWritableProperties(model);
        if (properties.IsDefaultOrEmpty) {
            context.ReportDiagnostic(Diagnostic.Create(
                NoWritableProperties,
                model.Locations.FirstOrDefault(),
                model.ToDisplayString()));
            return;
        }

        string namespaceName = model.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : model.ContainingNamespace.ToDisplayString();
        string modelType = model.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string mappingTypeName = GetMappingTypeName(model);
        string accessibility = model.DeclaredAccessibility == Accessibility.Public ? "public" : "internal";
        var source = new StringBuilder(2048);
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        if (namespaceName.Length != 0) {
            source.Append("namespace ").Append(namespaceName).AppendLine(";");
            source.AppendLine();
        }
        source.Append(accessibility).Append(" static class ").Append(mappingTypeName).AppendLine(" {");
        source.Append("    public static void Configure(global::OfficeIMO.Data.RowMapper<")
            .Append(modelType).AppendLine("> mapper) {");
        source.AppendLine("        if (mapper is null) throw new global::System.ArgumentNullException(nameof(mapper));");

        foreach (IPropertySymbol property in properties) {
            string propertyType = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string propertyName = EscapeIdentifier(property.Name);
            string[] columnNames = GetColumnNames(property).ToArray();
            source.Append("        mapper.FromColumns<").Append(propertyType)
                .Append(">(new string[] { ");
            for (int index = 0; index < columnNames.Length; index++) {
                if (index != 0) source.Append(", ");
                source.Append(SymbolDisplay.FormatLiteral(columnNames[index], quote: true));
            }
            source.Append(" }, static (row, value) => { row.").Append(propertyName)
                .AppendLine(" = value; return row; });");
        }

        source.AppendLine("    }");
        source.AppendLine("}");
        context.AddSource(GetHintName(model), SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static bool HasPublicParameterlessConstructor(INamedTypeSymbol model) {
        if (model.IsValueType) return true;
        if (model.IsAbstract) return false;
        return model.InstanceConstructors.Any(static constructor =>
            constructor.Parameters.Length == 0 &&
            constructor.DeclaredAccessibility == Accessibility.Public);
    }

    private static bool IsFileLocal(INamedTypeSymbol model) =>
        model.DeclaringSyntaxReferences.Any(static reference =>
            reference.GetSyntax() is TypeDeclarationSyntax declaration &&
            declaration.Modifiers.Any(static modifier => modifier.IsKind(SyntaxKind.FileKeyword)));

    private static ImmutableArray<IPropertySymbol> GetWritableProperties(INamedTypeSymbol model) {
        var builder = ImmutableArray.CreateBuilder<IPropertySymbol>();
        var propertyNames = new HashSet<string>(StringComparer.Ordinal);
        for (INamedTypeSymbol? current = model;
             current is not null && current.SpecialType != SpecialType.System_Object;
             current = current.BaseType) {
            foreach (IPropertySymbol property in current.GetMembers().OfType<IPropertySymbol>()) {
                if (!property.IsStatic &&
                    property.DeclaredAccessibility == Accessibility.Public &&
                    property.SetMethod?.DeclaredAccessibility == Accessibility.Public &&
                    !property.SetMethod.IsInitOnly &&
                    property.Parameters.Length == 0 &&
                    propertyNames.Add(property.Name)) {
                    builder.Add(property);
                }
            }
        }
        return builder.ToImmutable();
    }

    private static IEnumerable<string> GetColumnNames(IPropertySymbol property) {
        AttributeData? attribute = GetInheritedColumnAttribute(property);
        if (attribute == null || attribute.ConstructorArguments.Length == 0 ||
            attribute.ConstructorArguments[0].Value is not string primary ||
            string.IsNullOrWhiteSpace(primary)) {
            yield return property.Name;
            yield break;
        }

        yield return primary;
        if (attribute.ConstructorArguments.Length < 2) yield break;
        TypedConstant aliases = attribute.ConstructorArguments[1];
        if (aliases.IsNull) yield break;
        foreach (TypedConstant alias in aliases.Values) {
            if (alias.Value is string text && !string.IsNullOrWhiteSpace(text)) yield return text;
        }
    }

    private static AttributeData? GetInheritedColumnAttribute(IPropertySymbol property) {
        for (IPropertySymbol? current = property; current != null; current = current.OverriddenProperty) {
            AttributeData? attribute = current.GetAttributes().FirstOrDefault(static candidate =>
                candidate.AttributeClass?.ToDisplayString() == ColumnAttributeName);
            if (attribute != null) return attribute;
        }

        return null;
    }

    private static string GetMappingTypeName(INamedTypeSymbol model) {
        var names = new Stack<string>();
        for (INamedTypeSymbol? current = model; current != null; current = current.ContainingType) {
            names.Push(SanitizeIdentifier(current.Name));
        }
        return string.Join("_", names) + "RowMapping";
    }

    private static string GetHintName(INamedTypeSymbol model) {
        string fullName = model.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        byte[] digest;
        using (SHA256 sha256 = SHA256.Create()) {
            digest = sha256.ComputeHash(Encoding.UTF8.GetBytes(fullName));
        }

        var suffix = new StringBuilder(digest.Length * 2);
        foreach (byte value in digest) suffix.Append(value.ToString("x2"));
        return SanitizeIdentifier(model.Name) + "_" + suffix + ".RowMapping.g.cs";
    }

    private static string EscapeIdentifier(string value) =>
        SyntaxFacts.GetKeywordKind(value) != SyntaxKind.None ? "@" + value : value;

    private static string SanitizeIdentifier(string value) {
        var builder = new StringBuilder(value.Length);
        foreach (char character in value) {
            builder.Append(SyntaxFacts.IsIdentifierPartCharacter(character) ? character : '_');
        }
        return builder.ToString();
    }
}
