// The C# PDF writer owns the Adobe AFM-derived metrics. This projection keeps both writers aligned.
import { readFile, writeFile } from "node:fs/promises";
const source = await readFile(new URL("../../OfficeIMO.Pdf/Rendering/Writer/PdfStandardFontWidths.cs", import.meta.url), "utf8");
const characters = [...source.match(/char\[\] Characters = \{([\s\S]*?)\};/)[1].matchAll(/\\u([0-9A-F]{4})/g)].map(m => parseInt(m[1], 16));
const arrays = ["Helvetica", "HelveticaBold"].map(name => [...source.match(new RegExp("short\\[\\] " + name + " = \\{([\\s\\S]*?)\\};"))[1].matchAll(/\d+/g)].map(m => Number(m[0])));
if (arrays.some(a => a.length !== characters.length)) throw new Error("Standard font metric source changed.");
const rows = characters.map((cp, i) => `[${cp},${arrays[0][i]},${arrays[1][i]}]`);
const text = "// Generated by scripts/pdf-widths.mjs from OfficeIMO.Pdf's Adobe AFM-derived metrics.\n" +
  "export const helveticaWidths = new Map<number, readonly [number, number]>([\n" +
  rows.map(r => { const [cp, a, b] = JSON.parse(r); return `  [${cp}, [${a}, ${b}]],`; }).join("\n") + "\n]);\n";
await writeFile(new URL("../src/pdf/standard-widths.ts", import.meta.url), text);
