namespace OfficeIMO.Project;

internal static partial class ProjectXmlFields {
    internal static readonly ProjectXmlField<ProjectTask>[] Task = {
        new ProjectXmlField<ProjectTask>("IgnoreResourceCalendar", (m,d) => ProjectXmlValue.Boolean(m.IgnoreResourceCalendar), (m,v,d,e) => m.IgnoreResourceCalendar = ProjectXmlValue.ParseBool(v)),
        new ProjectXmlField<ProjectTask>("FixedCostAccrual", (m,d) => ProjectXmlValue.Integer((int?)m.FixedCostAccrual), (m,v,d,e) => m.FixedCostAccrual = (ProjectCostAccrual)ProjectXmlValue.ParseInt(v)),
        new ProjectXmlField<ProjectTask>("Stop", (m,d) => ProjectXmlValue.Date(m.Stop), (m,v,d,e) => m.Stop = ProjectXmlValue.ParseDate(v)),
        new ProjectXmlField<ProjectTask>("Resume", (m,d) => ProjectXmlValue.Date(m.Resume), (m,v,d,e) => m.Resume = ProjectXmlValue.ParseDate(v)),
        new ProjectXmlField<ProjectTask>("EarnedValueMethod", (m,d) => ProjectXmlValue.Integer((int?)m.EarnedValueMethod), (m,v,d,e) => m.EarnedValueMethod = (ProjectEarnedValueMethod)ProjectXmlValue.ParseInt(v)),
        new ProjectXmlField<ProjectTask>("EarlyStart", (m, d) => ProjectXmlValue.Date(m.EarlyStart), (m, v, d, e) => m.EarlyStart = ProjectXmlValue.ParseDate(v)),
        new ProjectXmlField<ProjectTask>("EarlyFinish", (m, d) => ProjectXmlValue.Date(m.EarlyFinish), (m, v, d, e) => m.EarlyFinish = ProjectXmlValue.ParseDate(v)),
        new ProjectXmlField<ProjectTask>("LateStart", (m, d) => ProjectXmlValue.Date(m.LateStart), (m, v, d, e) => m.LateStart = ProjectXmlValue.ParseDate(v)),
        new ProjectXmlField<ProjectTask>("LateFinish", (m, d) => ProjectXmlValue.Date(m.LateFinish), (m, v, d, e) => m.LateFinish = ProjectXmlValue.ParseDate(v)),
        new ProjectXmlField<ProjectTask>("TotalSlack", (m, d) => ProjectXmlValue.Number(m.TotalSlackMinutes * 10m), (m, v, d, e) => m.TotalSlackMinutes = ProjectXmlValue.ParseNumber(v) / 10m),
        new ProjectXmlField<ProjectTask>("FreeSlack", (m, d) => ProjectXmlValue.Number(m.FreeSlackMinutes * 10m), (m, v, d, e) => m.FreeSlackMinutes = ProjectXmlValue.ParseNumber(v) / 10m),
        new ProjectXmlField<ProjectTask>("GUID", (m, d) => ProjectXmlValue.Identifier(m.Guid), (m, v, d, e) => m.Guid = ProjectXmlValue.ParseGuid(v)),
        new ProjectXmlField<ProjectTask>("Name", (m, d) => ProjectXmlValue.Text(m.Name), (m, v, d, e) => m.Name = v),
        new ProjectXmlField<ProjectTask>("ID", (m, d) => ProjectXmlValue.Integer(m.DisplayId), (m, v, d, e) => m.DisplayId = ProjectXmlValue.ParseInt(v)),
        new ProjectXmlField<ProjectTask>("WBS", (m, d) => ProjectXmlValue.Text(m.Wbs), (m, v, d, e) => m.Wbs = v),
        new ProjectXmlField<ProjectTask>("Duration", (m, d) => ProjectXmlValue.Duration(m.Duration, d), (m, v, d, e) => m.Duration = ProjectXmlValue.ParseDuration(v, (int?)e.Element(e.Name.Namespace + "DurationFormat"), d)),
        new ProjectXmlField<ProjectTask>("ActualDuration", (m, d) => ProjectXmlValue.Duration(m.ActualDuration, d), (m, v, d, e) => m.ActualDuration = ProjectXmlValue.ParseDuration(v, (int?)e.Element(e.Name.Namespace + "DurationFormat"), d)),
        new ProjectXmlField<ProjectTask>("RemainingDuration", (m, d) => ProjectXmlValue.Duration(m.RemainingDuration, d), (m, v, d, e) => m.RemainingDuration = ProjectXmlValue.ParseDuration(v, (int?)e.Element(e.Name.Namespace + "DurationFormat"), d)),
        new ProjectXmlField<ProjectTask>("Work", (m, d) => ProjectXmlValue.Work(m.Work), (m, v, d, e) => m.Work = ProjectXmlValue.ParseWork(v)),
        new ProjectXmlField<ProjectTask>("ActualWork", (m, d) => ProjectXmlValue.Work(m.ActualWork), (m, v, d, e) => m.ActualWork = ProjectXmlValue.ParseWork(v)),
        new ProjectXmlField<ProjectTask>("RemainingWork", (m, d) => ProjectXmlValue.Work(m.RemainingWork), (m, v, d, e) => m.RemainingWork = ProjectXmlValue.ParseWork(v)),
        new ProjectXmlField<ProjectTask>("Start", (m, d) => ProjectXmlValue.Date(m.Start), (m, v, d, e) => m.Start = ProjectXmlValue.ParseDate(v)),
        new ProjectXmlField<ProjectTask>("Finish", (m, d) => ProjectXmlValue.Date(m.Finish), (m, v, d, e) => m.Finish = ProjectXmlValue.ParseDate(v)),
        new ProjectXmlField<ProjectTask>("ActualStart", (m, d) => ProjectXmlValue.Date(m.ActualStart), (m, v, d, e) => m.ActualStart = ProjectXmlValue.ParseDate(v)),
        new ProjectXmlField<ProjectTask>("ActualFinish", (m, d) => ProjectXmlValue.Date(m.ActualFinish), (m, v, d, e) => m.ActualFinish = ProjectXmlValue.ParseDate(v)),
        new ProjectXmlField<ProjectTask>("Deadline", (m, d) => ProjectXmlValue.Date(m.Deadline), (m, v, d, e) => m.Deadline = ProjectXmlValue.ParseDate(v)),
        new ProjectXmlField<ProjectTask>("ConstraintDate", (m, d) => ProjectXmlValue.Date(m.ConstraintDate), (m, v, d, e) => m.ConstraintDate = ProjectXmlValue.ParseDate(v)),
        new ProjectXmlField<ProjectTask>("ConstraintType", (m, d) => m.ConstraintType.HasValue ? ((int)m.ConstraintType.Value).ToString(System.Globalization.CultureInfo.InvariantCulture) : null, (m, v, d, e) => m.ConstraintType = (ProjectConstraintType)ProjectXmlValue.ParseInt(v)),
        new ProjectXmlField<ProjectTask>("Type", (m, d) => m.Type.HasValue ? ((int)m.Type.Value).ToString(System.Globalization.CultureInfo.InvariantCulture) : null, (m, v, d, e) => m.Type = (ProjectTaskType)ProjectXmlValue.ParseInt(v)),
        new ProjectXmlField<ProjectTask>("Manual", (m, d) => ProjectXmlValue.Boolean(m.IsManual), (m, v, d, e) => m.IsManual = ProjectXmlValue.ParseBool(v)),
        new ProjectXmlField<ProjectTask>("Milestone", (m, d) => ProjectXmlValue.Boolean(m.IsMilestone), (m, v, d, e) => m.IsMilestone = ProjectXmlValue.ParseBool(v)),
        new ProjectXmlField<ProjectTask>("Recurring", (m, d) => ProjectXmlValue.Boolean(m.IsRecurring), (m, v, d, e) => m.IsRecurring = ProjectXmlValue.ParseBool(v)),
        new ProjectXmlField<ProjectTask>("LevelingCanSplit", (m, d) => ProjectXmlValue.Boolean(m.LevelingCanSplit), (m, v, d, e) => m.LevelingCanSplit = ProjectXmlValue.ParseBool(v)),
        new ProjectXmlField<ProjectTask>("EffortDriven", (m, d) => ProjectXmlValue.Boolean(m.EffortDriven), (m, v, d, e) => m.EffortDriven = ProjectXmlValue.ParseBool(v)),
        new ProjectXmlField<ProjectTask>("Active", (m, d) => ProjectXmlValue.Boolean(m.IsActive), (m, v, d, e) => m.IsActive = ProjectXmlValue.ParseBool(v)),
        new ProjectXmlField<ProjectTask>("IsNull", (m, d) => ProjectXmlValue.Boolean(m.IsNull), (m, v, d, e) => m.IsNull = ProjectXmlValue.ParseBool(v)),
        new ProjectXmlField<ProjectTask>("Critical", (m, d) => ProjectXmlValue.Boolean(m.IsCritical), (m, v, d, e) => m.IsCritical = ProjectXmlValue.ParseBool(v)),
        new ProjectXmlField<ProjectTask>("PercentComplete", (m, d) => ProjectXmlValue.Integer(m.PercentComplete), (m, v, d, e) => m.PercentComplete = ProjectXmlValue.ParseInt(v)),
        new ProjectXmlField<ProjectTask>("PercentWorkComplete", (m, d) => ProjectXmlValue.Integer(m.PercentWorkComplete), (m, v, d, e) => m.PercentWorkComplete = ProjectXmlValue.ParseInt(v)),
        new ProjectXmlField<ProjectTask>("PhysicalPercentComplete", (m, d) => ProjectXmlValue.Integer(m.PhysicalPercentComplete), (m, v, d, e) => m.PhysicalPercentComplete = ProjectXmlValue.ParseInt(v)),
        new ProjectXmlField<ProjectTask>("Priority", (m, d) => ProjectXmlValue.Integer(m.Priority), (m, v, d, e) => m.Priority = ProjectXmlValue.ParseInt(v)),
        new ProjectXmlField<ProjectTask>("LevelingDelay", (m, d) => m.LevelingDelay.HasValue ? ProjectXmlValue.Number(m.LevelingDelay.Value.Value * ProjectXmlValue.MinutesPerUnit(m.LevelingDelay.Value.Unit, m.LevelingDelay.Value.IsElapsed, d) * 10m) : null,
            (m, v, d, e) => m.LevelingDelay = ProjectXmlValue.ParseDuration(ProjectXmlValue.Work(new ProjectWork(ProjectXmlValue.ParseNumber(v) / 10m))!,
                (int?)e.Element(e.Name.Namespace + "LevelingDelayFormat") ?? (ProjectXmlValue.ParseNumber(v) == 0m ? 3 : throw new InvalidDataException("A nonzero leveling delay requires LevelingDelayFormat.")), d)),
        new ProjectXmlField<ProjectTask>("LevelingDelayFormat", (m, d) => m.LevelingDelay.HasValue ? ProjectXmlValue.Integer(ProjectXmlValue.DurationFormat(m.LevelingDelay.Value)) : null, (m, v, d, e) => { }),
        new ProjectXmlField<ProjectTask>("Cost", (m, d) => ProjectXmlValue.Money(m.Cost), (m, v, d, e) => m.Cost = ProjectXmlValue.ParseMoney(v)),
        new ProjectXmlField<ProjectTask>("ActualCost", (m, d) => ProjectXmlValue.Money(m.ActualCost), (m, v, d, e) => m.ActualCost = ProjectXmlValue.ParseMoney(v)),
        new ProjectXmlField<ProjectTask>("RemainingCost", (m, d) => ProjectXmlValue.Money(m.RemainingCost), (m, v, d, e) => m.RemainingCost = ProjectXmlValue.ParseMoney(v)),
        new ProjectXmlField<ProjectTask>("FixedCost", (m, d) => ProjectXmlValue.Money(m.FixedCost), (m, v, d, e) => m.FixedCost = ProjectXmlValue.ParseMoney(v)),
        new ProjectXmlField<ProjectTask>("Notes", (m, d) => ProjectXmlValue.Text(m.Notes), (m, v, d, e) => m.Notes = v),
        new ProjectXmlField<ProjectTask>("Contact", (m, d) => ProjectXmlValue.Text(m.Contact), (m, v, d, e) => m.Contact = v),
        new ProjectXmlField<ProjectTask>("Hyperlink", (m, d) => ProjectXmlValue.Text(m.Hyperlink), (m, v, d, e) => m.Hyperlink = v),
        new ProjectXmlField<ProjectTask>("HyperlinkAddress", (m, d) => ProjectXmlValue.Text(m.HyperlinkAddress), (m, v, d, e) => m.HyperlinkAddress = v),
    };
}
