using OfficeIMO.Drawing;
using OfficeIMO.Pdf;
using System.IO;

namespace OfficeIMO.Examples.Pdf {
    internal static class ProfessionalReportPdf {
        public static void Example_Pdf_ProfessionalReport(string folderPath, bool open = false) {
            string path = Path.Combine(folderPath, "Pdf.ProfessionalReport.pdf");
            string imagePath = Path.Combine(AppContext.BaseDirectory, "Images", "EvotecLogo.png");
            byte[] logoBytes = File.Exists(imagePath) ? File.ReadAllBytes(imagePath) : CreateFallbackLogo();
            byte[] alphaBadge = CreateTransparentBadgePng();

            PdfDoc.Create(new PdfOptions {
                    DefaultFont = PdfStandardFont.Helvetica,
                    DefaultFontSize = 10,
                    HeaderFont = PdfStandardFont.Helvetica,
                    HeaderFontSize = 8,
                    HeaderFormat = "OfficeIMO.Pdf professional report",
                    HeaderAlign = PdfAlign.Left,
                    HeaderOffsetY = 18,
                    ShowHeader = true,
                    FooterFont = PdfStandardFont.Helvetica,
                    FooterFontSize = 8,
                    FooterFormat = "OfficeIMO.Pdf professional report - page {page}/{pages}",
                    FooterAlign = PdfAlign.Center,
                    ShowPageNumbers = true,
                    CreateOutlineFromHeadings = true
                })
                .Meta(
                    title: "OfficeIMO.Pdf Professional Report",
                    author: "OfficeIMO",
                    subject: "Dependency-free PDF report example",
                    keywords: "OfficeIMO,Pdf,PSWriteOffice,report")
                .H1("Executive Security Summary", PdfAlign.Left, PdfColor.FromRgb(25, 55, 85))
                .Paragraph(p => p
                    .Text("A polished first-party PDF report built with ")
                    .Bold("OfficeIMO.Pdf")
                    .Text(", shared drawing descriptors, wrapped tables, images, and generated bookmarks."))
                .Image(logoBytes, 120, 48, PdfAlign.Right, fit: OfficeImageFit.Contain)
                .PanelParagraph(
                    p => p.Bold("Healthy").Text(" posture with no critical findings."),
                    CreateStatusPanelStyle(),
                    defaultColor: PdfColor.FromRgb(42, 132, 82))
                .Image(alphaBadge, 18, 18, PdfAlign.Left)
                .Shape(CreateAccentRibbon(), spacingBefore: 12, spacingAfter: 10)
                .PanelParagraph(
                    p => p.Text("Operator note: long values should wrap cleanly, tables should stay inside the page, and reusable drawing primitives should remain available to Word, Excel, PowerPoint, and PDF exporters."),
                    new PanelStyle {
                        Background = PdfColor.FromRgb(248, 250, 252),
                        BorderColor = PdfColor.FromRgb(183, 194, 207),
                        PaddingX = 9,
                        PaddingY = 7
                    })
                .Table(new[] {
                    new[] { "Signal", "Evidence", "Action" },
                    new[] { "DMARC", "Policy is enforced for the primary domain and aligned subdomains.", "Monitor" },
                    new[] { "TLS", "Certificate chain and protocol posture are ready for automated PSWriteOffice reports.", "Keep" },
                    new[] { "DNS", "Delegation and stale-record checks are summarized without overflowing table cells.", "Review" },
                    new[] { "PDF", "The report is generated by the MIT licensed dependency-free OfficeIMO.Pdf engine.", "Expand" }
                }, style: CreateReportTableStyle())
                .Image(logoBytes, 112, 36, PdfAlign.Center, fit: OfficeImageFit.Contain)
                .Paragraph(p => p.Text("Generated by OfficeIMO.Pdf."), PdfAlign.Right, PdfColor.FromRgb(80, 80, 80))
                .Save(path);

            if (open) {
                System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo { FileName = path, UseShellExecute = true });
            }
        }

        private static PanelStyle CreateStatusPanelStyle() {
            return new PanelStyle {
                Background = PdfColor.FromRgb(230, 247, 238),
                BorderColor = PdfColor.FromRgb(42, 132, 82),
                BorderWidth = 1.2,
                PaddingX = 8,
                PaddingY = 5,
                MaxWidth = 245
            };
        }

        private static OfficeShape CreateAccentRibbon() {
            var accent = OfficeShape.RoundedRectangle(168, 8, 4);
            accent.FillGradient = OfficeLinearGradient.Horizontal(
                OfficeColor.FromRgb(32, 76, 120),
                OfficeColor.FromRgb(78, 159, 188));
            accent.Shadow = new OfficeShadow(OfficeColor.Black, 0.16, 1.5, 1.5);
            accent.StrokeColor = OfficeColor.FromRgb(32, 76, 120);
            accent.StrokeWidth = 0;
            return accent;
        }

        private static PdfTableStyle CreateReportTableStyle() {
            return new PdfTableStyle {
                HeaderFill = PdfColor.FromRgb(32, 76, 120),
                HeaderTextColor = PdfColor.White,
                TextColor = PdfColor.FromRgb(31, 41, 55),
                RowStripeFill = PdfColor.FromRgb(248, 250, 252),
                BorderColor = PdfColor.FromRgb(210, 218, 226),
                BorderWidth = 0.5,
                CellPaddingX = 6,
                CellPaddingY = 5,
                AutoFitColumns = true
            };
        }

        private static byte[] CreateFallbackLogo() {
            return new byte[] {
                137, 80, 78, 71, 13, 10, 26, 10,
                0, 0, 0, 13,
                73, 72, 68, 82,
                0, 0, 0, 1,
                0, 0, 0, 1,
                8, 2, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 12,
                73, 68, 65, 84,
                0x78, 0x9C, 0x63, 0xF8, 0xCF, 0xC0, 0x00, 0x00, 0x03, 0x01, 0x01, 0x00,
                0, 0, 0, 0,
                0, 0, 0, 0,
                73, 69, 78, 68,
                0, 0, 0, 0
            };
        }

        private static byte[] CreateTransparentBadgePng() {
            return new byte[] {
                137, 80, 78, 71, 13, 10, 26, 10,
                0, 0, 0, 13,
                73, 72, 68, 82,
                0, 0, 0, 1,
                0, 0, 0, 1,
                8, 6, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 16,
                73, 68, 65, 84,
                0x78, 0x01, 0x01, 0x05, 0x00, 0xFA, 0xFF, 0x00,
                0x2A, 0x84, 0x52, 0xA0, 0x03, 0x7D, 0x01, 0xA1,
                0, 0, 0, 0,
                0, 0, 0, 0,
                73, 69, 78, 68,
                0, 0, 0, 0
            };
        }
    }
}
